"""
Stream Characterization Harness Testbench

Drives the stream_char_harness module through its UART interface using
the CocoTBFramework UARTMaster and UARTMonitor BFMs.  All host-visible
operations (register access, descriptor loading, CRC readback, trace dump)
are exercised through the same UART command protocol the real FPGA uses.

For simulation speed, UART_BAUD is overridden to ~12.5 MHz
(CLKS_PER_BIT=8) so each byte takes ~80 ns instead of ~87 us.

Architecture:
    UARTMaster  --> i_uart_rx  --> uart_axil_bridge
    UARTMonitor <-- o_uart_tx  <-- uart_axil_bridge
    (inside the harness: AXIL decode -> CSR / desc_ram / STREAM / debug_sram)

Author: RTL Design Sherpa
Created: 2026-04-10
"""

import os
import sys
import cocotb
from cocotb.triggers import RisingEdge, Timer

from TBClasses.shared.utilities import get_repo_root
from TBClasses.shared.tbbase import TBBase

repo_root = get_repo_root()
sys.path.insert(0, repo_root)
from CocoTBFramework.components.uart import UARTMaster, UARTMonitor

# Add host/ to path for descriptor_builder
sys.path.insert(0, os.path.join(
    repo_root, 'projects', 'NexysA7', 'stream_characterization',
    'flows-stream-bridge', 'host'))
from descriptor_builder import DescriptorBuilder, CharConfig


# =========================================================================
# Memory map constants (must match stream_char_harness parameters)
# =========================================================================
STREAM_APB_BASE    = 0x0000_0000
HARNESS_CSR_BASE   = 0x0001_0000
DESC_RAM_BASE      = 0x0002_0000
STREAM_ERR_BASE    = 0x0003_0000
DEBUG_SRAM_BASE    = 0x0004_0000

# Harness CSR offsets
CSR_CTRL           = HARNESS_CSR_BASE + 0x00
CSR_STATUS         = HARNESS_CSR_BASE + 0x04
CSR_DBG_WR_PTR    = HARNESS_CSR_BASE + 0x08
CSR_DBG_OVERFLOW   = HARNESS_CSR_BASE + 0x0C
CSR_CRC_RD_EXPECTED = HARNESS_CSR_BASE + 0x10
CSR_CRC_WR_EXPECTED = HARNESS_CSR_BASE + 0x14
CSR_CRC_WR_COMPUTED = HARNESS_CSR_BASE + 0x18
CSR_CRC_MATCH      = HARNESS_CSR_BASE + 0x1C

# Per-channel CRC verification (multi-channel). Up to 8 channels supported
# in the layout; only NUM_CHANNELS slots are populated by the harness.
CSR_CRC_RD_PER_CH_BASE = HARNESS_CSR_BASE + 0x60   # 0x60+4*ch
CSR_CRC_WR_PER_CH_BASE = HARNESS_CSR_BASE + 0x80   # 0x80+4*ch
CSR_CRC_VALID_MASK     = HARNESS_CSR_BASE + 0xA0   # [NC-1:0]
CSR_CRC_MATCH_MASK     = HARNESS_CSR_BASE + 0xA4   # [NC-1:0]

# Kick-burst fast path. A single UART write to KICK_GO with a channel bitmask
# pulses the in-RTL kick lines for every set bit on one aclk cycle -- eliminates
# the multi-ms UART gap between per-channel APB kick writes.
#
# KICK_GO sits at 0xC0 (in the middle of the kick-addr slot range), so the
# per-channel kick-address slots are split into two banks:
#   ch 0..3 -> 0xB0/0xB4/0xB8/0xBC  (4-byte stride from 0xB0)
#   ch 4..7 -> 0xC4/0xC8/0xCC/0xD0  (4-byte stride from 0xC4)
# A naive `4*ch` stride hits 0xC0 for ch=4 and writes the kick address into
# KICK_GO -- it pulses a spurious kick for whichever channels the LSBs happen
# to encode and never delivers the real address for channels >= 4. Use the
# kick_addr_csr() helper below instead of the bare base + 4*ch.
CSR_KICK_GO            = HARNESS_CSR_BASE + 0xC0

# Harness timer (matches run_characterization.py). The completion signal the
# FPGA runner waits on is TIMER_STATUS.done, which fires when the sink-side
# (write-engine) beat counter reaches CSR_TIMER_EXPECTED_BEATS. Polling this
# (instead of stream_irq) is what makes a sim run an apples-to-apples copy
# of an FPGA run -- the IRQ path fires on the first per-burst completion
# packet, much earlier than the final beat, so sim that polls IRQ "completes"
# even when the harness timer would still be waiting.
CSR_TIMER_CTRL           = HARNESS_CSR_BASE + 0x28   # W: bit 0 = clear pulse
CSR_TIMER_STATUS         = HARNESS_CSR_BASE + 0x2C   # R: [0]=done [1]=running [2]=pass
CSR_TIMER_EXPECTED_BEATS = HARNESS_CSR_BASE + 0x38   # RW: stop when sink beat >= this


def kick_addr_csr(ch: int) -> int:
    """CSR address for the per-channel kick-address shadow register.

    Skips the 0xC0 KICK_GO slot so the 8-channel layout is unambiguous.
    """
    if ch < 4:
        return HARNESS_CSR_BASE + 0xB0 + 4 * ch          # ch 0..3
    return HARNESS_CSR_BASE + 0xC4 + 4 * (ch - 4)        # ch 4..7
CSR_SCRATCH        = HARNESS_CSR_BASE + 0x20
CSR_BUILD_ID       = HARNESS_CSR_BASE + 0x24

EXPECTED_BUILD_ID  = 0x5354_5243  # "STRC"

# STREAM APB registers — addresses from projects/components/stream/rtl/stream_regmap.py
# (generated by PeakRDL, routed via cmdrsp_router)
APB_GLOBAL_CTRL         = STREAM_APB_BASE + 0x100
APB_GLOBAL_STATUS       = STREAM_APB_BASE + 0x104
APB_CHANNEL_ENABLE      = STREAM_APB_BASE + 0x120
APB_CHANNEL_RESET       = STREAM_APB_BASE + 0x124
APB_SCHED_TIMEOUT_CYC   = STREAM_APB_BASE + 0x200
APB_SCHED_CONFIG        = STREAM_APB_BASE + 0x204
APB_DESCENG_CONFIG      = STREAM_APB_BASE + 0x220
APB_DESCENG_ADDR0_BASE  = STREAM_APB_BASE + 0x224
APB_DESCENG_ADDR0_LIMIT = STREAM_APB_BASE + 0x228
APB_DESCENG_ADDR1_BASE  = STREAM_APB_BASE + 0x22C
APB_DESCENG_ADDR1_LIMIT = STREAM_APB_BASE + 0x230
APB_AXI_XFER_CONFIG     = STREAM_APB_BASE + 0x2A0
APB_CH_KICK_BASE        = STREAM_APB_BASE + 0x000  # kick-off via apbtodescr
APB_CH_KICK_STRIDE      = 0x08                     # 8 bytes per ch (LOW + HIGH)

# Monitor configuration registers (stream_regs.rdl).
# stream_irq == monbus_axil_group.irq_out == !err_fifo_empty. A packet only
# reaches the err FIFO if ALL of the following are true:
#   1. PKT_MASK[pkt_type] == 0     — packet not dropped at monbus entry
#                                      (RDL default is 16'hFFFF = drop everything!)
#   2. <MON>_ENABLE bit set         — monitor is allowed to emit that pkt type
#   3. <MON>_MASK[event_code] == 0  — event code not masked (defaults OK)
#   4. ERR_CFG.ERR_SELECT[pkt_type]==1 — route that type to err FIFO (default 0!)
# Steps 1 and 4 were silently blocking everything.
APB_DAXMON_PKT_MASK     = STREAM_APB_BASE + 0x24C  # [15:0] per-type drop mask
APB_DAXMON_ENABLE       = STREAM_APB_BASE + 0x240
APB_DAXMON_ERR_CFG      = STREAM_APB_BASE + 0x250  # [3:0]=ERR_SELECT, [15:8]=ERR_MASK
APB_RDMON_PKT_MASK      = STREAM_APB_BASE + 0x26C
APB_RDMON_ENABLE        = STREAM_APB_BASE + 0x260
APB_RDMON_ERR_CFG       = STREAM_APB_BASE + 0x270
APB_WRMON_PKT_MASK      = STREAM_APB_BASE + 0x28C
APB_WRMON_ENABLE        = STREAM_APB_BASE + 0x280
APB_WRMON_ERR_CFG       = STREAM_APB_BASE + 0x290

# Value to enable MON + ERR + COMPL + TIMEOUT events (PERF stays off to avoid
# packet congestion). Matches <MON>_ENABLE bit layout: [0]=MON_EN, [1]=ERR_EN,
# [2]=COMPL_EN, [3]=TIMEOUT_EN, [4]=PERF_EN.
MON_ENABLE_COMPL_IRQ    = 0x0F
# WRMON_ENABLE.COMPRESS_EN (bit 5): runtime monbus compression enable, exactly
# as run_characterization.py sets it for "--compression on". Without it
# w_use_comp=0 and the raw expander is selected -- the compressor is NOT
# exercised (this is why earlier sims never caught the pipelined-CAM bug).
WRMON_COMPRESS_EN_BIT   = 1 << 5

# Per-type drop mask: clear bits 0..3 so Error/Completion/Threshold/Timeout
# packets are NOT dropped at monbus entry. Keep bits 4..15 masked to avoid
# traffic we don't care about.
MON_PKT_MASK_ALLOW_BASIC = 0x0000_FFF0

# ERR_CFG value: route packet types 0..3 (Error, Completion, Threshold, Timeout)
# to the err FIFO so irq_out fires on any of them. ERR_MASK[15:8] cleared to 0
# (default is 0xFF = "mask all error codes 0-7"; we want them to pass through).
MON_ERR_CFG_ROUTE_ALL   = 0x0000_000F
# ERR_SELECT=0 routes every packet type to the bulk-trace write FIFO
# (-> m_axil_mon -> debug_sram, through the compressor) instead of the
# err FIFO IRQ path. Used by the compression-characterization workload.
MON_ERR_CFG_BULK_TRACE  = 0x0000_0000


class StreamCharTB(TBBase):
    """
    Testbench for stream_char_harness.

    Drives the full characterization harness through UART. Uses fast baud
    rate for simulation (CLKS_PER_BIT from RTL parameter, typically 8 for sim).
    """

    def __init__(self, dut):
        super().__init__(dut)

        self.clk = dut.aclk
        self.clk_name = 'aclk'
        self.rst_n = dut.aresetn

        self.TEST_LEVEL = os.environ.get('TEST_LEVEL', 'gate').lower()
        self.SEED = self.convert_to_int(os.environ.get('SEED', '12345'))

        # CLKS_PER_BIT must match the RTL parameterisation
        fpga_clk_hz = self.convert_to_int(os.environ.get('FPGA_CLK_HZ', '100000000'))
        uart_baud = self.convert_to_int(os.environ.get('UART_BAUD', '12500000'))
        self.clks_per_bit = fpga_clk_hz // uart_baud

        # UART BFMs
        self.uart_master = UARTMaster(
            entity=dut,
            title="HOST_TX",
            signal_name="i_uart_rx",
            clock=self.clk,
            clks_per_bit=self.clks_per_bit,
            log=self.log,
        )
        self.uart_monitor = UARTMonitor(
            entity=dut,
            title="HOST_RX",
            signal_name="o_uart_tx",
            clock=self.clk,
            clks_per_bit=self.clks_per_bit,
            direction='RX',
            log=self.log,
        )

        # Statistics
        self.writes_ok = 0
        self.reads_ok = 0
        self.errors = 0

        self.log.info(
            f"StreamCharTB: TEST_LEVEL={self.TEST_LEVEL} "
            f"CLKS_PER_BIT={self.clks_per_bit}")

    # =====================================================================
    # Mandatory methods
    # =====================================================================

    async def setup_clocks_and_reset(self):
        await self.start_clock(self.clk_name, freq=10, units='ns')
        # Drive UART idle (high) before reset
        self.dut.i_uart_rx.value = 1
        await self.assert_reset()
        await self.wait_clocks(self.clk_name, 20)
        await self.deassert_reset()
        await self.wait_clocks(self.clk_name, 20)

    async def assert_reset(self):
        self.rst_n.value = 0

    async def deassert_reset(self):
        self.rst_n.value = 1

    # =====================================================================
    # Low-level UART command helpers
    # =====================================================================

    def _uart_byte_clocks(self, num_bytes: int) -> int:
        """Clock cycles for num_bytes over UART (10 bits/byte)."""
        return num_bytes * 10 * self.clks_per_bit

    async def uart_write(self, addr: int, data: int) -> bool:
        """Send 'W addr data\\n', wait for 'OK\\n'. Return True on success."""
        cmd = f"W {addr:08X} {data:08X}\n"
        self.uart_monitor._recvQ.clear()
        await self.uart_master.send_string(cmd)

        # Wait for command TX + bridge latency + response TX
        wait = self._uart_byte_clocks(len(cmd) + 4) + 500
        await self.wait_clocks(self.clk_name, wait)

        resp = self._drain_response()
        if resp == "OK\n":
            self.writes_ok += 1
            return True
        self.log.error(f"uart_write(0x{addr:08X}, 0x{data:08X}): "
                       f"expected 'OK\\n', got {resp!r}")
        self.errors += 1
        return False

    async def uart_read(self, addr: int) -> int | None:
        """Send 'R addr\\n', return 32-bit value or None."""
        cmd = f"R {addr:08X}\n"
        self.uart_monitor._recvQ.clear()
        await self.uart_master.send_string(cmd)

        # Response is "0xHHHHHHHH\n" = 11 chars
        wait = self._uart_byte_clocks(len(cmd) + 12) + 500
        await self.wait_clocks(self.clk_name, wait)

        resp = self._drain_response()
        if resp and resp.startswith("0x") and resp.endswith("\n"):
            try:
                val = int(resp[2:].strip(), 16)
                self.reads_ok += 1
                return val
            except ValueError:
                pass
        self.log.error(f"uart_read(0x{addr:08X}): bad response {resp!r}")
        self.errors += 1
        return None

    def _drain_response(self) -> str:
        """Collect all bytes currently in the UART monitor queue."""
        chars = []
        while self.uart_monitor._recvQ:
            pkt = self.uart_monitor._recvQ.popleft()
            chars.append(chr(pkt.data))
        return ''.join(chars)

    # =====================================================================
    # High-level harness operations
    # =====================================================================

    async def ping_scratch(self, value: int = 0xDEAD_BEEF) -> bool:
        """Write scratch register and read it back."""
        ok = await self.uart_write(CSR_SCRATCH, value)
        if not ok:
            return False
        rb = await self.uart_read(CSR_SCRATCH)
        if rb != value:
            self.log.error(
                f"Scratch mismatch: wrote 0x{value:08X}, read 0x{rb:08X}"
                if rb is not None else "Scratch read failed")
            return False
        self.log.info(f"Scratch ping OK: 0x{value:08X}")
        return True

    async def check_build_id(self) -> bool:
        """Read BUILD_ID and verify."""
        val = await self.uart_read(CSR_BUILD_ID)
        ok = val == EXPECTED_BUILD_ID
        if ok:
            self.log.info(f"Build ID OK: 0x{val:08X}")
        else:
            self.log.error(
                f"Build ID mismatch: expected 0x{EXPECTED_BUILD_ID:08X}, "
                f"got 0x{val:08X}" if val is not None else "read failed")
        return ok

    async def load_descriptor(self, desc_index: int,
                              src_addr: int, dst_addr: int,
                              length: int, next_ptr: int = 0,
                              control: int = 0x01) -> bool:
        """
        Write one 256-bit STREAM descriptor to desc_ram.

        Descriptor layout (256 bits = 8 x 32-bit words):
          Word 0: src_addr[31:0]
          Word 1: src_addr[63:32]
          Word 2: dst_addr[31:0]
          Word 3: dst_addr[63:32]
          Word 4: length[31:0]
          Word 5: next_descriptor_ptr[31:0]
          Word 6: control (valid, last, interrupt, priority, channel_id)
          Word 7: reserved
        """
        base = DESC_RAM_BASE + desc_index * 32  # 32 bytes per descriptor
        words = [
            src_addr & 0xFFFF_FFFF,
            (src_addr >> 32) & 0xFFFF_FFFF,
            dst_addr & 0xFFFF_FFFF,
            (dst_addr >> 32) & 0xFFFF_FFFF,
            length & 0xFFFF_FFFF,
            next_ptr & 0xFFFF_FFFF,
            control & 0xFFFF_FFFF,
            0x0000_0000,  # reserved
        ]
        all_ok = True
        for i, w in enumerate(words):
            ok = await self.uart_write(base + i * 4, w)
            if not ok:
                all_ok = False
        self.log.info(
            f"Descriptor[{desc_index}]: src=0x{src_addr:08X} dst=0x{dst_addr:08X} "
            f"len={length} next=0x{next_ptr:08X} ctrl=0x{control:02X} "
            f"{'OK' if all_ok else 'FAILED'}")
        return all_ok

    async def read_crc_status(self, num_channels: int = 1) -> dict:
        """Read CRC registers and return a status dict.

        For backward compat the legacy aggregate fields (rd_expected,
        wr_expected, wr_computed, match, valid) are still returned —
        but for multi-channel runs they reflect channel 0 only and the
        aggregate match/valid reductions across all active channels.
        Per-channel arrays are returned alongside for verification.
        """
        rd_exp = await self.uart_read(CSR_CRC_RD_EXPECTED)
        wr_exp = await self.uart_read(CSR_CRC_WR_EXPECTED)
        wr_got = await self.uart_read(CSR_CRC_WR_COMPUTED)
        match  = await self.uart_read(CSR_CRC_MATCH)

        # Per-channel reads — only NUM_CHANNELS slots are populated, the
        # rest read as 0 (harness pads).
        rd_per_ch = []
        wr_per_ch = []
        for ch in range(num_channels):
            rd_per_ch.append(await self.uart_read(CSR_CRC_RD_PER_CH_BASE + 4 * ch))
            wr_per_ch.append(await self.uart_read(CSR_CRC_WR_PER_CH_BASE + 4 * ch))
        valid_mask = await self.uart_read(CSR_CRC_VALID_MASK)
        match_mask = await self.uart_read(CSR_CRC_MATCH_MASK)
        return {
            'rd_expected': rd_exp,
            'wr_expected': wr_exp,
            'wr_computed': wr_got,
            'match_reg':   match,
            'match':       (match is not None) and (match & 0x1 == 1),
            'valid':       (match is not None) and (match & 0x2 == 2),
            'rd_per_ch':   rd_per_ch,
            'wr_per_ch':   wr_per_ch,
            'valid_mask':  valid_mask if valid_mask is not None else 0,
            'match_mask':  match_mask if match_mask is not None else 0,
        }

    async def read_status(self) -> dict:
        """Read harness status register."""
        val = await self.uart_read(CSR_STATUS)
        if val is None:
            return {}
        return {
            'stream_irq':     bool(val & 0x01),
            'any_error':      bool(val & 0x02),
            'trace_overflow': bool(val & 0x04),
            'raw': val,
        }

    async def clear_stats(self):
        """Pulse clear_stats bit in CTRL."""
        await self.uart_write(CSR_CTRL, 0x02)

    # =====================================================================
    # Test scenarios
    # =====================================================================

    async def run_ping_test(self) -> bool:
        """Gate-level: verify UART → decode → CSR round-trip."""
        self.log.info("=== Ping test ===")
        ok = True
        ok &= await self.ping_scratch(0xDEAD_BEEF)
        ok &= await self.ping_scratch(0x1234_5678)
        ok &= await self.ping_scratch(0x0000_0000)
        ok &= await self.ping_scratch(0xFFFF_FFFF)
        ok &= await self.check_build_id()
        self.log.info(f"Ping test: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_descriptor_load_test(self) -> bool:
        """Func-level: load descriptors into desc_ram via UART."""
        self.log.info("=== Descriptor load test ===")
        ok = True
        ok &= await self.load_descriptor(
            desc_index=0,
            src_addr=0x8000_0000,
            dst_addr=0x9000_0000,
            length=64,
            next_ptr=0,
            control=0x07,  # valid + last + interrupt
        )
        if self.TEST_LEVEL != 'gate':
            ok &= await self.load_descriptor(
                desc_index=1,
                src_addr=0x8000_1000,
                dst_addr=0x9000_1000,
                length=128,
                next_ptr=0,
                control=0x07,
            )
        self.log.info(f"Descriptor load: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_csr_readback_test(self) -> bool:
        """Func-level: read status and CRC registers."""
        self.log.info("=== CSR readback test ===")
        ok = True

        status = await self.read_status()
        if not status:
            self.log.error("Failed to read status register")
            ok = False
        else:
            self.log.info(f"Status: {status}")

        wr_ptr = await self.uart_read(CSR_DBG_WR_PTR)
        if wr_ptr is None:
            ok = False
        else:
            self.log.info(f"Debug wr_ptr: {wr_ptr}")

        crc = await self.read_crc_status()
        self.log.info(f"CRC status: {crc}")

        self.log.info(f"CSR readback: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_apb_config_test(self) -> bool:
        """Func-level: read STREAM APB register space (verify axil2apb path)."""
        self.log.info("=== APB config path test ===")
        # Read STREAM's GLOBAL_CTRL register (offset 0x100 in APB space)
        # After reset, GLOBAL_EN should be 0
        val = await self.uart_read(STREAM_APB_BASE + 0x100)
        if val is None:
            self.log.error("Failed to read STREAM APB GLOBAL_CTRL")
            return False
        self.log.info(f"STREAM GLOBAL_CTRL = 0x{val:08X}")
        # Write and readback
        ok = await self.uart_write(STREAM_APB_BASE + 0x100, 0x01)  # GLOBAL_EN=1
        if not ok:
            return False
        rb = await self.uart_read(STREAM_APB_BASE + 0x100)
        if rb is None:
            return False
        wrote_ok = (rb & 0x01) == 0x01
        self.log.info(
            f"APB write/readback: wrote 0x01, read 0x{rb:08X} "
            f"{'PASS' if wrote_ok else 'FAIL'}")
        return wrote_ok

    # =====================================================================
    # DMA test using descriptor_builder
    # =====================================================================

    async def run_dma_test(self, num_channels: int,
                           descriptors_per_channel: int,
                           transfer_bytes: int,
                           timeout_clocks: int = 50_000,
                           mon_err_cfg: int = MON_ERR_CFG_ROUTE_ALL,
                           compress_en: bool = False) -> bool:
        # compress_en=True sets WRMON_ENABLE.COMPRESS_EN (bit 5) so the
        # compressor path (w_use_comp=1) is selected at runtime -- mirrors
        # run_characterization.py "--compression on". Combined with
        # mon_err_cfg=BULK_TRACE this exercises the compressor exactly as the
        # FPGA does.
        # mon_err_cfg picks the monbus routing: ROUTE_ALL (default) sends
        # packets to the err FIFO IRQ path; BULK_TRACE (0) sends them to the
        # debug_sram bulk-trace path through the compressor -- used by the
        # compression-characterization run.
        # timeout_clocks default = 50_000 ≈ 500 us of wait_clocks budget at a
        # 10 ns clock period. Reduced from 500_000 so failures surface fast;
        # bump it explicitly at the call site when a test legitimately needs
        # longer.
        """
        Full DMA test: load descriptors, configure STREAM, kick channels,
        poll completion, verify CRC.

        Uses the same DescriptorBuilder that the FPGA host script uses,
        so descriptor layout is identical between sim and hardware.
        """
        self.log.info(
            f"=== DMA test: {num_channels}ch x {descriptors_per_channel}desc "
            f"x {transfer_bytes}B ===")

        builder = DescriptorBuilder(data_width=128)
        config = CharConfig(
            name=f"sim_{descriptors_per_channel}desc_{num_channels}ch",
            num_channels=num_channels,
            descriptors_per_channel=descriptors_per_channel,
            transfer_bytes=transfer_bytes,
        )
        test_data = builder.build_test(config)

        # 1. Soft-reset the whole DMA + harness unit via the harness CSR
        # bit (CSR_CTRL[3]). This is the same call site as
        # run_characterization.py.reset_stream() -- a single pulse on
        # csr_soft_reset gets extended in the harness into ~16 clocks
        # of reset on unit_aresetn, which fans out to u_stream + all
        # the harness sub-blocks that hold cumulative state. Was just
        # APB_GLOBAL_CTRL bit 1 (STREAM's GLOBAL_RST), which only
        # resets per-channel state inside STREAM.
        await self.uart_write(CSR_CTRL, 0x08)         # bit 3 = soft_reset_pulse
        await self.wait_clocks(self.clk_name, 100)
        await self.clear_stats()
        await self.wait_clocks(self.clk_name, 50)

        # 2. Load all descriptors via UART
        self.log.info(
            f"  Loading {test_data['total_descriptors']} descriptors "
            f"({len(test_data['descriptor_writes'])} UART writes)...")
        for addr, data in test_data['descriptor_writes']:
            ok = await self.uart_write(addr, data)
            if not ok:
                self.log.error(f"  Descriptor write failed at 0x{addr:08X}")
                return False

        # 3. Full STREAM configuration — matches stream_top_tb._configure_stream_top()
        # and StreamHelper sequence. All register addresses from stream_regmap.py.

        # 3a. Scheduler config: enable + timeout + error/completion reporting
        sched_cfg = 0x0F  # [0]=SCHED_EN, [1]=TIMEOUT_EN, [2]=ERR_EN, [3]=COMPL_EN
        await self.uart_write(APB_SCHED_CONFIG, sched_cfg)
        # SCHED_TIMEOUT_CYCLES is a 32-bit field; use the full width.
        # The earlier 0x0FFFFFFF (28-bit, ~2.68 s @ 100 MHz) was too tight
        # for deep descriptor chains -- the scheduler would error out on
        # cumulative inter-descriptor stall before the chain finished. The
        # 32-bit max gives ~42.9 s of per-channel inactivity budget.
        await self.uart_write(APB_SCHED_TIMEOUT_CYC, 0xFFFFFFFF)  # ~42.9s @ 100MHz

        # 3b. Descriptor engine config: enable (no prefetch for now)
        desceng_cfg = 0x01  # [0]=DESCENG_EN
        await self.uart_write(APB_DESCENG_CONFIG, desceng_cfg)

        # 3c. Descriptor address ranges (for chaining validation)
        await self.uart_write(APB_DESCENG_ADDR0_BASE,  0x0000_0000)
        await self.uart_write(APB_DESCENG_ADDR0_LIMIT, 0xFFFF_FFFF)
        await self.uart_write(APB_DESCENG_ADDR1_BASE,  0x0000_0000)
        await self.uart_write(APB_DESCENG_ADDR1_LIMIT, 0xFFFF_FFFF)

        # 3d. AXI transfer config: burst sizes (ARLEN/AWLEN)
        axi_cfg = (15 & 0xFF) | ((15 & 0xFF) << 8)  # rd=16 beats, wr=16 beats
        await self.uart_write(APB_AXI_XFER_CONFIG, axi_cfg)

        # 3e. Unblock completion events all the way to the err FIFO so
        # monbus_axil_group.irq_out pulses when the DMA retires. FOUR things
        # must all be true (see register-group comment above):
        #   PKT_MASK[pkt_type]==0  ← RDL default drops EVERY type, must clear!
        #   ENABLE.COMPL_EN=1      ← monitor must emit completion packets
        #   MASK1 event_code       ← defaults are fine (COMPL_MASK=0)
        #   ERR_CFG.ERR_SELECT     ← routes pkt type to err FIFO (default 0)
        for pkt_mask_reg, en_reg, err_reg in (
            (APB_DAXMON_PKT_MASK, APB_DAXMON_ENABLE, APB_DAXMON_ERR_CFG),
            (APB_RDMON_PKT_MASK,  APB_RDMON_ENABLE,  APB_RDMON_ERR_CFG),
            (APB_WRMON_PKT_MASK,  APB_WRMON_ENABLE,  APB_WRMON_ERR_CFG),
        ):
            await self.uart_write(pkt_mask_reg, MON_PKT_MASK_ALLOW_BASIC)
            en_val = MON_ENABLE_COMPL_IRQ
            if compress_en and en_reg == APB_WRMON_ENABLE:
                en_val |= WRMON_COMPRESS_EN_BIT   # runtime compression on
            await self.uart_write(en_reg,       en_val)
            await self.uart_write(err_reg,      mon_err_cfg)

        # 4. Enable STREAM global + channels
        ch_mask = (1 << num_channels) - 1
        await self.uart_write(APB_GLOBAL_CTRL, 0x01)       # GLOBAL_EN
        await self.uart_write(APB_CHANNEL_ENABLE, ch_mask)  # channel mask
        self.log.info(f"  STREAM configured and enabled: ch_mask=0x{ch_mask:02X}")

        # 4z. Arm the harness timer with the expected sink-side beat count,
        # mirroring run_characterization.py.setup_timer() exactly. The FPGA
        # runner waits on TIMER_STATUS.done (which fires when write-side
        # beat counter reaches CSR_TIMER_EXPECTED_BEATS) -- if the sim
        # doesn't arm this register the completion path diverges from
        # hardware. Total expected_beats = bytes / 16 (DATA_WIDTH=128).
        expected_beats_total = (transfer_bytes * num_channels *
                                descriptors_per_channel) // 16
        await self.uart_write(CSR_TIMER_CTRL, 0x1)        # clear pulse
        await self.uart_write(CSR_TIMER_EXPECTED_BEATS, expected_beats_total)
        self.log.info(
            f"  Timer armed: expected_beats={expected_beats_total} "
            f"(= {expected_beats_total * 16} bytes)")

        # 4a. Debug: read back key registers to confirm config took effect
        for name, addr in [
            ("GLOBAL_CTRL",       APB_GLOBAL_CTRL),
            ("GLOBAL_STATUS",     APB_GLOBAL_STATUS),
            ("CHANNEL_ENABLE",    APB_CHANNEL_ENABLE),
            ("SCHED_CONFIG",      APB_SCHED_CONFIG),
            ("DESCENG_CONFIG",    APB_DESCENG_CONFIG),
            ("ADDR0_BASE",        APB_DESCENG_ADDR0_BASE),
            ("ADDR0_LIMIT",       APB_DESCENG_ADDR0_LIMIT),
            ("AXI_XFER_CONFIG",   APB_AXI_XFER_CONFIG),
            ("CHANNEL_IDLE",      STREAM_APB_BASE + 0x140),
            ("DESC_ENGINE_IDLE",  STREAM_APB_BASE + 0x144),
            ("SCHEDULER_IDLE",    STREAM_APB_BASE + 0x148),
            ("SCHED_ERROR",       STREAM_APB_BASE + 0x170),
        ]:
            val = await self.uart_read(addr)
            self.log.info(f"  [DEBUG] {name:20s} @ 0x{addr:03X} = 0x{val:08X}" if val is not None
                          else f"  [DEBUG] {name:20s} @ 0x{addr:03X} = READ FAILED")

        # 5. Kick all channels (two APB writes per channel: LOW + HIGH 32-bit)
        # Kick-burst fast path: pre-load each channel's first descriptor
        # address into the shadow register, then a single KICK_GO write
        # pulses every channel's hardware kick line on the same aclk
        # cycle. This avoids the multi-ms UART gap between per-channel
        # APB writes that would otherwise serialize multi-channel runs.
        kick_mask = 0
        for ch, kick_addr in sorted(test_data['kick_addresses'].items()):
            await self.uart_write(kick_addr_csr(ch),
                                  kick_addr & 0xFFFF_FFFF)
            kick_mask |= (1 << ch)
            self.log.info(f"  Loaded ch{ch} kick addr 0x{kick_addr:08X}")
        await self.uart_write(CSR_KICK_GO, kick_mask)
        self.log.info(f"  Kick burst fired, mask=0x{kick_mask:02X}")

        # 5a. Debug: read status immediately after kick
        await self.wait_clocks(self.clk_name, 1000)
        for name, addr in [
            ("GLOBAL_STATUS",     APB_GLOBAL_STATUS),
            ("CHANNEL_IDLE",      STREAM_APB_BASE + 0x140),
            ("DESC_ENGINE_IDLE",  STREAM_APB_BASE + 0x144),
            ("SCHEDULER_IDLE",    STREAM_APB_BASE + 0x148),
            ("SCHED_ERROR",       STREAM_APB_BASE + 0x170),
            ("AXI_RD_COMPLETE",   STREAM_APB_BASE + 0x174),
            ("AXI_WR_COMPLETE",   STREAM_APB_BASE + 0x178),
        ]:
            val = await self.uart_read(addr)
            self.log.info(f"  [POST-KICK] {name:20s} @ 0x{addr:03X} = 0x{val:08X}" if val is not None
                          else f"  [POST-KICK] {name:20s} @ 0x{addr:03X} = READ FAILED")

        # 6. Poll for completion the same way run_characterization.py does:
        # watch TIMER_STATUS.done (bit 0), TIMER_STATUS.running (bit 1) and
        # any_error in CSR_STATUS. The harness timer fires "done" when the
        # sink-side beat counter hits CSR_TIMER_EXPECTED_BEATS. If the DMA
        # is short by even one beat the FPGA hangs here forever -- exactly
        # the failure signature of the deep-chain regression we're chasing.
        self.log.info(f"  Waiting for harness timer.done (up to {timeout_clocks} clocks)...")
        completed = False
        timer_pass = False
        any_error  = False
        for _ in range(timeout_clocks // 100):
            await self.wait_clocks(self.clk_name, 100)
            ts = await self.uart_read(CSR_TIMER_STATUS) or 0
            st = await self.read_status() or {}
            done    = bool(ts & 0x01)
            running = bool(ts & 0x02)
            tpass   = bool(ts & 0x04)
            err     = bool(st.get('any_error'))
            if done or err:
                completed = True
                timer_pass = tpass
                any_error  = err
                self.log.info(
                    f"  Timer fired: done={done} running={running} "
                    f"pass={tpass} any_error={err}")
                break

        if not completed:
            # Match the FPGA "TIMEOUT after Ns" report and dump enough
            # diagnostic state to localize the wedge.
            self.log.error("  DMA timeout — TIMER_STATUS.done never asserted")
            ts = await self.uart_read(CSR_TIMER_STATUS) or 0
            st = await self.read_status() or {}
            try:
                wr_beats = int(self.dut.u_dma_slaves.u_wr_crc_check.write_beat_count_total.value)
                rd_beats = int(self.dut.u_dma_slaves.u_rd_pattern_gen.read_beat_count_total.value)
            except Exception:
                wr_beats = -1
                rd_beats = -1
            self.log.error(
                f"  Final timer_status=0x{ts:08X} read_beats={rd_beats} "
                f"write_beats={wr_beats} expected={expected_beats_total}")

            # Dump desc_ram observation counters (0xD4/0xD8 + 0xE0..0xFC).
            # The pair (DESC_AR_HS, DESC_SRAM_AR_HS) bisects the wedge:
            #   DESC_AR_HS > 0 & DESC_SRAM_AR_HS == 0  → bridge converter
            #                                            stalled (256→64
            #                                            or AXI4→AXIL).
            #   DESC_SRAM_AR_HS > 0 & DESC_SRAM_R_HS == 0 → SRAM stuck
            #                                              on read path.
            #   DESC_SRAM_R_HS > 0 & DESC_R_HS == 0 → response packing
            #                                         (64→256) stalled.
            self.log.error("  desc_ram observation counters:")
            for name, addr in [
                ("DESC_SRAM_AR_HS", HARNESS_CSR_BASE + 0xD4),
                ("DESC_SRAM_R_HS",  HARNESS_CSR_BASE + 0xD8),
                ("DESC_AR_HS",      HARNESS_CSR_BASE + 0xE0),
                ("DESC_AR_STALL",   HARNESS_CSR_BASE + 0xE4),
                ("DESC_R_HS",       HARNESS_CSR_BASE + 0xE8),
                ("DESC_R_STALL",    HARNESS_CSR_BASE + 0xEC),
                ("DESC_AW_HS",      HARNESS_CSR_BASE + 0xF0),
                ("DESC_W_HS",       HARNESS_CSR_BASE + 0xF4),
                ("DESC_B_HS",       HARNESS_CSR_BASE + 0xF8),
                ("DESC_VR_LIVE",    HARNESS_CSR_BASE + 0xFC),
            ]:
                val = await self.uart_read(addr)
                self.log.error(f"    {name:16s} @ 0x{addr:08X} = {val}"
                               if val is None
                               else f"    {name:16s} @ 0x{addr:08X} = 0x{val:08X}")

            # Peek the LATCHED first AR (harness r_first_desc_ar* regs).
            # STREAM only drives desc_arvalid for the handshake cycle, so
            # the live wires read 0; the latch holds the values captured
            # at the moment of the handshake.
            try:
                seen   = int(self.dut.r_first_desc_ar_seen.value)
                araddr = int(self.dut.r_first_desc_araddr.value)
                arlen  = int(self.dut.r_first_desc_arlen.value)
                arsize = int(self.dut.r_first_desc_arsize.value)
                arburst = int(self.dut.r_first_desc_arburst.value)
                arid    = int(self.dut.r_first_desc_arid.value)
                self.log.error(
                    f"  First STREAM m_axi_desc AR (latched): seen={seen} "
                    f"addr=0x{araddr:08X} len={arlen} size={arsize} "
                    f"burst={arburst} id={arid}")
                in_desc_range = 0x00020000 <= araddr <= 0x0002FFFF
                self.log.error(
                    f"  Routes to desc_ram (0x00020000..0x0002FFFF)? "
                    f"{in_desc_range}"
                    + ("" if in_desc_range
                       else " — bridge skid will wedge until AR drains"))
            except Exception as e:
                self.log.error(f"  Could not peek latched first AR: {e}")

            # SRAM-side obs peeks. The SRAM module's o_dbg_vr is the
            # external AXIL bus (should equal s2_* mirror); o_dbg_fub_vr
            # is the SRAM-INTERNAL fub side, between the axil4_slave_*
            # wrappers and the BRAM glue. If the SRAM's wrapper has an
            # AR queued but the BRAM glue hasn't fired, the fub-side AR
            # would be valid; if the wrapper itself never received an
            # AR, all SRAM-side bits stay 0.
            def _decode_dbg_vr(v: int) -> str:
                names = [
                    "awvalid", "awready", "wvalid", "wready",
                    "bvalid",  "bready",
                    "arvalid", "arready", "rvalid", "rready",
                ]
                return " ".join(f"{n}={(v >> i) & 1}"
                                for i, n in enumerate(names))
            try:
                sram_axil   = int(self.dut.w_desc_ram_dbg_vr_axil.value)
                sram_fub    = int(self.dut.w_desc_ram_dbg_fub_vr.value)
                sram_busyrd = int(self.dut.w_desc_ram_dbg_busy_rd.value)
                sram_busywr = int(self.dut.w_desc_ram_dbg_busy_wr.value)
                self.log.error(
                    f"  SRAM o_dbg_vr     (external AXIL bus): 0x{sram_axil:03X} "
                    f"[{_decode_dbg_vr(sram_axil)}]")
                self.log.error(
                    f"  SRAM o_dbg_fub_vr (post-skid fub side): 0x{sram_fub:03X} "
                    f"[{_decode_dbg_vr(sram_fub)}]")
                self.log.error(
                    f"  SRAM busy_rd={sram_busyrd} busy_wr={sram_busywr} "
                    "(wrapper-internal AR/R/AW/W in flight)")
            except Exception as e:
                self.log.error(f"  Could not peek SRAM obs: {e}")

            # Peek the SRAM's r_mem to see the actual descriptor bytes.
            # If the host 32->256 upsize is misaligning byte strobes, the
            # bytes will be at the wrong positions in the 256-bit word
            # and STREAM's descriptor parser will see CTRL_VALID=0.
            # Index 1 = descriptor 0 for ch0 (DESC_INDEX_OFFSET=1).
            try:
                mem = self.dut.u_desc_ram.r_mem
                for i in [0, 1, 2]:
                    word = int(mem[i].value)
                    # Decode fields per STREAM descriptor layout
                    src    = word & ((1 << 64) - 1)
                    dst    = (word >> 64) & ((1 << 64) - 1)
                    length = (word >> 128) & ((1 << 32) - 1)
                    nxt    = (word >> 160) & ((1 << 32) - 1)
                    ctrl   = (word >> 192) & ((1 << 32) - 1)
                    valid  = (ctrl >> 0) & 1
                    irq    = (ctrl >> 1) & 1
                    last   = (ctrl >> 2) & 1
                    chid   = (ctrl >> 4) & 0xF
                    self.log.error(
                        f"  SRAM r_mem[{i}] = 0x{word:064X}")
                    self.log.error(
                        f"    src=0x{src:016X} dst=0x{dst:016X} "
                        f"len={length} next=0x{nxt:08X}")
                    self.log.error(
                        f"    ctrl=0x{ctrl:08X} valid={valid} "
                        f"irq={irq} last={last} ch={chid}")
            except Exception as e:
                self.log.error(f"  Could not peek SRAM r_mem: {e}")

            # Bridge stream_desc_adapter internals. fub_axi_ar* are the
            # wrapper-skid HEAD signals (what the adapter sees AFTER the
            # external arvalid/arready handshake has stowed the AR into
            # the skid). If fub_axi_arvalid=1 here but xbar arready=0
            # AND comb_slave_select_ar=0, the address decode is missing
            # slave 2 → wedged forever.
            try:
                adp = self.dut.u_bridge.u_stream_desc_adapter
                fub_arvalid = int(adp.fub_axi_arvalid.value)
                fub_arready = int(adp.fub_axi_arready.value)
                fub_araddr  = int(adp.fub_axi_araddr.value)
                fub_arsize  = int(adp.fub_axi_arsize.value)
                fub_arlen   = int(adp.fub_axi_arlen.value)
                ss_ar = int(adp.comb_slave_select_ar.value)
                xbar_arvalid = int(adp.stream_desc_256b_arvalid.value)
                xbar_arready = int(adp.stream_desc_256b_arready.value)
                self.log.error(
                    f"  bridge stream_desc_adapter fub_axi: "
                    f"arvalid={fub_arvalid} arready={fub_arready} "
                    f"araddr=0x{fub_araddr:08X} size={fub_arsize} "
                    f"len={fub_arlen}")
                self.log.error(
                    f"  comb_slave_select_ar=0b{ss_ar:06b} "
                    f"(bit2=slave 2 desc_ram)")
                self.log.error(
                    f"  xbar-side stream_desc_256b_ar: "
                    f"valid={xbar_arvalid} ready={xbar_arready}")
            except Exception as e:
                self.log.error(
                    f"  Could not peek bridge stream_desc_adapter: {e}")

            # STREAM internal status (CHANNEL_IDLE/DESC_ENGINE_IDLE/SCHED_ERROR)
            # tells us whether the scheduler is stuck or has flagged an error.
            self.log.error("  STREAM status registers:")
            for name, addr in [
                ("GLOBAL_STATUS",    APB_GLOBAL_STATUS),
                ("CHANNEL_IDLE",     STREAM_APB_BASE + 0x140),
                ("DESC_ENGINE_IDLE", STREAM_APB_BASE + 0x144),
                ("SCHEDULER_IDLE",   STREAM_APB_BASE + 0x148),
                ("SCHED_ERROR",      STREAM_APB_BASE + 0x170),
                ("AXI_RD_COMPLETE",  STREAM_APB_BASE + 0x174),
                ("AXI_WR_COMPLETE",  STREAM_APB_BASE + 0x178),
            ]:
                val = await self.uart_read(addr)
                self.log.error(f"    {name:18s} @ 0x{addr:08X} = {val}"
                               if val is None
                               else f"    {name:18s} @ 0x{addr:08X} = 0x{val:08X}")
            return False

        if any_error:
            self.log.error(f"  DMA error flagged: status={st}")
            return False

        self.log.info("  DMA completed (IRQ received)")

        # 6a. Diagnostic: wait until pattern_gen + crc_check beat counts match
        # the descriptor total before checking CRCs. The IRQ fires on the very
        # first per-burst completion packet, which is *much* earlier than the
        # final beat — so reading CRCs immediately after IRQ samples them
        # mid-flight and gives a spurious mismatch on long transfers.
        expected_total = (transfer_bytes // 16) * num_channels * descriptors_per_channel
        prev_rd = -1
        prev_wr = -1
        stuck_for = 0
        max_extra_clocks = max(timeout_clocks, expected_total * 4)
        elapsed = 0
        while elapsed < max_extra_clocks:
            rd_beats = int(self.dut.u_dma_slaves.u_rd_pattern_gen.read_beat_count_total.value)
            wr_beats = int(self.dut.u_dma_slaves.u_wr_crc_check.write_beat_count_total.value)
            if wr_beats >= expected_total and rd_beats >= expected_total:
                self.log.info(f"  Beats reached expected ({expected_total}) after {elapsed} extra clocks")
                break
            # Detect a true hang: counts are not advancing
            if rd_beats == prev_rd and wr_beats == prev_wr:
                stuck_for += 200
                if stuck_for >= 20000:  # 20k cycles with no progress = hung
                    self.log.error(
                        f"  HANG: read={rd_beats} write={wr_beats} expected={expected_total} "
                        f"(stuck for {stuck_for} clocks)")
                    # Probe the write engine to see why it isn't issuing AW.
                    # Verilator flattens generate-block labels, so try several
                    # hierarchical variants and report which ones exist.
                    try:
                        candidates = [
                            'u_stream.u_stream_core',
                            'u_stream.g_stream_core_mon.u_stream_core',
                            'u_stream.g_stream_core_mon_u_stream_core',
                        ]
                        for c in candidates:
                            try:
                                obj = self.dut
                                for part in c.split('.'):
                                    obj = getattr(obj, part)
                                self.log.error(f"  Found path: {c}")
                            except Exception as ex:
                                self.log.error(f"  Path {c} fails: {ex}")
                        # Dump available children of u_stream — only sub-instances
                        try:
                            children = [n for n in dir(self.dut.u_stream) if not n.startswith('_')]
                            interesting = [n for n in children if 'core' in n.lower() or 'engine' in n.lower() or 'sched' in n.lower() or 'sram' in n.lower() or 'g_' in n.lower() or n.startswith('u_')]
                            self.log.error(f"  u_stream interesting children ({len(interesting)}): {interesting}")
                        except Exception as ex:
                            self.log.error(f"  Could not list u_stream children: {ex}")
                        wr_eng = self.dut.u_stream.g_stream_core_mon.u_stream_core.u_axi_write_engine
                        sched = self.dut.u_stream.g_stream_core_mon.u_stream_core.u_scheduler_group_array.gen_scheduler_groups[0].u_scheduler_group.u_scheduler
                        sram = self.dut.u_stream.g_stream_core_mon.u_stream_core.u_sram_controller.gen_units[0].u_sram_unit
                        self.log.error(
                            f"  WR ENGINE probes:\n"
                            f"    sched_wr_valid[0]      = {int(wr_eng.sched_wr_valid.value) & 1}\n"
                            f"    sched_wr_beats[0]      = {int(wr_eng.sched_wr_beats[0].value)}\n"
                            f"    drain_data_avail[0]    = {int(wr_eng.axi_wr_drain_data_avail[0].value)}\n"
                            f"    drain_data_avail (raw) = {int(sram.drain_data_available.value)}\n"
                            f"    bridge_occupancy       = {int(sram.bridge_occupancy.value)}\n"
                            f"    fifo_count             = {int(sram.fifo_count.value)}\n"
                            f"    w_has_data[0]          = {int(wr_eng.w_has_data.value) & 1}\n"
                            f"    w_final_burst[0]       = {int(wr_eng.w_final_burst.value) & 1}\n"
                            f"    w_data_ok[0]           = {int(wr_eng.w_data_ok.value) & 1}\n"
                            f"    w_no_outstanding[0]    = {int(wr_eng.w_no_outstanding.value) & 1}\n"
                            f"    w_arb_request[0]       = {int(wr_eng.w_arb_request.value) & 1}\n"
                            f"    w_transfer_size[0]     = {int(wr_eng.w_transfer_size[0].value)}\n"
                            f"    r_write_beats_remaining = {int(sched.r_write_beats_remaining.value)}\n"
                            f"    r_read_beats_remaining  = {int(sched.r_read_beats_remaining.value)}\n"
                        )
                    except Exception as e:
                        self.log.error(f"  Probe failed: {e}")
                    break
            else:
                stuck_for = 0
            prev_rd, prev_wr = rd_beats, wr_beats
            await self.wait_clocks(self.clk_name, 200)
            elapsed += 200

        # 6b. CRC verification (now post-completion or post-hang)
        crc = await self.read_crc_status(num_channels=num_channels)
        self.log.info(
            f"  CRC: rd_exp=0x{crc.get('rd_expected', 0):08X} "
            f"wr_comp=0x{crc.get('wr_computed', 0):08X} "
            f"match={crc.get('match')} valid={crc.get('valid')}")
        # Per-channel CRC readout (multi-channel verification)
        valid_mask = crc.get('valid_mask', 0) or 0
        match_mask = crc.get('match_mask', 0) or 0
        for ch in range(num_channels):
            rd_v = (crc.get('rd_per_ch') or [None])[ch] if ch < len(crc.get('rd_per_ch') or []) else None
            wr_v = (crc.get('wr_per_ch') or [None])[ch] if ch < len(crc.get('wr_per_ch') or []) else None
            self.log.info(
                f"    ch{ch}: rd=0x{(rd_v or 0):08X} wr=0x{(wr_v or 0):08X} "
                f"valid={(valid_mask >> ch) & 1} match={(match_mask >> ch) & 1}")

        # Diagnostic: directly probe the harness-side beat counters so we
        # can tell beat-loss from reordering when CRCs mismatch. Both signals
        # are now per-channel packed arrays — read the aggregate `_total`
        # outputs instead of treating the array as a scalar.
        try:
            rd_beats = int(self.dut.u_dma_slaves.u_rd_pattern_gen.read_beat_count_total.value)
            wr_beats = int(self.dut.u_dma_slaves.u_wr_crc_check.write_beat_count_total.value)
            expected_beats = transfer_bytes // 16  # DATA_WIDTH=128 → 16 B/beat
            self.log.info(
                f"  Beat counts: read={rd_beats} write={wr_beats} "
                f"expected={expected_beats * num_channels * descriptors_per_channel}")
        except Exception as e:
            self.log.warning(f"  Beat count probe failed: {e}")

        # Read the harness timer's cycle counts (same path characterize.py
        # uses on FPGA). Lets us directly compare sim vs FPGA cycles/beat
        # for the same workload.
        try:
            tcyc = int(self.dut.timer_cycles.value)
            r_first = int(self.dut.timer_r_first.value)
            r_last  = int(self.dut.timer_r_last.value)
            w_first = int(self.dut.timer_w_first.value)
            w_last  = int(self.dut.timer_w_last.value)
            r2r = max(r_last - r_first, 0)
            w2w = max(w_last - w_first, 0)
            beats_total = expected_total
            self.log.info(
                f"  Timer cycles: total={tcyc} r2r={r2r} w2w={w2w} "
                f"  beats={beats_total}  "
                f"  cyc/beat: tot={tcyc / max(beats_total,1):.2f} "
                f"r2r={r2r / max(beats_total,1):.2f} "
                f"w2w={w2w / max(beats_total,1):.2f}")
        except Exception as e:
            self.log.warning(f"  Timer cycles probe failed: {e}")

        # MonBus bulk-trace summary: words written to debug_sram plus the
        # compressor tier stats (live only on a USE_MON_COMPRESSION=1
        # build; 0 otherwise). Lets the compression characterization compare
        # records-out with vs without compression for the same workload.
        try:
            wr_words = await self.uart_read(CSR_DBG_WR_PTR)
            base = HARNESS_CSR_BASE
            t1a = await self.uart_read(base + 0x1E0)
            t1b = await self.uart_read(base + 0x1E4)
            t1c = await self.uart_read(base + 0x1E8)
            t0  = await self.uart_read(base + 0x1EC)
            cam = await self.uart_read(base + 0x1F0)
            recs = t1a + t1b + t1c + t0
            self.log.info(
                f"  MonBus trace: dbg_wr_ptr={wr_words} words "
                f"(~{wr_words // 6} raw-equiv records); "
                f"compressor tier1={t1a}/{t1b}/{t1c} tier0={t0} "
                f"cam_miss={cam} compressed_recs={recs}")
            self._trace_summary = {
                'dbg_wr_ptr_words': wr_words,
                'tier1_a': t1a, 'tier1_b': t1b, 'tier1_c': t1c,
                'tier0': t0, 'cam_miss': cam, 'compressed_records': recs,
            }
        except Exception as e:
            self.log.warning(f"  MonBus trace probe failed: {e}")

        if crc.get('match') and crc.get('valid'):
            self.log.info(f"  DMA test PASSED")
            return True
        else:
            self.log.error(f"  CRC mismatch — DMA test FAILED")
            return False

    def get_report(self) -> dict:
        return {
            'writes_ok': self.writes_ok,
            'reads_ok': self.reads_ok,
            'errors': self.errors,
            'test_level': self.TEST_LEVEL,
        }
