// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ioapic_regs_pkg;

    localparam IOAPIC_REGS_DATA_WIDTH = 32;
    localparam IOAPIC_REGS_MIN_ADDR_WIDTH = 8;
    localparam IOAPIC_REGS_SIZE = 'hd4;

    typedef struct {
        logic [31:0] next;
    } ioapic_regs__IOWIN__data__in_t;

    typedef struct {
        ioapic_regs__IOWIN__data__in_t data;
    } ioapic_regs__IOWIN__in_t;

    typedef struct {
        logic [3:0] next;
    } ioapic_regs__IOAPICARB__arb_id__in_t;

    typedef struct {
        ioapic_regs__IOAPICARB__arb_id__in_t arb_id;
    } ioapic_regs__IOAPICARB__in_t;

    typedef struct {
        logic next;
    } ioapic_regs__redirection_entry__REDIR_LO__deliv_status__in_t;

    typedef struct {
        logic next;
    } ioapic_regs__redirection_entry__REDIR_LO__remote_irr__in_t;

    typedef struct {
        ioapic_regs__redirection_entry__REDIR_LO__deliv_status__in_t deliv_status;
        ioapic_regs__redirection_entry__REDIR_LO__remote_irr__in_t remote_irr;
    } ioapic_regs__redirection_entry__REDIR_LO__in_t;

    typedef struct {
        ioapic_regs__redirection_entry__REDIR_LO__in_t REDIR_LO;
    } ioapic_regs__redirection_entry__in_t;

    typedef struct {
        ioapic_regs__IOWIN__in_t IOWIN;
        ioapic_regs__IOAPICARB__in_t IOAPICARB;
        ioapic_regs__redirection_entry__in_t IOREDTBL[24];
    } ioapic_regs__in_t;

    typedef struct {
        logic [7:0] value;
    } ioapic_regs__IOREGSEL__regsel__out_t;

    typedef struct {
        ioapic_regs__IOREGSEL__regsel__out_t regsel;
    } ioapic_regs__IOREGSEL__out_t;

    typedef struct {
        logic [31:0] value;
    } ioapic_regs__IOWIN__data__out_t;

    typedef struct {
        ioapic_regs__IOWIN__data__out_t data;
    } ioapic_regs__IOWIN__out_t;

    typedef struct {
        logic [3:0] value;
    } ioapic_regs__IOAPICID__apic_id__out_t;

    typedef struct {
        ioapic_regs__IOAPICID__apic_id__out_t apic_id;
    } ioapic_regs__IOAPICID__out_t;

    typedef struct {
        logic [7:0] value;
    } ioapic_regs__redirection_entry__REDIR_LO__vector__out_t;

    typedef struct {
        logic [2:0] value;
    } ioapic_regs__redirection_entry__REDIR_LO__deliv_mode__out_t;

    typedef struct {
        logic value;
    } ioapic_regs__redirection_entry__REDIR_LO__dest_mode__out_t;

    typedef struct {
        logic value;
    } ioapic_regs__redirection_entry__REDIR_LO__polarity__out_t;

    typedef struct {
        logic value;
    } ioapic_regs__redirection_entry__REDIR_LO__trigger_mode__out_t;

    typedef struct {
        logic value;
    } ioapic_regs__redirection_entry__REDIR_LO__mask__out_t;

    typedef struct {
        ioapic_regs__redirection_entry__REDIR_LO__vector__out_t vector;
        ioapic_regs__redirection_entry__REDIR_LO__deliv_mode__out_t deliv_mode;
        ioapic_regs__redirection_entry__REDIR_LO__dest_mode__out_t dest_mode;
        ioapic_regs__redirection_entry__REDIR_LO__polarity__out_t polarity;
        ioapic_regs__redirection_entry__REDIR_LO__trigger_mode__out_t trigger_mode;
        ioapic_regs__redirection_entry__REDIR_LO__mask__out_t mask;
    } ioapic_regs__redirection_entry__REDIR_LO__out_t;

    typedef struct {
        logic [7:0] value;
    } ioapic_regs__redirection_entry__REDIR_HI__destination__out_t;

    typedef struct {
        ioapic_regs__redirection_entry__REDIR_HI__destination__out_t destination;
    } ioapic_regs__redirection_entry__REDIR_HI__out_t;

    typedef struct {
        ioapic_regs__redirection_entry__REDIR_LO__out_t REDIR_LO;
        ioapic_regs__redirection_entry__REDIR_HI__out_t REDIR_HI;
    } ioapic_regs__redirection_entry__out_t;

    typedef struct {
        ioapic_regs__IOREGSEL__out_t IOREGSEL;
        ioapic_regs__IOWIN__out_t IOWIN;
        ioapic_regs__IOAPICID__out_t IOAPICID;
        ioapic_regs__redirection_entry__out_t IOREDTBL[24];
    } ioapic_regs__out_t;
endpackage
