# Filelist for math_fp32_gelu module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_fp32_gelu.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

$REPO_ROOT/rtl/math/math_fp32_gelu.sv
