# Filelist for math_ieee754_2008_fp32_adder module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_ieee754_2008_fp32_adder.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/common/filelists/shifter_barrel.f
-f $REPO_ROOT/rtl/common/filelists/count_leading_zeros.f
$REPO_ROOT/rtl/math/math_ieee754_2008_fp32_adder.sv
