# Filelist for math_prefix_cell module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_prefix_cell.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

$REPO_ROOT/rtl/math/math_prefix_cell.sv
