# Filelist for math_adder_ripple_carry module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_adder_ripple_carry.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/math/filelists/math_adder_full.f
$REPO_ROOT/rtl/math/math_adder_ripple_carry.sv
