# Filelist for math_int_to_bf16 module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_int_to_bf16.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/common/filelists/count_leading_zeros.f
$REPO_ROOT/rtl/math/math_int_to_bf16.sv
