# Filelist for math_multiplier_dadda_4to2_024 module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_multiplier_dadda_4to2_024.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/math/filelists/math_adder_full.f
-f $REPO_ROOT/rtl/math/filelists/math_compressor_4to2.f
-f $REPO_ROOT/rtl/math/filelists/math_adder_han_carlson_048.f
$REPO_ROOT/rtl/math/math_multiplier_dadda_4to2_024.sv
