# Filelist for math_adder_brent_kung_grouppg_032 module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_adder_brent_kung_grouppg_032.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/math/filelists/math_adder_brent_kung_gray.f
-f $REPO_ROOT/rtl/math/filelists/math_adder_brent_kung_black.f
$REPO_ROOT/rtl/math/math_adder_brent_kung_grouppg_032.sv
