# Filelist for math_fp8_e5m2_multiplier module (generated by bin/gen_math_filelists.py)
# Location: rtl/math/filelists/math_fp8_e5m2_multiplier.f

# Include directories
+incdir+$REPO_ROOT/rtl/amba/includes

# Header files with macros (MUST be compiled first)
$REPO_ROOT/rtl/amba/includes/reset_defs.svh

-f $REPO_ROOT/rtl/math/filelists/math_fp8_e5m2_mantissa_mult.f
-f $REPO_ROOT/rtl/math/filelists/math_fp8_e5m2_exponent_adder.f
$REPO_ROOT/rtl/math/math_fp8_e5m2_multiplier.sv
