# Genesys 2 DDR3 pin constraints -- GENERATED by bin/gen_genesys2_ddr3_xdc.py
# from litex_boards/platforms/digilent_genesys2.py. Do not hand-edit: regenerate.
#
# 2 x MT41J256M16 (x16) side by side -> 32-bit DQ, 4 byte groups, 8 banks.


# ddram_a  (15 pins, SSTL15)
set_property -dict {PACKAGE_PIN AC12  IOSTANDARD SSTL15} [get_ports {ddram_a[0]}]
set_property -dict {PACKAGE_PIN AE8  IOSTANDARD SSTL15} [get_ports {ddram_a[1]}]
set_property -dict {PACKAGE_PIN AD8  IOSTANDARD SSTL15} [get_ports {ddram_a[2]}]
set_property -dict {PACKAGE_PIN AC10  IOSTANDARD SSTL15} [get_ports {ddram_a[3]}]
set_property -dict {PACKAGE_PIN AD9  IOSTANDARD SSTL15} [get_ports {ddram_a[4]}]
set_property -dict {PACKAGE_PIN AA13  IOSTANDARD SSTL15} [get_ports {ddram_a[5]}]
set_property -dict {PACKAGE_PIN AA10  IOSTANDARD SSTL15} [get_ports {ddram_a[6]}]
set_property -dict {PACKAGE_PIN AA11  IOSTANDARD SSTL15} [get_ports {ddram_a[7]}]
set_property -dict {PACKAGE_PIN Y10  IOSTANDARD SSTL15} [get_ports {ddram_a[8]}]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD SSTL15} [get_ports {ddram_a[9]}]
set_property -dict {PACKAGE_PIN AB8  IOSTANDARD SSTL15} [get_ports {ddram_a[10]}]
set_property -dict {PACKAGE_PIN AA8  IOSTANDARD SSTL15} [get_ports {ddram_a[11]}]
set_property -dict {PACKAGE_PIN AB12  IOSTANDARD SSTL15} [get_ports {ddram_a[12]}]
set_property -dict {PACKAGE_PIN AA12  IOSTANDARD SSTL15} [get_ports {ddram_a[13]}]
set_property -dict {PACKAGE_PIN AH9  IOSTANDARD SSTL15} [get_ports {ddram_a[14]}]

# ddram_ba  (3 pins, SSTL15)
set_property -dict {PACKAGE_PIN AE9  IOSTANDARD SSTL15} [get_ports {ddram_ba[0]}]
set_property -dict {PACKAGE_PIN AB10  IOSTANDARD SSTL15} [get_ports {ddram_ba[1]}]
set_property -dict {PACKAGE_PIN AC11  IOSTANDARD SSTL15} [get_ports {ddram_ba[2]}]

# ddram_dq  (32 pins, SSTL15_T_DCI)
set_property -dict {PACKAGE_PIN AD3  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[0]}]
set_property -dict {PACKAGE_PIN AC2  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[1]}]
set_property -dict {PACKAGE_PIN AC1  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[2]}]
set_property -dict {PACKAGE_PIN AC5  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[3]}]
set_property -dict {PACKAGE_PIN AC4  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[4]}]
set_property -dict {PACKAGE_PIN AD6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[5]}]
set_property -dict {PACKAGE_PIN AE6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[6]}]
set_property -dict {PACKAGE_PIN AC7  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[7]}]
set_property -dict {PACKAGE_PIN AF2  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[8]}]
set_property -dict {PACKAGE_PIN AE1  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[9]}]
set_property -dict {PACKAGE_PIN AF1  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[10]}]
set_property -dict {PACKAGE_PIN AE4  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[11]}]
set_property -dict {PACKAGE_PIN AE3  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[12]}]
set_property -dict {PACKAGE_PIN AE5  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[13]}]
set_property -dict {PACKAGE_PIN AF5  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[14]}]
set_property -dict {PACKAGE_PIN AF6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[15]}]
set_property -dict {PACKAGE_PIN AJ4  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[16]}]
set_property -dict {PACKAGE_PIN AH6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[17]}]
set_property -dict {PACKAGE_PIN AH5  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[18]}]
set_property -dict {PACKAGE_PIN AH2  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[19]}]
set_property -dict {PACKAGE_PIN AJ2  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[20]}]
set_property -dict {PACKAGE_PIN AJ1  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[21]}]
set_property -dict {PACKAGE_PIN AK1  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[22]}]
set_property -dict {PACKAGE_PIN AJ3  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[23]}]
set_property -dict {PACKAGE_PIN AF7  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[24]}]
set_property -dict {PACKAGE_PIN AG7  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[25]}]
set_property -dict {PACKAGE_PIN AJ6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[26]}]
set_property -dict {PACKAGE_PIN AK6  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[27]}]
set_property -dict {PACKAGE_PIN AJ8  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[28]}]
set_property -dict {PACKAGE_PIN AK8  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[29]}]
set_property -dict {PACKAGE_PIN AK5  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[30]}]
set_property -dict {PACKAGE_PIN AK4  IOSTANDARD SSTL15_T_DCI} [get_ports {ddram_dq[31]}]

# ddram_dm  (4 pins, SSTL15)
set_property -dict {PACKAGE_PIN AD4  IOSTANDARD SSTL15} [get_ports {ddram_dm[0]}]
set_property -dict {PACKAGE_PIN AF3  IOSTANDARD SSTL15} [get_ports {ddram_dm[1]}]
set_property -dict {PACKAGE_PIN AH4  IOSTANDARD SSTL15} [get_ports {ddram_dm[2]}]
set_property -dict {PACKAGE_PIN AF8  IOSTANDARD SSTL15} [get_ports {ddram_dm[3]}]

# ddram_dqs_p  (4 pins, DIFF_SSTL15)
set_property -dict {PACKAGE_PIN AD2  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_p[0]}]
set_property -dict {PACKAGE_PIN AG4  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_p[1]}]
set_property -dict {PACKAGE_PIN AG2  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_p[2]}]
set_property -dict {PACKAGE_PIN AH7  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_p[3]}]

# ddram_dqs_n  (4 pins, DIFF_SSTL15)
set_property -dict {PACKAGE_PIN AD1  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_n[0]}]
set_property -dict {PACKAGE_PIN AG3  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_n[1]}]
set_property -dict {PACKAGE_PIN AH1  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_n[2]}]
set_property -dict {PACKAGE_PIN AJ7  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_dqs_n[3]}]

# ddram_ras_n  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AE11  IOSTANDARD SSTL15} [get_ports {ddram_ras_n}]

# ddram_cas_n  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AF11  IOSTANDARD SSTL15} [get_ports {ddram_cas_n}]

# ddram_we_n  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AG13  IOSTANDARD SSTL15} [get_ports {ddram_we_n}]

# ddram_cs_n  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AH12  IOSTANDARD SSTL15} [get_ports {ddram_cs_n}]

# ddram_clk_p  (1 pin, DIFF_SSTL15)
set_property -dict {PACKAGE_PIN AB9  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_clk_p}]

# ddram_clk_n  (1 pin, DIFF_SSTL15)
set_property -dict {PACKAGE_PIN AC9  IOSTANDARD DIFF_SSTL15} [get_ports {ddram_clk_n}]

# ddram_cke  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AJ9  IOSTANDARD SSTL15} [get_ports {ddram_cke}]

# ddram_odt  (1 pin, SSTL15)
set_property -dict {PACKAGE_PIN AK9  IOSTANDARD SSTL15} [get_ports {ddram_odt}]

# ddram_reset_n  (1 pin, LVCMOS15)
set_property -dict {PACKAGE_PIN AG5  IOSTANDARD LVCMOS15} [get_ports {ddram_reset_n}]

# VCCAUX_IO=HIGH and SLEW=FAST come from the platform's Misc() on the
# ddram group; they are bank-wide requirements for 1.5 V SSTL, not per-pin taste.
set_property SLEW FAST [get_ports -filter {NAME =~ "ddram_*"}]
