// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop_sram_controller_unit__pi14.h"

VL_ATTR_COLD void Vtop_sram_controller_unit__pi14___eval_initial__TOP__stream_top_ch8__DOT__g_stream_core__DOT__u_stream_core__DOT__u_sram_controller__DOT__gen_channel_units__BRA__0__KET____DOT__u_channel_unit(Vtop_sram_controller_unit__pi14* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vtop_sram_controller_unit__pi14___eval_initial__TOP__stream_top_ch8__DOT__g_stream_core__DOT__u_stream_core__DOT__u_sram_controller__DOT__gen_channel_units__BRA__0__KET____DOT__u_channel_unit\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    VL_WRITEF_NX("sram_controller_unit: SRAM_DEPTH=4096, ADDR_WIDTH=12\nstream_alloc_ctrl: DEPTH=4096, ADDR_WIDTH=12\n",0);
    vlSelfRef.u_alloc_ctrl__DOT__read_pointer_inst__DOT__w_max_val = 0xfffU;
    VL_WRITEF_NX("stream_drain_ctrl: DEPTH=4096, ADDR_WIDTH=12\n",0);
    vlSelfRef.u_drain_ctrl__DOT__write_pointer_inst__DOT__w_max_val = 0xfffU;
    vlSelfRef.u_channel_fifo__DOT__write_pointer_inst__DOT__w_max_val = 0xfffU;
    vlSelfRef.u_channel_fifo__DOT__read_pointer_inst__DOT__w_max_val = 0xfffU;
    vlSelfRef.u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__w_max_val = 3U;
    vlSelfRef.u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__w_max_val = 3U;
}

VL_ATTR_COLD void Vtop_sram_controller_unit__pi14___ctor_var_reset(Vtop_sram_controller_unit__pi14* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vtop_sram_controller_unit__pi14___ctor_var_reset\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clk = VL_RAND_RESET_I(1);
    vlSelf->rst_n = VL_RAND_RESET_I(1);
    vlSelf->axi_rd_alloc_req = VL_RAND_RESET_I(1);
    vlSelf->axi_rd_alloc_size = VL_RAND_RESET_I(8);
    vlSelf->axi_rd_alloc_space_free = VL_RAND_RESET_I(13);
    vlSelf->axi_rd_sram_valid = VL_RAND_RESET_I(1);
    vlSelf->axi_rd_sram_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->axi_rd_sram_data);
    vlSelf->axi_wr_drain_data_avail = VL_RAND_RESET_I(13);
    vlSelf->axi_wr_drain_req = VL_RAND_RESET_I(1);
    vlSelf->axi_wr_drain_size = VL_RAND_RESET_I(8);
    vlSelf->axi_wr_sram_valid = VL_RAND_RESET_I(1);
    vlSelf->axi_wr_sram_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->axi_wr_sram_data);
    vlSelf->dbg_bridge_pending = VL_RAND_RESET_I(1);
    vlSelf->dbg_bridge_out_valid = VL_RAND_RESET_I(1);
    vlSelf->alloc_space_free = VL_RAND_RESET_I(13);
    vlSelf->drain_data_available = VL_RAND_RESET_I(13);
    vlSelf->fifo_rd_valid_internal = VL_RAND_RESET_I(1);
    vlSelf->fifo_rd_ready_internal = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->fifo_rd_data_internal);
    vlSelf->fifo_count = VL_RAND_RESET_I(13);
    vlSelf->fifo_empty = VL_RAND_RESET_I(1);
    vlSelf->fifo_full = VL_RAND_RESET_I(1);
    vlSelf->bridge_occupancy = VL_RAND_RESET_I(3);
    vlSelf->u_alloc_ctrl__DOT__axi_aclk = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__axi_aresetn = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__wr_valid = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__wr_size = VL_RAND_RESET_I(8);
    vlSelf->u_alloc_ctrl__DOT__wr_ready = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__rd_valid = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__rd_ready = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__space_free = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__r_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__r_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__w_wr_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__w_rd_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__r_wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__r_wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__r_rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__r_rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__w_count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__w_write = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__w_read = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT____Vcellinp__read_pointer_inst__enable = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__read_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(12);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_clk = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_clk = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_almost_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rd_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_almost_full_count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_almost_empty_count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty = VL_RAND_RESET_I(1);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__r_count = VL_RAND_RESET_I(13);
    vlSelf->u_alloc_ctrl__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__axi_aclk = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__axi_aresetn = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__wr_valid = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__wr_ready = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__rd_valid = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__rd_size = VL_RAND_RESET_I(8);
    vlSelf->u_drain_ctrl__DOT__rd_ready = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__data_available = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__r_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__r_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__w_wr_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__w_rd_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__r_wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__r_wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__r_rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__r_rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__w_count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__w_available_data = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__w_write = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__w_read = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT____Vcellinp__write_pointer_inst__enable = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__write_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(12);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_clk = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_clk = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_almost_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rd_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_almost_full_count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_almost_empty_count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty = VL_RAND_RESET_I(1);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__w_count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__r_count = VL_RAND_RESET_I(13);
    vlSelf->u_drain_ctrl__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__axi_aclk = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__axi_aresetn = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__wr_valid = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__wr_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_channel_fifo__DOT__wr_data);
    vlSelf->u_channel_fifo__DOT__rd_ready = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__rd_valid = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_channel_fifo__DOT__rd_data);
    vlSelf->u_channel_fifo__DOT__r_wr_addr = VL_RAND_RESET_I(12);
    vlSelf->u_channel_fifo__DOT__r_rd_addr = VL_RAND_RESET_I(12);
    vlSelf->u_channel_fifo__DOT__r_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__r_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__w_wr_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__w_rd_ptr_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__r_wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__r_wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__r_rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__r_rd_almost_empty = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_channel_fifo__DOT__w_rd_data);
    vlSelf->u_channel_fifo__DOT__w_write = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__w_read = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT____Vcellinp__write_pointer_inst__enable = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 4096; ++__Vi0) {
        VL_RAND_RESET_W(512, vlSelf->u_channel_fifo__DOT__gen_auto__DOT__mem[__Vi0]);
    }
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__write_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(12);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__read_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(12);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wr_clk = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wr_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rd_clk = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rd_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rd_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_almost_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_rd_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_almost_full_count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_almost_empty_count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty = VL_RAND_RESET_I(1);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__w_count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__r_count = VL_RAND_RESET_I(13);
    vlSelf->u_channel_fifo__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed = VL_RAND_RESET_I(13);
    vlSelf->u_latency_bridge__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__s_valid = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__s_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__s_data);
    vlSelf->u_latency_bridge__DOT__m_valid = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__m_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__m_data);
    vlSelf->u_latency_bridge__DOT__occupancy = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__dbg_r_pending = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__dbg_r_out_valid = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__r_drain_ip = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__skid_wr_valid = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__skid_wr_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__skid_wr_data);
    vlSelf->u_latency_bridge__DOT__skid_count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__w_draining_now = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__w_write_stalled = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__pending_count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__w_room_available = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__w_drain_fifo = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__r_prev_occupancy = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__axi_aclk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__axi_aresetn = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__wr_valid = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__wr_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__wr_data);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__rd_ready = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__rd_valid = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__rd_data);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_addr = VL_RAND_RESET_I(2);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_addr = VL_RAND_RESET_I(2);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__w_wr_ptr_bin_next = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__w_rd_ptr_bin_next = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_almost_empty = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__w_rd_data);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__w_write = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__w_read = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT____Vcellinp__read_pointer_inst__enable = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        VL_RAND_RESET_W(512, vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__gen_auto__DOT__mem[__Vi0]);
    }
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(2);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__enable = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__counter_bin_curr = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__counter_bin_next = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__w_max_val = VL_RAND_RESET_I(2);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_clk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_clk = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_rst_n = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_full = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_almost_full = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_empty = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_almost_empty = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_almost_full_d = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rd_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_almost_full_count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_almost_empty_count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty = VL_RAND_RESET_I(1);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_count = VL_RAND_RESET_I(3);
    vlSelf->u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__r_count = VL_RAND_RESET_I(3);
}
