// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_SRAM_CONTROLLER_UNIT__PI14_H_
#define VERILATED_VTOP_SRAM_CONTROLLER_UNIT__PI14_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_sram_controller_unit__pi14 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(axi_rd_alloc_req,0,0);
        VL_IN8(axi_rd_alloc_size,7,0);
        VL_IN8(axi_rd_sram_valid,0,0);
        VL_OUT8(axi_rd_sram_ready,0,0);
        VL_IN8(axi_wr_drain_req,0,0);
        VL_IN8(axi_wr_drain_size,7,0);
        VL_OUT8(axi_wr_sram_valid,0,0);
        VL_IN8(axi_wr_sram_ready,0,0);
        VL_OUT8(dbg_bridge_pending,0,0);
        VL_OUT8(dbg_bridge_out_valid,0,0);
        CData/*0:0*/ fifo_rd_valid_internal;
        CData/*0:0*/ fifo_rd_ready_internal;
        CData/*0:0*/ fifo_empty;
        CData/*0:0*/ fifo_full;
        CData/*2:0*/ bridge_occupancy;
        CData/*0:0*/ u_alloc_ctrl__DOT__axi_aclk;
        CData/*0:0*/ u_alloc_ctrl__DOT__axi_aresetn;
        CData/*0:0*/ u_alloc_ctrl__DOT__wr_valid;
        CData/*7:0*/ u_alloc_ctrl__DOT__wr_size;
        CData/*0:0*/ u_alloc_ctrl__DOT__wr_ready;
        CData/*0:0*/ u_alloc_ctrl__DOT__rd_valid;
        CData/*0:0*/ u_alloc_ctrl__DOT__rd_ready;
        CData/*0:0*/ u_alloc_ctrl__DOT__wr_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__wr_almost_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__rd_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__rd_almost_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__r_wr_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__r_wr_almost_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__r_rd_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__r_rd_almost_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__w_write;
        CData/*0:0*/ u_alloc_ctrl__DOT__w_read;
        CData/*0:0*/ u_alloc_ctrl__DOT____Vcellinp__read_pointer_inst__enable;
        CData/*0:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__clk;
        CData/*0:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__enable;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_clk;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_rst_n;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_clk;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_rst_n;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_almost_full;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_almost_empty;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_full_d;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_almost_full_d;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rd_empty_d;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d;
        CData/*0:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__axi_aclk;
        CData/*0:0*/ u_drain_ctrl__DOT__axi_aresetn;
        CData/*0:0*/ u_drain_ctrl__DOT__wr_valid;
        CData/*0:0*/ u_drain_ctrl__DOT__wr_ready;
        CData/*0:0*/ u_drain_ctrl__DOT__rd_valid;
        CData/*7:0*/ u_drain_ctrl__DOT__rd_size;
        CData/*0:0*/ u_drain_ctrl__DOT__rd_ready;
        CData/*0:0*/ u_drain_ctrl__DOT__wr_full;
        CData/*0:0*/ u_drain_ctrl__DOT__wr_almost_full;
        CData/*0:0*/ u_drain_ctrl__DOT__rd_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__rd_almost_empty;
    };
    struct {
        CData/*0:0*/ u_drain_ctrl__DOT__r_wr_full;
        CData/*0:0*/ u_drain_ctrl__DOT__r_wr_almost_full;
        CData/*0:0*/ u_drain_ctrl__DOT__r_rd_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__r_rd_almost_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__w_write;
        CData/*0:0*/ u_drain_ctrl__DOT__w_read;
        CData/*0:0*/ u_drain_ctrl__DOT____Vcellinp__write_pointer_inst__enable;
        CData/*0:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__clk;
        CData/*0:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__enable;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_clk;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_rst_n;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_clk;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_rst_n;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_full;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_almost_full;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_almost_empty;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_full_d;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_almost_full_d;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rd_empty_d;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d;
        CData/*0:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty;
        CData/*0:0*/ u_channel_fifo__DOT__axi_aclk;
        CData/*0:0*/ u_channel_fifo__DOT__axi_aresetn;
        CData/*0:0*/ u_channel_fifo__DOT__wr_valid;
        CData/*0:0*/ u_channel_fifo__DOT__wr_ready;
        CData/*0:0*/ u_channel_fifo__DOT__rd_ready;
        CData/*0:0*/ u_channel_fifo__DOT__rd_valid;
        CData/*0:0*/ u_channel_fifo__DOT__r_wr_full;
        CData/*0:0*/ u_channel_fifo__DOT__r_wr_almost_full;
        CData/*0:0*/ u_channel_fifo__DOT__r_rd_empty;
        CData/*0:0*/ u_channel_fifo__DOT__r_rd_almost_empty;
        CData/*0:0*/ u_channel_fifo__DOT__w_write;
        CData/*0:0*/ u_channel_fifo__DOT__w_read;
        CData/*0:0*/ u_channel_fifo__DOT____Vcellinp__write_pointer_inst__enable;
        CData/*0:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__clk;
        CData/*0:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__enable;
        CData/*0:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__clk;
        CData/*0:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__enable;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wr_clk;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wr_rst_n;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rd_clk;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rd_rst_n;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wr_full;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wr_almost_full;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rd_empty;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rd_almost_empty;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_full_d;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_almost_full_d;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_rd_empty_d;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d;
        CData/*0:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty;
        CData/*0:0*/ u_latency_bridge__DOT__clk;
        CData/*0:0*/ u_latency_bridge__DOT__rst_n;
        CData/*0:0*/ u_latency_bridge__DOT__s_valid;
        CData/*0:0*/ u_latency_bridge__DOT__s_ready;
        CData/*0:0*/ u_latency_bridge__DOT__m_valid;
    };
    struct {
        CData/*0:0*/ u_latency_bridge__DOT__m_ready;
        CData/*2:0*/ u_latency_bridge__DOT__occupancy;
        CData/*0:0*/ u_latency_bridge__DOT__dbg_r_pending;
        CData/*0:0*/ u_latency_bridge__DOT__dbg_r_out_valid;
        CData/*0:0*/ u_latency_bridge__DOT__r_drain_ip;
        CData/*0:0*/ u_latency_bridge__DOT__skid_wr_valid;
        CData/*0:0*/ u_latency_bridge__DOT__skid_wr_ready;
        CData/*2:0*/ u_latency_bridge__DOT__skid_count;
        CData/*0:0*/ u_latency_bridge__DOT__w_draining_now;
        CData/*0:0*/ u_latency_bridge__DOT__w_write_stalled;
        CData/*2:0*/ u_latency_bridge__DOT__pending_count;
        CData/*0:0*/ u_latency_bridge__DOT__w_room_available;
        CData/*0:0*/ u_latency_bridge__DOT__w_drain_fifo;
        CData/*2:0*/ u_latency_bridge__DOT__r_prev_occupancy;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__axi_aclk;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__axi_aresetn;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__wr_valid;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__wr_ready;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__rd_ready;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__count;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__rd_valid;
        CData/*1:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_addr;
        CData/*1:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_addr;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__w_wr_ptr_bin_next;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__w_rd_ptr_bin_next;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_full;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_wr_almost_full;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_empty;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__r_rd_almost_empty;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__w_write;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__w_read;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT____Vcellinp__read_pointer_inst__enable;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__clk;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__enable;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__counter_bin_curr;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__counter_bin_next;
        CData/*1:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__w_max_val;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__clk;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__rst_n;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__enable;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__counter_bin_curr;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__counter_bin_next;
        CData/*1:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__w_max_val;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_clk;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_rst_n;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_clk;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_rst_n;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__count;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_full;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__wr_almost_full;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_empty;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__rd_almost_empty;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wdom_ptr_xor;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_full_d;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_almost_full_d;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rd_empty_d;
    };
    struct {
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rd_almost_empty_d;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_almost_full_count;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_almost_empty_count;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty;
        CData/*0:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_rdom_ptr_xor_for_empty;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__w_count;
        CData/*2:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__r_count;
        VL_OUT16(axi_rd_alloc_space_free,12,0);
        VL_OUT16(axi_wr_drain_data_avail,12,0);
        SData/*12:0*/ alloc_space_free;
        SData/*12:0*/ drain_data_available;
        SData/*12:0*/ fifo_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__space_free;
        SData/*12:0*/ u_alloc_ctrl__DOT__r_wr_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__r_rd_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__w_wr_ptr_bin_next;
        SData/*12:0*/ u_alloc_ctrl__DOT__w_rd_ptr_bin_next;
        SData/*12:0*/ u_alloc_ctrl__DOT__w_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__counter_bin_curr;
        SData/*12:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__counter_bin_next;
        SData/*11:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__w_max_val;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wr_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rd_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__count;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_almost_full_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_almost_empty_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__w_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__r_count;
        SData/*12:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed;
        SData/*12:0*/ u_drain_ctrl__DOT__data_available;
        SData/*12:0*/ u_drain_ctrl__DOT__r_wr_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__r_rd_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__w_wr_ptr_bin_next;
        SData/*12:0*/ u_drain_ctrl__DOT__w_rd_ptr_bin_next;
        SData/*12:0*/ u_drain_ctrl__DOT__w_count;
        SData/*12:0*/ u_drain_ctrl__DOT__w_available_data;
        SData/*12:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__counter_bin_curr;
        SData/*12:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__counter_bin_next;
        SData/*11:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__w_max_val;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wr_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rd_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__count;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_almost_full_count;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_almost_empty_count;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__w_count;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__r_count;
        SData/*12:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed;
        SData/*12:0*/ u_channel_fifo__DOT__count;
        SData/*11:0*/ u_channel_fifo__DOT__r_wr_addr;
        SData/*11:0*/ u_channel_fifo__DOT__r_rd_addr;
        SData/*12:0*/ u_channel_fifo__DOT__r_wr_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__r_rd_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__w_wr_ptr_bin_next;
        SData/*12:0*/ u_channel_fifo__DOT__w_rd_ptr_bin_next;
        SData/*12:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__counter_bin_curr;
        SData/*12:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__counter_bin_next;
        SData/*11:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__w_max_val;
        SData/*12:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__counter_bin_curr;
    };
    struct {
        SData/*12:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__counter_bin_next;
        SData/*11:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__w_max_val;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wr_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__wdom_rd_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rd_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__rdom_wr_ptr_bin;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__count;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_almost_full_count;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_almost_empty_count;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_wr_ptr_for_empty;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__w_count;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__r_count;
        SData/*12:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__gen_flop_mode__DOT__r_rdom_wr_ptr_bin_delayed;
        VL_INW(axi_rd_sram_data,511,0,16);
        VL_OUTW(axi_wr_sram_data,511,0,16);
        VlWide<16>/*511:0*/ fifo_rd_data_internal;
        VlWide<16>/*511:0*/ u_channel_fifo__DOT__wr_data;
        VlWide<16>/*511:0*/ u_channel_fifo__DOT__rd_data;
        VlWide<16>/*511:0*/ u_channel_fifo__DOT__w_rd_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__s_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__m_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__skid_wr_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__wr_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__rd_data;
        VlWide<16>/*511:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__w_rd_data;
        VlUnpacked<VlWide<16>/*511:0*/, 4096> u_channel_fifo__DOT__gen_auto__DOT__mem;
        VlUnpacked<VlWide<16>/*511:0*/, 4> u_latency_bridge__DOT__u_skid_buffer__DOT__gen_auto__DOT__mem;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ DATA_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ SRAM_DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ SEG_COUNT_WIDTH = 0x0000000dU;
    static constexpr IData/*31:0*/ DW = 0x00000200U;
    static constexpr IData/*31:0*/ SD = 0x00001000U;
    static constexpr IData/*31:0*/ SCW = 0x0000000dU;
    static constexpr IData/*31:0*/ ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__WIDTH = 0x0000000dU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__read_pointer_inst__DOT__MAX = 0x00001000U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__AFULL = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__AEMPTY = 1U;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__AFT = 0x00000fffU;
    static constexpr IData/*31:0*/ u_alloc_ctrl__DOT__fifo_control_inst__DOT__AET = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__WIDTH = 0x0000000dU;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__write_pointer_inst__DOT__MAX = 0x00001000U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__AFULL = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__AEMPTY = 1U;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__AFT = 0x00000fffU;
    static constexpr IData/*31:0*/ u_drain_ctrl__DOT__fifo_control_inst__DOT__AET = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__MEM_STYLE = 0U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__DATA_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__DW = 0x00000200U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__WIDTH = 0x0000000dU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__write_pointer_inst__DOT__MAX = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__WIDTH = 0x0000000dU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__read_pointer_inst__DOT__MAX = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__REGISTERED = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__D = 0x00001000U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__AFULL = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__AEMPTY = 1U;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__AFT = 0x00000fffU;
    static constexpr IData/*31:0*/ u_channel_fifo__DOT__fifo_control_inst__DOT__AET = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__DATA_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__SKID_DEPTH = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__DW = 0x00000200U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__MEM_STYLE = 0U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__REGISTERED = 0U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__DATA_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__DEPTH = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__DW = 0x00000200U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__D = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__AW = 2U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__WIDTH = 3U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__write_pointer_inst__DOT__MAX = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__WIDTH = 3U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__read_pointer_inst__DOT__MAX = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__ADDR_WIDTH = 2U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__DEPTH = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__ALMOST_WR_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__ALMOST_RD_MARGIN = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__REGISTERED = 0U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__D = 4U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__AW = 2U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__AFULL = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__AEMPTY = 1U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__AFT = 3U;
    static constexpr IData/*31:0*/ u_latency_bridge__DOT__u_skid_buffer__DOT__fifo_control_inst__DOT__AET = 1U;
    static const std::string u_channel_fifo__DOT__INSTANCE_NAME;
    static const std::string u_latency_bridge__DOT__u_skid_buffer__DOT__INSTANCE_NAME;

    // CONSTRUCTORS
    Vtop_sram_controller_unit__pi14(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_sram_controller_unit__pi14();
    VL_UNCOPYABLE(Vtop_sram_controller_unit__pi14);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
