# SYNTHESIS filelist for the scoria DDR3 board build on the Genesys 2.
#
# This list is what VIVADO reads. It names the REAL generated PHY, which is
# Xilinx-primitive soup (OSERDESE2, ISERDESE2, IDELAYE2, ODELAYE2) and which
# Verilator cannot elaborate -- use scoria_char_board_lint.f for lint, which
# substitutes a blackbox stub derived from this same PHY.
#
# The PHY is NOT tracked RTL: it is generated by bin/gen_k7ddrphy.py into
# rtl/generated/, like LiteDRAM's core in build-litedram. Generate it before
# synthesis (`make phy`) or Vivado fails on a missing module 90 seconds in,
# which is the same trap regen.sh records for VexRiscv.

+incdir+$REPO_ROOT/projects/components/mem-ctrl-ip/research-ip/scoria-ddr3-lpddr3/rtl/includes
+incdir+$REPO_ROOT/rtl/amba/includes

# The harness, which carries the controller, the engine and the instruments.
-f $REPO_ROOT/projects/fpga-systems/Genesys2/mem-ctrl-ip/scoria/rtl/filelists/scoria_char_harness.f

# Flat DFI -> per-phase DFI. Lives with the PHY it feeds, not with the harness.
$REPO_ROOT/projects/fpga-systems/Genesys2/mem-ctrl-ip/scoria/rtl/dfi_flat_to_k7ddrphy.sv

# The generated PHY body.
$REPO_ROOT/projects/fpga-systems/Genesys2/mem-ctrl-ip/scoria/build-scoria/rtl/generated/k7ddrphy.v

# The board top.
$REPO_ROOT/projects/fpga-systems/Genesys2/mem-ctrl-ip/scoria/build-scoria/rtl/scoria_char_top.sv
