#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# patch_flat.py - Fix multi-driver issues in sv2v-flattened Verilog for yosys
#
# Problem: The descriptor_engine_beats RTL uses two separate always_ff blocks
# that both drive r_descriptor_error:
#   1. Main FSM block - handles reset, state-based error setting/clearing
#   2. APB address-0 check - sets error on invalid APB address
#
# sv2v correctly translates both into separate always @(posedge clk) blocks,
# but yosys treats this as a multi-driver error since plain Verilog doesn't
# support multiple procedural drivers for the same reg.
#
# Fix: Remove the small standalone always block and fold its condition into
# the main FSM block's else branch, just before the channel_reset override.
#
# Usage: python3 patch_flat.py input.v output.v

import re
import sys


def patch_multi_driver(text: str) -> str:
    """Remove the standalone APB address-0 error always block and merge
    its logic into the main FSM always block."""

    # Pattern: the small standalone always block generated by sv2v
    # It looks like:
    #   always @(posedge clk)
    #       if (!rst_n)
    #           ;
    #       else if (apb_valid && !w_apb_addr_valid)
    #           r_descriptor_error <= 1'b1;
    #
    # We match this block and remove it entirely.
    standalone_pattern = re.compile(
        r'\n\talways @\(posedge clk\)\n'
        r'\t\tif \(!rst_n\)\n'
        r'\t\t\t;\n'
        r'\t\telse if \(apb_valid && !w_apb_addr_valid\)\n'
        r'\t\t\tr_descriptor_error <= 1\'b1;\n',
        re.MULTILINE,
    )

    match = standalone_pattern.search(text)
    if not match:
        print("WARNING: Could not find standalone APB error always block to patch",
              file=sys.stderr)
        print("         The flat file may have a different structure than expected.",
              file=sys.stderr)
        print("         Passing through unmodified.", file=sys.stderr)
        return text

    # Remove the standalone block
    text = text[:match.start()] + '\n' + text[match.end():]

    # Now insert the APB address-0 error check into the main FSM block.
    # We insert it just before the channel_reset override, which looks like:
    #   if (r_channel_reset_active) begin
    #       ...
    #       r_descriptor_error <= 1'b0;
    #   end
    #
    # We add:
    #   if (apb_valid && !w_apb_addr_valid)
    #       r_descriptor_error <= 1'b1;
    #
    # right before the channel_reset block so channel_reset still takes priority.

    insert_marker = '\t\t\tif (r_channel_reset_active) begin\n'
    insert_code = (
        '\t\t\t// APB address-0 error detection (merged from separate always block)\n'
        '\t\t\tif (apb_valid && !w_apb_addr_valid)\n'
        '\t\t\t\tr_descriptor_error <= 1\'b1;\n'
    )

    idx = text.find(insert_marker)
    if idx == -1:
        print("WARNING: Could not find r_channel_reset_active block to insert APB error check",
              file=sys.stderr)
        print("         Standalone block was removed but merge point not found.", file=sys.stderr)
        return text

    text = text[:idx] + insert_code + text[idx:]

    return text


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.v> <output.v>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(input_path, 'r') as f:
        content = f.read()

    patched = patch_multi_driver(content)

    with open(output_path, 'w') as f:
        f.write(patched)

    print(f"Patched {input_path} -> {output_path}")


if __name__ == '__main__':
    main()
