// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package smbus_regs_pkg;

    localparam SMBUS_REGS_DATA_WIDTH = 32;
    localparam SMBUS_REGS_MIN_ADDR_WIDTH = 6;
    localparam SMBUS_REGS_SIZE = 'h3c;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_CONTROL__fifo_reset__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_CONTROL__soft_reset__in_t;

    typedef struct {
        smbus_regs__SMBUS_CONTROL__fifo_reset__in_t fifo_reset;
        smbus_regs__SMBUS_CONTROL__soft_reset__in_t soft_reset;
    } smbus_regs__SMBUS_CONTROL__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__busy__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__bus_error__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__timeout_error__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__pec_error__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__arb_lost__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__nak_received__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__slave_addressed__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_STATUS__complete__in_t;

    typedef struct {
        logic [3:0] next;
    } smbus_regs__SMBUS_STATUS__fsm_state__in_t;

    typedef struct {
        smbus_regs__SMBUS_STATUS__busy__in_t busy;
        smbus_regs__SMBUS_STATUS__bus_error__in_t bus_error;
        smbus_regs__SMBUS_STATUS__timeout_error__in_t timeout_error;
        smbus_regs__SMBUS_STATUS__pec_error__in_t pec_error;
        smbus_regs__SMBUS_STATUS__arb_lost__in_t arb_lost;
        smbus_regs__SMBUS_STATUS__nak_received__in_t nak_received;
        smbus_regs__SMBUS_STATUS__slave_addressed__in_t slave_addressed;
        smbus_regs__SMBUS_STATUS__complete__in_t complete;
        smbus_regs__SMBUS_STATUS__fsm_state__in_t fsm_state;
    } smbus_regs__SMBUS_STATUS__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_COMMAND__start__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_COMMAND__stop__in_t;

    typedef struct {
        smbus_regs__SMBUS_COMMAND__start__in_t start;
        smbus_regs__SMBUS_COMMAND__stop__in_t stop;
    } smbus_regs__SMBUS_COMMAND__in_t;

    typedef struct {
        logic [7:0] next;
    } smbus_regs__SMBUS_DATA__data__in_t;

    typedef struct {
        smbus_regs__SMBUS_DATA__data__in_t data;
    } smbus_regs__SMBUS_DATA__in_t;

    typedef struct {
        logic [7:0] next;
    } smbus_regs__SMBUS_RX_FIFO__rx_data__in_t;

    typedef struct {
        smbus_regs__SMBUS_RX_FIFO__rx_data__in_t rx_data;
    } smbus_regs__SMBUS_RX_FIFO__in_t;

    typedef struct {
        logic [5:0] next;
    } smbus_regs__SMBUS_FIFO_STATUS__tx_level__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_FIFO_STATUS__tx_full__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_FIFO_STATUS__tx_empty__in_t;

    typedef struct {
        logic [5:0] next;
    } smbus_regs__SMBUS_FIFO_STATUS__rx_level__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_FIFO_STATUS__rx_full__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_FIFO_STATUS__rx_empty__in_t;

    typedef struct {
        smbus_regs__SMBUS_FIFO_STATUS__tx_level__in_t tx_level;
        smbus_regs__SMBUS_FIFO_STATUS__tx_full__in_t tx_full;
        smbus_regs__SMBUS_FIFO_STATUS__tx_empty__in_t tx_empty;
        smbus_regs__SMBUS_FIFO_STATUS__rx_level__in_t rx_level;
        smbus_regs__SMBUS_FIFO_STATUS__rx_full__in_t rx_full;
        smbus_regs__SMBUS_FIFO_STATUS__rx_empty__in_t rx_empty;
    } smbus_regs__SMBUS_FIFO_STATUS__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_INT_STATUS__complete_int__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_INT_STATUS__error_int__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_INT_STATUS__tx_thresh_int__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_INT_STATUS__rx_thresh_int__in_t;

    typedef struct {
        logic next;
    } smbus_regs__SMBUS_INT_STATUS__slave_addr_int__in_t;

    typedef struct {
        smbus_regs__SMBUS_INT_STATUS__complete_int__in_t complete_int;
        smbus_regs__SMBUS_INT_STATUS__error_int__in_t error_int;
        smbus_regs__SMBUS_INT_STATUS__tx_thresh_int__in_t tx_thresh_int;
        smbus_regs__SMBUS_INT_STATUS__rx_thresh_int__in_t rx_thresh_int;
        smbus_regs__SMBUS_INT_STATUS__slave_addr_int__in_t slave_addr_int;
    } smbus_regs__SMBUS_INT_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } smbus_regs__SMBUS_PEC__pec__in_t;

    typedef struct {
        smbus_regs__SMBUS_PEC__pec__in_t pec;
    } smbus_regs__SMBUS_PEC__in_t;

    typedef struct {
        logic [5:0] next;
    } smbus_regs__SMBUS_BLOCK_COUNT__block_count__in_t;

    typedef struct {
        smbus_regs__SMBUS_BLOCK_COUNT__block_count__in_t block_count;
    } smbus_regs__SMBUS_BLOCK_COUNT__in_t;

    typedef struct {
        smbus_regs__SMBUS_CONTROL__in_t SMBUS_CONTROL;
        smbus_regs__SMBUS_STATUS__in_t SMBUS_STATUS;
        smbus_regs__SMBUS_COMMAND__in_t SMBUS_COMMAND;
        smbus_regs__SMBUS_DATA__in_t SMBUS_DATA;
        smbus_regs__SMBUS_RX_FIFO__in_t SMBUS_RX_FIFO;
        smbus_regs__SMBUS_FIFO_STATUS__in_t SMBUS_FIFO_STATUS;
        smbus_regs__SMBUS_INT_STATUS__in_t SMBUS_INT_STATUS;
        smbus_regs__SMBUS_PEC__in_t SMBUS_PEC;
        smbus_regs__SMBUS_BLOCK_COUNT__in_t SMBUS_BLOCK_COUNT;
    } smbus_regs__in_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__master_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__slave_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__pec_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__fast_mode__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__fifo_reset__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_CONTROL__soft_reset__out_t;

    typedef struct {
        smbus_regs__SMBUS_CONTROL__master_en__out_t master_en;
        smbus_regs__SMBUS_CONTROL__slave_en__out_t slave_en;
        smbus_regs__SMBUS_CONTROL__pec_en__out_t pec_en;
        smbus_regs__SMBUS_CONTROL__fast_mode__out_t fast_mode;
        smbus_regs__SMBUS_CONTROL__fifo_reset__out_t fifo_reset;
        smbus_regs__SMBUS_CONTROL__soft_reset__out_t soft_reset;
    } smbus_regs__SMBUS_CONTROL__out_t;

    typedef struct {
        logic [3:0] value;
    } smbus_regs__SMBUS_COMMAND__trans_type__out_t;

    typedef struct {
        logic [7:0] value;
    } smbus_regs__SMBUS_COMMAND__cmd_code__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_COMMAND__start__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_COMMAND__stop__out_t;

    typedef struct {
        smbus_regs__SMBUS_COMMAND__trans_type__out_t trans_type;
        smbus_regs__SMBUS_COMMAND__cmd_code__out_t cmd_code;
        smbus_regs__SMBUS_COMMAND__start__out_t start;
        smbus_regs__SMBUS_COMMAND__stop__out_t stop;
    } smbus_regs__SMBUS_COMMAND__out_t;

    typedef struct {
        logic [6:0] value;
    } smbus_regs__SMBUS_SLAVE_ADDR__slave_addr__out_t;

    typedef struct {
        smbus_regs__SMBUS_SLAVE_ADDR__slave_addr__out_t slave_addr;
    } smbus_regs__SMBUS_SLAVE_ADDR__out_t;

    typedef struct {
        logic [7:0] value;
    } smbus_regs__SMBUS_DATA__data__out_t;

    typedef struct {
        smbus_regs__SMBUS_DATA__data__out_t data;
    } smbus_regs__SMBUS_DATA__out_t;

    typedef struct {
        logic [7:0] value;
    } smbus_regs__SMBUS_TX_FIFO__tx_data__out_t;

    typedef struct {
        smbus_regs__SMBUS_TX_FIFO__tx_data__out_t tx_data;
    } smbus_regs__SMBUS_TX_FIFO__out_t;

    typedef struct {
        logic [15:0] value;
    } smbus_regs__SMBUS_CLK_DIV__clk_div__out_t;

    typedef struct {
        smbus_regs__SMBUS_CLK_DIV__clk_div__out_t clk_div;
    } smbus_regs__SMBUS_CLK_DIV__out_t;

    typedef struct {
        logic [23:0] value;
    } smbus_regs__SMBUS_TIMEOUT__timeout__out_t;

    typedef struct {
        smbus_regs__SMBUS_TIMEOUT__timeout__out_t timeout;
    } smbus_regs__SMBUS_TIMEOUT__out_t;

    typedef struct {
        logic [6:0] value;
    } smbus_regs__SMBUS_OWN_ADDR__own_addr__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_OWN_ADDR__addr_en__out_t;

    typedef struct {
        smbus_regs__SMBUS_OWN_ADDR__own_addr__out_t own_addr;
        smbus_regs__SMBUS_OWN_ADDR__addr_en__out_t addr_en;
    } smbus_regs__SMBUS_OWN_ADDR__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_INT_ENABLE__complete_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_INT_ENABLE__error_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_INT_ENABLE__tx_thresh_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_INT_ENABLE__rx_thresh_en__out_t;

    typedef struct {
        logic value;
    } smbus_regs__SMBUS_INT_ENABLE__slave_addr_en__out_t;

    typedef struct {
        smbus_regs__SMBUS_INT_ENABLE__complete_en__out_t complete_en;
        smbus_regs__SMBUS_INT_ENABLE__error_en__out_t error_en;
        smbus_regs__SMBUS_INT_ENABLE__tx_thresh_en__out_t tx_thresh_en;
        smbus_regs__SMBUS_INT_ENABLE__rx_thresh_en__out_t rx_thresh_en;
        smbus_regs__SMBUS_INT_ENABLE__slave_addr_en__out_t slave_addr_en;
    } smbus_regs__SMBUS_INT_ENABLE__out_t;

    typedef struct {
        logic [7:0] value;
    } smbus_regs__SMBUS_PEC__pec__out_t;

    typedef struct {
        smbus_regs__SMBUS_PEC__pec__out_t pec;
    } smbus_regs__SMBUS_PEC__out_t;

    typedef struct {
        logic [5:0] value;
    } smbus_regs__SMBUS_BLOCK_COUNT__block_count__out_t;

    typedef struct {
        smbus_regs__SMBUS_BLOCK_COUNT__block_count__out_t block_count;
    } smbus_regs__SMBUS_BLOCK_COUNT__out_t;

    typedef struct {
        smbus_regs__SMBUS_CONTROL__out_t SMBUS_CONTROL;
        smbus_regs__SMBUS_COMMAND__out_t SMBUS_COMMAND;
        smbus_regs__SMBUS_SLAVE_ADDR__out_t SMBUS_SLAVE_ADDR;
        smbus_regs__SMBUS_DATA__out_t SMBUS_DATA;
        smbus_regs__SMBUS_TX_FIFO__out_t SMBUS_TX_FIFO;
        smbus_regs__SMBUS_CLK_DIV__out_t SMBUS_CLK_DIV;
        smbus_regs__SMBUS_TIMEOUT__out_t SMBUS_TIMEOUT;
        smbus_regs__SMBUS_OWN_ADDR__out_t SMBUS_OWN_ADDR;
        smbus_regs__SMBUS_INT_ENABLE__out_t SMBUS_INT_ENABLE;
        smbus_regs__SMBUS_PEC__out_t SMBUS_PEC;
        smbus_regs__SMBUS_BLOCK_COUNT__out_t SMBUS_BLOCK_COUNT;
    } smbus_regs__out_t;
endpackage
