// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module smbus_regs (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [5:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input smbus_regs_pkg::smbus_regs__in_t hwif_in,
        output smbus_regs_pkg::smbus_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic SMBUS_CONTROL;
        logic SMBUS_STATUS;
        logic SMBUS_COMMAND;
        logic SMBUS_SLAVE_ADDR;
        logic SMBUS_DATA;
        logic SMBUS_TX_FIFO;
        logic SMBUS_RX_FIFO;
        logic SMBUS_FIFO_STATUS;
        logic SMBUS_CLK_DIV;
        logic SMBUS_TIMEOUT;
        logic SMBUS_OWN_ADDR;
        logic SMBUS_INT_ENABLE;
        logic SMBUS_INT_STATUS;
        logic SMBUS_PEC;
        logic SMBUS_BLOCK_COUNT;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.SMBUS_CONTROL = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.SMBUS_STATUS = cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.SMBUS_COMMAND = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.SMBUS_SLAVE_ADDR = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.SMBUS_DATA = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.SMBUS_TX_FIFO = cpuif_req_masked & (cpuif_addr == 6'h14);
        decoded_reg_strb.SMBUS_RX_FIFO = cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.SMBUS_FIFO_STATUS = cpuif_req_masked & (cpuif_addr == 6'h1c);
        decoded_reg_strb.SMBUS_CLK_DIV = cpuif_req_masked & (cpuif_addr == 6'h20);
        decoded_reg_strb.SMBUS_TIMEOUT = cpuif_req_masked & (cpuif_addr == 6'h24);
        decoded_reg_strb.SMBUS_OWN_ADDR = cpuif_req_masked & (cpuif_addr == 6'h28);
        decoded_reg_strb.SMBUS_INT_ENABLE = cpuif_req_masked & (cpuif_addr == 6'h2c);
        decoded_reg_strb.SMBUS_INT_STATUS = cpuif_req_masked & (cpuif_addr == 6'h30);
        decoded_reg_strb.SMBUS_PEC = cpuif_req_masked & (cpuif_addr == 6'h34);
        decoded_reg_strb.SMBUS_BLOCK_COUNT = cpuif_req_masked & (cpuif_addr == 6'h38);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } master_en;
            struct {
                logic next;
                logic load_next;
            } slave_en;
            struct {
                logic next;
                logic load_next;
            } pec_en;
            struct {
                logic next;
                logic load_next;
            } fast_mode;
            struct {
                logic next;
                logic load_next;
            } fifo_reset;
            struct {
                logic next;
                logic load_next;
            } soft_reset;
        } SMBUS_CONTROL;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } trans_type;
            struct {
                logic [7:0] next;
                logic load_next;
            } cmd_code;
            struct {
                logic next;
                logic load_next;
            } start;
            struct {
                logic next;
                logic load_next;
            } stop;
        } SMBUS_COMMAND;
        struct {
            struct {
                logic [6:0] next;
                logic load_next;
            } slave_addr;
        } SMBUS_SLAVE_ADDR;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } data;
        } SMBUS_DATA;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } tx_data;
        } SMBUS_TX_FIFO;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } clk_div;
        } SMBUS_CLK_DIV;
        struct {
            struct {
                logic [23:0] next;
                logic load_next;
            } timeout;
        } SMBUS_TIMEOUT;
        struct {
            struct {
                logic [6:0] next;
                logic load_next;
            } own_addr;
            struct {
                logic next;
                logic load_next;
            } addr_en;
        } SMBUS_OWN_ADDR;
        struct {
            struct {
                logic next;
                logic load_next;
            } complete_en;
            struct {
                logic next;
                logic load_next;
            } error_en;
            struct {
                logic next;
                logic load_next;
            } tx_thresh_en;
            struct {
                logic next;
                logic load_next;
            } rx_thresh_en;
            struct {
                logic next;
                logic load_next;
            } slave_addr_en;
        } SMBUS_INT_ENABLE;
        struct {
            struct {
                logic next;
                logic load_next;
            } complete_int;
            struct {
                logic next;
                logic load_next;
            } error_int;
            struct {
                logic next;
                logic load_next;
            } tx_thresh_int;
            struct {
                logic next;
                logic load_next;
            } rx_thresh_int;
            struct {
                logic next;
                logic load_next;
            } slave_addr_int;
        } SMBUS_INT_STATUS;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } pec;
        } SMBUS_PEC;
        struct {
            struct {
                logic [5:0] next;
                logic load_next;
            } block_count;
        } SMBUS_BLOCK_COUNT;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } master_en;
            struct {
                logic value;
            } slave_en;
            struct {
                logic value;
            } pec_en;
            struct {
                logic value;
            } fast_mode;
            struct {
                logic value;
            } fifo_reset;
            struct {
                logic value;
            } soft_reset;
        } SMBUS_CONTROL;
        struct {
            struct {
                logic [3:0] value;
            } trans_type;
            struct {
                logic [7:0] value;
            } cmd_code;
            struct {
                logic value;
            } start;
            struct {
                logic value;
            } stop;
        } SMBUS_COMMAND;
        struct {
            struct {
                logic [6:0] value;
            } slave_addr;
        } SMBUS_SLAVE_ADDR;
        struct {
            struct {
                logic [7:0] value;
            } data;
        } SMBUS_DATA;
        struct {
            struct {
                logic [7:0] value;
            } tx_data;
        } SMBUS_TX_FIFO;
        struct {
            struct {
                logic [15:0] value;
            } clk_div;
        } SMBUS_CLK_DIV;
        struct {
            struct {
                logic [23:0] value;
            } timeout;
        } SMBUS_TIMEOUT;
        struct {
            struct {
                logic [6:0] value;
            } own_addr;
            struct {
                logic value;
            } addr_en;
        } SMBUS_OWN_ADDR;
        struct {
            struct {
                logic value;
            } complete_en;
            struct {
                logic value;
            } error_en;
            struct {
                logic value;
            } tx_thresh_en;
            struct {
                logic value;
            } rx_thresh_en;
            struct {
                logic value;
            } slave_addr_en;
        } SMBUS_INT_ENABLE;
        struct {
            struct {
                logic value;
            } complete_int;
            struct {
                logic value;
            } error_int;
            struct {
                logic value;
            } tx_thresh_int;
            struct {
                logic value;
            } rx_thresh_int;
            struct {
                logic value;
            } slave_addr_int;
        } SMBUS_INT_STATUS;
        struct {
            struct {
                logic [7:0] value;
            } pec;
        } SMBUS_PEC;
        struct {
            struct {
                logic [5:0] value;
            } block_count;
        } SMBUS_BLOCK_COUNT;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: smbus_regs.SMBUS_CONTROL.master_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.master_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.master_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.master_en.next = next_c;
        field_combo.SMBUS_CONTROL.master_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.master_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.master_en.load_next) begin
                field_storage.SMBUS_CONTROL.master_en.value <= field_combo.SMBUS_CONTROL.master_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.master_en.value = field_storage.SMBUS_CONTROL.master_en.value;
    // Field: smbus_regs.SMBUS_CONTROL.slave_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.slave_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.slave_en.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.slave_en.next = next_c;
        field_combo.SMBUS_CONTROL.slave_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.slave_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.slave_en.load_next) begin
                field_storage.SMBUS_CONTROL.slave_en.value <= field_combo.SMBUS_CONTROL.slave_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.slave_en.value = field_storage.SMBUS_CONTROL.slave_en.value;
    // Field: smbus_regs.SMBUS_CONTROL.pec_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.pec_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.pec_en.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.pec_en.next = next_c;
        field_combo.SMBUS_CONTROL.pec_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.pec_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.pec_en.load_next) begin
                field_storage.SMBUS_CONTROL.pec_en.value <= field_combo.SMBUS_CONTROL.pec_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.pec_en.value = field_storage.SMBUS_CONTROL.pec_en.value;
    // Field: smbus_regs.SMBUS_CONTROL.fast_mode
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.fast_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.fast_mode.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.fast_mode.next = next_c;
        field_combo.SMBUS_CONTROL.fast_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.fast_mode.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.fast_mode.load_next) begin
                field_storage.SMBUS_CONTROL.fast_mode.value <= field_combo.SMBUS_CONTROL.fast_mode.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.fast_mode.value = field_storage.SMBUS_CONTROL.fast_mode.value;
    // Field: smbus_regs.SMBUS_CONTROL.fifo_reset
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.fifo_reset.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.fifo_reset.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_CONTROL.fifo_reset.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.fifo_reset.next = next_c;
        field_combo.SMBUS_CONTROL.fifo_reset.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.fifo_reset.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.fifo_reset.load_next) begin
                field_storage.SMBUS_CONTROL.fifo_reset.value <= field_combo.SMBUS_CONTROL.fifo_reset.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.fifo_reset.value = field_storage.SMBUS_CONTROL.fifo_reset.value;
    // Field: smbus_regs.SMBUS_CONTROL.soft_reset
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CONTROL.soft_reset.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CONTROL.soft_reset.value & ~decoded_wr_biten[5:5]) | (decoded_wr_data[5:5] & decoded_wr_biten[5:5]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_CONTROL.soft_reset.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_CONTROL.soft_reset.next = next_c;
        field_combo.SMBUS_CONTROL.soft_reset.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CONTROL.soft_reset.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_CONTROL.soft_reset.load_next) begin
                field_storage.SMBUS_CONTROL.soft_reset.value <= field_combo.SMBUS_CONTROL.soft_reset.next;
            end
        end
    end
    assign hwif_out.SMBUS_CONTROL.soft_reset.value = field_storage.SMBUS_CONTROL.soft_reset.value;
    // Field: smbus_regs.SMBUS_COMMAND.trans_type
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_COMMAND.trans_type.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_COMMAND && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_COMMAND.trans_type.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_COMMAND.trans_type.next = next_c;
        field_combo.SMBUS_COMMAND.trans_type.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_COMMAND.trans_type.value <= 4'h0;
        end else begin
            if(field_combo.SMBUS_COMMAND.trans_type.load_next) begin
                field_storage.SMBUS_COMMAND.trans_type.value <= field_combo.SMBUS_COMMAND.trans_type.next;
            end
        end
    end
    assign hwif_out.SMBUS_COMMAND.trans_type.value = field_storage.SMBUS_COMMAND.trans_type.value;
    // Field: smbus_regs.SMBUS_COMMAND.cmd_code
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_COMMAND.cmd_code.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_COMMAND && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_COMMAND.cmd_code.value & ~decoded_wr_biten[15:8]) | (decoded_wr_data[15:8] & decoded_wr_biten[15:8]);
            load_next_c = '1;
        end
        field_combo.SMBUS_COMMAND.cmd_code.next = next_c;
        field_combo.SMBUS_COMMAND.cmd_code.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_COMMAND.cmd_code.value <= 8'h0;
        end else begin
            if(field_combo.SMBUS_COMMAND.cmd_code.load_next) begin
                field_storage.SMBUS_COMMAND.cmd_code.value <= field_combo.SMBUS_COMMAND.cmd_code.next;
            end
        end
    end
    assign hwif_out.SMBUS_COMMAND.cmd_code.value = field_storage.SMBUS_COMMAND.cmd_code.value;
    // Field: smbus_regs.SMBUS_COMMAND.start
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_COMMAND.start.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_COMMAND && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_COMMAND.start.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_COMMAND.start.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_COMMAND.start.next = next_c;
        field_combo.SMBUS_COMMAND.start.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_COMMAND.start.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_COMMAND.start.load_next) begin
                field_storage.SMBUS_COMMAND.start.value <= field_combo.SMBUS_COMMAND.start.next;
            end
        end
    end
    assign hwif_out.SMBUS_COMMAND.start.value = field_storage.SMBUS_COMMAND.start.value;
    // Field: smbus_regs.SMBUS_COMMAND.stop
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_COMMAND.stop.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_COMMAND && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_COMMAND.stop.value & ~decoded_wr_biten[17:17]) | (decoded_wr_data[17:17] & decoded_wr_biten[17:17]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_COMMAND.stop.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_COMMAND.stop.next = next_c;
        field_combo.SMBUS_COMMAND.stop.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_COMMAND.stop.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_COMMAND.stop.load_next) begin
                field_storage.SMBUS_COMMAND.stop.value <= field_combo.SMBUS_COMMAND.stop.next;
            end
        end
    end
    assign hwif_out.SMBUS_COMMAND.stop.value = field_storage.SMBUS_COMMAND.stop.value;
    // Field: smbus_regs.SMBUS_SLAVE_ADDR.slave_addr
    always_comb begin
        automatic logic [6:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_SLAVE_ADDR.slave_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_SLAVE_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_SLAVE_ADDR.slave_addr.value & ~decoded_wr_biten[6:0]) | (decoded_wr_data[6:0] & decoded_wr_biten[6:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_SLAVE_ADDR.slave_addr.next = next_c;
        field_combo.SMBUS_SLAVE_ADDR.slave_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_SLAVE_ADDR.slave_addr.value <= 7'h0;
        end else begin
            if(field_combo.SMBUS_SLAVE_ADDR.slave_addr.load_next) begin
                field_storage.SMBUS_SLAVE_ADDR.slave_addr.value <= field_combo.SMBUS_SLAVE_ADDR.slave_addr.next;
            end
        end
    end
    assign hwif_out.SMBUS_SLAVE_ADDR.slave_addr.value = field_storage.SMBUS_SLAVE_ADDR.slave_addr.value;
    // Field: smbus_regs.SMBUS_DATA.data
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_DATA.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_DATA && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_DATA.data.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_DATA.data.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_DATA.data.next = next_c;
        field_combo.SMBUS_DATA.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_DATA.data.value <= 8'h0;
        end else begin
            if(field_combo.SMBUS_DATA.data.load_next) begin
                field_storage.SMBUS_DATA.data.value <= field_combo.SMBUS_DATA.data.next;
            end
        end
    end
    assign hwif_out.SMBUS_DATA.data.value = field_storage.SMBUS_DATA.data.value;
    // Field: smbus_regs.SMBUS_TX_FIFO.tx_data
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_TX_FIFO.tx_data.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_TX_FIFO && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_TX_FIFO.tx_data.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_TX_FIFO.tx_data.next = next_c;
        field_combo.SMBUS_TX_FIFO.tx_data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_TX_FIFO.tx_data.value <= 8'h0;
        end else begin
            if(field_combo.SMBUS_TX_FIFO.tx_data.load_next) begin
                field_storage.SMBUS_TX_FIFO.tx_data.value <= field_combo.SMBUS_TX_FIFO.tx_data.next;
            end
        end
    end
    assign hwif_out.SMBUS_TX_FIFO.tx_data.value = field_storage.SMBUS_TX_FIFO.tx_data.value;
    // Field: smbus_regs.SMBUS_CLK_DIV.clk_div
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_CLK_DIV.clk_div.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_CLK_DIV && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_CLK_DIV.clk_div.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_CLK_DIV.clk_div.next = next_c;
        field_combo.SMBUS_CLK_DIV.clk_div.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_CLK_DIV.clk_div.value <= 16'hf9;
        end else begin
            if(field_combo.SMBUS_CLK_DIV.clk_div.load_next) begin
                field_storage.SMBUS_CLK_DIV.clk_div.value <= field_combo.SMBUS_CLK_DIV.clk_div.next;
            end
        end
    end
    assign hwif_out.SMBUS_CLK_DIV.clk_div.value = field_storage.SMBUS_CLK_DIV.clk_div.value;
    // Field: smbus_regs.SMBUS_TIMEOUT.timeout
    always_comb begin
        automatic logic [23:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_TIMEOUT.timeout.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_TIMEOUT && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_TIMEOUT.timeout.value & ~decoded_wr_biten[23:0]) | (decoded_wr_data[23:0] & decoded_wr_biten[23:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_TIMEOUT.timeout.next = next_c;
        field_combo.SMBUS_TIMEOUT.timeout.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_TIMEOUT.timeout.value <= 24'h2625a0;
        end else begin
            if(field_combo.SMBUS_TIMEOUT.timeout.load_next) begin
                field_storage.SMBUS_TIMEOUT.timeout.value <= field_combo.SMBUS_TIMEOUT.timeout.next;
            end
        end
    end
    assign hwif_out.SMBUS_TIMEOUT.timeout.value = field_storage.SMBUS_TIMEOUT.timeout.value;
    // Field: smbus_regs.SMBUS_OWN_ADDR.own_addr
    always_comb begin
        automatic logic [6:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_OWN_ADDR.own_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_OWN_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_OWN_ADDR.own_addr.value & ~decoded_wr_biten[6:0]) | (decoded_wr_data[6:0] & decoded_wr_biten[6:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_OWN_ADDR.own_addr.next = next_c;
        field_combo.SMBUS_OWN_ADDR.own_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_OWN_ADDR.own_addr.value <= 7'h0;
        end else begin
            if(field_combo.SMBUS_OWN_ADDR.own_addr.load_next) begin
                field_storage.SMBUS_OWN_ADDR.own_addr.value <= field_combo.SMBUS_OWN_ADDR.own_addr.next;
            end
        end
    end
    assign hwif_out.SMBUS_OWN_ADDR.own_addr.value = field_storage.SMBUS_OWN_ADDR.own_addr.value;
    // Field: smbus_regs.SMBUS_OWN_ADDR.addr_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_OWN_ADDR.addr_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_OWN_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_OWN_ADDR.addr_en.value & ~decoded_wr_biten[7:7]) | (decoded_wr_data[7:7] & decoded_wr_biten[7:7]);
            load_next_c = '1;
        end
        field_combo.SMBUS_OWN_ADDR.addr_en.next = next_c;
        field_combo.SMBUS_OWN_ADDR.addr_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_OWN_ADDR.addr_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_OWN_ADDR.addr_en.load_next) begin
                field_storage.SMBUS_OWN_ADDR.addr_en.value <= field_combo.SMBUS_OWN_ADDR.addr_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_OWN_ADDR.addr_en.value = field_storage.SMBUS_OWN_ADDR.addr_en.value;
    // Field: smbus_regs.SMBUS_INT_ENABLE.complete_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_ENABLE.complete_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_INT_ENABLE.complete_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_ENABLE.complete_en.next = next_c;
        field_combo.SMBUS_INT_ENABLE.complete_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_ENABLE.complete_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_ENABLE.complete_en.load_next) begin
                field_storage.SMBUS_INT_ENABLE.complete_en.value <= field_combo.SMBUS_INT_ENABLE.complete_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_INT_ENABLE.complete_en.value = field_storage.SMBUS_INT_ENABLE.complete_en.value;
    // Field: smbus_regs.SMBUS_INT_ENABLE.error_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_ENABLE.error_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_INT_ENABLE.error_en.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_ENABLE.error_en.next = next_c;
        field_combo.SMBUS_INT_ENABLE.error_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_ENABLE.error_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_ENABLE.error_en.load_next) begin
                field_storage.SMBUS_INT_ENABLE.error_en.value <= field_combo.SMBUS_INT_ENABLE.error_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_INT_ENABLE.error_en.value = field_storage.SMBUS_INT_ENABLE.error_en.value;
    // Field: smbus_regs.SMBUS_INT_ENABLE.tx_thresh_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_ENABLE.tx_thresh_en.next = next_c;
        field_combo.SMBUS_INT_ENABLE.tx_thresh_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_ENABLE.tx_thresh_en.load_next) begin
                field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value <= field_combo.SMBUS_INT_ENABLE.tx_thresh_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_INT_ENABLE.tx_thresh_en.value = field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value;
    // Field: smbus_regs.SMBUS_INT_ENABLE.rx_thresh_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_ENABLE.rx_thresh_en.next = next_c;
        field_combo.SMBUS_INT_ENABLE.rx_thresh_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_ENABLE.rx_thresh_en.load_next) begin
                field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value <= field_combo.SMBUS_INT_ENABLE.rx_thresh_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_INT_ENABLE.rx_thresh_en.value = field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value;
    // Field: smbus_regs.SMBUS_INT_ENABLE.slave_addr_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_ENABLE.slave_addr_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_INT_ENABLE.slave_addr_en.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_ENABLE.slave_addr_en.next = next_c;
        field_combo.SMBUS_INT_ENABLE.slave_addr_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_ENABLE.slave_addr_en.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_ENABLE.slave_addr_en.load_next) begin
                field_storage.SMBUS_INT_ENABLE.slave_addr_en.value <= field_combo.SMBUS_INT_ENABLE.slave_addr_en.next;
            end
        end
    end
    assign hwif_out.SMBUS_INT_ENABLE.slave_addr_en.value = field_storage.SMBUS_INT_ENABLE.slave_addr_en.value;
    // Field: smbus_regs.SMBUS_INT_STATUS.complete_int
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_STATUS.complete_int.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.SMBUS_INT_STATUS.complete_int.value & ~(decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_INT_STATUS.complete_int.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_STATUS.complete_int.next = next_c;
        field_combo.SMBUS_INT_STATUS.complete_int.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_STATUS.complete_int.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_STATUS.complete_int.load_next) begin
                field_storage.SMBUS_INT_STATUS.complete_int.value <= field_combo.SMBUS_INT_STATUS.complete_int.next;
            end
        end
    end
    // Field: smbus_regs.SMBUS_INT_STATUS.error_int
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_STATUS.error_int.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.SMBUS_INT_STATUS.error_int.value & ~(decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_INT_STATUS.error_int.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_STATUS.error_int.next = next_c;
        field_combo.SMBUS_INT_STATUS.error_int.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_STATUS.error_int.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_STATUS.error_int.load_next) begin
                field_storage.SMBUS_INT_STATUS.error_int.value <= field_combo.SMBUS_INT_STATUS.error_int.next;
            end
        end
    end
    // Field: smbus_regs.SMBUS_INT_STATUS.tx_thresh_int
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_STATUS.tx_thresh_int.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.SMBUS_INT_STATUS.tx_thresh_int.value & ~(decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_INT_STATUS.tx_thresh_int.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_STATUS.tx_thresh_int.next = next_c;
        field_combo.SMBUS_INT_STATUS.tx_thresh_int.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_STATUS.tx_thresh_int.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_STATUS.tx_thresh_int.load_next) begin
                field_storage.SMBUS_INT_STATUS.tx_thresh_int.value <= field_combo.SMBUS_INT_STATUS.tx_thresh_int.next;
            end
        end
    end
    // Field: smbus_regs.SMBUS_INT_STATUS.rx_thresh_int
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_STATUS.rx_thresh_int.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.SMBUS_INT_STATUS.rx_thresh_int.value & ~(decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_INT_STATUS.rx_thresh_int.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_STATUS.rx_thresh_int.next = next_c;
        field_combo.SMBUS_INT_STATUS.rx_thresh_int.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_STATUS.rx_thresh_int.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_STATUS.rx_thresh_int.load_next) begin
                field_storage.SMBUS_INT_STATUS.rx_thresh_int.value <= field_combo.SMBUS_INT_STATUS.rx_thresh_int.next;
            end
        end
    end
    // Field: smbus_regs.SMBUS_INT_STATUS.slave_addr_int
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_INT_STATUS.slave_addr_int.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.SMBUS_INT_STATUS.slave_addr_int.value & ~(decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_INT_STATUS.slave_addr_int.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_INT_STATUS.slave_addr_int.next = next_c;
        field_combo.SMBUS_INT_STATUS.slave_addr_int.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_INT_STATUS.slave_addr_int.value <= 1'h0;
        end else begin
            if(field_combo.SMBUS_INT_STATUS.slave_addr_int.load_next) begin
                field_storage.SMBUS_INT_STATUS.slave_addr_int.value <= field_combo.SMBUS_INT_STATUS.slave_addr_int.next;
            end
        end
    end
    // Field: smbus_regs.SMBUS_PEC.pec
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_PEC.pec.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_PEC && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_PEC.pec.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_PEC.pec.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_PEC.pec.next = next_c;
        field_combo.SMBUS_PEC.pec.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_PEC.pec.value <= 8'h0;
        end else begin
            if(field_combo.SMBUS_PEC.pec.load_next) begin
                field_storage.SMBUS_PEC.pec.value <= field_combo.SMBUS_PEC.pec.next;
            end
        end
    end
    assign hwif_out.SMBUS_PEC.pec.value = field_storage.SMBUS_PEC.pec.value;
    // Field: smbus_regs.SMBUS_BLOCK_COUNT.block_count
    always_comb begin
        automatic logic [5:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SMBUS_BLOCK_COUNT.block_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.SMBUS_BLOCK_COUNT && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SMBUS_BLOCK_COUNT.block_count.value & ~decoded_wr_biten[5:0]) | (decoded_wr_data[5:0] & decoded_wr_biten[5:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.SMBUS_BLOCK_COUNT.block_count.next;
            load_next_c = '1;
        end
        field_combo.SMBUS_BLOCK_COUNT.block_count.next = next_c;
        field_combo.SMBUS_BLOCK_COUNT.block_count.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SMBUS_BLOCK_COUNT.block_count.value <= 6'h0;
        end else begin
            if(field_combo.SMBUS_BLOCK_COUNT.block_count.load_next) begin
                field_storage.SMBUS_BLOCK_COUNT.block_count.value <= field_combo.SMBUS_BLOCK_COUNT.block_count.next;
            end
        end
    end
    assign hwif_out.SMBUS_BLOCK_COUNT.block_count.value = field_storage.SMBUS_BLOCK_COUNT.block_count.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[15];
    assign readback_array[0][0:0] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.master_en.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.slave_en.value : '0;
    assign readback_array[0][2:2] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.pec_en.value : '0;
    assign readback_array[0][3:3] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.fast_mode.value : '0;
    assign readback_array[0][4:4] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.fifo_reset.value : '0;
    assign readback_array[0][5:5] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? field_storage.SMBUS_CONTROL.soft_reset.value : '0;
    assign readback_array[0][31:6] = (decoded_reg_strb.SMBUS_CONTROL && !decoded_req_is_wr) ? 26'h0 : '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.busy.next : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.bus_error.next : '0;
    assign readback_array[1][2:2] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.timeout_error.next : '0;
    assign readback_array[1][3:3] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.pec_error.next : '0;
    assign readback_array[1][4:4] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.arb_lost.next : '0;
    assign readback_array[1][5:5] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.nak_received.next : '0;
    assign readback_array[1][6:6] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.slave_addressed.next : '0;
    assign readback_array[1][7:7] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.complete.next : '0;
    assign readback_array[1][11:8] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_STATUS.fsm_state.next : '0;
    assign readback_array[1][31:12] = (decoded_reg_strb.SMBUS_STATUS && !decoded_req_is_wr) ? 20'h0 : '0;
    assign readback_array[2][3:0] = (decoded_reg_strb.SMBUS_COMMAND && !decoded_req_is_wr) ? field_storage.SMBUS_COMMAND.trans_type.value : '0;
    assign readback_array[2][7:4] = '0;
    assign readback_array[2][15:8] = (decoded_reg_strb.SMBUS_COMMAND && !decoded_req_is_wr) ? field_storage.SMBUS_COMMAND.cmd_code.value : '0;
    assign readback_array[2][16:16] = (decoded_reg_strb.SMBUS_COMMAND && !decoded_req_is_wr) ? field_storage.SMBUS_COMMAND.start.value : '0;
    assign readback_array[2][17:17] = (decoded_reg_strb.SMBUS_COMMAND && !decoded_req_is_wr) ? field_storage.SMBUS_COMMAND.stop.value : '0;
    assign readback_array[2][31:18] = (decoded_reg_strb.SMBUS_COMMAND && !decoded_req_is_wr) ? 14'h0 : '0;
    assign readback_array[3][6:0] = (decoded_reg_strb.SMBUS_SLAVE_ADDR && !decoded_req_is_wr) ? field_storage.SMBUS_SLAVE_ADDR.slave_addr.value : '0;
    assign readback_array[3][31:7] = (decoded_reg_strb.SMBUS_SLAVE_ADDR && !decoded_req_is_wr) ? 25'h0 : '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.SMBUS_DATA && !decoded_req_is_wr) ? field_storage.SMBUS_DATA.data.value : '0;
    assign readback_array[4][31:8] = (decoded_reg_strb.SMBUS_DATA && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[5][7:0] = '0;
    assign readback_array[5][31:8] = (decoded_reg_strb.SMBUS_TX_FIFO && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[6][7:0] = (decoded_reg_strb.SMBUS_RX_FIFO && !decoded_req_is_wr) ? hwif_in.SMBUS_RX_FIFO.rx_data.next : '0;
    assign readback_array[6][31:8] = (decoded_reg_strb.SMBUS_RX_FIFO && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[7][5:0] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.tx_level.next : '0;
    assign readback_array[7][6:6] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.tx_full.next : '0;
    assign readback_array[7][7:7] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.tx_empty.next : '0;
    assign readback_array[7][13:8] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.rx_level.next : '0;
    assign readback_array[7][14:14] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.rx_full.next : '0;
    assign readback_array[7][15:15] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? hwif_in.SMBUS_FIFO_STATUS.rx_empty.next : '0;
    assign readback_array[7][31:16] = (decoded_reg_strb.SMBUS_FIFO_STATUS && !decoded_req_is_wr) ? 16'h0 : '0;
    assign readback_array[8][15:0] = (decoded_reg_strb.SMBUS_CLK_DIV && !decoded_req_is_wr) ? field_storage.SMBUS_CLK_DIV.clk_div.value : '0;
    assign readback_array[8][31:16] = (decoded_reg_strb.SMBUS_CLK_DIV && !decoded_req_is_wr) ? 16'h0 : '0;
    assign readback_array[9][23:0] = (decoded_reg_strb.SMBUS_TIMEOUT && !decoded_req_is_wr) ? field_storage.SMBUS_TIMEOUT.timeout.value : '0;
    assign readback_array[9][31:24] = (decoded_reg_strb.SMBUS_TIMEOUT && !decoded_req_is_wr) ? 8'h0 : '0;
    assign readback_array[10][6:0] = (decoded_reg_strb.SMBUS_OWN_ADDR && !decoded_req_is_wr) ? field_storage.SMBUS_OWN_ADDR.own_addr.value : '0;
    assign readback_array[10][7:7] = (decoded_reg_strb.SMBUS_OWN_ADDR && !decoded_req_is_wr) ? field_storage.SMBUS_OWN_ADDR.addr_en.value : '0;
    assign readback_array[10][31:8] = (decoded_reg_strb.SMBUS_OWN_ADDR && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[11][0:0] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? field_storage.SMBUS_INT_ENABLE.complete_en.value : '0;
    assign readback_array[11][1:1] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? field_storage.SMBUS_INT_ENABLE.error_en.value : '0;
    assign readback_array[11][2:2] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? field_storage.SMBUS_INT_ENABLE.tx_thresh_en.value : '0;
    assign readback_array[11][3:3] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? field_storage.SMBUS_INT_ENABLE.rx_thresh_en.value : '0;
    assign readback_array[11][4:4] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? field_storage.SMBUS_INT_ENABLE.slave_addr_en.value : '0;
    assign readback_array[11][31:5] = (decoded_reg_strb.SMBUS_INT_ENABLE && !decoded_req_is_wr) ? 27'h0 : '0;
    assign readback_array[12][0:0] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? field_storage.SMBUS_INT_STATUS.complete_int.value : '0;
    assign readback_array[12][1:1] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? field_storage.SMBUS_INT_STATUS.error_int.value : '0;
    assign readback_array[12][2:2] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? field_storage.SMBUS_INT_STATUS.tx_thresh_int.value : '0;
    assign readback_array[12][3:3] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? field_storage.SMBUS_INT_STATUS.rx_thresh_int.value : '0;
    assign readback_array[12][4:4] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? field_storage.SMBUS_INT_STATUS.slave_addr_int.value : '0;
    assign readback_array[12][31:5] = (decoded_reg_strb.SMBUS_INT_STATUS && !decoded_req_is_wr) ? 27'h0 : '0;
    assign readback_array[13][7:0] = (decoded_reg_strb.SMBUS_PEC && !decoded_req_is_wr) ? field_storage.SMBUS_PEC.pec.value : '0;
    assign readback_array[13][31:8] = (decoded_reg_strb.SMBUS_PEC && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[14][5:0] = (decoded_reg_strb.SMBUS_BLOCK_COUNT && !decoded_req_is_wr) ? field_storage.SMBUS_BLOCK_COUNT.block_count.value : '0;
    assign readback_array[14][31:6] = (decoded_reg_strb.SMBUS_BLOCK_COUNT && !decoded_req_is_wr) ? 26'h0 : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<15; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
