[tool.pylint]
max-line-length = 120  # Increase line length limit
disable = [
    "E1120",  # Suppress cocotb decorator issue
    "C0114",  # Missing module docstring
    "C0116",  # Missing function docstring
]

