// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 sean galloway
//
// Module: cdc_counter_domain
// Purpose: One counter that lives in its own divided-clock domain, with
//          CDC paths in (cfg) and out (status) to the sys_clk-domain
//          harness. Used by cdc_demo_top — four instances of this block,
//          each driven by a different physical button and a different
//          clock divisor.
//
// Clock generation
//   ctr_clk is generated by rtl/common/clock_divider with N=1 and
//   PO_WIDTH=8, taking i_cfg_divisor[7:0] as the pickoff point. So the
//   effective frequency is sys_clk / 2^(pickoff+1):
//     pickoff =  0  → sys_clk/2
//     pickoff = 11  → sys_clk/4096  (~24 kHz @ 100 MHz)
//     pickoff = 15  → sys_clk/65536 (~1.5 kHz)
//     pickoff = 19  → sys_clk/1M    (~95 Hz)
//     pickoff = 23  → sys_clk/16M   (~6 Hz)
//   The host can rewrite this at any time to retune the domain — useful
//   for sweeping clock ratios in characterization.
//
//   Note: the harness CSR field is documented as "DIVISOR[31:0]" for
//   future-proofing, but currently only the low 8 bits matter. Bits
//   [31:8] are ignored.
//
// CDC strategy
//   sys_clk → ctr_clk:
//     - cfg_init, cfg_increment   : quasi-static buses, 2-FF sync per bit
//     - cfg_freeze                : single-bit level, 2-FF sync
//     - cfg_load_pulse,
//       cfg_host_press_pulse      : single-shot pulses, sync_pulse module
//   ctr_clk → sys_clk:
//     - r_value, r_press_count,
//       r_clk_ticks               : bin2gray → 2-FF sync → gray2bin
//     - alive_event               : ctr_clk pulse → sync_pulse → sys_clk

`timescale 1ns / 1ps

module cdc_counter_domain #(
    parameter int VAL_WIDTH   = 16,
    parameter int PRESS_WIDTH = 16,
    parameter int TICK_WIDTH  = 32,
    parameter int SYNC_STAGES = 3,
    // CDC modes for the value-out path:
    //   0 NO_CDC      raw flop per bit (multi-bit skew, breaks at fast ctr_clk)
    //   1 STRETCH     cdc_open_loop with STRETCH_CYCLES_STRETCH (tuned for ~20 MHz cliff)
    //   2 SYNC_FIFO   fifo_async (Gray-pointer async FIFO, always safe)
    //   3 TWO_PHASE   cdc_2_phase_handshake (toggle handshake, safe, faster than 4-phase)
    //   4 FOUR_PHASE  cdc_4_phase_handshake (RTZ handshake, safe, classic)
    parameter int STRETCH_CYCLES_STRETCH = 1,   // mode 1: 1 src clk hold → cliff near sys_clk/4
    parameter int FIFO_DEPTH             = 16,  // mode 2: depth of the value-passing FIFO
    parameter int HANDSHAKE_INTERVAL     = 256  // modes 3/4: ctr_clk cycles between snapshots
) (
    // ----------------------------------------------------------------
    // sys_clk domain
    // ----------------------------------------------------------------
    input  logic                       sys_clk,
    input  logic                       sys_rstn,

    // ctr_clk fed in from the top (selected by top-level BUFGMUX tree
    // between MMCM outputs and the per-counter divided clock).
    input  logic                       ctr_clk,

    // Config in (sys_clk domain)
    input  logic [VAL_WIDTH-1:0]       i_cfg_init,
    input  logic [VAL_WIDTH-1:0]       i_cfg_increment,
    input  logic                       i_cfg_load_pulse,
    input  logic                       i_cfg_host_press_pulse,
    input  logic                       i_cfg_freeze,
    input  logic                       i_cfg_ignore_btn,
    input  logic [2:0]                 i_cfg_cdc_mode,  // 0=no-cdc, 1=stretch, 2=sync_fifo,
                                                         // 3=two-phase, 4=four-phase
    input  logic                       i_cfg_auto_inc,  // 1=increment every ctr_clk edge

    // Raw physical button (async to ctr_clk; will be synchronized)
    input  logic                       i_btn,

    // Status out (sys_clk domain — already CDC'd from ctr_clk)
    output logic [VAL_WIDTH-1:0]       o_value,
    output logic [PRESS_WIDTH-1:0]     o_press_count,
    output logic [TICK_WIDTH-1:0]      o_clk_ticks,
    output logic                       o_alive_event
);

    // -----------------------------------------------------------------
    // ctr_clk is driven from the top via a BUFGMUX tree (or in sim,
    // tied directly). We only need to synchronize the reset into the
    // ctr_clk domain.
    // -----------------------------------------------------------------
    logic                       ctr_rstn;

    // Async-assert / sync-deassert reset into the ctr_clk domain.
    // Simple 2-FF synchronizer on the deassertion edge.
    logic [1:0] r_ctr_rstn_sync;
    always_ff @(posedge ctr_clk or negedge sys_rstn) begin
        if (!sys_rstn) r_ctr_rstn_sync <= 2'b00;
        else           r_ctr_rstn_sync <= {r_ctr_rstn_sync[0], 1'b1};
    end
    assign ctr_rstn = r_ctr_rstn_sync[1];

    // -----------------------------------------------------------------
    // CDC: cfg_init / cfg_increment / cfg_freeze (sys_clk → ctr_clk)
    // Quasi-static — 2-FF sync per bit. Host writes these slowly relative
    // to ctr_clk (rule: host must not rewrite faster than the slowest
    // ctr_clk period; trivially true for a UART-paced controller).
    // -----------------------------------------------------------------
    logic [VAL_WIDTH-1:0]  ctr_cfg_init;
    logic [VAL_WIDTH-1:0]  ctr_cfg_increment;
    logic                  ctr_cfg_freeze;
    logic                  ctr_cfg_ignore_btn;

    // ASYNC_REG hints (Xilinx) — synthesizer will keep these in adjacent
    // slices and not optimize across the synchronizer pair.
    (* ASYNC_REG = "TRUE" *) logic [VAL_WIDTH-1:0] r_init_sync0,    r_init_sync1;
    (* ASYNC_REG = "TRUE" *) logic [VAL_WIDTH-1:0] r_inc_sync0,     r_inc_sync1;
    (* ASYNC_REG = "TRUE" *) logic                 r_freeze_sync0,  r_freeze_sync1;
    (* ASYNC_REG = "TRUE" *) logic                 r_ignore_sync0,  r_ignore_sync1;
    (* ASYNC_REG = "TRUE" *) logic                 r_auto_sync0,    r_auto_sync1;
    logic                                          ctr_cfg_auto_inc;

    always_ff @(posedge ctr_clk or negedge ctr_rstn) begin
        if (!ctr_rstn) begin
            r_init_sync0   <= '0; r_init_sync1   <= '0;
            r_inc_sync0    <= '0; r_inc_sync1    <= '0;
            r_freeze_sync0 <= 1'b0; r_freeze_sync1 <= 1'b0;
            r_ignore_sync0 <= 1'b0; r_ignore_sync1 <= 1'b0;
            r_auto_sync0   <= 1'b0; r_auto_sync1   <= 1'b0;
        end else begin
            r_init_sync0   <= i_cfg_init;
            r_init_sync1   <= r_init_sync0;
            r_inc_sync0    <= i_cfg_increment;
            r_inc_sync1    <= r_inc_sync0;
            r_freeze_sync0 <= i_cfg_freeze;
            r_freeze_sync1 <= r_freeze_sync0;
            r_ignore_sync0 <= i_cfg_ignore_btn;
            r_ignore_sync1 <= r_ignore_sync0;
            r_auto_sync0   <= i_cfg_auto_inc;
            r_auto_sync1   <= r_auto_sync0;
        end
    end
    assign ctr_cfg_init       = r_init_sync1;
    assign ctr_cfg_increment  = r_inc_sync1;
    assign ctr_cfg_freeze     = r_freeze_sync1;
    assign ctr_cfg_ignore_btn = r_ignore_sync1;
    assign ctr_cfg_auto_inc   = r_auto_sync1;

    // -----------------------------------------------------------------
    // CDC: cfg_load_pulse / cfg_host_press_pulse (sys_clk → ctr_clk)
    // Single-shot pulses — use sync_pulse (toggle-based pulse sync).
    // -----------------------------------------------------------------
    logic ctr_load_pulse;
    logic ctr_host_press_pulse;

    sync_pulse #(.SYNC_STAGES(SYNC_STAGES)) u_load_sync (
        .i_src_clk   (sys_clk),
        .i_src_rst_n (sys_rstn),
        .i_pulse     (i_cfg_load_pulse),
        .i_dst_clk   (ctr_clk),
        .i_dst_rst_n (ctr_rstn),
        .o_pulse     (ctr_load_pulse)
    );

    sync_pulse #(.SYNC_STAGES(SYNC_STAGES)) u_host_press_sync (
        .i_src_clk   (sys_clk),
        .i_src_rst_n (sys_rstn),
        .i_pulse     (i_cfg_host_press_pulse),
        .i_dst_clk   (ctr_clk),
        .i_dst_rst_n (ctr_rstn),
        .o_pulse     (ctr_host_press_pulse)
    );

    // -----------------------------------------------------------------
    // Button input: 2-FF sync into ctr_clk + edge detect
    // No debouncing — relies on ctr_clk being slower than typical bounce
    // for the slow counters; the fast counters (e.g., 24 kHz) will see
    // some bounce in the press count. That is part of the demo: host can
    // compare physical-button press counts vs HOST_PRESS injected counts.
    // -----------------------------------------------------------------
    (* ASYNC_REG = "TRUE" *) logic r_btn_sync0, r_btn_sync1;
    logic r_btn_prev;
    logic w_btn_edge;

    always_ff @(posedge ctr_clk or negedge ctr_rstn) begin
        if (!ctr_rstn) begin
            r_btn_sync0 <= 1'b0;
            r_btn_sync1 <= 1'b0;
            r_btn_prev  <= 1'b0;
        end else begin
            r_btn_sync0 <= i_btn;
            r_btn_sync1 <= r_btn_sync0;
            r_btn_prev  <= r_btn_sync1;
        end
    end
    assign w_btn_edge = r_btn_sync1 && !r_btn_prev;

    // Combined press event (physical button rising edge + host inject).
    // Suppress physical if ctr_cfg_ignore_btn is asserted.
    // If auto-inc is on, every ctr_clk edge is a press (overrides the above
    // entirely) — this is how the host drives huge transition rates without
    // needing UART bandwidth to inject presses.
    logic w_press_event_real;
    logic w_press_event;
    assign w_press_event_real = (w_btn_edge && !ctr_cfg_ignore_btn) || ctr_host_press_pulse;
    assign w_press_event      = ctr_cfg_auto_inc ? 1'b1 : w_press_event_real;

    // -----------------------------------------------------------------
    // The counter itself + supporting stats (all in ctr_clk)
    // -----------------------------------------------------------------
    logic [VAL_WIDTH-1:0]   r_value;
    logic [PRESS_WIDTH-1:0] r_press_count;
    logic [TICK_WIDTH-1:0]  r_clk_ticks;

    always_ff @(posedge ctr_clk or negedge ctr_rstn) begin
        if (!ctr_rstn) begin
            r_value       <= '0;
            r_press_count <= '0;
            r_clk_ticks   <= '0;
        end else begin
            // Free-running tick counter (counts ctr_clk edges since reset)
            r_clk_ticks <= r_clk_ticks + 1'b1;

            if (ctr_load_pulse) begin
                // Host requested counter reload
                r_value <= ctr_cfg_init;
            end else if (!ctr_cfg_freeze && w_press_event) begin
                r_value       <= r_value + ctr_cfg_increment;
                r_press_count <= r_press_count + 1'b1;
            end
        end
    end

    // -----------------------------------------------------------------
    // CDC: r_value / r_press_count / r_clk_ticks (ctr_clk → sys_clk)
    // bin2gray (combinational) → register in ctr_clk → 2-FF sync in
    // sys_clk → gray2bin (combinational, registered output).
    //
    // Important: these are all monotonically increasing counters (or
    // value, which advances by INCREMENT and wraps at 2^VAL_WIDTH).
    // Monotonic-counter Gray CDC is safe because only one Gray bit
    // changes per source-clock cycle, so the sampled value during
    // metastability is either the old or the new value, never a
    // hybrid. The wrap on r_value is one Gray transition like any
    // other.
    // -----------------------------------------------------------------
    logic [VAL_WIDTH-1:0]   r_value_gray_src;
    logic [PRESS_WIDTH-1:0] r_press_gray_src;
    logic [TICK_WIDTH-1:0]  r_ticks_gray_src;

    always_ff @(posedge ctr_clk or negedge ctr_rstn) begin
        if (!ctr_rstn) begin
            r_value_gray_src <= '0;
            r_press_gray_src <= '0;
            r_ticks_gray_src <= '0;
        end else begin
            r_value_gray_src <= bin2gray_inline_value(r_value);
            r_press_gray_src <= bin2gray_inline_press(r_press_count);
            r_ticks_gray_src <= bin2gray_inline_ticks(r_clk_ticks);
        end
    end

    // 2-FF sync in sys_clk
    (* ASYNC_REG = "TRUE" *) logic [VAL_WIDTH-1:0]   r_value_gray_sync0,   r_value_gray_sync1;
    (* ASYNC_REG = "TRUE" *) logic [PRESS_WIDTH-1:0] r_press_gray_sync0,   r_press_gray_sync1;
    (* ASYNC_REG = "TRUE" *) logic [TICK_WIDTH-1:0]  r_ticks_gray_sync0,   r_ticks_gray_sync1;

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn) begin
            r_value_gray_sync0 <= '0; r_value_gray_sync1 <= '0;
            r_press_gray_sync0 <= '0; r_press_gray_sync1 <= '0;
            r_ticks_gray_sync0 <= '0; r_ticks_gray_sync1 <= '0;
        end else begin
            r_value_gray_sync0 <= r_value_gray_src;
            r_value_gray_sync1 <= r_value_gray_sync0;
            r_press_gray_sync0 <= r_press_gray_src;
            r_press_gray_sync1 <= r_press_gray_sync0;
            r_ticks_gray_sync0 <= r_ticks_gray_src;
            r_ticks_gray_sync1 <= r_ticks_gray_sync0;
        end
    end

    // gray2bin (combinational) — output registered in sys_clk
    logic [VAL_WIDTH-1:0]   w_value_bin;
    logic [PRESS_WIDTH-1:0] w_press_bin;
    logic [TICK_WIDTH-1:0]  w_ticks_bin;

    gray2bin #(.WIDTH(VAL_WIDTH))   u_gv (.gray(r_value_gray_sync1), .binary(w_value_bin));
    gray2bin #(.WIDTH(PRESS_WIDTH)) u_gp (.gray(r_press_gray_sync1), .binary(w_press_bin));
    gray2bin #(.WIDTH(TICK_WIDTH))  u_gt (.gray(r_ticks_gray_sync1), .binary(w_ticks_bin));

    // =================================================================
    // Five CDC modes for the value-output path.
    //
    // Each path drives its own sys_clk-domain register; r_cdc_mode_sysclk
    // selects which one drives o_value.
    //
    //   Mode 0 NO_CDC      Raw flop per bit. No Gray. No ASYNC_REG.
    //                      Demonstrates multi-bit skew at fast ctr_clk.
    //   Mode 1 STRETCH     cdc_open_loop: source holds data + valid
    //                      for STRETCH_CYCLES_STRETCH src clocks; dst
    //                      synchronizes. STRETCH=1 gives a clean cliff
    //                      around ctr_clk = sys_clk / (SYNC_STAGES+1),
    //                      i.e. ~25 MHz with SYNC_STAGES=3. Works ≤
    //                      ~20 MHz, fails above.
    //   Mode 2 SYNC_FIFO   fifo_async: push every press_event in
    //                      ctr_clk, pop continuously in sys_clk. The
    //                      Gray-pointer FIFO is the textbook robust
    //                      crossing — always safe across the full
    //                      pickoff range.
    //   Mode 3 TWO_PHASE   cdc_2_phase_handshake: toggle (NRZ)
    //                      protocol, fewer round trips than 4-phase.
    //                      Periodic snapshot in ctr_clk.
    //   Mode 4 FOUR_PHASE  cdc_4_phase_handshake: classic RTZ
    //                      req/ack with the source holding data
    //                      stable across the entire crossing. Most
    //                      conservative, also slowest.
    // =================================================================

    // ----- Mode 0 NO_CDC -----
    (* ASYNC_REG = "FALSE" *) logic [VAL_WIDTH-1:0] r_value_raw_sysclk;
    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn) r_value_raw_sysclk <= '0;
        else           r_value_raw_sysclk <= r_value;   // intentional CDC violation
    end

    // ----- Mode 1 STRETCH (cdc_open_loop) -----
    // Pulse src_valid on every press_event (i.e. on every counter
    // increment). cdc_open_loop holds data + valid for STRETCH_CYCLES
    // src clocks and synchronizes the valid pulse into the dst domain.
    // If STRETCH is too short for the SYNC_STAGES + src/dst clock
    // ratio, the destination misses the pulse and that value is
    // dropped. With STRETCH=1, SYNC=3, sys_clk=100MHz: works for
    // ctr_clk ≤ ~25 MHz, drops values above.
    logic                  w_stretch_busy;
    logic                  w_stretch_dst_valid;
    logic [VAL_WIDTH-1:0]  w_stretch_dst_data;
    logic [VAL_WIDTH-1:0]  r_value_stretch_sysclk;

    cdc_open_loop #(
        .DATA_WIDTH     (VAL_WIDTH),
        .STRETCH_CYCLES (STRETCH_CYCLES_STRETCH),
        .SYNC_STAGES    (SYNC_STAGES)
    ) u_stretch (
        .clk_src    (ctr_clk),
        .rst_src_n  (ctr_rstn),
        .src_valid  (w_press_event),
        .src_data   (r_value),
        .src_busy   (w_stretch_busy),
        .clk_dst    (sys_clk),
        .rst_dst_n  (sys_rstn),
        .dst_valid  (w_stretch_dst_valid),
        .dst_data   (w_stretch_dst_data)
    );

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn)                  r_value_stretch_sysclk <= '0;
        else if (w_stretch_dst_valid)   r_value_stretch_sysclk <= w_stretch_dst_data;
    end

    // ----- Mode 2 SYNC_FIFO (fifo_async) -----
    // Push every press_event from ctr_clk; pop continuously from
    // sys_clk and latch the most-recent popped value for display. The
    // FIFO is shallow because the read side is faster (sys_clk = 100 MHz
    // vs ctr_clk max 50 MHz), so it never backs up under normal use.
    logic                  w_fifo_full;
    logic                  w_fifo_empty;
    logic                  w_fifo_read;
    logic [VAL_WIDTH-1:0]  w_fifo_rd_data;
    logic [VAL_WIDTH-1:0]  r_value_fifo_sysclk;

    assign w_fifo_read = !w_fifo_empty;

    fifo_async #(
        .REGISTERED (1),
        .DATA_WIDTH (VAL_WIDTH),
        .DEPTH      (FIFO_DEPTH)
    ) u_fifo (
        .wr_clk           (ctr_clk),
        .wr_rst_n         (ctr_rstn),
        .write            (w_press_event && !w_fifo_full),
        .wr_data          (r_value),
        .wr_full          (w_fifo_full),
        .wr_almost_full   (),
        .rd_clk           (sys_clk),
        .rd_rst_n         (sys_rstn),
        .read             (w_fifo_read),
        .rd_data          (w_fifo_rd_data),
        .rd_empty         (w_fifo_empty),
        .rd_almost_empty  ()
    );

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn)        r_value_fifo_sysclk <= '0;
        else if (w_fifo_read) r_value_fifo_sysclk <= w_fifo_rd_data;
    end

    // ----- Modes 3 & 4: handshake snapshot driver -----
    // Both 2-phase and 4-phase share the same source-side state
    // machine: a free-running counter fires every HANDSHAKE_INTERVAL
    // ctr_clk cycles; snapshot the counter value and pulse src_valid.
    // We instantiate both handshake modules in parallel; only one
    // result is selected by the mode mux. The "wrong" module's src_ready
    // is observed but no harm done; data is held by both.
    logic [$clog2(HANDSHAKE_INTERVAL+1)-1:0] r_handshake_cnt;
    logic                                    w_handshake_trigger;
    logic                                    r_src_valid;
    logic                                    w_src_ready_2p, w_src_ready_4p;
    logic [VAL_WIDTH-1:0]                    r_handshake_snap;

    assign w_handshake_trigger = (r_handshake_cnt == HANDSHAKE_INTERVAL-1);

    always_ff @(posedge ctr_clk or negedge ctr_rstn) begin
        if (!ctr_rstn) begin
            r_handshake_cnt  <= '0;
            r_src_valid      <= 1'b0;
            r_handshake_snap <= '0;
        end else begin
            r_handshake_cnt <= w_handshake_trigger ? '0 : r_handshake_cnt + 1'b1;
            // Use whichever ready signal we're currently watching; OR-ing both
            // means we drop src_valid as soon as EITHER consumer accepted, which
            // is fine since the unselected one's accept just gets ignored.
            if ((w_src_ready_2p || w_src_ready_4p) && r_src_valid) begin
                r_src_valid <= 1'b0;
            end else if (!r_src_valid && w_handshake_trigger) begin
                r_handshake_snap <= r_value;
                r_src_valid      <= 1'b1;
            end
        end
    end

    // ----- Mode 3 TWO_PHASE handshake -----
    logic                  w_hs2p_dst_valid;
    logic [VAL_WIDTH-1:0]  w_hs2p_dst_data;
    logic [VAL_WIDTH-1:0]  r_value_hs2p_sysclk;

    cdc_2_phase_handshake #(
        .DATA_WIDTH  (VAL_WIDTH),
        .SYNC_STAGES (SYNC_STAGES)
    ) u_hs2p (
        .clk_src     (ctr_clk),
        .rst_src_n   (ctr_rstn),
        .src_valid   (r_src_valid),
        .src_ready   (w_src_ready_2p),
        .src_data    (r_handshake_snap),
        .src_timeout (),
        .clk_dst     (sys_clk),
        .rst_dst_n   (sys_rstn),
        .dst_valid   (w_hs2p_dst_valid),
        .dst_ready   (1'b1),
        .dst_data    (w_hs2p_dst_data)
    );

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn)              r_value_hs2p_sysclk <= '0;
        else if (w_hs2p_dst_valid)  r_value_hs2p_sysclk <= w_hs2p_dst_data;
    end

    // ----- Mode 4 FOUR_PHASE handshake -----
    logic                  w_hs4p_dst_valid;
    logic [VAL_WIDTH-1:0]  w_hs4p_dst_data;
    logic [VAL_WIDTH-1:0]  r_value_hs4p_sysclk;

    cdc_4_phase_handshake #(
        .DATA_WIDTH  (VAL_WIDTH),
        .SYNC_STAGES (SYNC_STAGES),
        .FAST_PATH   (1'b1)
    ) u_hs4p (
        .clk_src     (ctr_clk),
        .rst_src_n   (ctr_rstn),
        .src_valid   (r_src_valid),
        .src_ready   (w_src_ready_4p),
        .src_data    (r_handshake_snap),
        .src_timeout (),
        .clk_dst     (sys_clk),
        .rst_dst_n   (sys_rstn),
        .dst_valid   (w_hs4p_dst_valid),
        .dst_ready   (1'b1),
        .dst_data    (w_hs4p_dst_data)
    );

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn)              r_value_hs4p_sysclk <= '0;
        else if (w_hs4p_dst_valid)  r_value_hs4p_sysclk <= w_hs4p_dst_data;
    end

    // -----------------------------------------------------------------
    // Mode select in sys_clk. 3-bit field, 5 valid modes (0..4); modes
    // 5..7 fall through to NO_CDC.
    // -----------------------------------------------------------------
    logic [2:0] r_cdc_mode_sysclk;
    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn) r_cdc_mode_sysclk <= 3'b000;
        else           r_cdc_mode_sysclk <= i_cfg_cdc_mode;
    end

    logic [VAL_WIDTH-1:0] w_value_muxed;
    always_comb begin
        unique case (r_cdc_mode_sysclk)
            3'd0:    w_value_muxed = r_value_raw_sysclk;     // NO_CDC
            3'd1:    w_value_muxed = r_value_stretch_sysclk; // STRETCH
            3'd2:    w_value_muxed = r_value_fifo_sysclk;    // SYNC_FIFO
            3'd3:    w_value_muxed = r_value_hs2p_sysclk;    // TWO_PHASE
            3'd4:    w_value_muxed = r_value_hs4p_sysclk;    // FOUR_PHASE
            default: w_value_muxed = r_value_raw_sysclk;
        endcase
    end

    always_ff @(posedge sys_clk or negedge sys_rstn) begin
        if (!sys_rstn) begin
            o_value       <= '0;
            o_press_count <= '0;
            o_clk_ticks   <= '0;
        end else begin
            o_value       <= w_value_muxed;
            o_press_count <= w_press_bin;
            o_clk_ticks   <= w_ticks_bin;
        end
    end

    // -----------------------------------------------------------------
    // CDC: press_event → alive_event (ctr_clk → sys_clk pulse)
    // -----------------------------------------------------------------
    sync_pulse #(.SYNC_STAGES(SYNC_STAGES)) u_alive_sync (
        .i_src_clk   (ctr_clk),
        .i_src_rst_n (ctr_rstn),
        .i_pulse     (w_press_event),
        .i_dst_clk   (sys_clk),
        .i_dst_rst_n (sys_rstn),
        .o_pulse     (o_alive_event)
    );

    // -----------------------------------------------------------------
    // bin2gray inlined as functions — small enough that an instance per
    // signal width is fine, but functions keep the cdc storage block tidy
    // without three extra module instances.
    // bin2gray formula: gray = bin ^ (bin >> 1)
    // -----------------------------------------------------------------
    function automatic [VAL_WIDTH-1:0] bin2gray_inline_value(input [VAL_WIDTH-1:0] b);
        return b ^ (b >> 1);
    endfunction
    function automatic [PRESS_WIDTH-1:0] bin2gray_inline_press(input [PRESS_WIDTH-1:0] b);
        return b ^ (b >> 1);
    endfunction
    function automatic [TICK_WIDTH-1:0] bin2gray_inline_ticks(input [TICK_WIDTH-1:0] b);
        return b ^ (b >> 1);
    endfunction

endmodule
