# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sean galloway
#
# Register map for the RAPIDS characterization HARNESS DESC-LOAD region.
# SEPARATE from rapids_regmap.py (the RAPIDS DUT registers) -- this is the char
# harness's OWN hand-rolled register block, decoded directly in rapids_char_top.sv
# (not PeakRDL). Hand-maintained to mirror that RTL; regenerate with
# bin/gen_rapids_harness_regmap.py. Offsets are relative to the region base
# (host region 1); the Device/RegisterMap is given start_address.
#
# Accessed BY NAME so the harness code never hardcodes an offset/bitmask:
#   regs.write("DESC_KICK", HALF=..)   /   regs.field("STATUS", "GEN_DONE")

"""RAPIDS Characterization Harness DESC-LOAD Register Map."""

top_block = {'DESC_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
               'address': '0x20',
               'default': '0x00000000',
               'name': 'DESC_ADDR',
               'offset': '0x20',
               'size': 4,
               'sw': 'rw',
               'type': 'reg'},
 'DESC_KICK': {'HALF': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
               'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
               'address': '0x24',
               'default': '0x00000000',
               'name': 'DESC_KICK',
               'offset': '0x24',
               'size': 4,
               'sw': 'w',
               'type': 'reg'},
 'DESC_STATUS': {'OK': {'default': '0x0', 'offset': '0:0', 'sw': 'r', 'type': 'field'},
                 'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
                 'address': '0x28',
                 'default': '0x00000000',
                 'name': 'DESC_STATUS',
                 'offset': '0x28',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'DESC_WORD0': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x0',
                'default': '0x00000000',
                'name': 'DESC_WORD0',
                'offset': '0x0',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD1': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x4',
                'default': '0x00000000',
                'name': 'DESC_WORD1',
                'offset': '0x4',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD2': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x8',
                'default': '0x00000000',
                'name': 'DESC_WORD2',
                'offset': '0x8',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD3': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0xc',
                'default': '0x00000000',
                'name': 'DESC_WORD3',
                'offset': '0xc',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD4': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x10',
                'default': '0x00000000',
                'name': 'DESC_WORD4',
                'offset': '0x10',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD5': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x14',
                'default': '0x00000000',
                'name': 'DESC_WORD5',
                'offset': '0x14',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD6': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x18',
                'default': '0x00000000',
                'name': 'DESC_WORD6',
                'offset': '0x18',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'DESC_WORD7': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x1c',
                'default': '0x00000000',
                'name': 'DESC_WORD7',
                'offset': '0x1c',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'}}
