rm -f report.txt
touch report.txt
pytest test_arbiter_round_robin.py >& report.txt
pytest test_arbiter_weighted_round_robin.py >& report.txt
pytest test_cache_lru.py >& report.txt
pytest test_cache_plru_mesi.py >& report.txt
pytest test_cache_plru.py >& report.txt
pytest test_cam_tag.py >& report.txt
pytest test_clock_gate_ctrl.py >& report.txt
pytest test_dataint_checksum.py >& report.txt
pytest test_dataint_crc.py >& report.txt
pytest test_fifo_async_div2.py >& report.txt
pytest test_fifo_async.py >& report.txt
pytest test_fifo_sync.py >& report.txt
pytest test_math_adder_brent_kung_008.py >& report.txt
pytest test_math_adder_brent_kung_016.py >& report.txt
pytest test_math_adder_brent_kung_032.py >& report.txt
pytest test_math_adder_carry_lookahead.py >& report.txt
pytest test_math_adder_carry_save_nbit.py >& report.txt
pytest test_math_adder_carry_save.py >& report.txt
pytest test_math_adder_full_nbit.py >& report.txt
pytest test_math_adder_full.py >& report.txt
pytest test_math_adder_half.py >& report.txt
pytest test_math_adder_kogge_stone_nbit.py >& report.txt
pytest test_math_adder_ripple_carry.py >& report.txt
pytest test_math_addsub_full_nbit.py >& report.txt
pytest test_shifter_lfsr_fibonacci.py >& report.txt
pytest test_shifter_lfsr_galois.py >& report.txt
pytest test_shifter_lfsr.py >& report.txt
