# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sean galloway
#
# Register map for the RAPIDS characterization HARNESS CSR region.
# SEPARATE from rapids_regmap.py (the RAPIDS DUT registers) -- this is the char
# harness's OWN hand-rolled register block, decoded directly in rapids_char_top.sv
# (not PeakRDL). Hand-maintained to mirror that RTL; regenerate with
# bin/gen_rapids_harness_regmap.py. Offsets are relative to the region base
# (host region 2); the Device/RegisterMap is given start_address.
#
# Accessed BY NAME so the harness code never hardcodes an offset/bitmask:
#   regs.write("GEN_CTRL", GEN_START=..)   /   regs.field("STATUS", "GEN_DONE")

"""RAPIDS Characterization Harness CSR Register Map."""

top_block = {'CHK_ACT_CRC': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0xa4',
                 'default': '0x00000000',
                 'name': 'CHK_ACT_CRC',
                 'offset': '0xa4',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'CHK_ACT_VLD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0xb4',
                 'default': '0x00000000',
                 'name': 'CHK_ACT_VLD',
                 'offset': '0xb4',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'CHK_BEATS_T': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x88',
                 'default': '0x00000000',
                 'name': 'CHK_BEATS_T',
                 'offset': '0x88',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'CHK_CTRL': {'CHK_READY_EN': {'default': '0x0', 'offset': '1:1', 'sw': 'rw', 'type': 'field'},
              'CHK_START': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
              'RSVD': {'default': '0x0', 'offset': '31:2', 'sw': 'r', 'type': 'field'},
              'address': '0x30',
              'default': '0x00000000',
              'name': 'CHK_CTRL',
              'offset': '0x30',
              'size': 4,
              'sw': 'rw',
              'type': 'reg'},
 'CHK_SEED': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
              'address': '0x34',
              'default': '0x00000000',
              'name': 'CHK_SEED',
              'offset': '0x34',
              'size': 4,
              'sw': 'rw',
              'type': 'reg'},
 'CH_SEL': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
            'address': '0x60',
            'default': '0x00000000',
            'name': 'CH_SEL',
            'offset': '0x60',
            'size': 4,
            'sw': 'rw',
            'type': 'reg'},
 'CTRL': {'CAM_CLEAR': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
          'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
          'address': '0x0',
          'default': '0x00000000',
          'name': 'CTRL',
          'offset': '0x0',
          'size': 4,
          'sw': 'w',
          'type': 'reg'},
 'GEN_BEATS_T': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x84',
                 'default': '0x00000000',
                 'name': 'GEN_BEATS_T',
                 'offset': '0x84',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'GEN_BPP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
             'address': '0x1c',
             'default': '0x00000000',
             'name': 'GEN_BPP',
             'offset': '0x1c',
             'size': 4,
             'sw': 'rw',
             'type': 'reg'},
 'GEN_CHMASK': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x20',
                'default': '0x00000000',
                'name': 'GEN_CHMASK',
                'offset': '0x20',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'GEN_CTRL': {'GEN_START': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
              'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
              'address': '0x10',
              'default': '0x00000000',
              'name': 'GEN_CTRL',
              'offset': '0x10',
              'size': 4,
              'sw': 'w',
              'type': 'reg'},
 'GEN_EXP_CRC': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0xa0',
                 'default': '0x00000000',
                 'name': 'GEN_EXP_CRC',
                 'offset': '0xa0',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'GEN_EXP_VLD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0xb0',
                 'default': '0x00000000',
                 'name': 'GEN_EXP_VLD',
                 'offset': '0xb0',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'GEN_NBEATS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                'address': '0x18',
                'default': '0x00000000',
                'name': 'GEN_NBEATS',
                'offset': '0x18',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'GEN_SEED': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
              'address': '0x14',
              'default': '0x00000000',
              'name': 'GEN_SEED',
              'offset': '0x14',
              'size': 4,
              'sw': 'rw',
              'type': 'reg'},
 'GEN_TDEST': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
               'address': '0x24',
               'default': '0x00000000',
               'name': 'GEN_TDEST',
               'offset': '0x24',
               'size': 4,
               'sw': 'rw',
               'type': 'reg'},
 'MEM_CTRL': {'RD_CRC_LFSR_RESET': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
              'RSVD': {'default': '0x0', 'offset': '31:2', 'sw': 'r', 'type': 'field'},
              'WR_CRC_RESET': {'default': '0x0', 'offset': '1:1', 'sw': 'w', 'type': 'field'},
              'address': '0x40',
              'default': '0x00000000',
              'name': 'MEM_CTRL',
              'offset': '0x40',
              'size': 4,
              'sw': 'w',
              'type': 'reg'},
 'MON_BASE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
              'address': '0x50',
              'default': '0x00000000',
              'name': 'MON_BASE',
              'offset': '0x50',
              'size': 4,
              'sw': 'rw',
              'type': 'reg'},
 'MON_FLUSHWM': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                 'address': '0x58',
                 'default': '0x00000000',
                 'name': 'MON_FLUSHWM',
                 'offset': '0x58',
                 'size': 4,
                 'sw': 'rw',
                 'type': 'reg'},
 'MON_LIMIT': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
               'address': '0x54',
               'default': '0x00000000',
               'name': 'MON_LIMIT',
               'offset': '0x54',
               'size': 4,
               'sw': 'rw',
               'type': 'reg'},
 'OBS_CTRL': {'ARM': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
              'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
              'address': '0xc0',
              'default': '0x00000000',
              'name': 'OBS_CTRL',
              'offset': '0xc0',
              'size': 4,
              'sw': 'w',
              'type': 'reg'},
 'OBS_RD_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0x104',
               'default': '0x00000000',
               'name': 'OBS_RD_BP',
               'offset': '0x104',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'OBS_RD_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x10c',
                 'default': '0x00000000',
                 'name': 'OBS_RD_IDLE',
                 'offset': '0x10c',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_RD_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x100',
                 'default': '0x00000000',
                 'name': 'OBS_RD_PROD',
                 'offset': '0x100',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_RD_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x108',
                  'default': '0x00000000',
                  'name': 'OBS_RD_STARV',
                  'offset': '0x108',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'OBS_SIN_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x124',
                'default': '0x00000000',
                'name': 'OBS_SIN_BP',
                'offset': '0x124',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'OBS_SIN_BYTES_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x144',
                      'default': '0x00000000',
                      'name': 'OBS_SIN_BYTES_HI',
                      'offset': '0x144',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'OBS_SIN_BYTES_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x140',
                      'default': '0x00000000',
                      'name': 'OBS_SIN_BYTES_LO',
                      'offset': '0x140',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'OBS_SIN_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x12c',
                  'default': '0x00000000',
                  'name': 'OBS_SIN_IDLE',
                  'offset': '0x12c',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'OBS_SIN_PKTS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x148',
                  'default': '0x00000000',
                  'name': 'OBS_SIN_PKTS',
                  'offset': '0x148',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'OBS_SIN_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x120',
                  'default': '0x00000000',
                  'name': 'OBS_SIN_PROD',
                  'offset': '0x120',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'OBS_SIN_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x128',
                   'default': '0x00000000',
                   'name': 'OBS_SIN_STARV',
                   'offset': '0x128',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'OBS_SOUT_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x134',
                 'default': '0x00000000',
                 'name': 'OBS_SOUT_BP',
                 'offset': '0x134',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_SOUT_BYTES_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                       'address': '0x150',
                       'default': '0x00000000',
                       'name': 'OBS_SOUT_BYTES_HI',
                       'offset': '0x150',
                       'size': 4,
                       'sw': 'r',
                       'type': 'reg'},
 'OBS_SOUT_BYTES_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                       'address': '0x14c',
                       'default': '0x00000000',
                       'name': 'OBS_SOUT_BYTES_LO',
                       'offset': '0x14c',
                       'size': 4,
                       'sw': 'r',
                       'type': 'reg'},
 'OBS_SOUT_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x13c',
                   'default': '0x00000000',
                   'name': 'OBS_SOUT_IDLE',
                   'offset': '0x13c',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'OBS_SOUT_PKTS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x154',
                   'default': '0x00000000',
                   'name': 'OBS_SOUT_PKTS',
                   'offset': '0x154',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'OBS_SOUT_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x130',
                   'default': '0x00000000',
                   'name': 'OBS_SOUT_PROD',
                   'offset': '0x130',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'OBS_SOUT_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x138',
                    'default': '0x00000000',
                    'name': 'OBS_SOUT_STARV',
                    'offset': '0x138',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'OBS_WR_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0x114',
               'default': '0x00000000',
               'name': 'OBS_WR_BP',
               'offset': '0x114',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'OBS_WR_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x11c',
                 'default': '0x00000000',
                 'name': 'OBS_WR_IDLE',
                 'offset': '0x11c',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_WR_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x110',
                 'default': '0x00000000',
                 'name': 'OBS_WR_PROD',
                 'offset': '0x110',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_WR_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x118',
                  'default': '0x00000000',
                  'name': 'OBS_WR_STARV',
                  'offset': '0x118',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'PKT_CNT': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
             'address': '0x8c',
             'default': '0x00000000',
             'name': 'PKT_CNT',
             'offset': '0x8c',
             'size': 4,
             'sw': 'r',
             'type': 'reg'},
 'RD_BEATS_T': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x90',
                'default': '0x00000000',
                'name': 'RD_BEATS_T',
                'offset': '0x90',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'RD_CRC': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
            'address': '0xa8',
            'default': '0x00000000',
            'name': 'RD_CRC',
            'offset': '0xa8',
            'size': 4,
            'sw': 'r',
            'type': 'reg'},
 'RD_CRC_VLD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0xb8',
                'default': '0x00000000',
                'name': 'RD_CRC_VLD',
                'offset': '0xb8',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'SNK_SCHERR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x9c',
                'default': '0x00000000',
                'name': 'SNK_SCHERR',
                'offset': '0x9c',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'SRC_SCHERR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x98',
                'default': '0x00000000',
                'name': 'SRC_SCHERR',
                'offset': '0x98',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'STATUS': {'DATA_ERROR': {'default': '0x0', 'offset': '5:5', 'sw': 'r', 'type': 'field'},
            'GEN_BUSY': {'default': '0x0', 'offset': '3:3', 'sw': 'r', 'type': 'field'},
            'GEN_DONE': {'default': '0x0', 'offset': '4:4', 'sw': 'r', 'type': 'field'},
            'MON_IRQ': {'default': '0x0', 'offset': '0:0', 'sw': 'r', 'type': 'field'},
            'RD_MEM_BUSY': {'default': '0x0', 'offset': '6:6', 'sw': 'r', 'type': 'field'},
            'RSVD': {'default': '0x0', 'offset': '31:8', 'sw': 'r', 'type': 'field'},
            'SNK_IDLE': {'default': '0x0', 'offset': '2:2', 'sw': 'r', 'type': 'field'},
            'SRC_IDLE': {'default': '0x0', 'offset': '1:1', 'sw': 'r', 'type': 'field'},
            'WR_MEM_BUSY': {'default': '0x0', 'offset': '7:7', 'sw': 'r', 'type': 'field'},
            'address': '0x80',
            'default': '0x00000000',
            'name': 'STATUS',
            'offset': '0x80',
            'size': 4,
            'sw': 'r',
            'type': 'reg'},
 'WR_BEATS_T': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x94',
                'default': '0x00000000',
                'name': 'WR_BEATS_T',
                'offset': '0x94',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'WR_CRC': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
            'address': '0xac',
            'default': '0x00000000',
            'name': 'WR_CRC',
            'offset': '0xac',
            'size': 4,
            'sw': 'r',
            'type': 'reg'},
 'WR_CRC_VLD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0xbc',
                'default': '0x00000000',
                'name': 'WR_CRC_VLD',
                'offset': '0xbc',
                'size': 4,
                'sw': 'r',
                'type': 'reg'}}
