"""Deterministic cache_sim trace generator for the amber parity grid
(Task 10, PRD criterion 1).

Word-addressed traces in the cache_sim address-text format (one decimal word
address per line, '//' comments allowed -- parsed by the app's own
parseAddressText on the golden side).  Every trace is a pure function of its
pinned seed constant below; regenerate with:

    python3 projects/components/cache-ip/amber-mesi-l1/dv/traces/gen_traces.py

or verify the committed files are current:

    python3 .../gen_traces.py --check

Shapes (brief: sequential / strided / RandomLRU-walks / TH-shaped mixes,
1k-100k accesses):
  seq_1k       sequential sweep, 1024 words (64 lines: fits 128/4, wraps 16/2)
  strided_8k   fixed-stride walk (stride 17 words), 8192 accesses
  walk_16k     seeded random walk inside a 36-line working set (LRU-friendly
               reuse; capacity pressure at the 16/2 geometry)
  thrash_32k   uniform random over 2048 lines (THrash: working set >> both
               geometries' capacity)
  mix_100k     five 20k segments (sequential / strided / walk / thrash /
               sequential-revisit) over disjoint spans

Author: RTL Design Sherpa
Created: 2026-10-09
"""

import argparse
import os
import random
import sys


SEED = {
    'seq_1k': 0xA4B3C001,
    'strided_8k': 0xA4B3C002,
    'walk_16k': 0xA4B3C003,
    'thrash_32k': 0xA4B3C004,
    'mix_100k': 0xA4B3C005,
}

DESCRIPTION = {
    'seq_1k': 'sequential sweep 0..1023 words (64 lines)',
    'strided_8k': 'strided walk, start 3 stride 17 words, wrapping 8192-word '
                  'span (512 lines), 8192 accesses',
    'walk_16k': 'seeded random walk in a 36-line (576-word) working set, '
                '16000 accesses',
    'thrash_32k': 'uniform random over 2048 lines (32768 words), '
                  '32000 accesses',
    'mix_100k': '5 x 20k segments: sequential / strided(31) / walk(48 lines) '
                '/ thrash(1024 lines) / sequential-revisit',
}

BLOCK_WORDS = 16   # 64 B lines / 4 B words; kept in the file headers only


def gen_seq_1k(rng):
    return [i for i in range(1024)]


def gen_strided_8k(rng):
    # stride 17 words across a wrapping 8192-word span (512 lines): revisits
    # after the first sweep -- hits at 128/4, set conflicts at 16/2
    return [(3 + 17 * i) % 8192 for i in range(8192)]


def _walk(rng, n, ws_lines, start_line=0):
    """RandomLRU-walk: mostly +-1 line steps with occasional random jumps --
    working-set reuse an LRU cache exploits."""
    words_per_line = BLOCK_WORDS
    line = rng.randrange(ws_lines)
    out = []
    for _ in range(n):
        r = rng.random()
        if r < 0.60:
            line = (line + 1) % ws_lines
        elif r < 0.80:
            line = (line - 1) % ws_lines
        else:
            line = rng.randrange(ws_lines)
        word_off = rng.randrange(words_per_line)
        out.append(((start_line + line) * words_per_line + word_off)
                   & 0xFFFFFFFF)
    return out


def _thrash(rng, n, span_lines, start_line=0):
    words_per_line = BLOCK_WORDS
    return [((start_line + rng.randrange(span_lines)) * words_per_line
             + rng.randrange(words_per_line)) & 0xFFFFFFFF
            for _ in range(n)]


def gen_walk_16k(rng):
    return _walk(rng, 16000, ws_lines=36)


def gen_thrash_32k(rng):
    return _thrash(rng, 32000, span_lines=2048)


def gen_mix_100k(rng):
    trace = []
    trace += [i for i in range(20000)]                       # sequential
    trace += [(0x8000 + 31 * i) & 0xFFFFFFFF
              for i in range(20000)]                         # strided
    trace += _walk(rng, 20000, ws_lines=48, start_line=0x1000)
    trace += _thrash(rng, 20000, span_lines=1024, start_line=0x1800)
    trace += [(19999 - i) for i in range(20000)]             # revisit seg 1
    return trace


GENERATORS = {
    'seq_1k': gen_seq_1k,
    'strided_8k': gen_strided_8k,
    'walk_16k': gen_walk_16k,
    'thrash_32k': gen_thrash_32k,
    'mix_100k': gen_mix_100k,
}


def render(name):
    rng = random.Random(SEED[name])
    words = GENERATORS[name](rng)
    lines = [f'// {name}: {DESCRIPTION[name]}',
             f'// generated by dv/traces/gen_traces.py (seed 0x{SEED[name]:08x}, '
             'pinned) -- do not hand-edit',
             f'// accesses: {len(words)}']
    lines += [str(w) for w in words]
    return '\n'.join(lines) + '\n'


def main(argv=None):
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='verify committed files match regeneration '
                         '(exit 1 on drift)')
    args = ap.parse_args(argv)
    rc = 0
    for name in GENERATORS:
        path = os.path.join(here, f'{name}.txt')
        want = render(name)
        if args.check:
            with open(path, 'r', encoding='utf-8') as fh:
                got = fh.read()
            if got != want:
                print(f'DRIFT: {path} does not match gen_traces.py output')
                rc = 1
            else:
                print(f'OK: {path}')
        else:
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(want)
            print(f'wrote {path} ({want.count(chr(10))} lines)')
    return rc


if __name__ == '__main__':
    sys.exit(main())
