# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# RTL Design Sherpa - Industry-Standard RTL Design and Verification
# https://github.com/sean-galloway/RTLDesignSherpa
#
# Module: PIC8259MediumTests
# Purpose: GitHub #50 defect-regression suite for PIC 8259
#
# Created: 2026-09-09

"""
PIC 8259 GitHub #50 Defect-Regression Test Suite

These tests encode the acknowledge-by-read contract GitHub issue #50 (body
C3/C4 + qc round_2 + qc round_3 comments) specifies: PIC_INTA, a read-only
register at APB offset 0x02C, replaces the missing INTA pin (PL190-VIC
style). Reading PIC_INTA performs the interrupt acknowledge - if an
unmasked, unblocked request is pending it returns {valid=1 at bit 8,
vector[7:0] = ICW2 base[7:3] | irq}, sets ISR[irq], clears IRR[irq] in edge
mode (level mode: IRR follows the pin), and in AEOI mode immediately clears
ISR again (rotating the priority base once if rotate-on-AEOI is set). If
nothing is pending it returns valid=0 with the spurious vector (base | 7)
and no side effects. PIC_INTA is now a real register in pic_8259_regs.rdl /
pic_8259_regmap.py (0x02C); PIC8259RegisterMap.PIC_INTA in pic_8259_tb.py
still carries the TB-side definition rather than importing the generated
regmap, matching this TB's existing by-address style for every other
register.

History: this suite was authored RED (2026-09-09) against the pre-fix RTL,
where none of the above existed - PIC_INTA was unmapped and always read
0x00000000 with no side effects. The GitHub #50 RTL fix has since landed
(uncommitted) and the suite is 30/31 green; two tests below are still RED
pending a follow-up to match 8259A datasheet semantics exactly (see MED-2
and MED-4, each documented at the point of divergence).

Defect index (GitHub #50, historical - the state before the fix landed):
  1. C3 - ISR is never set. The core's r_isr always_ff (pic_8259_core.sv
     ~294-324) has only clear paths; nothing sets a bit. isr_out always
     reads 0x00, so EOI/nesting/SMM are all no-ops on live state.
  2. C4 - edge-triggered IRR bits can never be cleared. r_irr (~281) is
     set-only in edge mode; only reset/ICW1/pic_disable clear it. Once an
     edge IRQ fires, int_out latches high permanently (barring IMR mask or
     re-init).
  3. EOI/nesting/SMM fallout of C3: w_pending_irqs (~404-406) subtracting
     r_isr never engages (isr is always 0), so ISR-based blocking, nesting,
     and special mask mode are all unobservable/inert.
  4a. Rotate-on-non-specific-EOI (case 3'b101, ~357) sets
     r_priority_base <= highest_isr_comb, which is ISR-derived and hence
     always 0 - a fallout of C3 independent of whether PIC_INTA exists.
  4b. qc round_2 item 1 - rotate-on-AEOI oscillates EVERY clock while
     cfg_aeoi && r_rotate_on_aeoi && int_output (~369), instead of once per
     acknowledge. This is independent of the (nonexistent) ack mechanism -
     it fires from int_output alone.
  5. qc round_3 item 1 - OCW2/OCW3 side effects (rotation, SMM) execute
     with no INIT_COMPLETE/pic_enable gating, unlike IRR/ISR, and persist
     because r_priority_base/r_special_mask_mode only reset on `rst`, not
     on ICW1 re-init.
  6. qc round_2 item 3 - init_mode=1 with auto_reset_init=0 makes init
     impossible: INIT_COMPLETE bounces straight back to INIT_IDLE the cycle
     after completing, because cfg_init_mode is never cleared (core ~157).
  7. qc round_2 item 2 - register decode uses regblk_addr[5:0] but every
     side-effect strobe (icw1_wr etc., pic_8259_config_regs.sv ~173+)
     compares the full 12 bits, so writes through a 0x40 alias update
     storage without stepping the init FSM / executing OCW2, and there is
     no address-window check at all (unlike ioapic_config_regs's
     w_addr_in_window/w_drop, added for GitHub #48) - no PSLVERR is ever
     generated by this block today.
  8. qc round_2 item 4 - IMR read-after-write one-cycle stale window: the
     PIC_OCW1.imr field reloads from the core mirror (hwif_in...imr.next)
     every cycle it is not being SW-written, so a read immediately after a
     write should see the new value before any HW-mirror overwrite lands.
  9. Consequence of C3/C4: int_out must deassert once the last pending/
     in-service request is acknowledged and EOI'd, and must never assert
     for a masked IRQ (the masked-IRQ half already holds today; the
     ack+EOI-deassert half does not, because IRR never clears on ack).

Which existing pic_8259_tests_basic.py tests/helpers mask each defect:
  - test_single_irq(): warns (does not fail) if ISR is still set after EOI,
    and since ISR starts and stays 0 the warning never even fires - masks
    C3 and C4 together.
  - test_irq_masking(), test_multiple_irqs(), test_nested_interrupt_
    handling(), test_simultaneous_irqs_priority(), test_imr_protection():
    all check only IRR and int_out, never ISR - mask C3.
  - test_eoi_handling(): sends EOI commands and only checks they do not
    raise an exception; never reads ISR - masks C3, C4, and the EOI/
    nesting fallout together.
  - test_priority_rotation(), test_rotate_on_specific_eoi(): send OCW2
    rotate/set-priority commands and read IRR, but never read back
    PIC_STATUS.highest_priority to confirm the base actually moved - mask
    4a and 4b.
  - test_special_mask_mode(): toggles OCW3 SMM but never asserts a lower-
    priority IRQ during another's service to prove SMM actually let it
    through - masks the SMM fallout of C3.
  - test_auto_eoi_mode(): reads ISR after auto-EOI but only logs it (no
    assertion) - masks C3 in AEOI mode.
  - test_initialization(): only exercises the default auto_reset_init=1
    path (initialize_pic() deliberately never sets init_mode, per its own
    comment) - masks item 6 entirely.
  - test_register_access(): only touches canonical offsets - there is no
    existing address-decode/alias test at all, so item 7 has zero coverage.
  - Item 8 (IMR read-after-write) has zero existing coverage either way.
"""

from cocotb.triggers import RisingEdge

from .pic_8259_tb import PIC8259RegisterMap


class PIC8259MediumTests:
    """GitHub #50 defect-regression suite for PIC 8259 (medium/full levels)."""

    def __init__(self, tb):
        """
        Args:
            tb: PIC8259TB instance
        """
        self.tb = tb
        self.log = tb.log

    # =========================================================================
    # Defect 1 (C3): ISR is never set by acknowledge
    # =========================================================================

    async def test_c3_isr_set_by_acknowledge(self) -> bool:
        """
        GitHub #50 C3: raising IRQ3 (edge) and reading PIC_INTA must
        acknowledge it - valid=1, vector=ICW2_base|3 - set PIC_ISR to 0x08,
        and (with nothing else pending) deassert int_out.

        History: r_isr (pic_8259_core.sv ~294-324) has no set path at all,
        so isr_out is permanently 0x00 and int_out never deasserts from an
        acknowledge. test_single_irq() in the basic suite reads ISR after
        the (nonexistent) ack but only WARNS if it is still set - since ISR
        starts at 0 the "still set" check is trivially false and the
        warning never fires, so this defect has never been observed by the
        existing suite.
        """
        self.log.info("TEST MED-1 (GH50 C3): ISR set by acknowledge")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xF7)  # unmask only IRQ3
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            irr = await self.tb.read_irr()
            if (irr & 0x08) == 0:
                self.log.error(f"IRR[3] not set after IRQ3 assertion: IRR=0x{irr:02X}")
                return False

            ack = await self.tb.read_inta()
            if not ack['valid']:
                self.log.error(
                    f"PIC_INTA valid bit not set for a pending, unmasked "
                    f"IRQ3: raw=0x{ack['raw']:08X} (expected bit8=1, got 0) "
                    f"- the acknowledge-by-read mechanism does not exist "
                    f"in the current RTL (PIC_INTA is not decoded at all)"
                )
                return False

            expected_vector = 0x20 | 3
            if ack['vector'] != expected_vector:
                self.log.error(
                    f"PIC_INTA vector mismatch: expected 0x{expected_vector:02X} "
                    f"(base 0x20 | irq 3), got 0x{ack['vector']:02X}"
                )
                return False

            isr = await self.tb.read_isr()
            if isr != 0x08:
                self.log.error(
                    f"PIC_ISR after acknowledge of IRQ3: expected 0x08, got "
                    f"0x{isr:02X} - r_isr has no set path in the current RTL"
                )
                return False

            await self.tb.wait_clocks('pclk', 2)
            if self.tb.dut.int_out.value == 1:
                self.log.error(
                    "int_out still asserted after IRQ3 was acknowledged and "
                    "no other request is pending"
                )
                return False

            self.log.info("PASS: PIC_INTA read acknowledged IRQ3 (ISR set, int_out cleared)")
            return True

        except Exception as e:
            self.log.error(f"FAIL: C3 acknowledge test raised {e}")
            return False

    # =========================================================================
    # Defect 2 (C4): edge-triggered IRR never clears
    # =========================================================================

    async def test_c4_edge_irr_clears_on_acknowledge(self) -> bool:
        """
        GitHub #50 C4, 8259A datasheet semantics: after PIC_INTA
        acknowledges an edge-triggered IRQ3 (ISR[3]=1), IRR[3] clears and
        int_out deasserts. A datasheet 8259A's in-service level blocks
        itself (as well as all lower-priority levels) until EOI: a second
        IRQ3 edge while ISR[3] is still set must SET IRR[3] again (the
        request is latched), but int_out must stay LOW - it is blocked by
        its own in-service bit, not delivered a second time. Only after a
        non-specific EOI does int_out reassert and PIC_INTA return IRQ3
        again.

        History (RTL fix landed, uncommitted): r_irr (pic_8259_core.sv
        ~281) used to be set-only in edge mode with no acknowledge path at
        all (module comment ~251-256), so int_out latched high permanently
        once any unmasked edge IRQ fired. test_irq_masking(),
        test_multiple_irqs(), test_nested_interrupt_handling() and
        test_simultaneous_irqs_priority() all read IRR and int_out but only
        ever check that they SET correctly, never that they clear - none
        of them observed this.

        RTL follow-up expected: today's RTL still lets the same level
        re-request while in service (int_out reasserts on the second edge
        instead of staying blocked until EOI) - the "int_out stays LOW"
        assertion below is expected RED until that follow-up lands.
        """
        self.log.info("TEST MED-2 (GH50 C4, datasheet self/lower-priority in-service block): edge IRR clears on acknowledge")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xF7)  # unmask only IRQ3
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            ack = await self.tb.read_inta()  # acknowledge cycle -> ISR[3]=1
            if not ack['valid'] or ack['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of IRQ3 failed: valid={ack['valid']}, "
                    f"vector=0x{ack['vector']:02X} (expected valid=1, vector=0x23)"
                )
                return False
            await self.tb.wait_clocks('pclk', 2)

            irr_after_ack = await self.tb.read_irr()
            if (irr_after_ack & 0x08) != 0:
                self.log.error(
                    f"IRR[3] still set after acknowledge: IRR=0x{irr_after_ack:02X} "
                    f"- edge-triggered IRR has no clear-on-acknowledge path in "
                    f"the current RTL"
                )
                return False

            if self.tb.dut.int_out.value == 1:
                self.log.error("int_out still asserted after IRQ3 IRR was acknowledged")
                return False

            # A second IRQ3 edge while ISR[3] is still set (no EOI yet) must
            # re-set IRR[3] but must NOT re-deliver: int_out stays LOW
            # because the level is still in service (datasheet self-block).
            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            irr_second = await self.tb.read_irr()
            if (irr_second & 0x08) == 0:
                self.log.error(
                    f"IRR[3] did not re-set on a second edge while still in "
                    f"service: IRR=0x{irr_second:02X}"
                )
                return False

            if self.tb.dut.int_out.value == 1:
                self.log.error(
                    "int_out reasserted for a second IRQ3 edge while IRQ3 is "
                    "still in service (ISR[3]=1) - a datasheet 8259A blocks a "
                    "level from re-interrupting itself until EOI"
                )
                return False

            # Non-specific EOI clears ISR[3]; the re-latched IRR[3] must now
            # be delivered.
            await self.tb.send_eoi(irq=None, specific=False)
            await self.tb.wait_clocks('pclk', 2)

            if self.tb.dut.int_out.value != 1:
                self.log.error("int_out did not reassert after EOI cleared the in-service IRQ3")
                return False

            ack2 = await self.tb.read_inta()
            if not ack2['valid'] or ack2['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of the re-latched IRQ3 after EOI failed: "
                    f"valid={ack2['valid']}, vector=0x{ack2['vector']:02X} "
                    f"(expected valid=1, vector=0x23)"
                )
                return False

            await self.tb.send_eoi(irq=None, specific=False)

            self.log.info(
                "PASS: edge IRR clears on acknowledge, a same-level re-edge "
                "is latched but blocked while in service, and EOI releases it"
            )
            return True

        except Exception as e:
            self.log.error(f"FAIL: C4 IRR-clear test raised {e}")
            return False

    # =========================================================================
    # Defect 3: EOI clears ISR, and nested priority blocking after ack
    # =========================================================================

    async def test_eoi_and_nesting_after_acknowledge(self) -> bool:
        """
        GitHub #50 C3 fallout: after PIC_INTA acknowledges IRQ3 (ISR[3]
        set), a specific/non-specific EOI must clear ISR[3]. While ISR[3]
        is set, a lower-priority IRQ5 request must NOT assert int_out (it
        is blocked, not consumed - it stays pending), but a higher-priority
        IRQ1 must (and its acknowledge sets ISR[1] alongside ISR[3]); after
        EOI-ing both IRQ1 and IRQ3, the IRQ5 that was blocked earlier is
        still legitimately pending and must now be delivered - acknowledge
        it (PIC_INTA -> vector 0x25), EOI it, and only then is int_out low
        and ISR back to 0x00.

        History (RTL fix landed, uncommitted): since ISR never sets (C3),
        w_pending_irqs's `& ~r_isr` term (pic_8259_core.sv ~404-406) never
        removed anything, so ISR-based nesting was inert - the GitHub #50
        body calls this out directly under C3's "Fallout" bullet.
        test_eoi_handling() sends both EOI forms but never reads ISR at
        all, and test_nested_interrupt_handling() asserts IRQ5 then IRQ1
        but only checks IRR and int_out ASSERTING, never that the
        lower-priority one is held off while the higher one is serviced -
        neither test could have caught this.

        Test-authoring fix (2026-09-09): the original version of this test
        unmasked 0xD6 (IRQ0/3/5) instead of the documented IRQ1/3/5
        (0xD5), so the "higher priority IRQ1 must interrupt" check failed
        because IRQ1 was still masked - a test bug, not an RTL bug. It also
        never accounted for the IRQ5 raised while IRQ3 was in service: that
        request is BLOCKED (nesting), not consumed, so once IRQ1 and IRQ3
        are both EOI'd it is legitimately still pending and must be
        acknowledged and EOI'd before int_out is expected to go low.
        """
        self.log.info("TEST MED-3 (GH50 C3 fallout): EOI + nesting after acknowledge")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            # Unmask IRQ1 (high), IRQ3 (mid), IRQ5 (low)
            await self.tb.set_imr(0xD5)
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            ack3 = await self.tb.read_inta()
            if not ack3['valid'] or ack3['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of IRQ3 failed: valid={ack3['valid']}, "
                    f"vector=0x{ack3['vector']:02X} (expected valid=1, "
                    f"vector=0x23)"
                )
                return False

            isr = await self.tb.read_isr()
            if isr != 0x08:
                self.log.error(f"ISR after IRQ3 acknowledge: expected 0x08, got 0x{isr:02X}")
                return False

            # Lower priority IRQ5 must NOT interrupt while IRQ3 is in service.
            await self.tb.pulse_irq(5, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)
            if self.tb.dut.int_out.value == 1:
                self.log.error(
                    "int_out asserted for lower-priority IRQ5 while higher-"
                    "priority IRQ3 is in service (ISR[3]=1)"
                )
                return False

            # Higher priority IRQ1 MUST interrupt.
            await self.tb.pulse_irq(1, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)
            if self.tb.dut.int_out.value != 1:
                self.log.error(
                    "int_out did not assert for higher-priority IRQ1 while "
                    "lower-priority IRQ3 is in service"
                )
                return False

            ack1 = await self.tb.read_inta()
            if not ack1['valid'] or ack1['vector'] != (0x20 | 1):
                self.log.error(
                    f"Acknowledge of IRQ1 failed: valid={ack1['valid']}, "
                    f"vector=0x{ack1['vector']:02X} (expected valid=1, "
                    f"vector=0x21)"
                )
                return False

            isr2 = await self.tb.read_isr()
            if isr2 != 0x0A:  # bits 1 and 3
                self.log.error(f"ISR with IRQ1+IRQ3 both in service: expected 0x0A, got 0x{isr2:02X}")
                return False

            # EOI both, non-specific for the top of stack (IRQ1), specific for IRQ3.
            await self.tb.send_eoi(irq=1, specific=True)
            isr3 = await self.tb.read_isr()
            if isr3 != 0x08:
                self.log.error(f"ISR after EOI-ing IRQ1: expected 0x08, got 0x{isr3:02X}")
                return False

            await self.tb.send_eoi(irq=3, specific=True)
            isr4 = await self.tb.read_isr()
            if isr4 != 0x00:
                self.log.error(f"ISR after EOI-ing IRQ3: expected 0x00, got 0x{isr4:02X}")
                return False

            # The IRQ5 raised earlier was blocked (nested), not consumed -
            # with both higher-priority in-service levels now EOI'd, it is
            # legitimately pending and must be delivered.
            await self.tb.wait_clocks('pclk', 2)
            ack5 = await self.tb.read_inta()
            if not ack5['valid'] or ack5['vector'] != (0x20 | 5):
                self.log.error(
                    f"Acknowledge of the previously-blocked IRQ5 failed: "
                    f"valid={ack5['valid']}, vector=0x{ack5['vector']:02X} "
                    f"(expected valid=1, vector=0x25) - it should still be "
                    f"pending now that IRQ1 and IRQ3 are both EOI'd"
                )
                return False

            isr5 = await self.tb.read_isr()
            if isr5 != 0x20:
                self.log.error(f"ISR after IRQ5 acknowledge: expected 0x20, got 0x{isr5:02X}")
                return False

            await self.tb.send_eoi(irq=5, specific=True)
            await self.tb.wait_clocks('pclk', 2)

            isr6 = await self.tb.read_isr()
            if isr6 != 0x00:
                self.log.error(f"ISR after EOI-ing IRQ5: expected 0x00, got 0x{isr6:02X}")
                return False

            if self.tb.dut.int_out.value == 1:
                self.log.error("int_out still asserted after all three IRQs were acknowledged and EOI'd")
                return False

            self.log.info("PASS: EOI clears ISR, nested priority blocking held, and the blocked IRQ5 was delivered afterward")
            return True

        except Exception as e:
            self.log.error(f"FAIL: EOI/nesting test raised {e}")
            return False

    # =========================================================================
    # Defect 3 (SMM half): special mask mode allows lower priority through
    # =========================================================================

    async def test_special_mask_mode_allows_lower_priority_during_service(self) -> bool:
        """
        GitHub #50 C3 fallout, 8259A datasheet semantics: special mask mode
        does NOT lift the in-service block for every other level - it lifts
        it ONLY for levels whose IMR bit is explicitly set ("a mask bit set
        in OCW1 inhibits further interrupts at that level and enables
        interrupts from all other levels that are not masked"). With IRQ3
        acknowledged (ISR[3]=1) and SMM enabled: (a) while IMR[3]=0, an
        IRQ5 request must still be BLOCKED exactly like normal mode; (b)
        only once IMR[3] is set to 1 does IRQ5 become deliverable
        (PIC_INTA -> vector 0x25).

        History (RTL fix landed, uncommitted): w_pending_irqs's
        special-mask branch (`r_special_mask_mode ? (r_irr & ~r_imr) : ...`,
        pic_8259_core.sv ~404-406) unconditionally drops the `& ~r_isr`
        term for ALL levels once SMM is set, regardless of IMR - it lifts
        blocking universally instead of only for the masked level.
        test_special_mask_mode() in the basic suite toggles OCW3 SMM on and
        off but never asserts a second, lower-priority IRQ during another's
        service to prove SMM's IMR-gated behavior.

        RTL follow-up expected: part (a) (still blocked while IMR[3]=0) is
        expected RED until that follow-up lands; part (b) (delivered once
        IMR[3]=1) already passes today, coincidentally, because today's RTL
        lifts blocking unconditionally.
        """
        self.log.info("TEST MED-4 (GH50 C3 fallout, datasheet SMM is IMR-gated): SMM allows lower priority only for the masked level")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)

            await self.tb.set_imr(0xD7)  # unmask IRQ3, IRQ5
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            ack3 = await self.tb.read_inta()
            if not ack3['valid'] or ack3['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of IRQ3 failed: valid={ack3['valid']}, "
                    f"vector=0x{ack3['vector']:02X}"
                )
                return False

            isr = await self.tb.read_isr()
            if isr != 0x08:
                self.log.error(f"ISR after IRQ3 acknowledge: expected 0x08, got 0x{isr:02X}")
                return False

            # Enable special mask mode (OCW3: ESMM=1, SMM=1) AFTER IRQ3 is
            # already in service.
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW3, 0x68)
            await self.tb.wait_clocks('pclk', 5)

            # (a) IMR[3] is still 0 (unmasked): SMM must NOT lift the block
            # for IRQ3's own in-service level - IRQ5 stays blocked.
            await self.tb.pulse_irq(5, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            if self.tb.dut.int_out.value == 1:
                self.log.error(
                    "int_out asserted for IRQ5 under special mask mode while "
                    "IMR[3]=0 - a datasheet 8259A only lifts the in-service "
                    "block for a level whose IMR bit is explicitly set, and "
                    "IRQ3's mask bit is still clear here"
                )
                return False

            # (b) Set IMR[3]=1 (mask the in-service level) - SMM must now
            # deliver IRQ5.
            await self.tb.set_imr(0xDF)  # IRQ3 masked, IRQ5 still unmasked
            await self.tb.wait_clocks('pclk', 5)

            if self.tb.dut.int_out.value != 1:
                self.log.error(
                    "int_out did not assert for IRQ5 under special mask mode "
                    "after IMR[3] was set to 1 (SMM should now allow "
                    "lower-priority delivery)"
                )
                return False

            ack5 = await self.tb.read_inta()
            if not ack5['valid'] or ack5['vector'] != (0x20 | 5):
                self.log.error(
                    f"Acknowledge of IRQ5 under SMM (IMR[3]=1) failed: "
                    f"valid={ack5['valid']}, vector=0x{ack5['vector']:02X} "
                    f"(expected valid=1, vector=0x25)"
                )
                return False

            # Cleanup
            await self.tb.send_eoi(irq=5, specific=True)
            await self.tb.send_eoi(irq=3, specific=True)
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW3, 0x48)  # SMM off

            self.log.info(
                "PASS: SMM blocked IRQ5 while IMR[3]=0 and delivered it once "
                "IMR[3] was set to 1"
            )
            return True

        except Exception as e:
            self.log.error(f"FAIL: special mask mode test raised {e}")
            return False

    # =========================================================================
    # Defect 4a: rotate-on-non-specific-EOI uses the (always-zero) ISR
    # =========================================================================

    async def test_rotate_on_nonspecific_eoi_changes_priority_base(self) -> bool:
        """
        GitHub #50 C3 fallout: after acknowledging and EOI-rotating IRQ3
        (OCW2 0xA0, rotate on non-specific EOI), the priority base must
        become 3 (making IRQ4 the new highest priority). Verified by
        asserting IRQ2 and IRQ4 together afterward and checking which one
        PIC_STATUS.highest_priority reports.

        History: case 3'b101 in the rotation always_ff (pic_8259_core.sv
        ~356-358) sets `r_priority_base <= highest_isr_comb`, which is
        derived from r_isr. Since ISR is always 0 (C3), highest_isr_comb is
        always 0, so this command ALWAYS resets the base to 0 regardless of
        which IRQ was actually serviced - independent of whether PIC_INTA
        exists at all. test_priority_rotation() sends this exact command
        (rotate_eoi_cmd = 0xA0) but never reads PIC_STATUS.highest_priority
        afterward to check the base actually moved to the acknowledged IRQ.
        """
        self.log.info("TEST MED-5 (GH50 C3 fallout, 4a): rotate-on-non-specific-EOI base")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xF7)  # unmask only IRQ3
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)
            await self.tb.read_inta()  # attempt acknowledge (sets ISR[3] once fixed)

            # Rotate on non-specific EOI.
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW2, 0xA0)
            await self.tb.wait_clocks('pclk', 5)

            # Discriminate the resulting base: unmask IRQ2 and IRQ4 together.
            # base=3 (correct, IRQ3 was serviced) -> search order 4,5,6,7,0,1,2
            #   -> IRQ4 found first -> highest_priority == 4.
            # base=0 (buggy, ISR-derived-0) -> search order 1,2,...,7,0
            #   -> IRQ2 found first -> highest_priority == 2.
            await self.tb.set_imr(0xEB)  # unmask IRQ2, IRQ4
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.pulse_irq(2, pulse_cycles=10)
            await self.tb.pulse_irq(4, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            status = await self.tb.read_status_fields()
            if status['highest_priority'] != 4:
                self.log.error(
                    f"highest_priority after rotate-on-non-specific-EOI of "
                    f"IRQ3: expected 4 (base=3, IRQ4 highest), got "
                    f"{status['highest_priority']} - rotate-on-non-specific-"
                    f"EOI derives the new base from the (always-zero) ISR"
                )
                return False

            self.log.info("PASS: rotate-on-non-specific-EOI moved the priority base to 3")
            return True

        except Exception as e:
            self.log.error(f"FAIL: rotate-on-non-specific-EOI test raised {e}")
            return False

    # =========================================================================
    # Defect 4b (qc round_2 item 1): rotate-on-AEOI oscillates every cycle
    # =========================================================================

    async def test_rotate_on_aeoi_rotates_once_per_acknowledge(self) -> bool:
        """
        GitHub #50 qc round_2 item 1: with rotate-on-AEOI enabled (OCW2
        0x80) and two IRQs pending, the priority base must NOT change on
        its own while no acknowledge has occurred - it must rotate only in
        response to an actual acknowledge event, not merely because
        int_output happens to be asserted.

        History: the rotation always_ff's AEOI branch
        (pic_8259_core.sv ~369-372) is gated only on
        `cfg_aeoi && r_rotate_on_aeoi && int_output` - no edge/strobe, no
        acknowledge dependency. With >=2 pending IRQs and int_output held
        high, the base changes EVERY clock cycle forever (a strict 2-cycle
        alternation between the two pending IRQs in this scenario). This
        does not require PIC_INTA to exist at all - it is observable purely
        from OCW2 configuration and IRQ stimulus, independent of defects
        1-3. No existing test samples the priority base across consecutive
        cycles to catch this; test_priority_rotation() sends 0xA0 (a
        different command, rotate-on-non-specific-EOI) and never enables
        AEOI at all.

        Sampling note: an APB read transaction (read_status_fields()) spans
        several clock cycles per call, which aliases with the exact
        2-cycle oscillation period and can make every sample land on the
        same phase, hiding the bug. This test instead samples
        dut.u_pic_core.r_priority_base directly on consecutive
        RisingEdge(pclk) - the same white-box internal-signal pattern
        hpet_tests_medium.py uses (dut.u_hpet_core.r_timer_comparator
        etc.), enabled by the --public-flat-rw Verilator build flag this
        area already compiles with.
        """
        self.log.info("TEST MED-6 (GH50 round_2 item 1): rotate-on-AEOI base stability")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True, auto_eoi=True)

            # Enable rotate-in-auto-EOI-mode (OCW2 eoi_cmd=100).
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW2, 0x80)
            await self.tb.wait_clocks('pclk', 5)

            await self.tb.set_imr(0xDB)  # unmask IRQ2, IRQ5
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.assert_irq(2)
            await self.tb.assert_irq(5)
            await self.tb.wait_clocks('pclk', 3)
            await self.tb.deassert_irq(2)
            await self.tb.deassert_irq(5)
            await self.tb.wait_clocks('pclk', 2)

            if self.tb.dut.int_out.value != 1:
                self.log.error("int_out did not assert for the pending IRQ2/IRQ5 pair")
                return False

            # No acknowledge has happened at all (PIC_INTA does not exist
            # pre-fix, and is never touched in this test). The base must
            # therefore stay constant across consecutive cycles. Sampled
            # directly off the internal register (see docstring) so the
            # multi-cycle APB read transaction cannot alias with the
            # 2-cycle oscillation period and hide the bug.
            samples = []
            for _ in range(6):
                samples.append(int(self.tb.dut.u_pic_core.r_priority_base.value))
                await RisingEdge(self.tb.dut.pclk)

            if len(set(samples)) != 1:
                self.log.error(
                    f"r_priority_base changed across consecutive cycles with "
                    f"no acknowledge: samples={samples} - rotate-on-AEOI is "
                    f"rotating every cycle from int_output alone instead of "
                    f"once per acknowledge"
                )
                return False

            self.log.info(f"PASS: priority base stable at {samples[0]} with no acknowledge")
            return True

        except Exception as e:
            self.log.error(f"FAIL: rotate-on-AEOI stability test raised {e}")
            return False

    # =========================================================================
    # Defect 5 (qc round_3 item 1): OCW2/OCW3 side effects gated on init
    # =========================================================================

    async def test_ocw2_ocw3_gated_before_init(self) -> bool:
        """
        GitHub #50 qc round_3 item 1: an OCW2 set-priority command issued
        BEFORE the PIC is initialized (or while pic_enable=0) must have NO
        effect - after a subsequent, proper ICW1-4 initialization, the
        priority base must still be the power-on default (base=7, IRQ0
        highest).

        History: the rotation always_ff (pic_8259_core.sv ~344-373) and
        SMM always_ff (~379-391) act on OCW2/OCW3 write strobes with no
        INIT_COMPLETE or cfg_pic_enable gating at all (unlike the IRR/ISR
        blocks, which both check `r_init_state == INIT_COMPLETE`), and
        r_priority_base/r_special_mask_mode only reset on `rst` - not on
        ICW1 re-init - so a pre-init OCW2 write corrupts state that then
        persists through initialization. No existing test issues an OCW2
        command before initialize_pic() is called.
        """
        self.log.info("TEST MED-7 (GH50 round_3 item 1): OCW2 gated before init")

        try:
            await self.tb.reset_dut()  # PIC left disabled/uninitialized

            # Set-priority command (base=3) issued before any ICW1 write.
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW2, 0xC3)
            await self.tb.wait_clocks('pclk', 5)

            # Now perform a normal initialization (does not touch priority base).
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xEE)  # unmask IRQ0, IRQ4
            await self.tb.wait_clocks('pclk', 2)

            # Assert IRQ0 and IRQ4 together: base=7 (correct, default) -> search
            # order 0,1,...,7 -> IRQ0 found first -> highest_priority == 0.
            # base=3 (buggy, pre-init write took effect) -> search order
            # 4,5,6,7,0,1,2,3 -> IRQ4 found first -> highest_priority == 4.
            await self.tb.pulse_irq(0, pulse_cycles=10)
            await self.tb.pulse_irq(4, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            status = await self.tb.read_status_fields()
            if status['highest_priority'] != 0:
                self.log.error(
                    f"highest_priority after a pre-init OCW2 set-priority "
                    f"write: expected 0 (base=7 default, unaffected by a "
                    f"pre-init write), got {status['highest_priority']} - "
                    f"the pre-init OCW2 write took effect and its base "
                    f"survived initialization"
                )
                return False

            self.log.info("PASS: pre-init OCW2 write had no effect on the priority base")
            return True

        except Exception as e:
            self.log.error(f"FAIL: OCW2-gated-before-init test raised {e}")
            return False

    # =========================================================================
    # Defect 6 (qc round_2 item 3): init_mode=1, auto_reset_init=0
    # =========================================================================

    async def test_init_mode_manual_hold_stays_complete(self) -> bool:
        """
        GitHub #50 qc round_2 item 3: with PIC_CONFIG.init_mode=1 and
        auto_reset_init=0, running ICW1..ICW4 must still reach and STAY at
        INIT_COMPLETE (PIC_STATUS.init_complete=1, icw_step=4), and an IRQ
        must be deliverable afterward.

        History: with auto_reset_init=0, pic_8259_config_regs.sv's
        `hwif_in.PIC_CONFIG.init_mode.next` (~200) never clears init_mode,
        so cfg_init_mode stays 1 after ICW4. The init FSM (pic_8259_core.sv
        ~153-160) checks `cfg_init_mode` in INIT_COMPLETE and, since no
        icw1_wr is pending on the very next cycle, immediately falls back
        to INIT_IDLE. initialize_pic() in the TB deliberately never sets
        init_mode at all (see its own comment), so this path has never been
        exercised by the existing suite.
        """
        self.log.info("TEST MED-8 (GH50 round_2 item 3): init_mode=1/auto_reset_init=0 hold")

        try:
            await self.tb.reset_dut()

            # PIC_CONFIG: pic_enable=1, init_mode=1, auto_reset_init=0.
            await self.tb.write_register(PIC8259RegisterMap.PIC_CONFIG, 0x03)
            await self.tb.wait_clocks('pclk', 5)

            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW1, 0x13)  # edge, single, ic4
            await self.tb.wait_clocks('pclk', 5)
            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW2, 0x20)  # vector base
            await self.tb.wait_clocks('pclk', 5)
            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW4, 0x01)  # 8086 mode
            await self.tb.wait_clocks('pclk', 10)

            status = await self.tb.read_status_fields()
            if status['init_complete'] != 1 or status['icw_step'] != 4:
                self.log.error(
                    f"PIC_STATUS after ICW1-4 with init_mode=1/"
                    f"auto_reset_init=0: expected init_complete=1, "
                    f"icw_step=4, got init_complete={status['init_complete']}, "
                    f"icw_step={status['icw_step']} - init bounced back to "
                    f"INIT_IDLE because cfg_init_mode was never cleared"
                )
                return False

            # An IRQ must be deliverable.
            await self.tb.set_imr(0xFE)  # unmask IRQ0
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.pulse_irq(0, pulse_cycles=10)
            int_asserted = await self.tb.wait_for_int(timeout_cycles=10)
            if not int_asserted:
                self.log.error("INT not asserted for IRQ0 after manual-hold initialization")
                return False

            self.log.info("PASS: init_complete held with init_mode=1/auto_reset_init=0")
            return True

        except Exception as e:
            self.log.error(f"FAIL: init_mode manual-hold test raised {e}")
            return False

    # =========================================================================
    # Defect 7 (qc round_2 item 2): address decode aliasing, no PSLVERR
    # =========================================================================

    async def test_address_decode_aliases_dropped_with_pslverr(self) -> bool:
        """
        GitHub #50 qc round_2 item 2 (decided policy, same as ioapic
        GitHub #48): only the mapped registers 0x000-0x028 (plus the fix's
        new 0x02C) are software-visible in this block's 4KB APB window;
        every other address - including an alias that happens to share the
        low 6 bits with a real register, e.g. 0x044 (= 0x004 + 0x40, ICW1)
        and 0x054 (= 0x014 + 0x40, OCW1/IMR) - must be dropped (write
        ignored, read a defined 0) with PSLVERR asserted.

        History: pic_8259_regs's PeakRDL address decode matches only the
        low 6 bits (`cpuif_addr == 6'h4` etc.), but
        pic_8259_config_regs.sv's write-strobe edge detectors
        (r_icw1_wr_ack etc., ~163-181) compare the FULL 12-bit
        regblk_addr, so an alias write updates register-block storage
        (since the 6-bit decode still matches) without stepping the init
        FSM or executing OCW2/OCW3. There is no address-window check at
        all in this block (unlike ioapic_config_regs's w_addr_in_window/
        w_drop, added for GitHub #48's fix) - cpuif_wr_err is hardwired to
        0 in pic_8259_regs.sv, so PSLVERR is never asserted for anything.
        test_register_access() only exercises canonical offsets; there is
        no existing address-decode test for this block at all.
        """
        self.log.info("TEST MED-9 (GH50 round_2 item 2): address decode aliasing")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xAA)
            await self.tb.wait_clocks('pclk', 5)

            golden_imr = await self.tb.read_imr()
            golden_status = await self.tb.read_status_fields()

            # 0x044 would alias ICW1 (0x004) if decode ignores the upper bits.
            wr_044 = await self.tb.write_register(0x044, 0x13)
            # 0x054 would alias OCW1/IMR (0x014).
            wr_054 = await self.tb.write_register(0x054, 0x55)

            for addr, pkt in [(0x044, wr_044), (0x054, wr_054)]:
                if not pkt.pslverr:
                    self.log.error(
                        f"APB write to 0x{addr:03X} (alias of a mapped "
                        f"register's low 6 bits) did not assert PSLVERR"
                    )
                    return False

            imr_after = await self.tb.read_imr()
            if imr_after != golden_imr:
                self.log.error(
                    f"IMR corrupted by a write to APB 0x054: was "
                    f"0x{golden_imr:02X}, now 0x{imr_after:02X} - address "
                    f"decode is aliasing 0x054 onto 0x014 (OCW1/IMR)"
                )
                return False

            status_after = await self.tb.read_status_fields()
            if status_after['icw_step'] != golden_status['icw_step']:
                self.log.error(
                    f"init FSM stepped from a write to APB 0x044: icw_step "
                    f"was {golden_status['icw_step']}, now "
                    f"{status_after['icw_step']} - address decode is "
                    f"aliasing 0x044 onto 0x004 (ICW1)"
                )
                return False

            rd_044, data_044 = await self.tb.read_register(0x044)
            if data_044 != 0:
                self.log.error(
                    f"APB read at 0x044 (alias) returned 0x{data_044:08X}, "
                    f"expected a defined 0 for a dropped access"
                )
                return False
            if not rd_044.pslverr:
                self.log.error("APB read at 0x044 (alias) did not assert PSLVERR")
                return False

            self.log.info("PASS: aliased accesses (0x044, 0x054) dropped with PSLVERR")
            return True

        except Exception as e:
            self.log.error(f"FAIL: address decode aliasing test raised {e}")
            return False

    # =========================================================================
    # Defect 8 (qc round_2 item 4): IMR read-after-write stale window
    # =========================================================================

    async def test_imr_read_after_write_no_stale_window(self) -> bool:
        """
        GitHub #50 qc round_2 item 4: writing PIC_OCW1 (IMR) and reading it
        back immediately must return the just-written value.

        History: pic_8259_regs.sv's PIC_OCW1.imr field reloads from
        hwif_in.PIC_OCW1.imr.next (the core's r_imr mirror) on every cycle
        it is not itself being SW-written, so a read landing exactly two
        cycles after the write could observe the pre-write mirror value.
        The task description flags this window may be unreachable through
        the APB bridge's fixed read/write latency - if so this test is a
        passing guard, recorded as such rather than forced red.
        """
        self.log.info("TEST MED-10 (GH50 round_2 item 4): IMR read-after-write")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)

            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW1, 0x5A)
            imr = await self.tb.read_imr()

            if imr != 0x5A:
                self.log.error(
                    f"IMR read immediately after write: expected 0x5A, got "
                    f"0x{imr:02X} - one-cycle stale mirror window reached "
                    f"through the APB bridge"
                )
                return False

            self.log.info(
                "PASS (guard): IMR read-after-write returned the written value - "
                "the one-cycle stale window described in qc round_2 item 4 is not "
                "reachable through this APB bridge's fixed read/write latency"
            )
            return True

        except Exception as e:
            self.log.error(f"FAIL: IMR read-after-write test raised {e}")
            return False

    # =========================================================================
    # Defect 9: int_out deassert on last-ack+EOI; masked IRQ never asserts
    # =========================================================================

    async def test_int_out_deasserts_after_last_ack_eoi_and_masked_irq_no_assert(self) -> bool:
        """
        GitHub #50 consequence of C3/C4: int_out must NOT assert for a
        masked IRQ (already holds today), and must deassert once the last
        pending/in-service request has been acknowledged and EOI'd (does
        not hold today, because IRR never clears on acknowledge).

        History: test_irq_masking() already covers the masked-IRQ half.
        The ack+EOI-deassert half has no existing coverage: without an
        acknowledge mechanism, EOI only ever touches the (always-zero) ISR,
        so IRR (and hence int_out) never clears via the ack+EOI path at
        all - it only ever clears via IMR masking or full re-init.
        """
        self.log.info("TEST MED-11 (GH50 C3/C4 consequence): int_out deassert + masked no-assert")

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)

            # Part A (already holds today): masked IRQ never asserts int_out.
            await self.tb.set_imr(0xFF)  # mask everything
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.pulse_irq(1, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 10)
            if self.tb.dut.int_out.value == 1:
                self.log.error("int_out asserted for a fully masked IRQ1")
                return False

            # Part B: int_out must deassert once the last request is ack'd+EOI'd.
            await self.tb.set_imr(0xFE)  # unmask only IRQ0
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.pulse_irq(0, pulse_cycles=10)

            int_asserted = await self.tb.wait_for_int(timeout_cycles=10)
            if not int_asserted:
                self.log.error("INT not asserted for IRQ0")
                return False

            await self.tb.read_inta()  # acknowledge
            await self.tb.send_eoi(irq=0, specific=True)
            await self.tb.wait_clocks('pclk', 5)

            if self.tb.dut.int_out.value != 0:
                self.log.error(
                    "int_out still asserted after IRQ0 was acknowledged and "
                    "EOI'd with nothing else pending - IRR never clears on "
                    "acknowledge in the current RTL, so the interrupt stays "
                    "latched"
                )
                return False

            self.log.info("PASS: masked IRQ never asserted, int_out deasserted after ack+EOI")
            return True

        except Exception as e:
            self.log.error(f"FAIL: int_out deassert consequence test raised {e}")
            return False

    # =========================================================================
    # RTL-review finding on the uncommitted #50 fix: non-specific EOI under SMM
    # =========================================================================

    async def test_nonspecific_eoi_under_smm_retires_unmasked_level(self) -> bool:
        """
        RTL review of the uncommitted GitHub #50 fix, 8259A datasheet SMM
        note: a non-specific EOI retires the highest-priority in-service
        level AMONG THOSE WHOSE IMR BIT IS NOT SET - not the highest-
        priority in-service level overall. Scenario: IRQ3 acknowledged
        (ISR[3]=1), then the handler masks its own level and enables SMM
        (IMR[3]=1, SMM on) so a lower-priority IRQ5 can be serviced;
        IRQ5 is acknowledged (ISR[3]|ISR[5] = 0x28). The IRQ5 handler then
        issues a NON-SPECIFIC EOI. Since IRQ3 (higher priority) is masked
        and IRQ5 is not, the EOI must retire IRQ5 (the highest-priority
        UNMASKED in-service level) - ISR must read 0x08 (IRQ3 still in
        service, awaiting its own explicit EOI later).

        History: the non-specific-EOI case in the rotation/ISR-clear logic
        (pic_8259_core.sv, `highest_isr_comb`) scans the raw r_isr with no
        IMR qualification, so it picks the highest-priority bit in ISR
        regardless of mask state. With ISR=0x28 (bits 3 and 5), it retires
        bit 3 (IRQ3, lower index = higher priority in the fixed-priority
        scan) instead of bit 5 - ISR reads 0x20, not the datasheet-correct
        0x08. RTL follow-up expected: this assertion is RED until the
        ISR-scan is made IMR-aware for the non-specific-EOI case.
        """
        self.log.info(
            "TEST MED-13 (GH50 RTL-review, datasheet SMM note): non-specific "
            "EOI under SMM retires the highest-priority UNMASKED in-service level"
        )

        try:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)  # base=7

            await self.tb.set_imr(0xD7)  # unmask IRQ3, IRQ5
            await self.tb.wait_clocks('pclk', 2)

            await self.tb.pulse_irq(3, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            ack3 = await self.tb.read_inta()
            if not ack3['valid'] or ack3['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of IRQ3 failed: valid={ack3['valid']}, "
                    f"vector=0x{ack3['vector']:02X} (expected valid=1, vector=0x23)"
                )
                return False

            isr1 = await self.tb.read_isr()
            if isr1 != 0x08:
                self.log.error(f"ISR after IRQ3 acknowledge: expected 0x08, got 0x{isr1:02X}")
                return False

            # Handler masks its own level and enables SMM.
            await self.tb.set_imr(0xDF)  # IMR[3]=1, IRQ5 still unmasked
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW3, 0x68)  # SMM on
            await self.tb.wait_clocks('pclk', 5)

            # IRQ5 is now eligible under SMM.
            await self.tb.pulse_irq(5, pulse_cycles=10)
            await self.tb.wait_clocks('pclk', 5)

            ack5 = await self.tb.read_inta()
            if not ack5['valid'] or ack5['vector'] != (0x20 | 5):
                self.log.error(
                    f"Acknowledge of IRQ5 under SMM failed: valid={ack5['valid']}, "
                    f"vector=0x{ack5['vector']:02X} (expected valid=1, vector=0x25)"
                )
                return False

            isr2 = await self.tb.read_isr()
            if isr2 != 0x28:
                self.log.error(f"ISR with IRQ3+IRQ5 both in service: expected 0x28, got 0x{isr2:02X}")
                return False

            # IRQ5's handler issues a NON-SPECIFIC EOI.
            await self.tb.send_eoi(irq=None, specific=False)
            await self.tb.wait_clocks('pclk', 2)

            isr3 = await self.tb.read_isr()
            if isr3 != 0x08:
                self.log.error(
                    f"ISR after non-specific EOI under SMM: expected 0x08 "
                    f"(IRQ5 retired as the highest-priority UNMASKED "
                    f"in-service level, IRQ3 still in service), got "
                    f"0x{isr3:02X} - the non-specific-EOI scan is not "
                    f"IMR-aware and retired the wrong level"
                )
                return False

            # Cleanup: disable SMM, unmask, retire IRQ3.
            await self.tb.write_register(PIC8259RegisterMap.PIC_OCW3, 0x48)  # SMM off
            await self.tb.set_imr(0x00)
            await self.tb.wait_clocks('pclk', 2)
            await self.tb.send_eoi(irq=None, specific=False)
            await self.tb.wait_clocks('pclk', 2)

            isr4 = await self.tb.read_isr()
            if isr4 != 0x00:
                self.log.error(f"ISR after final cleanup EOI: expected 0x00, got 0x{isr4:02X}")
                return False

            self.log.info(
                "PASS: non-specific EOI under SMM retired the highest-priority "
                "unmasked in-service level"
            )
            return True

        except Exception as e:
            self.log.error(f"FAIL: non-specific-EOI-under-SMM test raised {e}")
            return False

    # =========================================================================
    # RTL-review finding on the uncommitted #50 fix: edge frozen while disabled
    # =========================================================================

    async def test_edge_inside_disabled_window_is_not_lost(self) -> bool:
        """
        RTL review of the uncommitted GitHub #50 fix: a genuinely NEW edge
        that occurs while cfg_pic_enable=0 must be seen once the PIC is
        re-enabled, even though the line never toggles again after
        re-enable.

        Scenario: IRQ3 is asserted, acknowledged and EOI'd with the line
        left HIGH (a level-style hold on an edge-triggered input, as a
        real interrupt source often does). The PIC is then disabled
        (PIC_CONFIG.pic_enable=0). While disabled, IRQ3 is deasserted and
        then re-asserted (a genuine new request) and held. The PIC is then
        re-enabled. Contract: the new request must be observed - IRR[3]
        sets and int_out asserts (equivalently, PIC_INTA returns valid=1,
        vector=0x23) - without requiring the line to toggle again after
        re-enable.

        History: pic_8259_core.sv's edge-detect reference register
        (`r_irq_last`) only updates `else if (cfg_pic_enable &&
        (r_init_state == INIT_COMPLETE))` - it is frozen at whatever value
        it held when the PIC was disabled. Here that frozen value is 1
        (IRQ3 was high at disable time). The deassert+reassert transition
        that happens WHILE disabled is invisible to r_irq_last, so on
        re-enable, r_irq_last (=1, frozen) and irq_in (=1, held) are equal
        and `w_irq_trigger = irq_in & ~r_irq_last` is 0 - no edge is
        detected, and the new request is silently swallowed. RTL follow-up
        expected: this assertion is RED until r_irq_last is made to track
        (or IRR is otherwise made to catch) an edge that occurred while
        disabled.

        ICW2..ICW4 window (observational, not asserted): a line that rises
        after ICW1 but before ICW4 sits in a similarly-gated window - the
        IRR update block only runs at `r_init_state == INIT_COMPLETE`, so
        the mid-init transition itself produces no IRR bit during the
        window. What is observed and logged below (deliberately not
        asserted, per the ambiguity in this scenario) is whether IRR ends
        up set for that line once INIT_COMPLETE is reached: r_irq_last is
        sampled from irq_in at the icw1_wr edge (before the line rose) and
        then stays frozen through the WAIT_ICW2/WAIT_ICW4 states, so on the
        first INIT_COMPLETE cycle w_irq_trigger evaluates
        `irq_in(=1) & ~r_irq_last(=0, stale from icw1_wr time)` = 1 - IRR
        appears to catch a "manufactured" edge exactly at INIT_COMPLETE,
        even though the physical rising transition happened earlier and
        the line has been steady-high since. Whether that is the intended
        contract (arguably reasonable - the level is genuinely pending and
        unmasked by the time the PIC can act on it) or a defect
        (a transition mid-init is being reported as if it just occurred)
        is exactly the ambiguity called out in the task; this test states
        the observation rather than asserting a verdict on it.
        """
        self.log.info(
            "TEST MED-14 (GH50 RTL-review): a genuinely new edge while "
            "disabled must not be lost on re-enable"
        )

        async def _run_main_scenario() -> bool:
            await self.tb.reset_dut()
            await self.tb.initialize_pic(vector_base=0x20, edge_triggered=True)
            await self.tb.set_imr(0xF7)  # unmask only IRQ3
            await self.tb.wait_clocks('pclk', 2)

            # Service IRQ3 with the line left HIGH (not pulsed off).
            await self.tb.assert_irq(3)
            await self.tb.wait_clocks('pclk', 5)

            ack = await self.tb.read_inta()
            if not ack['valid'] or ack['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of IRQ3 failed: valid={ack['valid']}, "
                    f"vector=0x{ack['vector']:02X} (expected valid=1, vector=0x23)"
                )
                return False

            await self.tb.send_eoi(irq=3, specific=True)
            await self.tb.wait_clocks('pclk', 2)

            # Disable the PIC (PIC_CONFIG: pic_enable=0).
            await self.tb.write_register(PIC8259RegisterMap.PIC_CONFIG, 0x00)
            await self.tb.wait_clocks('pclk', 5)

            # While disabled: deassert then re-assert IRQ3 - a genuine new
            # request - and hold it.
            await self.tb.deassert_irq(3)
            await self.tb.wait_clocks('pclk', 5)
            await self.tb.assert_irq(3)
            await self.tb.wait_clocks('pclk', 5)

            # Re-enable the PIC. The line does not toggle again from here.
            await self.tb.write_register(PIC8259RegisterMap.PIC_CONFIG, 0x01)
            await self.tb.wait_clocks('pclk', 10)

            irr = await self.tb.read_irr()
            if (irr & 0x08) == 0:
                self.log.error(
                    f"IRR[3] not set after re-enable for an edge that "
                    f"occurred while the PIC was disabled: IRR=0x{irr:02X} "
                    f"- the edge-detect reference (r_irq_last) is frozen "
                    f"while disabled and does not track transitions that "
                    f"happen during the disabled window, so this new "
                    f"request was swallowed"
                )
                return False

            if self.tb.dut.int_out.value != 1:
                self.log.error(
                    "int_out did not assert after re-enable for an edge "
                    "that occurred while the PIC was disabled"
                )
                return False

            ack2 = await self.tb.read_inta()
            if not ack2['valid'] or ack2['vector'] != (0x20 | 3):
                self.log.error(
                    f"Acknowledge of the edge-while-disabled IRQ3 failed: "
                    f"valid={ack2['valid']}, vector=0x{ack2['vector']:02X} "
                    f"(expected valid=1, vector=0x23)"
                )
                return False

            await self.tb.send_eoi(irq=3, specific=True)
            return True

        async def _run_observational_icw_window() -> None:
            # --- Observational only: ICW2..ICW4 mid-init window ---------
            await self.tb.reset_dut()
            await self.tb.write_register(PIC8259RegisterMap.PIC_CONFIG, 0x01)  # pic_enable=1
            await self.tb.wait_clocks('pclk', 5)

            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW1, 0x13)  # edge, single, ic4
            await self.tb.wait_clocks('pclk', 3)

            # Line rises after ICW1 (mid-init) and is held high through the
            # rest of the sequence.
            await self.tb.assert_irq(5)
            await self.tb.wait_clocks('pclk', 3)

            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW2, 0x20)
            await self.tb.wait_clocks('pclk', 3)
            await self.tb.write_register(PIC8259RegisterMap.PIC_ICW4, 0x01)
            await self.tb.wait_clocks('pclk', 10)

            await self.tb.set_imr(0xDF)  # unmask IRQ5
            await self.tb.wait_clocks('pclk', 5)

            irr_mid_init = await self.tb.read_irr()
            observed = bool(irr_mid_init & 0x20)
            self.log.info(
                f"OBSERVED (not asserted): IRR[5] = {int(observed)} "
                f"(IRR=0x{irr_mid_init:02X}) for a line that rose after "
                f"ICW1 and was held high through ICW2/ICW4 - see docstring "
                f"for why this is ambiguous rather than a pass/fail contract"
            )

        try:
            # try/finally (rather than this file's usual early-return
            # style) is deliberate here: this test holds irq_in bits HIGH
            # across several assertions by design (that is the whole
            # scenario), so an early `return False` on ANY of them must
            # still release those lines - otherwise a RED result here
            # leaks a stuck-high IRQ line into every test that runs after
            # it in the suite (found during authoring: an early version
            # left IRQ3 asserted after a failed check, and the very next
            # full-only test, test_all_irq_lines(), failed collaterally
            # because it never calls reset_dut() and inherited the stuck
            # line).
            try:
                main_ok = await _run_main_scenario()
            finally:
                await self.tb.deassert_irq(3)
                await self.tb.wait_clocks('pclk', 2)

            if not main_ok:
                return False

            self.log.info(
                "PASS: an edge that occurred while the PIC was disabled was "
                "observed and delivered once re-enabled"
            )

            try:
                await _run_observational_icw_window()
            finally:
                await self.tb.deassert_irq(5)

            return True

        except Exception as e:
            self.log.error(f"FAIL: edge-inside-disabled-window test raised {e}")
            await self.tb.deassert_irq(3)
            await self.tb.deassert_irq(5)
            return False
