#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# Bridge1x2RdRegblockMonTB - Testbench for bridge_1x2_rd_regblock_mon
# Generated by bridge test generator from TOML/CSV configuration.
#
# Architecture:
#   - Masters use protocol-specific BFMs (AXI4MasterRead/Write,
#     AXIL4MasterRead/Write, APBMaster). NEVER bare GAXI — reaching past
#     the protocol BFM bypasses the framework's memory model, ID tracking,
#     response generation, and compliance checking, forcing the test to
#     reimplement protocol semantics by hand.
#   - Slaves use protocol-specific BFMs (AXI4SlaveRead/Write,
#     AXIL4SlaveRead/Write, APBSlave), each backed by its own MemoryModel
#     pre-seeded with a distinct per-slave pattern. The slave BFM auto-
#     responds from memory honoring whatever ARSIZE/ARLEN/ARADDR the
#     bridge forwards, so the same TB works across direct, width-converted,
#     and AXIL-shimmed paths.
#
# Slave memory seed pattern (32-bit data path):
#   value(slave_idx, word_offset) = ((slave_idx+1) << 24) | (word_offset & 0xFFFFFF)
#
#   Upper byte = (1-indexed) slave ID, lower 24 bits = word index within
#   the slave's window. A misroute is visible at a glance: a read of
#   slave 4 that returns 0x02_xxxxxx came from slave 1.

import os
import sys

# Import framework utilities (PYTHONPATH includes bin/)
from TBClasses.shared.utilities import get_repo_root

# Add repo root to Python path using robust git-based method
repo_root = get_repo_root()
sys.path.insert(0, repo_root)

import cocotb
from cocotb.triggers import RisingEdge, ClockCycles
from TBClasses.shared.tbbase import TBBase

# Protocol BFMs — required entry points for every transaction.
from CocoTBFramework.components.axi4.axi4_interfaces import (
    AXI4MasterRead, AXI4MasterWrite, AXI4SlaveRead, AXI4SlaveWrite,
)
from CocoTBFramework.components.axil4.axil4_interfaces import (
    AXIL4MasterRead, AXIL4MasterWrite, AXIL4SlaveRead, AXIL4SlaveWrite,
)
# Protocol checkers ride every AXI master port, AXI4 as well as AXI5: the
# checker binds its five channel monitors and reports handshake, burst, ID
# and response-code violations that a data round-trip cannot see.
from CocoTBFramework.components.axi4.axi4_compliance_checker import AXI4ComplianceChecker
from CocoTBFramework.components.apb.apb_components import APBMaster, APBSlave

# Memory model — shared across all protocol slave BFMs (every slave gets
# its own instance, pre-seeded with a distinct pattern).
from CocoTBFramework.components.shared.memory_model import MemoryModel
from projects.components.bridge.dv.tbclasses.bridge_levels import (
    PROFILE, current_level, seeded_rng,
)


class Bridge1x2RdRegblockMonTB(TBBase):
    """
    Testbench for bridge_1x2_rd_regblock_mon bridge.

    Configuration:
        Masters: 1 (cpu_rd)
        Slaves:  2 (ddr_rd, sram_rd)
        Channels: RD
        Data Width: 32
        Addr Width: 64
        ID Width: 8
    """

    # ----------------------------------------------------------------------
    # Construction
    # ----------------------------------------------------------------------

    def __init__(self, dut):
        super().__init__(dut)
        self.dut = dut
        self.clock = dut.aclk
        self.clock_name = 'aclk'
        self.reset_n = dut.aresetn

        # Bridge configuration
        self.num_masters = 1
        self.num_slaves = 2
        self.data_width = 32
        self.addr_width = 64
        self.id_width = 8

        # Depth: TEST_LEVEL (exported by the pytest wrapper) picks the profile
        # every count in the tests is read from; SEED (pinned per test node
        # by the repo-root conftest) seeds the one RNG the tests draw from.
        # Both are logged so a failing cell names how to replay it.
        self.level = current_level()
        self.level_cfg = PROFILE[self.level]
        self.seed, self.rng = seeded_rng(self.log)
        self.log.info(f"TEST_LEVEL={self.level}: {self.level_cfg}")

        # Per-slave metadata used by misroute checks and pattern computation.
        # slave_info[i] = (protocol, base_addr, addr_range, data_width)
        self.slave_info = {
            0: ('axi4', 0x00000000, 0x80000000, 32),  # ddr_rd
            1: ('axi4', 0x80000000, 0x80000000, 32),  # sram_rd
        }

        # Per-master data width (in bits). Used by master_read/write helpers
        # and by slave_mem_read so verification reads back master-width
        # bytes regardless of the slave's native width.
        self.master_data_width = {
            0: 32,  # cpu_rd
        }

        # Slave memory models — one per slave, pre-seeded.
        self.slave_memory = {}
        # Slave BFMs (auto-responds from memory_model).
        # For rw slaves we keep both read+write handles.
        self.slave_rd = {}
        self.slave_wr = {}
        # APB doesn't split rd/wr — single APBSlave per port.
        self.slave_apb = {}

        # Master BFMs — separate read and write handles. For wr-only or
        # rd-only masters only one of these gets populated.
        self.master_rd = {}
        self.master_wr = {}
        # APB master (one handle per APB master port).
        self.master_apb = {}
        # AXI5ComplianceChecker per AXI5 master port (see _setup_master_*).
        self.compliance = {}

        self._setup_slave_0_ddr_rd()
        self._setup_slave_1_sram_rd()
        self._setup_master_0_cpu_rd()

    # ----------------------------------------------------------------------
    # Slave seed pattern
    # ----------------------------------------------------------------------

    @staticmethod
    def _seed_value(slave_idx: int, word_offset: int, data_width: int) -> int:
        """Deterministic seed pattern for slave[slave_idx]'s memory.

        Encoding (32-bit case): upper byte = slave_idx+1, lower 24 bits =
        word index. Generalizes to wider data widths by placing the slave
        ID byte in the top byte of the data word (so a hex dump still
        shows the slave ID in the high nibbles).
        """
        id_byte = (slave_idx + 1) & 0xFF
        index_mask = (1 << (data_width - 8)) - 1
        return (id_byte << (data_width - 8)) | (word_offset & index_mask)

    # Cap the per-slave MemoryModel size. The seeded pattern is purely a
    # test fixture — bytes the bridge moves out of memory; the slave's
    # natural addr_range in the TOML can be huge (e.g. 1 GB DDR window)
    # but tests only ever touch a handful of addresses. Eager-filling
    # the full window OOM's the safety monitor (numpy uint8 for data
    # plus two uint32 access-tracking maps = 9 bytes per addressable
    # byte, scaled across multiple multi-hundred-MB slaves).
    #
    # Pre-seed the first SLAVE_MEM_CAP_BYTES of each slave; tests must
    # probe within that window for data verification.
    #
    # 64 KB, not 4 KB, and the difference is load-bearing. The two slave BFMs
    # DISAGREE about an out-of-range access: AXI4SlaveWrite logs it and leaves
    # RESP alone (a silent drop, answering OKAY), while AXIL4SlaveWrite answers
    # SLVERR. An earlier version of this comment asserted the first behaviour
    # for both and sized the cap at 4 KB on that basis, so a boundary probe of
    # a 64 KB AXI4-Lite slave -- mix_a's axil_periph, mix_c's cfg_regs -- got a
    # legitimate SLVERR from a model that simply did not extend that far, and
    # the master raised. Routing was correct the whole time; the model was
    # short.
    #
    # 64 KB covers a typical peripheral window whole, so those probes now land
    # in real memory and verify DATA as well as routing rather than depending
    # on a drop. Cost is 9 bytes per addressable byte (uint8 data + two uint32
    # access maps) = ~576 KB per slave, against the multi-GB windows the cap
    # exists to stop. A slave larger than this is still capped, and a probe
    # past the cap is answered by the ONE out-of-range contract every slave
    # BFM now follows (RDS-DV shared/memory_model.py, BRIDGE-008 closed
    # 2026-09-09): SLVERR, nothing written, 0xDEADDEAD data, one warning.
    # The probe still proves routing -- the error comes back from the slave
    # the address decodes to -- and is data-checked only inside the seeded
    # region. That is the model's limit; an address the bridge does not
    # decode at all is the subtractive slave's DECERR (BRIDGE-009), a
    # different thing.
    SLAVE_MEM_CAP_BYTES = 64 * 1024

    # Bridge page granularity. The slave-window validator already aligns
    # each base_addr / addr_range to PAGE_SIZE (4 KB), so page-level probes
    # are always safe to construct.
    PAGE_SIZE = 0x1000

    def _build_preset(self, slave_idx: int, addr_range: int, data_width: int) -> bytearray:
        """Build the bytearray preset for a slave's MemoryModel. Caps the
        seeded region at SLAVE_MEM_CAP_BYTES — see the class-level note."""
        bytes_per_word = data_width // 8
        effective = min(addr_range, self.SLAVE_MEM_CAP_BYTES)
        num_words = effective // bytes_per_word
        buf = bytearray(effective)
        for w in range(num_words):
            v = self._seed_value(slave_idx, w, data_width)
            chunk = v.to_bytes(bytes_per_word, 'little')
            buf[w * bytes_per_word:(w + 1) * bytes_per_word] = chunk
        return buf

    def _slave_mem_bytes(self, slave_idx: int) -> int:
        """Return the actual MemoryModel byte capacity for slave_idx
        (= min(addr_range, SLAVE_MEM_CAP_BYTES))."""
        _, _, addr_range, _ = self.slave_info[slave_idx]
        return min(addr_range, self.SLAVE_MEM_CAP_BYTES)

    def slave_probe_pages(self, slave_idx: int, mode: str = 'boundary') -> list:
        """Return absolute page-base addresses to probe within slave_idx's
        window.

        mode='boundary': three pages — first, middle, last of the slave's
            addr_range. For a one-page slave returns [base]; for two pages
            [base, base+PAGE]. This is the default — it exercises low-bit,
            mid-bit, and high-bit address decode without scaling test
            runtime with slave size.

        mode='all': every page in the slave's addr_range. Useful for
            stress / regression on small slaves; large windows (GB-class
            DDR) explode the probe count, so use with care.
        """
        _, base, addr_range, _ = self.slave_info[slave_idx]
        num_pages = max(1, addr_range // self.PAGE_SIZE)
        if mode == 'all':
            return [base + i * self.PAGE_SIZE for i in range(num_pages)]
        # boundary (default)
        if num_pages == 1:
            boundary = [base]
        elif num_pages == 2:
            boundary = [base, base + self.PAGE_SIZE]
        else:
            mid = (num_pages // 2) * self.PAGE_SIZE
            last = (num_pages - 1) * self.PAGE_SIZE
            boundary = [base, base + mid, base + last]
        if mode != 'seeded':
            return boundary
        # 'seeded' (the full level): the boundary pages plus EVERY page whose
        # data can be verified -- the seeded region is capped at
        # SLAVE_MEM_CAP_BYTES, so this walks at most 16 pages per slave
        # however large the window, unlike 'all'.
        seeded_pages = min(num_pages, self._slave_mem_bytes(slave_idx) // self.PAGE_SIZE)
        pages = [base + i * self.PAGE_SIZE for i in range(seeded_pages)]
        return pages + [pg for pg in boundary if pg not in pages]

    def _probe_align(self, slave_idx: int, master_idx: int = 0) -> int:
        """Byte alignment a probe must honour: max(master_width, slave_width)."""
        master_bytes = self.master_data_width[master_idx] // 8
        slave_bytes = self.slave_info[slave_idx][3] // 8
        return max(master_bytes, slave_bytes)

    def page_probe_offsets(self, slave_idx: int, master_idx: int = 0,
                           count: int = None) -> list:
        """Return in-page byte offsets [low, mid, high] for probing, each
        aligned to max(master_width, slave_width). Catches address decoders
        that ignore low bits (low probe), mid-bit decoders (middle), and
        decoders that off-by-one at the page boundary (high — last aligned
        word in the page). `count` (from the level profile) takes the first
        N of the three: gate probes low only, func and full all three."""
        align = self._probe_align(slave_idx, master_idx)
        align_mask = ~(align - 1) & 0xFFFFFFFFFFFFFFFF
        low = 0
        mid = (self.PAGE_SIZE // 2) & align_mask
        high = (self.PAGE_SIZE - align) & align_mask
        offsets = [low, mid, high]
        if count is None:
            count = self.level_cfg['in_page_probes']
        return offsets[:max(1, count)]

    def connectivity_addrs(self, slave_idx: int, master_idx: int = 0) -> list:
        """Addresses the connectivity test touches for one (master, slave)
        pair: the fixed +0x100 probe first (every level, so gate is the old
        test exactly), then `connectivity_offsets - 1` further aligned,
        seeded, distinct offsets drawn from this TB's RNG. Verifiable by
        construction: all inside the seeded region."""
        _, base, _, _ = self.slave_info[slave_idx]
        align = self._probe_align(slave_idx, master_idx)
        seeded = self._slave_mem_bytes(slave_idx)
        want = max(1, self.level_cfg['connectivity_offsets'])
        addrs = [base + 0x100] if seeded > 0x100 + align else [base]
        slots = max(1, seeded // align)
        tries = 0
        while len(addrs) < want and tries < 64 * want:
            tries += 1
            a = base + self.rng.randrange(slots) * align
            if a not in addrs:
                addrs.append(a)
        return addrs

    def is_seeded(self, slave_idx: int, addr: int) -> bool:
        """True if `addr` falls inside slave_idx's seeded MemoryModel
        region — i.e. a read at this addr will return the seed pattern
        and a write here is observable via slave_mem_read."""
        _, base, _, _ = self.slave_info[slave_idx]
        offset = addr - base
        return 0 <= offset < self._slave_mem_bytes(slave_idx)

    def expected_pattern(self, slave_idx: int, addr: int) -> int:
        """Return the seeded *master-width* value at the given absolute
        address. Reads `master_data_width_bytes` bytes of memory at
        addr (relative to the slave's base) and interprets little-endian.

        Works for direct paths, width-converted paths, and AXIL-shimmed
        paths uniformly — the bridge moves bytes; we read the same bytes
        back and the master's view is whatever those bytes spell out at
        its data width."""
        # Default to the first master's width — single-master configs
        # this is unambiguous. For multi-master, callers should use
        # slave_mem_read(slave_idx, addr, byte_count=...) explicitly.
        master_width = self.master_data_width.get(0, self.data_width)
        return self.slave_mem_read(slave_idx, addr, byte_count=master_width // 8)

    def slave_mem_read(self, slave_idx: int, addr: int, byte_count: int = None,
                       master_idx: int = 0) -> int:
        """Read `byte_count` bytes from slave[slave_idx]'s memory at
        absolute address `addr` and return as a little-endian int.

        If byte_count is None, derives it from master_idx's data width.
        Defaulting to master 0 covers single-master configs; multi-master
        callers must pass master_idx of the master that wrote (or that
        the master_read will probe), otherwise read-back will include
        stale bytes from the seed pattern beyond what the master touched.
        For APB slaves, reads directly from the APBSlave's internal memory."""
        proto, base, _, slave_dw = self.slave_info[slave_idx]
        if byte_count is None:
            master_width = self.master_data_width.get(master_idx, self.data_width)
            byte_count = master_width // 8
        offset = addr - base
        if proto in ('apb', 'apb5'):
            apb = self.slave_apb[slave_idx]
            # Read where the APB slave ACTUALLY stored it. APBSlave does not
            # subtract the window base: it masks the full PADDR by its own
            # memory size --
            #     addr_bits = (num_lines * strb_bits - 1).bit_length()
            #     self.mem.write(address & ((1 << addr_bits) - 1), ...)
            # -- so `addr - base` is only the same place when
            # `base & mask == 0`. It silently was, for every APB slave whose
            # base happened to be mask-aligned, until the memory model grew and
            # widened the mask: mix_d's apb_periph at base 0x4000_1000 then
            # stored a write to 0x4000_1100 at 0x1100 while this read looked at
            # 0x0100 and got seed data back. Mirror the slave's own mapping
            # instead of assuming one.
            span = apb.num_lines * apb.strb_bits
            mask = (1 << (span - 1).bit_length()) - 1
            data_bytes = apb.mem.read(addr & mask, byte_count)
        else:
            mem = self.slave_memory[slave_idx]
            data_bytes = mem.read(offset, byte_count)
        return int.from_bytes(bytes(data_bytes), 'little')

    # ----------------------------------------------------------------------
    # Per-master setup (uses dispatched protocol BFM)
    # ----------------------------------------------------------------------

    def _setup_master_0_cpu_rd(self):
        """Set up protocol BFMs for master 0: cpu_rd (protocol: axi4)"""
        self.master_rd[0] = AXI4MasterRead(
            self.dut, self.clock,
            prefix="cpu_rd_axi_",
            log=self.log,
            data_width=32,
            addr_width=32,
            id_width=4,
            user_width=1,
            multi_sig=True,
        )
        # Protocol checker on the AXI4 boundary: handshake stability, burst
        # length/size, xLAST, ID ordering and response codes. Armed in
        # setup_clocks_and_reset; assert_compliance() reads the verdict.
        self.compliance[0] = AXI4ComplianceChecker(
            self.dut, self.clock,
            prefix="cpu_rd_axi_",
            log=self.log,
            data_width=32,
            addr_width=32,
            id_width=4,
            user_width=1,
        )

    # ----------------------------------------------------------------------
    # Per-slave setup (BFM + pre-seeded MemoryModel)
    # ----------------------------------------------------------------------

    def _setup_slave_0_ddr_rd(self):
        """Set up protocol BFM and pre-seeded MemoryModel for slave 0: ddr_rd (protocol: axi4)"""
        # AXI4 slave — full memory-backed BFM.
        bytes_per_line = 32 // 8
        addr_range = 0x80000000
        # Cap MemoryModel size — see SLAVE_MEM_CAP_BYTES comment.
        mem_bytes = min(addr_range, self.SLAVE_MEM_CAP_BYTES)
        preset = self._build_preset(0, addr_range, 32)
        self.slave_memory[0] = MemoryModel(
            num_lines=mem_bytes // bytes_per_line,
            bytes_per_line=bytes_per_line,
            preset_values=list(preset),
            log=self.log,
        )
        self.slave_rd[0] = AXI4SlaveRead(
            self.dut, self.clock,
            prefix="ddr_rd_axi_",
            log=self.log,
            data_width=32,
            addr_width=32,
            id_width=4,
            user_width=1,
            multi_sig=True,
            memory_model=self.slave_memory[0],
            base_addr=0x00000000,
        )
    def _setup_slave_1_sram_rd(self):
        """Set up protocol BFM and pre-seeded MemoryModel for slave 1: sram_rd (protocol: axi4)"""
        # AXI4 slave — full memory-backed BFM.
        bytes_per_line = 32 // 8
        addr_range = 0x80000000
        # Cap MemoryModel size — see SLAVE_MEM_CAP_BYTES comment.
        mem_bytes = min(addr_range, self.SLAVE_MEM_CAP_BYTES)
        preset = self._build_preset(1, addr_range, 32)
        self.slave_memory[1] = MemoryModel(
            num_lines=mem_bytes // bytes_per_line,
            bytes_per_line=bytes_per_line,
            preset_values=list(preset),
            log=self.log,
        )
        self.slave_rd[1] = AXI4SlaveRead(
            self.dut, self.clock,
            prefix="sram_rd_axi_",
            log=self.log,
            data_width=32,
            addr_width=32,
            id_width=4,
            user_width=1,
            multi_sig=True,
            memory_model=self.slave_memory[1],
            base_addr=0x80000000,
        )

    # ----------------------------------------------------------------------
    # Reset / clock plumbing
    # ----------------------------------------------------------------------

    async def setup_clocks_and_reset(self):
        await self.start_clock(self.clock_name, freq=10, units='ns')
        await self.assert_reset()
        await self.wait_clocks(self.clock_name, 10)
        await self.deassert_reset()
        await self.wait_clocks(self.clock_name, 5)
        for idx, checker in self.compliance.items():
            # setup_monitors binds the five channel monitors AND starts the
            # transaction / handshake / cycle loops itself (and raises if it
            # cannot bind). Starting the loops again here doubled every count.
            checker.setup_monitors()
            self.log.info(f"AXI protocol checker armed on master {idx}")

    def assert_compliance(self, allow: dict = None) -> dict:
        """Every AXI master port's protocol checker must report zero violations.
        Called by each generated test before it declares PASSED, so a
        protocol error on the AXI5 boundary fails the test that caused it
        even when the data still round-tripped. Returns the reports.

        `allow` = {violation_type_name: exact_count} lets a hand-written test
        name a violation class it deliberately provokes -- and the count it
        expects, so one more or one fewer still fails. Nothing is tolerated
        implicitly; the generated tests never pass it."""
        reports = {}
        allow = dict(allow or {})
        for idx, checker in self.compliance.items():
            report = checker.get_compliance_report()
            reports[idx] = report
            # A checker that never armed reports 'disabled' and no counts; a
            # checker that armed but saw nothing has checks_performed == 0.
            # Both read as "zero violations" to a naive caller -- and did,
            # for a month (RDS-DV 2026-09-09). Neither is a pass.
            assert report.get('compliance_checking') == 'enabled', (
                f"protocol checker on master {idx} is not enabled: {report}")
            # 'armed' and 'channels' exist so a blind checker cannot pass as a
            # clean one: a prefix whose separator did not resolve used to bind
            # no channels and report zero violations forever.
            assert report.get('armed'), (
                f"protocol checker on master {idx} bound no channels "
                f"(prefix resolution failed?): {report}")
            stats = report.get('statistics', {})
            checks = stats.get('checks_performed', 0)
            violations = report.get('total_violations', 0)
            if isinstance(violations, (list, tuple)):
                violations = len(violations)
            self.log.info(f"AXI compliance master {idx}: {violations} violation(s) in "
                          f"{checks} checks; stats={ {k: v for k, v in stats.items() if v} }")
            assert checks > 0, (
                f"protocol checker on master {idx} performed no checks -- "
                f"its verdict is vacuous")
            summary = dict(report.get('violation_summary', {}))
            for name, expected in allow.items():
                got = summary.pop(name, 0)
                assert got == expected, (
                    f"AXI5 compliance master {idx}: expected exactly {expected} "
                    f"{name} (deliberately provoked), saw {got}")
            assert not summary, (
                f"AXI protocol violations on master {idx}: {summary}")
        return reports

    async def assert_reset(self):
        self.reset_n.value = 0

    async def deassert_reset(self):
        self.reset_n.value = 1

    # ----------------------------------------------------------------------
    # Slave backpressure (depth knob)
    # ----------------------------------------------------------------------

    def set_slave_response_delay(self, slave_idx: int, cycles: int) -> None:
        """Hold B/R off at slave[slave_idx] for `cycles` before responding.

        The bridge tracks the originating master in a fixed-depth FIFO per
        slave port and pops it on the response, so OUTSTANDING DEPTH is only
        reachable when a slave is slow. The default BFM slave answers in ~1
        cycle, which is why no test got anywhere near the depth where
        BRIDGE-011 bit until this knob existed. APB slaves have no such
        attribute and are left alone.
        """
        for container in (self.slave_wr, self.slave_rd):
            bfm = container.get(slave_idx)
            if bfm is not None and hasattr(bfm, 'response_delay_cycles'):
                bfm.response_delay_cycles = cycles

    def apply_level_slave_delay(self) -> int:
        """Apply the level profile's slave_delay to every slave (full: 24
        cycles, so requests queue in the fabric; gate/func: 0). Returns it."""
        cycles = self.level_cfg['slave_delay']
        if cycles:
            for idx in self.slave_info:
                self.set_slave_response_delay(idx, cycles)
            self.log.info(f"level {self.level}: slave response delay {cycles} cycles on all slaves")
        return cycles

    # ----------------------------------------------------------------------
    # Transaction helpers — thin wrappers over protocol BFMs
    # ----------------------------------------------------------------------

    def _natural_arsize(self, master_idx: int) -> int:
        """AXI4 ARSIZE/AWSIZE encoding for one beat at the master's native
        data width: log2(bytes_per_beat). The bridge's dwidth converters
        rewrite (size,len) on the way to the slave based on the ratio of
        master_dw to slave_dw — that math only works if the master tells
        the truth about its native beat size. The BFM defaults to size=2
        (4 bytes), which silently misrepresents 64b masters and makes the
        converter emit twice the burst length expected."""
        master_dw = self.master_data_width[master_idx]
        bytes_per_beat = master_dw // 8
        return (bytes_per_beat - 1).bit_length()

    async def master_read(self, master_idx: int, address: int) -> int:
        """Single-beat read from master[master_idx]. Returns master-width int."""
        if master_idx in self.master_apb:
            return await self.master_apb[master_idx].read(address)
        rd = self.master_rd[master_idx]
        return await rd.single_read(address, size=self._natural_arsize(master_idx))

    async def master_write(self, master_idx: int, address: int, data: int,
                           txn_id: int = None) -> None:
        """Single-beat write from master[master_idx]. `data` is master-width.

        `txn_id` sets AWID. Give each master a DISJOINT id range and the
        returned BID identifies which master a response belongs to, which is
        the only way to tell a correctly routed response from one that merely
        arrived somewhere. APB has no id and ignores it.
        """
        if master_idx in self.master_apb:
            await self.master_apb[master_idx].write(address, data)
            return
        wr = self.master_wr[master_idx]
        kwargs = {'size': self._natural_arsize(master_idx)}
        if txn_id is not None:
            kwargs['id'] = txn_id
        result = await wr.single_write(address, data, **kwargs)
        # single_write does NOT raise on an error response -- it reports it
        # in the returned dict -- so a SLVERR/DECERR write used to pass
        # straight through this helper unnoticed. Raise, the way single_read
        # does, so a caller that expects the write to land finds out.
        if isinstance(result, dict) and not result.get('success', True):
            raise RuntimeError(f"AXI write error at 0x{address:08x}: {result.get('error', result)}")
