"""
Stream Characterization Harness Testbench

Drives the stream_char_harness module through its UART interface using
the CocoTBFramework UARTMaster and UARTMonitor BFMs.  All host-visible
operations (register access, descriptor loading, CRC readback, trace dump)
are exercised through the same UART command protocol the real FPGA uses.

For simulation speed, UART_BAUD is overridden to ~12.5 MHz
(CLKS_PER_BIT=8) so each byte takes ~80 ns instead of ~87 us.

Architecture:
    UARTMaster  --> i_uart_rx  --> uart_axil_bridge
    UARTMonitor <-- o_uart_tx  <-- uart_axil_bridge
    (inside the harness: AXIL decode -> CSR / desc_ram / STREAM / debug_sram)

Author: RTL Design Sherpa
Created: 2026-04-10
"""

import os
import sys
import cocotb
from cocotb.triggers import RisingEdge, Timer

from TBClasses.shared.utilities import get_repo_root
from TBClasses.shared.tbbase import TBBase

repo_root = get_repo_root()
sys.path.insert(0, repo_root)
from CocoTBFramework.components.uart import UARTMaster, UARTMonitor

# Add host/ to path for descriptor_builder
sys.path.insert(0, os.path.join(
    repo_root, 'projects', 'NexysA7', 'stream_characterization', 'host'))
from descriptor_builder import DescriptorBuilder, CharConfig


# =========================================================================
# Memory map constants (must match stream_char_harness parameters)
# =========================================================================
STREAM_APB_BASE    = 0x0000_0000
HARNESS_CSR_BASE   = 0x0001_0000
DESC_RAM_BASE      = 0x0002_0000
STREAM_ERR_BASE    = 0x0003_0000
DEBUG_SRAM_BASE    = 0x0004_0000

# Harness CSR offsets
CSR_CTRL           = HARNESS_CSR_BASE + 0x00
CSR_STATUS         = HARNESS_CSR_BASE + 0x04
CSR_DBG_WR_PTR    = HARNESS_CSR_BASE + 0x08
CSR_DBG_OVERFLOW   = HARNESS_CSR_BASE + 0x0C
CSR_CRC_RD_EXPECTED = HARNESS_CSR_BASE + 0x10
CSR_CRC_WR_EXPECTED = HARNESS_CSR_BASE + 0x14
CSR_CRC_WR_COMPUTED = HARNESS_CSR_BASE + 0x18
CSR_CRC_MATCH      = HARNESS_CSR_BASE + 0x1C
CSR_SCRATCH        = HARNESS_CSR_BASE + 0x20
CSR_BUILD_ID       = HARNESS_CSR_BASE + 0x24

EXPECTED_BUILD_ID  = 0x5354_5243  # "STRC"

# STREAM APB registers — addresses from projects/components/stream/rtl/stream_regmap.py
# (generated by PeakRDL, routed via cmdrsp_router)
APB_GLOBAL_CTRL         = STREAM_APB_BASE + 0x100
APB_GLOBAL_STATUS       = STREAM_APB_BASE + 0x104
APB_CHANNEL_ENABLE      = STREAM_APB_BASE + 0x120
APB_CHANNEL_RESET       = STREAM_APB_BASE + 0x124
APB_SCHED_TIMEOUT_CYC   = STREAM_APB_BASE + 0x200
APB_SCHED_CONFIG        = STREAM_APB_BASE + 0x204
APB_DESCENG_CONFIG      = STREAM_APB_BASE + 0x220
APB_DESCENG_ADDR0_BASE  = STREAM_APB_BASE + 0x224
APB_DESCENG_ADDR0_LIMIT = STREAM_APB_BASE + 0x228
APB_DESCENG_ADDR1_BASE  = STREAM_APB_BASE + 0x22C
APB_DESCENG_ADDR1_LIMIT = STREAM_APB_BASE + 0x230
APB_AXI_XFER_CONFIG     = STREAM_APB_BASE + 0x2A0
APB_CH_KICK_BASE        = STREAM_APB_BASE + 0x000  # kick-off via apbtodescr
APB_CH_KICK_STRIDE      = 0x08                     # 8 bytes per ch (LOW + HIGH)


class StreamCharTB(TBBase):
    """
    Testbench for stream_char_harness.

    Drives the full characterization harness through UART. Uses fast baud
    rate for simulation (CLKS_PER_BIT from RTL parameter, typically 8 for sim).
    """

    def __init__(self, dut):
        super().__init__(dut)

        self.clk = dut.aclk
        self.clk_name = 'aclk'
        self.rst_n = dut.aresetn

        self.TEST_LEVEL = os.environ.get('TEST_LEVEL', 'gate').lower()
        self.SEED = self.convert_to_int(os.environ.get('SEED', '12345'))

        # CLKS_PER_BIT must match the RTL parameterisation
        fpga_clk_hz = self.convert_to_int(os.environ.get('FPGA_CLK_HZ', '100000000'))
        uart_baud = self.convert_to_int(os.environ.get('UART_BAUD', '12500000'))
        self.clks_per_bit = fpga_clk_hz // uart_baud

        # UART BFMs
        self.uart_master = UARTMaster(
            entity=dut,
            title="HOST_TX",
            signal_name="i_uart_rx",
            clock=self.clk,
            clks_per_bit=self.clks_per_bit,
            log=self.log,
        )
        self.uart_monitor = UARTMonitor(
            entity=dut,
            title="HOST_RX",
            signal_name="o_uart_tx",
            clock=self.clk,
            clks_per_bit=self.clks_per_bit,
            direction='RX',
            log=self.log,
        )

        # Statistics
        self.writes_ok = 0
        self.reads_ok = 0
        self.errors = 0

        self.log.info(
            f"StreamCharTB: TEST_LEVEL={self.TEST_LEVEL} "
            f"CLKS_PER_BIT={self.clks_per_bit}")

    # =====================================================================
    # Mandatory methods
    # =====================================================================

    async def setup_clocks_and_reset(self):
        await self.start_clock(self.clk_name, freq=10, units='ns')
        # Drive UART idle (high) before reset
        self.dut.i_uart_rx.value = 1
        await self.assert_reset()
        await self.wait_clocks(self.clk_name, 20)
        await self.deassert_reset()
        await self.wait_clocks(self.clk_name, 20)

    async def assert_reset(self):
        self.rst_n.value = 0

    async def deassert_reset(self):
        self.rst_n.value = 1

    # =====================================================================
    # Low-level UART command helpers
    # =====================================================================

    def _uart_byte_clocks(self, num_bytes: int) -> int:
        """Clock cycles for num_bytes over UART (10 bits/byte)."""
        return num_bytes * 10 * self.clks_per_bit

    async def uart_write(self, addr: int, data: int) -> bool:
        """Send 'W addr data\\n', wait for 'OK\\n'. Return True on success."""
        cmd = f"W {addr:08X} {data:08X}\n"
        self.uart_monitor._recvQ.clear()
        await self.uart_master.send_string(cmd)

        # Wait for command TX + bridge latency + response TX
        wait = self._uart_byte_clocks(len(cmd) + 4) + 500
        await self.wait_clocks(self.clk_name, wait)

        resp = self._drain_response()
        if resp == "OK\n":
            self.writes_ok += 1
            return True
        self.log.error(f"uart_write(0x{addr:08X}, 0x{data:08X}): "
                       f"expected 'OK\\n', got {resp!r}")
        self.errors += 1
        return False

    async def uart_read(self, addr: int) -> int | None:
        """Send 'R addr\\n', return 32-bit value or None."""
        cmd = f"R {addr:08X}\n"
        self.uart_monitor._recvQ.clear()
        await self.uart_master.send_string(cmd)

        # Response is "0xHHHHHHHH\n" = 11 chars
        wait = self._uart_byte_clocks(len(cmd) + 12) + 500
        await self.wait_clocks(self.clk_name, wait)

        resp = self._drain_response()
        if resp and resp.startswith("0x") and resp.endswith("\n"):
            try:
                val = int(resp[2:].strip(), 16)
                self.reads_ok += 1
                return val
            except ValueError:
                pass
        self.log.error(f"uart_read(0x{addr:08X}): bad response {resp!r}")
        self.errors += 1
        return None

    def _drain_response(self) -> str:
        """Collect all bytes currently in the UART monitor queue."""
        chars = []
        while self.uart_monitor._recvQ:
            pkt = self.uart_monitor._recvQ.popleft()
            chars.append(chr(pkt.data))
        return ''.join(chars)

    # =====================================================================
    # High-level harness operations
    # =====================================================================

    async def ping_scratch(self, value: int = 0xDEAD_BEEF) -> bool:
        """Write scratch register and read it back."""
        ok = await self.uart_write(CSR_SCRATCH, value)
        if not ok:
            return False
        rb = await self.uart_read(CSR_SCRATCH)
        if rb != value:
            self.log.error(
                f"Scratch mismatch: wrote 0x{value:08X}, read 0x{rb:08X}"
                if rb is not None else "Scratch read failed")
            return False
        self.log.info(f"Scratch ping OK: 0x{value:08X}")
        return True

    async def check_build_id(self) -> bool:
        """Read BUILD_ID and verify."""
        val = await self.uart_read(CSR_BUILD_ID)
        ok = val == EXPECTED_BUILD_ID
        if ok:
            self.log.info(f"Build ID OK: 0x{val:08X}")
        else:
            self.log.error(
                f"Build ID mismatch: expected 0x{EXPECTED_BUILD_ID:08X}, "
                f"got 0x{val:08X}" if val is not None else "read failed")
        return ok

    async def load_descriptor(self, desc_index: int,
                              src_addr: int, dst_addr: int,
                              length: int, next_ptr: int = 0,
                              control: int = 0x01) -> bool:
        """
        Write one 256-bit STREAM descriptor to desc_ram.

        Descriptor layout (256 bits = 8 x 32-bit words):
          Word 0: src_addr[31:0]
          Word 1: src_addr[63:32]
          Word 2: dst_addr[31:0]
          Word 3: dst_addr[63:32]
          Word 4: length[31:0]
          Word 5: next_descriptor_ptr[31:0]
          Word 6: control (valid, last, interrupt, priority, channel_id)
          Word 7: reserved
        """
        base = DESC_RAM_BASE + desc_index * 32  # 32 bytes per descriptor
        words = [
            src_addr & 0xFFFF_FFFF,
            (src_addr >> 32) & 0xFFFF_FFFF,
            dst_addr & 0xFFFF_FFFF,
            (dst_addr >> 32) & 0xFFFF_FFFF,
            length & 0xFFFF_FFFF,
            next_ptr & 0xFFFF_FFFF,
            control & 0xFFFF_FFFF,
            0x0000_0000,  # reserved
        ]
        all_ok = True
        for i, w in enumerate(words):
            ok = await self.uart_write(base + i * 4, w)
            if not ok:
                all_ok = False
        self.log.info(
            f"Descriptor[{desc_index}]: src=0x{src_addr:08X} dst=0x{dst_addr:08X} "
            f"len={length} next=0x{next_ptr:08X} ctrl=0x{control:02X} "
            f"{'OK' if all_ok else 'FAILED'}")
        return all_ok

    async def read_crc_status(self) -> dict:
        """Read CRC registers and return a status dict."""
        rd_exp = await self.uart_read(CSR_CRC_RD_EXPECTED)
        wr_exp = await self.uart_read(CSR_CRC_WR_EXPECTED)
        wr_got = await self.uart_read(CSR_CRC_WR_COMPUTED)
        match  = await self.uart_read(CSR_CRC_MATCH)
        return {
            'rd_expected': rd_exp,
            'wr_expected': wr_exp,
            'wr_computed': wr_got,
            'match_reg':   match,
            'match':       (match is not None) and (match & 0x1 == 1),
            'valid':       (match is not None) and (match & 0x2 == 2),
        }

    async def read_status(self) -> dict:
        """Read harness status register."""
        val = await self.uart_read(CSR_STATUS)
        if val is None:
            return {}
        return {
            'stream_irq':     bool(val & 0x01),
            'any_error':      bool(val & 0x02),
            'trace_overflow': bool(val & 0x04),
            'raw': val,
        }

    async def clear_stats(self):
        """Pulse clear_stats bit in CTRL."""
        await self.uart_write(CSR_CTRL, 0x02)

    # =====================================================================
    # Test scenarios
    # =====================================================================

    async def run_ping_test(self) -> bool:
        """Gate-level: verify UART → decode → CSR round-trip."""
        self.log.info("=== Ping test ===")
        ok = True
        ok &= await self.ping_scratch(0xDEAD_BEEF)
        ok &= await self.ping_scratch(0x1234_5678)
        ok &= await self.ping_scratch(0x0000_0000)
        ok &= await self.ping_scratch(0xFFFF_FFFF)
        ok &= await self.check_build_id()
        self.log.info(f"Ping test: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_descriptor_load_test(self) -> bool:
        """Func-level: load descriptors into desc_ram via UART."""
        self.log.info("=== Descriptor load test ===")
        ok = True
        ok &= await self.load_descriptor(
            desc_index=0,
            src_addr=0x8000_0000,
            dst_addr=0x9000_0000,
            length=64,
            next_ptr=0,
            control=0x07,  # valid + last + interrupt
        )
        if self.TEST_LEVEL != 'gate':
            ok &= await self.load_descriptor(
                desc_index=1,
                src_addr=0x8000_1000,
                dst_addr=0x9000_1000,
                length=128,
                next_ptr=0,
                control=0x07,
            )
        self.log.info(f"Descriptor load: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_csr_readback_test(self) -> bool:
        """Func-level: read status and CRC registers."""
        self.log.info("=== CSR readback test ===")
        ok = True

        status = await self.read_status()
        if not status:
            self.log.error("Failed to read status register")
            ok = False
        else:
            self.log.info(f"Status: {status}")

        wr_ptr = await self.uart_read(CSR_DBG_WR_PTR)
        if wr_ptr is None:
            ok = False
        else:
            self.log.info(f"Debug wr_ptr: {wr_ptr}")

        crc = await self.read_crc_status()
        self.log.info(f"CRC status: {crc}")

        self.log.info(f"CSR readback: {'PASS' if ok else 'FAIL'}")
        return ok

    async def run_apb_config_test(self) -> bool:
        """Func-level: read STREAM APB register space (verify axil2apb path)."""
        self.log.info("=== APB config path test ===")
        # Read STREAM's GLOBAL_CTRL register (offset 0x100 in APB space)
        # After reset, GLOBAL_EN should be 0
        val = await self.uart_read(STREAM_APB_BASE + 0x100)
        if val is None:
            self.log.error("Failed to read STREAM APB GLOBAL_CTRL")
            return False
        self.log.info(f"STREAM GLOBAL_CTRL = 0x{val:08X}")
        # Write and readback
        ok = await self.uart_write(STREAM_APB_BASE + 0x100, 0x01)  # GLOBAL_EN=1
        if not ok:
            return False
        rb = await self.uart_read(STREAM_APB_BASE + 0x100)
        if rb is None:
            return False
        wrote_ok = (rb & 0x01) == 0x01
        self.log.info(
            f"APB write/readback: wrote 0x01, read 0x{rb:08X} "
            f"{'PASS' if wrote_ok else 'FAIL'}")
        return wrote_ok

    # =====================================================================
    # DMA test using descriptor_builder
    # =====================================================================

    async def run_dma_test(self, num_channels: int,
                           descriptors_per_channel: int,
                           transfer_bytes: int,
                           timeout_clocks: int = 500_000) -> bool:
        """
        Full DMA test: load descriptors, configure STREAM, kick channels,
        poll completion, verify CRC.

        Uses the same DescriptorBuilder that the FPGA host script uses,
        so descriptor layout is identical between sim and hardware.
        """
        self.log.info(
            f"=== DMA test: {num_channels}ch x {descriptors_per_channel}desc "
            f"x {transfer_bytes}B ===")

        builder = DescriptorBuilder(data_width=128)
        config = CharConfig(
            name=f"sim_{descriptors_per_channel}desc_{num_channels}ch",
            num_channels=num_channels,
            descriptors_per_channel=descriptors_per_channel,
            transfer_bytes=transfer_bytes,
        )
        test_data = builder.build_test(config)

        # 1. Reset STREAM and clear CRC/stats
        await self.uart_write(APB_GLOBAL_CTRL, 0x02)   # GLOBAL_RST
        await self.wait_clocks(self.clk_name, 100)
        await self.uart_write(APB_GLOBAL_CTRL, 0x00)   # clear reset
        await self.wait_clocks(self.clk_name, 100)
        await self.clear_stats()
        await self.wait_clocks(self.clk_name, 50)

        # 2. Load all descriptors via UART
        self.log.info(
            f"  Loading {test_data['total_descriptors']} descriptors "
            f"({len(test_data['descriptor_writes'])} UART writes)...")
        for addr, data in test_data['descriptor_writes']:
            ok = await self.uart_write(addr, data)
            if not ok:
                self.log.error(f"  Descriptor write failed at 0x{addr:08X}")
                return False

        # 3. Full STREAM configuration — matches stream_top_tb._configure_stream_top()
        # and StreamHelper sequence. All register addresses from stream_regmap.py.

        # 3a. Scheduler config: enable + timeout + error/completion reporting
        sched_cfg = 0x0F  # [0]=SCHED_EN, [1]=TIMEOUT_EN, [2]=ERR_EN, [3]=COMPL_EN
        await self.uart_write(APB_SCHED_CONFIG, sched_cfg)
        await self.uart_write(APB_SCHED_TIMEOUT_CYC, 0xFFFF)  # max timeout

        # 3b. Descriptor engine config: enable (no prefetch for now)
        desceng_cfg = 0x01  # [0]=DESCENG_EN
        await self.uart_write(APB_DESCENG_CONFIG, desceng_cfg)

        # 3c. Descriptor address ranges (for chaining validation)
        await self.uart_write(APB_DESCENG_ADDR0_BASE,  0x0000_0000)
        await self.uart_write(APB_DESCENG_ADDR0_LIMIT, 0xFFFF_FFFF)
        await self.uart_write(APB_DESCENG_ADDR1_BASE,  0x0000_0000)
        await self.uart_write(APB_DESCENG_ADDR1_LIMIT, 0xFFFF_FFFF)

        # 3d. AXI transfer config: burst sizes (ARLEN/AWLEN)
        axi_cfg = (15 & 0xFF) | ((15 & 0xFF) << 8)  # rd=16 beats, wr=16 beats
        await self.uart_write(APB_AXI_XFER_CONFIG, axi_cfg)

        # 4. Enable STREAM global + channels
        ch_mask = (1 << num_channels) - 1
        await self.uart_write(APB_GLOBAL_CTRL, 0x01)       # GLOBAL_EN
        await self.uart_write(APB_CHANNEL_ENABLE, ch_mask)  # channel mask
        self.log.info(f"  STREAM configured and enabled: ch_mask=0x{ch_mask:02X}")

        # 4a. Debug: read back key registers to confirm config took effect
        for name, addr in [
            ("GLOBAL_CTRL",       APB_GLOBAL_CTRL),
            ("GLOBAL_STATUS",     APB_GLOBAL_STATUS),
            ("CHANNEL_ENABLE",    APB_CHANNEL_ENABLE),
            ("SCHED_CONFIG",      APB_SCHED_CONFIG),
            ("DESCENG_CONFIG",    APB_DESCENG_CONFIG),
            ("ADDR0_BASE",        APB_DESCENG_ADDR0_BASE),
            ("ADDR0_LIMIT",       APB_DESCENG_ADDR0_LIMIT),
            ("AXI_XFER_CONFIG",   APB_AXI_XFER_CONFIG),
            ("CHANNEL_IDLE",      STREAM_APB_BASE + 0x140),
            ("DESC_ENGINE_IDLE",  STREAM_APB_BASE + 0x144),
            ("SCHEDULER_IDLE",    STREAM_APB_BASE + 0x148),
            ("SCHED_ERROR",       STREAM_APB_BASE + 0x170),
        ]:
            val = await self.uart_read(addr)
            self.log.info(f"  [DEBUG] {name:20s} @ 0x{addr:03X} = 0x{val:08X}" if val is not None
                          else f"  [DEBUG] {name:20s} @ 0x{addr:03X} = READ FAILED")

        # 5. Kick all channels (two APB writes per channel: LOW + HIGH 32-bit)
        # apbtodescr expects LOW write first (bits [31:0]), then HIGH (bits [63:32])
        for ch, kick_addr in sorted(test_data['kick_addresses'].items()):
            kick_reg = APB_CH_KICK_BASE + ch * APB_CH_KICK_STRIDE
            low  = kick_addr & 0xFFFF_FFFF
            high = (kick_addr >> 32) & 0xFFFF_FFFF
            await self.uart_write(kick_reg + 0, low)    # LOW word
            await self.uart_write(kick_reg + 4, high)   # HIGH word
            self.log.info(f"  Kicked ch{ch} → desc@0x{kick_addr:08X}")

        # 5a. Debug: read status immediately after kick
        await self.wait_clocks(self.clk_name, 1000)
        for name, addr in [
            ("GLOBAL_STATUS",     APB_GLOBAL_STATUS),
            ("CHANNEL_IDLE",      STREAM_APB_BASE + 0x140),
            ("DESC_ENGINE_IDLE",  STREAM_APB_BASE + 0x144),
            ("SCHEDULER_IDLE",    STREAM_APB_BASE + 0x148),
            ("SCHED_ERROR",       STREAM_APB_BASE + 0x170),
            ("AXI_RD_COMPLETE",   STREAM_APB_BASE + 0x174),
            ("AXI_WR_COMPLETE",   STREAM_APB_BASE + 0x178),
        ]:
            val = await self.uart_read(addr)
            self.log.info(f"  [POST-KICK] {name:20s} @ 0x{addr:03X} = 0x{val:08X}" if val is not None
                          else f"  [POST-KICK] {name:20s} @ 0x{addr:03X} = READ FAILED")

        # 6. Poll for completion (stream_irq or error in status register)
        self.log.info(f"  Waiting for completion (up to {timeout_clocks} clocks)...")
        completed = False
        for _ in range(timeout_clocks // 100):
            await self.wait_clocks(self.clk_name, 100)
            status = await self.read_status()
            if status.get('stream_irq') or status.get('any_error'):
                completed = True
                break

        if not completed:
            self.log.error("  DMA timeout — no IRQ or error detected")
            status = await self.read_status()
            self.log.error(f"  Final status: {status}")
            return False

        if status.get('any_error'):
            self.log.error(f"  DMA error flagged: {status}")
            return False

        self.log.info("  DMA completed (IRQ received)")

        # 6. CRC verification
        crc = await self.read_crc_status()
        self.log.info(
            f"  CRC: rd_exp=0x{crc.get('rd_expected', 0):08X} "
            f"wr_comp=0x{crc.get('wr_computed', 0):08X} "
            f"match={crc.get('match')} valid={crc.get('valid')}")

        if crc.get('match') and crc.get('valid'):
            self.log.info(f"  DMA test PASSED")
            return True
        else:
            self.log.error(f"  CRC mismatch — DMA test FAILED")
            return False

    def get_report(self) -> dict:
        return {
            'writes_ok': self.writes_ok,
            'reads_ok': self.reads_ok,
            'errors': self.errors,
            'test_level': self.TEST_LEVEL,
        }
