// Slave Adapter: axil_periph_adapter
// Generated by: SlaveAdapterGenerator
//
// Provides timing isolation and protocol conversion for slave: axil_periph
// Protocol: AXIL

`timescale 1ns / 1ps

import bridge_1x5_rd_pkg::*;

module axil_periph_adapter (
    input  logic aclk,
    input  logic aresetn,

    // Crossbar interface (AXI4 from crossbar)
    input  logic [3:0]  xbar_axil_periph_axi_arid,
    input  logic [31:0]  xbar_axil_periph_axi_araddr,
    input  logic [7:0]  xbar_axil_periph_axi_arlen,
    input  logic [2:0]  xbar_axil_periph_axi_arsize,
    input  logic [1:0]  xbar_axil_periph_axi_arburst,
    input  logic         xbar_axil_periph_axi_arlock,
    input  logic [3:0]  xbar_axil_periph_axi_arcache,
    input  logic [2:0]  xbar_axil_periph_axi_arprot,
    input  logic [3:0]  xbar_axil_periph_axi_arqos,
    input  logic [3:0]  xbar_axil_periph_axi_arregion,
    input  logic         xbar_axil_periph_axi_aruser,
    input  logic         xbar_axil_periph_axi_arvalid,
    output  logic         xbar_axil_periph_axi_arready,
    output  logic [3:0]  xbar_axil_periph_axi_rid,
    output  logic [31:0]  xbar_axil_periph_axi_rdata,
    output  logic [1:0]  xbar_axil_periph_axi_rresp,
    output  logic         xbar_axil_periph_axi_rlast,
    output  logic         xbar_axil_periph_axi_ruser,
    output  logic         xbar_axil_periph_axi_rvalid,
    input  logic         xbar_axil_periph_axi_rready,

    // External slave interface (AXIL)
    output logic [31:0] axil_periph_axi_araddr,
    output logic [2:0]            axil_periph_axi_arprot,
    output logic                  axil_periph_axi_arvalid,
    input  logic                  axil_periph_axi_arready,
    // Read Data Channel
    input  logic [31:0] axil_periph_axi_rdata,
    input  logic [1:0]            axil_periph_axi_rresp,
    input  logic                  axil_periph_axi_rvalid,
    output logic                  axil_periph_axi_rready
);

    // Internal signals (if needed for protocol conversion)

    // AXI4-to-AXI4-Lite converter
    axi4_to_axil4_rd #(
        .AXI_ID_WIDTH     (4),
        .AXI_ADDR_WIDTH   (32),
        .AXI_DATA_WIDTH   (64),
        .AXI_USER_WIDTH   (1),
        .SKID_DEPTH_AR    (2),
        .SKID_DEPTH_R     (4)
    ) u_axil_periph_axil_converter (
        .aclk             (aclk),
        .aresetn          (aresetn),

        // AXI4 read address channel (from crossbar)
        .s_axi_arid       (xbar_axil_periph_axi_arid),
        .s_axi_araddr     (xbar_axil_periph_axi_araddr),
        .s_axi_arlen      (xbar_axil_periph_axi_arlen),
        .s_axi_arsize     (xbar_axil_periph_axi_arsize),
        .s_axi_arburst    (xbar_axil_periph_axi_arburst),
        .s_axi_arlock     (xbar_axil_periph_axi_arlock),
        .s_axi_arcache    (xbar_axil_periph_axi_arcache),
        .s_axi_arprot     (xbar_axil_periph_axi_arprot),
        .s_axi_arqos      (xbar_axil_periph_axi_arqos),
        .s_axi_arregion   (xbar_axil_periph_axi_arregion),
        .s_axi_aruser     (xbar_axil_periph_axi_aruser),
        .s_axi_arvalid    (xbar_axil_periph_axi_arvalid),
        .s_axi_arready    (xbar_axil_periph_axi_arready),

        // AXI4 read data channel
        .s_axi_rid        (xbar_axil_periph_axi_rid),
        .s_axi_rdata      (xbar_axil_periph_axi_rdata),
        .s_axi_rresp      (xbar_axil_periph_axi_rresp),
        .s_axi_rlast      (xbar_axil_periph_axi_rlast),
        .s_axi_ruser      (xbar_axil_periph_axi_ruser),
        .s_axi_rvalid     (xbar_axil_periph_axi_rvalid),
        .s_axi_rready     (xbar_axil_periph_axi_rready),

        // AXI4-Lite read address channel (to external slave)
        .m_axil_araddr    (axil_periph_axi_araddr),
        .m_axil_arprot    (axil_periph_axi_arprot),
        .m_axil_arvalid   (axil_periph_axi_arvalid),
        .m_axil_arready   (axil_periph_axi_arready),

        // AXI4-Lite read data channel
        .m_axil_rdata     (axil_periph_axi_rdata),
        .m_axil_rresp     (axil_periph_axi_rresp),
        .m_axil_rvalid    (axil_periph_axi_rvalid),
        .m_axil_rready    (axil_periph_axi_rready)
    );

endmodule : axil_periph_adapter
