// Bridge Package: bridge_1x5_rd
// Generated by: PackageGenerator
// Defines AXI channel structs for all data widths used in this bridge

`timescale 1ns / 1ps

package bridge_1x5_rd_pkg;

    // AXI4 Write Address Channel (width-independent)
    // Note: ID width is 4-bit for this bridge
    typedef struct packed {
        logic [3:0]   id;      // Transaction ID
        logic [31:0]  addr;    // Address
        logic [7:0]   len;     // Burst length
        logic [2:0]   size;    // Burst size
        logic [1:0]   burst;   // Burst type
        logic         lock;    // Lock type
        logic [3:0]   cache;   // Cache type
        logic [2:0]   prot;    // Protection type
        logic [3:0]   qos;     // Quality of Service
        logic [3:0]   region;  // Region identifier
        logic         user;    // User signal
    } axi4_aw_t;

    // AXI4 Read Address Channel (width-independent)
    typedef struct packed {
        logic [3:0]   id;      // Transaction ID
        logic [31:0]  addr;    // Address
        logic [7:0]   len;     // Burst length
        logic [2:0]   size;    // Burst size
        logic [1:0]   burst;   // Burst type
        logic         lock;    // Lock type
        logic [3:0]   cache;   // Cache type
        logic [2:0]   prot;    // Protection type
        logic [3:0]   qos;     // Quality of Service
        logic [3:0]   region;  // Region identifier
        logic         user;    // User signal
    } axi4_ar_t;

    // AXI4 Write Data Channel - 32-bit data width
    typedef struct packed {
        logic [31:0]  data;    // Write data
        logic [3:0]   strb;    // Write strobes
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_w_32b_t;

    // AXI4 Write Data Channel - 64-bit data width
    typedef struct packed {
        logic [63:0]  data;    // Write data
        logic [7:0]   strb;    // Write strobes
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_w_64b_t;

    // AXI4 Write Data Channel - 128-bit data width
    typedef struct packed {
        logic [127:0]  data;    // Write data
        logic [15:0]   strb;    // Write strobes
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_w_128b_t;

    // AXI4 Write Response Channel (width-independent)
    typedef struct packed {
        logic [3:0]   id;      // Response ID
        logic [1:0]   resp;    // Write response
        logic         user;    // User signal
    } axi4_b_t;

    // AXI4 Read Data Channel - 32-bit data width
    typedef struct packed {
        logic [3:0]   id;      // Response ID
        logic [31:0]  data;    // Read data
        logic [1:0]   resp;    // Read response
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_r_32b_t;

    // AXI4 Read Data Channel - 64-bit data width
    typedef struct packed {
        logic [3:0]   id;      // Response ID
        logic [63:0]  data;    // Read data
        logic [1:0]   resp;    // Read response
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_r_64b_t;

    // AXI4 Read Data Channel - 128-bit data width
    typedef struct packed {
        logic [3:0]   id;      // Response ID
        logic [127:0]  data;    // Read data
        logic [1:0]   resp;    // Read response
        logic         last;    // Last transfer in burst
        logic         user;    // User signal
    } axi4_r_128b_t;

endpackage : bridge_1x5_rd_pkg
