// Slave Adapter: periph_rd_adapter
// Generated by: SlaveAdapterGenerator
//
// Provides timing isolation and protocol conversion for slave: periph_rd
// Protocol: AXI4

`timescale 1ns / 1ps

import bridge_1x5_rd_pkg::*;

module periph_rd_adapter (
    input  logic aclk,
    input  logic aresetn,

    // Crossbar interface (AXI4 from crossbar)
    input  logic [3:0]  xbar_periph_rd_axi_arid,
    input  logic [31:0]  xbar_periph_rd_axi_araddr,
    input  logic [7:0]  xbar_periph_rd_axi_arlen,
    input  logic [2:0]  xbar_periph_rd_axi_arsize,
    input  logic [1:0]  xbar_periph_rd_axi_arburst,
    input  logic         xbar_periph_rd_axi_arlock,
    input  logic [3:0]  xbar_periph_rd_axi_arcache,
    input  logic [2:0]  xbar_periph_rd_axi_arprot,
    input  logic [3:0]  xbar_periph_rd_axi_arqos,
    input  logic [3:0]  xbar_periph_rd_axi_arregion,
    input  logic         xbar_periph_rd_axi_aruser,
    input  logic         xbar_periph_rd_axi_arvalid,
    output  logic         xbar_periph_rd_axi_arready,
    output  logic [3:0]  xbar_periph_rd_axi_rid,
    output  logic [31:0]  xbar_periph_rd_axi_rdata,
    output  logic [1:0]  xbar_periph_rd_axi_rresp,
    output  logic         xbar_periph_rd_axi_rlast,
    output  logic         xbar_periph_rd_axi_ruser,
    output  logic         xbar_periph_rd_axi_rvalid,
    input  logic         xbar_periph_rd_axi_rready,

    // External slave interface (AXI4)
    output  logic [3:0]  periph_rd_axi_arid,
    output  logic [31:0]  periph_rd_axi_araddr,
    output  logic [7:0]  periph_rd_axi_arlen,
    output  logic [2:0]  periph_rd_axi_arsize,
    output  logic [1:0]  periph_rd_axi_arburst,
    output  logic         periph_rd_axi_arlock,
    output  logic [3:0]  periph_rd_axi_arcache,
    output  logic [2:0]  periph_rd_axi_arprot,
    output  logic [3:0]  periph_rd_axi_arqos,
    output  logic [3:0]  periph_rd_axi_arregion,
    output  logic         periph_rd_axi_aruser,
    output  logic         periph_rd_axi_arvalid,
    input  logic         periph_rd_axi_arready,
    input  logic [3:0]  periph_rd_axi_rid,
    input  logic [31:0]  periph_rd_axi_rdata,
    input  logic [1:0]  periph_rd_axi_rresp,
    input  logic         periph_rd_axi_rlast,
    input  logic         periph_rd_axi_ruser,
    input  logic         periph_rd_axi_rvalid,
    output  logic         periph_rd_axi_rready
);

    // Internal signals (if needed for protocol conversion)

    // AXI4 Master Read Timing Wrapper
    axi4_master_rd #(
        .SKID_DEPTH_AR(2),
        .SKID_DEPTH_R(2),
        .AXI_ID_WIDTH(4),
        .AXI_ADDR_WIDTH(32),
        .AXI_DATA_WIDTH(32),
        .AXI_USER_WIDTH(1)
    ) u_master_rd (
        .aclk(aclk),
        .aresetn(aresetn),

        // Slave interface (from crossbar)
        .fub_axi_arid(xbar_periph_rd_axi_arid),
        .fub_axi_araddr(xbar_periph_rd_axi_araddr),
        .fub_axi_arlen(xbar_periph_rd_axi_arlen),
        .fub_axi_arsize(xbar_periph_rd_axi_arsize),
        .fub_axi_arburst(xbar_periph_rd_axi_arburst),
        .fub_axi_arlock(xbar_periph_rd_axi_arlock),
        .fub_axi_arcache(xbar_periph_rd_axi_arcache),
        .fub_axi_arprot(xbar_periph_rd_axi_arprot),
        .fub_axi_arqos(xbar_periph_rd_axi_arqos),
        .fub_axi_arregion(xbar_periph_rd_axi_arregion),
        .fub_axi_aruser(xbar_periph_rd_axi_aruser),
        .fub_axi_arvalid(xbar_periph_rd_axi_arvalid),
        .fub_axi_arready(xbar_periph_rd_axi_arready),

        .fub_axi_rid(xbar_periph_rd_axi_rid),
        .fub_axi_rdata(xbar_periph_rd_axi_rdata),
        .fub_axi_rresp(xbar_periph_rd_axi_rresp),
        .fub_axi_rlast(xbar_periph_rd_axi_rlast),
        .fub_axi_ruser(xbar_periph_rd_axi_ruser),
        .fub_axi_rvalid(xbar_periph_rd_axi_rvalid),
        .fub_axi_rready(xbar_periph_rd_axi_rready),

        // Master interface (to external slave)
        .m_axi_arid(periph_rd_axi_arid),
        .m_axi_araddr(periph_rd_axi_araddr),
        .m_axi_arlen(periph_rd_axi_arlen),
        .m_axi_arsize(periph_rd_axi_arsize),
        .m_axi_arburst(periph_rd_axi_arburst),
        .m_axi_arlock(periph_rd_axi_arlock),
        .m_axi_arcache(periph_rd_axi_arcache),
        .m_axi_arprot(periph_rd_axi_arprot),
        .m_axi_arqos(periph_rd_axi_arqos),
        .m_axi_arregion(periph_rd_axi_arregion),
        .m_axi_aruser(periph_rd_axi_aruser),
        .m_axi_arvalid(periph_rd_axi_arvalid),
        .m_axi_arready(periph_rd_axi_arready),

        .m_axi_rid(periph_rd_axi_rid),
        .m_axi_rdata(periph_rd_axi_rdata),
        .m_axi_rresp(periph_rd_axi_rresp),
        .m_axi_rlast(periph_rd_axi_rlast),
        .m_axi_ruser(periph_rd_axi_ruser),
        .m_axi_rvalid(periph_rd_axi_rvalid),
        .m_axi_rready(periph_rd_axi_rready),

        // Status output (unconnected - for clock gating)
        .busy()
    );

endmodule : periph_rd_adapter
