// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module gpio_regs (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [5:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input gpio_regs_pkg::gpio_regs__in_t hwif_in,
        output gpio_regs_pkg::gpio_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic GPIO_CONTROL;
        logic GPIO_DIRECTION;
        logic GPIO_OUTPUT;
        logic GPIO_INPUT;
        logic GPIO_INT_ENABLE;
        logic GPIO_INT_TYPE;
        logic GPIO_INT_POLARITY;
        logic GPIO_INT_BOTH;
        logic GPIO_INT_STATUS;
        logic GPIO_RAW_INT;
        logic GPIO_OUTPUT_SET;
        logic GPIO_OUTPUT_CLR;
        logic GPIO_OUTPUT_TGL;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.GPIO_CONTROL = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.GPIO_DIRECTION = cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.GPIO_OUTPUT = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.GPIO_INPUT = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.GPIO_INT_ENABLE = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.GPIO_INT_TYPE = cpuif_req_masked & (cpuif_addr == 6'h14);
        decoded_reg_strb.GPIO_INT_POLARITY = cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.GPIO_INT_BOTH = cpuif_req_masked & (cpuif_addr == 6'h1c);
        decoded_reg_strb.GPIO_INT_STATUS = cpuif_req_masked & (cpuif_addr == 6'h20);
        decoded_reg_strb.GPIO_RAW_INT = cpuif_req_masked & (cpuif_addr == 6'h24);
        decoded_reg_strb.GPIO_OUTPUT_SET = cpuif_req_masked & (cpuif_addr == 6'h28);
        decoded_reg_strb.GPIO_OUTPUT_CLR = cpuif_req_masked & (cpuif_addr == 6'h2c);
        decoded_reg_strb.GPIO_OUTPUT_TGL = cpuif_req_masked & (cpuif_addr == 6'h30);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } gpio_enable;
            struct {
                logic next;
                logic load_next;
            } int_enable;
        } GPIO_CONTROL;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } direction;
        } GPIO_DIRECTION;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } output_data;
        } GPIO_OUTPUT;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } int_enable;
        } GPIO_INT_ENABLE;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } int_type;
        } GPIO_INT_TYPE;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } int_polarity;
        } GPIO_INT_POLARITY;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } int_both;
        } GPIO_INT_BOTH;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } int_status;
        } GPIO_INT_STATUS;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } set_bits;
        } GPIO_OUTPUT_SET;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } clear_bits;
        } GPIO_OUTPUT_CLR;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } toggle_bits;
        } GPIO_OUTPUT_TGL;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } gpio_enable;
            struct {
                logic value;
            } int_enable;
        } GPIO_CONTROL;
        struct {
            struct {
                logic [31:0] value;
            } direction;
        } GPIO_DIRECTION;
        struct {
            struct {
                logic [31:0] value;
            } output_data;
        } GPIO_OUTPUT;
        struct {
            struct {
                logic [31:0] value;
            } int_enable;
        } GPIO_INT_ENABLE;
        struct {
            struct {
                logic [31:0] value;
            } int_type;
        } GPIO_INT_TYPE;
        struct {
            struct {
                logic [31:0] value;
            } int_polarity;
        } GPIO_INT_POLARITY;
        struct {
            struct {
                logic [31:0] value;
            } int_both;
        } GPIO_INT_BOTH;
        struct {
            struct {
                logic [31:0] value;
            } int_status;
        } GPIO_INT_STATUS;
        struct {
            struct {
                logic [31:0] value;
            } set_bits;
        } GPIO_OUTPUT_SET;
        struct {
            struct {
                logic [31:0] value;
            } clear_bits;
        } GPIO_OUTPUT_CLR;
        struct {
            struct {
                logic [31:0] value;
            } toggle_bits;
        } GPIO_OUTPUT_TGL;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: gpio_regs.GPIO_CONTROL.gpio_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_CONTROL.gpio_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_CONTROL.gpio_enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_CONTROL.gpio_enable.next = next_c;
        field_combo.GPIO_CONTROL.gpio_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_CONTROL.gpio_enable.value <= 1'h1;
        end else begin
            if(field_combo.GPIO_CONTROL.gpio_enable.load_next) begin
                field_storage.GPIO_CONTROL.gpio_enable.value <= field_combo.GPIO_CONTROL.gpio_enable.next;
            end
        end
    end
    assign hwif_out.GPIO_CONTROL.gpio_enable.value = field_storage.GPIO_CONTROL.gpio_enable.value;
    // Field: gpio_regs.GPIO_CONTROL.int_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_CONTROL.int_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_CONTROL.int_enable.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.GPIO_CONTROL.int_enable.next = next_c;
        field_combo.GPIO_CONTROL.int_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_CONTROL.int_enable.value <= 1'h0;
        end else begin
            if(field_combo.GPIO_CONTROL.int_enable.load_next) begin
                field_storage.GPIO_CONTROL.int_enable.value <= field_combo.GPIO_CONTROL.int_enable.next;
            end
        end
    end
    assign hwif_out.GPIO_CONTROL.int_enable.value = field_storage.GPIO_CONTROL.int_enable.value;
    // Field: gpio_regs.GPIO_DIRECTION.direction
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_DIRECTION.direction.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_DIRECTION && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_DIRECTION.direction.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_DIRECTION.direction.next = next_c;
        field_combo.GPIO_DIRECTION.direction.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_DIRECTION.direction.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_DIRECTION.direction.load_next) begin
                field_storage.GPIO_DIRECTION.direction.value <= field_combo.GPIO_DIRECTION.direction.next;
            end
        end
    end
    assign hwif_out.GPIO_DIRECTION.direction.value = field_storage.GPIO_DIRECTION.direction.value;
    // Field: gpio_regs.GPIO_OUTPUT.output_data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_OUTPUT.output_data.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_OUTPUT && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_OUTPUT.output_data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_OUTPUT.output_data.next = next_c;
        field_combo.GPIO_OUTPUT.output_data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_OUTPUT.output_data.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_OUTPUT.output_data.load_next) begin
                field_storage.GPIO_OUTPUT.output_data.value <= field_combo.GPIO_OUTPUT.output_data.next;
            end
        end
    end
    assign hwif_out.GPIO_OUTPUT.output_data.value = field_storage.GPIO_OUTPUT.output_data.value;
    // Field: gpio_regs.GPIO_INT_ENABLE.int_enable
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_INT_ENABLE.int_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_INT_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_INT_ENABLE.int_enable.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_INT_ENABLE.int_enable.next = next_c;
        field_combo.GPIO_INT_ENABLE.int_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_INT_ENABLE.int_enable.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_INT_ENABLE.int_enable.load_next) begin
                field_storage.GPIO_INT_ENABLE.int_enable.value <= field_combo.GPIO_INT_ENABLE.int_enable.next;
            end
        end
    end
    assign hwif_out.GPIO_INT_ENABLE.int_enable.value = field_storage.GPIO_INT_ENABLE.int_enable.value;
    // Field: gpio_regs.GPIO_INT_TYPE.int_type
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_INT_TYPE.int_type.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_INT_TYPE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_INT_TYPE.int_type.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_INT_TYPE.int_type.next = next_c;
        field_combo.GPIO_INT_TYPE.int_type.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_INT_TYPE.int_type.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_INT_TYPE.int_type.load_next) begin
                field_storage.GPIO_INT_TYPE.int_type.value <= field_combo.GPIO_INT_TYPE.int_type.next;
            end
        end
    end
    assign hwif_out.GPIO_INT_TYPE.int_type.value = field_storage.GPIO_INT_TYPE.int_type.value;
    // Field: gpio_regs.GPIO_INT_POLARITY.int_polarity
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_INT_POLARITY.int_polarity.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_INT_POLARITY && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_INT_POLARITY.int_polarity.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_INT_POLARITY.int_polarity.next = next_c;
        field_combo.GPIO_INT_POLARITY.int_polarity.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_INT_POLARITY.int_polarity.value <= 32'hffffffff;
        end else begin
            if(field_combo.GPIO_INT_POLARITY.int_polarity.load_next) begin
                field_storage.GPIO_INT_POLARITY.int_polarity.value <= field_combo.GPIO_INT_POLARITY.int_polarity.next;
            end
        end
    end
    assign hwif_out.GPIO_INT_POLARITY.int_polarity.value = field_storage.GPIO_INT_POLARITY.int_polarity.value;
    // Field: gpio_regs.GPIO_INT_BOTH.int_both
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_INT_BOTH.int_both.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_INT_BOTH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_INT_BOTH.int_both.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_INT_BOTH.int_both.next = next_c;
        field_combo.GPIO_INT_BOTH.int_both.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_INT_BOTH.int_both.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_INT_BOTH.int_both.load_next) begin
                field_storage.GPIO_INT_BOTH.int_both.value <= field_combo.GPIO_INT_BOTH.int_both.next;
            end
        end
    end
    assign hwif_out.GPIO_INT_BOTH.int_both.value = field_storage.GPIO_INT_BOTH.int_both.value;
    // Field: gpio_regs.GPIO_INT_STATUS.int_status
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_INT_STATUS.int_status.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_INT_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.GPIO_INT_STATUS.int_status.value & ~(decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end else if(hwif_in.GPIO_INT_STATUS.int_status.next != '0) begin // stickybit
            next_c = field_storage.GPIO_INT_STATUS.int_status.value | hwif_in.GPIO_INT_STATUS.int_status.next;
            load_next_c = '1;
        end
        field_combo.GPIO_INT_STATUS.int_status.next = next_c;
        field_combo.GPIO_INT_STATUS.int_status.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_INT_STATUS.int_status.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_INT_STATUS.int_status.load_next) begin
                field_storage.GPIO_INT_STATUS.int_status.value <= field_combo.GPIO_INT_STATUS.int_status.next;
            end
        end
    end
    assign hwif_out.GPIO_INT_STATUS.int_status.value = field_storage.GPIO_INT_STATUS.int_status.value;
    // Field: gpio_regs.GPIO_OUTPUT_SET.set_bits
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_OUTPUT_SET.set_bits.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_OUTPUT_SET && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_OUTPUT_SET.set_bits.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_OUTPUT_SET.set_bits.next = next_c;
        field_combo.GPIO_OUTPUT_SET.set_bits.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_OUTPUT_SET.set_bits.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_OUTPUT_SET.set_bits.load_next) begin
                field_storage.GPIO_OUTPUT_SET.set_bits.value <= field_combo.GPIO_OUTPUT_SET.set_bits.next;
            end
        end
    end
    assign hwif_out.GPIO_OUTPUT_SET.set_bits.value = field_storage.GPIO_OUTPUT_SET.set_bits.value;
    // Field: gpio_regs.GPIO_OUTPUT_CLR.clear_bits
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_OUTPUT_CLR.clear_bits.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_OUTPUT_CLR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_OUTPUT_CLR.clear_bits.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_OUTPUT_CLR.clear_bits.next = next_c;
        field_combo.GPIO_OUTPUT_CLR.clear_bits.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_OUTPUT_CLR.clear_bits.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_OUTPUT_CLR.clear_bits.load_next) begin
                field_storage.GPIO_OUTPUT_CLR.clear_bits.value <= field_combo.GPIO_OUTPUT_CLR.clear_bits.next;
            end
        end
    end
    assign hwif_out.GPIO_OUTPUT_CLR.clear_bits.value = field_storage.GPIO_OUTPUT_CLR.clear_bits.value;
    // Field: gpio_regs.GPIO_OUTPUT_TGL.toggle_bits
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.GPIO_OUTPUT_TGL.toggle_bits.value;
        load_next_c = '0;
        if(decoded_reg_strb.GPIO_OUTPUT_TGL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.GPIO_OUTPUT_TGL.toggle_bits.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.GPIO_OUTPUT_TGL.toggle_bits.next = next_c;
        field_combo.GPIO_OUTPUT_TGL.toggle_bits.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.GPIO_OUTPUT_TGL.toggle_bits.value <= 32'h0;
        end else begin
            if(field_combo.GPIO_OUTPUT_TGL.toggle_bits.load_next) begin
                field_storage.GPIO_OUTPUT_TGL.toggle_bits.value <= field_combo.GPIO_OUTPUT_TGL.toggle_bits.next;
            end
        end
    end
    assign hwif_out.GPIO_OUTPUT_TGL.toggle_bits.value = field_storage.GPIO_OUTPUT_TGL.toggle_bits.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[10];
    assign readback_array[0][0:0] = (decoded_reg_strb.GPIO_CONTROL && !decoded_req_is_wr) ? field_storage.GPIO_CONTROL.gpio_enable.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.GPIO_CONTROL && !decoded_req_is_wr) ? field_storage.GPIO_CONTROL.int_enable.value : '0;
    assign readback_array[0][31:2] = (decoded_reg_strb.GPIO_CONTROL && !decoded_req_is_wr) ? 30'h0 : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.GPIO_DIRECTION && !decoded_req_is_wr) ? field_storage.GPIO_DIRECTION.direction.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.GPIO_OUTPUT && !decoded_req_is_wr) ? field_storage.GPIO_OUTPUT.output_data.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.GPIO_INPUT && !decoded_req_is_wr) ? hwif_in.GPIO_INPUT.input_data.next : '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.GPIO_INT_ENABLE && !decoded_req_is_wr) ? field_storage.GPIO_INT_ENABLE.int_enable.value : '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.GPIO_INT_TYPE && !decoded_req_is_wr) ? field_storage.GPIO_INT_TYPE.int_type.value : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.GPIO_INT_POLARITY && !decoded_req_is_wr) ? field_storage.GPIO_INT_POLARITY.int_polarity.value : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.GPIO_INT_BOTH && !decoded_req_is_wr) ? field_storage.GPIO_INT_BOTH.int_both.value : '0;
    assign readback_array[8][31:0] = (decoded_reg_strb.GPIO_INT_STATUS && !decoded_req_is_wr) ? field_storage.GPIO_INT_STATUS.int_status.value : '0;
    assign readback_array[9][31:0] = (decoded_reg_strb.GPIO_RAW_INT && !decoded_req_is_wr) ? hwif_in.GPIO_RAW_INT.raw_status.next : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<10; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
