# delta_axis_flat_4x16 -- the flat 4x16 AXIS delta network.
#
# Generated by projects/components/delta/bin/delta_generator.py; the variants
# under rtl_test/ are other shapes from the same generator and are not part of
# this area's compile closure.
#
# Self-contained: the module instantiates nothing. Its only dependency is
# `reset_defs.svh`, which area.mk already supplies via -I rtl/amba/includes.
# Root path token is $REPO_ROOT.

$REPO_ROOT/projects/components/delta/rtl/delta_axis_flat_4x16.sv
