#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# Test file for bridge_2x2_rw
# Generated by bridge test generator from CSV configuration
#
# Configuration:
#   Masters: 2 (cpu, dma)
#   Slaves:  2 (ddr, sram)
#   Channels: RW

import os
import sys
import pytest
import logging

# Import framework utilities (PYTHONPATH includes bin/)
from TBClasses.shared.utilities import get_repo_root

# Add repo root to Python path using robust git-based method
repo_root = get_repo_root()
sys.path.insert(0, repo_root)

import cocotb
from cocotb.triggers import RisingEdge, ClockCycles
from cocotb_test.simulator import run
from TBClasses.shared.utilities import get_paths, get_wave_config
from TBClasses.shared.filelist_utils import get_sources_from_filelist

# Import generated testbench class
from projects.components.bridge.dv.tbclasses.bridge2x2_rw_tb import Bridge2x2RwTB


# ============================================================================
# CocoTB Test Functions (prefixed with cocotb_test_* to prevent pytest collection)
# ============================================================================

@cocotb.test(timeout_time=200, timeout_unit="ms")
async def cocotb_test_basic_connectivity(dut):
    """
    Basic connectivity test - verify master-to-slave routing

    Test plan:
    1. Initialize testbench
    2. For each master:
        - Send write to each connected slave
        - Verify address decode routes to correct slave
        - Slave responds with OKAY
        - Verify response reaches master
    3. For each master:
        - Send read to each connected slave
        - Verify address decode routes to correct slave
        - Slave responds with data
        - Verify response reaches master
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting basic connectivity test")
    tb.log.info(f"Configuration: 2M x 2S, RW channels")
    tb.log.info("=" * 80)

    # Write connectivity test
    tb.log.info(f"Testing master 0 (cpu) write connectivity")

    # Master 0 → Slave 0 (ddr)
    test_addr = 0x00000000
    # Use a 32-bit-or-less data pattern so it fits any slave's data path.
    # The original 0xDEADBEEFXX form was 40 bits and got truncated by the
    # narrowest slave BFM (e.g. a 32-bit APB/AXIL slave), which then broke
    # the data-equality assertion downstream. Master-width masking didn't
    # help because the data still has to ride the slave's BFM first.
    test_data = (0xDEADBE00 | 0x00)
    tb.log.info(f"  Write: addr=0x{test_addr:08x}, data=0x{test_data:08x}")

    # Master sends write transaction
    await tb.write_transaction(
        master_idx=0,
        address=test_addr,
        data=test_data,
        txn_id=0
    )

    # Verify the bridge actually routed the AW to *this* slave (and only
    # this slave). Catches silent misroutes that the old version of this
    # test missed by responding from the expected slave without first
    # checking it had received anything.
    await tb.expect_aw_at_slave(
        slave_idx=0,
        expected_addr=test_addr,
        expected_id=0
    )

    # Slave responds
    await tb.slave_respond_write(
        slave_idx=0,
        txn_id=0,
        resp=0  # OKAY
    )

    # Verify the B response actually came back to the originating master.
    await tb.expect_b_at_master(
        master_idx=0,
        expected_id=0,
        expected_resp=0
    )

    tb.log.info(f"  Write completed successfully (routing + response verified)")

    # Master 0 → Slave 1 (sram)
    test_addr = 0x80000000
    # Use a 32-bit-or-less data pattern so it fits any slave's data path.
    # The original 0xDEADBEEFXX form was 40 bits and got truncated by the
    # narrowest slave BFM (e.g. a 32-bit APB/AXIL slave), which then broke
    # the data-equality assertion downstream. Master-width masking didn't
    # help because the data still has to ride the slave's BFM first.
    test_data = (0xDEADBE00 | 0x01)
    tb.log.info(f"  Write: addr=0x{test_addr:08x}, data=0x{test_data:08x}")

    # Master sends write transaction
    await tb.write_transaction(
        master_idx=0,
        address=test_addr,
        data=test_data,
        txn_id=0
    )

    # Verify the bridge actually routed the AW to *this* slave (and only
    # this slave). Catches silent misroutes that the old version of this
    # test missed by responding from the expected slave without first
    # checking it had received anything.
    await tb.expect_aw_at_slave(
        slave_idx=1,
        expected_addr=test_addr,
        expected_id=0
    )

    # Slave responds
    await tb.slave_respond_write(
        slave_idx=1,
        txn_id=0,
        resp=0  # OKAY
    )

    # Verify the B response actually came back to the originating master.
    await tb.expect_b_at_master(
        master_idx=0,
        expected_id=0,
        expected_resp=0
    )

    tb.log.info(f"  Write completed successfully (routing + response verified)")
    tb.log.info(f"Testing master 1 (dma) write connectivity")

    # Master 1 → Slave 0 (ddr)
    test_addr = 0x00000000
    # Use a 32-bit-or-less data pattern so it fits any slave's data path.
    # The original 0xDEADBEEFXX form was 40 bits and got truncated by the
    # narrowest slave BFM (e.g. a 32-bit APB/AXIL slave), which then broke
    # the data-equality assertion downstream. Master-width masking didn't
    # help because the data still has to ride the slave's BFM first.
    test_data = (0xDEADBE00 | 0x00)
    tb.log.info(f"  Write: addr=0x{test_addr:08x}, data=0x{test_data:08x}")

    # Master sends write transaction
    await tb.write_transaction(
        master_idx=1,
        address=test_addr,
        data=test_data,
        txn_id=1
    )

    # Verify the bridge actually routed the AW to *this* slave (and only
    # this slave). Catches silent misroutes that the old version of this
    # test missed by responding from the expected slave without first
    # checking it had received anything.
    await tb.expect_aw_at_slave(
        slave_idx=0,
        expected_addr=test_addr,
        expected_id=1
    )

    # Slave responds
    await tb.slave_respond_write(
        slave_idx=0,
        txn_id=1,
        resp=0  # OKAY
    )

    # Verify the B response actually came back to the originating master.
    await tb.expect_b_at_master(
        master_idx=1,
        expected_id=1,
        expected_resp=0
    )

    tb.log.info(f"  Write completed successfully (routing + response verified)")

    # Master 1 → Slave 1 (sram)
    test_addr = 0x80000000
    # Use a 32-bit-or-less data pattern so it fits any slave's data path.
    # The original 0xDEADBEEFXX form was 40 bits and got truncated by the
    # narrowest slave BFM (e.g. a 32-bit APB/AXIL slave), which then broke
    # the data-equality assertion downstream. Master-width masking didn't
    # help because the data still has to ride the slave's BFM first.
    test_data = (0xDEADBE00 | 0x01)
    tb.log.info(f"  Write: addr=0x{test_addr:08x}, data=0x{test_data:08x}")

    # Master sends write transaction
    await tb.write_transaction(
        master_idx=1,
        address=test_addr,
        data=test_data,
        txn_id=1
    )

    # Verify the bridge actually routed the AW to *this* slave (and only
    # this slave). Catches silent misroutes that the old version of this
    # test missed by responding from the expected slave without first
    # checking it had received anything.
    await tb.expect_aw_at_slave(
        slave_idx=1,
        expected_addr=test_addr,
        expected_id=1
    )

    # Slave responds
    await tb.slave_respond_write(
        slave_idx=1,
        txn_id=1,
        resp=0  # OKAY
    )

    # Verify the B response actually came back to the originating master.
    await tb.expect_b_at_master(
        master_idx=1,
        expected_id=1,
        expected_resp=0
    )

    tb.log.info(f"  Write completed successfully (routing + response verified)")
    # Read connectivity test    tb.log.info(f"Testing master 0 (cpu) read connectivity")
    # Master 0 → Slave 0 (ddr)
    # Probe a non-base offset (catches decoders that ignore the low bits).
    # The config validator enforces addr_range is a multiple of 4 KB, so
    # +0x100 is always safely inside every slave's window.
    test_addr = 0x00000100
    # 32-bit-or-less value (see DEADBEEF comment above for rationale).
    test_data = (0xCAFEBA00 | 0x00)
    tb.log.info(f"  Read: addr=0x{test_addr:08x}, expect_data=0x{test_data:08x}")

    # Master sends read transaction
    await tb.read_transaction(
        master_idx=0,
        address=test_addr,
        txn_id=0
    )

    # Verify AR routed to expected slave only.
    await tb.expect_ar_at_slave(
        slave_idx=0,
        expected_addr=test_addr,
        expected_id=0
    )

    # Slave responds with data
    await tb.slave_respond_read(
        slave_idx=0,
        data=test_data,
        txn_id=0,
        resp=0  # OKAY
    )

    # Verify R response (data + id) returned to originating master.
    await tb.expect_r_at_master(
        master_idx=0,
        expected_id=0,
        expected_data=test_data,
        expected_resp=0
    )

    tb.log.info(f"  Read completed successfully (routing + response verified)")

    # Master 0 → Slave 1 (sram)
    # Probe a non-base offset (catches decoders that ignore the low bits).
    # The config validator enforces addr_range is a multiple of 4 KB, so
    # +0x100 is always safely inside every slave's window.
    test_addr = 0x80000100
    # 32-bit-or-less value (see DEADBEEF comment above for rationale).
    test_data = (0xCAFEBA00 | 0x01)
    tb.log.info(f"  Read: addr=0x{test_addr:08x}, expect_data=0x{test_data:08x}")

    # Master sends read transaction
    await tb.read_transaction(
        master_idx=0,
        address=test_addr,
        txn_id=0
    )

    # Verify AR routed to expected slave only.
    await tb.expect_ar_at_slave(
        slave_idx=1,
        expected_addr=test_addr,
        expected_id=0
    )

    # Slave responds with data
    await tb.slave_respond_read(
        slave_idx=1,
        data=test_data,
        txn_id=0,
        resp=0  # OKAY
    )

    # Verify R response (data + id) returned to originating master.
    await tb.expect_r_at_master(
        master_idx=0,
        expected_id=0,
        expected_data=test_data,
        expected_resp=0
    )

    tb.log.info(f"  Read completed successfully (routing + response verified)")
    tb.log.info(f"Testing master 1 (dma) read connectivity")
    # Master 1 → Slave 0 (ddr)
    # Probe a non-base offset (catches decoders that ignore the low bits).
    # The config validator enforces addr_range is a multiple of 4 KB, so
    # +0x100 is always safely inside every slave's window.
    test_addr = 0x00000100
    # 32-bit-or-less value (see DEADBEEF comment above for rationale).
    test_data = (0xCAFEBA00 | 0x00)
    tb.log.info(f"  Read: addr=0x{test_addr:08x}, expect_data=0x{test_data:08x}")

    # Master sends read transaction
    await tb.read_transaction(
        master_idx=1,
        address=test_addr,
        txn_id=1
    )

    # Verify AR routed to expected slave only.
    await tb.expect_ar_at_slave(
        slave_idx=0,
        expected_addr=test_addr,
        expected_id=1
    )

    # Slave responds with data
    await tb.slave_respond_read(
        slave_idx=0,
        data=test_data,
        txn_id=1,
        resp=0  # OKAY
    )

    # Verify R response (data + id) returned to originating master.
    await tb.expect_r_at_master(
        master_idx=1,
        expected_id=1,
        expected_data=test_data,
        expected_resp=0
    )

    tb.log.info(f"  Read completed successfully (routing + response verified)")

    # Master 1 → Slave 1 (sram)
    # Probe a non-base offset (catches decoders that ignore the low bits).
    # The config validator enforces addr_range is a multiple of 4 KB, so
    # +0x100 is always safely inside every slave's window.
    test_addr = 0x80000100
    # 32-bit-or-less value (see DEADBEEF comment above for rationale).
    test_data = (0xCAFEBA00 | 0x01)
    tb.log.info(f"  Read: addr=0x{test_addr:08x}, expect_data=0x{test_data:08x}")

    # Master sends read transaction
    await tb.read_transaction(
        master_idx=1,
        address=test_addr,
        txn_id=1
    )

    # Verify AR routed to expected slave only.
    await tb.expect_ar_at_slave(
        slave_idx=1,
        expected_addr=test_addr,
        expected_id=1
    )

    # Slave responds with data
    await tb.slave_respond_read(
        slave_idx=1,
        data=test_data,
        txn_id=1,
        resp=0  # OKAY
    )

    # Verify R response (data + id) returned to originating master.
    await tb.expect_r_at_master(
        master_idx=1,
        expected_id=1,
        expected_data=test_data,
        expected_resp=0
    )

    tb.log.info(f"  Read completed successfully (routing + response verified)")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Basic connectivity test PASSED")
    tb.log.info("=" * 80)


@cocotb.test(timeout_time=500, timeout_unit="ms")
async def cocotb_test_address_decode(dut):
    """
    Address decode verification test

    Test plan:
    1. For each master:
        - Send transactions to boundary addresses of each slave region
        - Verify correct slave is selected via address decode
        - Test: base_addr, base_addr + range - 1, out-of-range addresses
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting address decode test")
    tb.log.info("=" * 80)    # Master 0: cpu
    tb.log.info(f"Testing master 0 address decode")
    # Slave 0: ddr
    # Range: 0x00000000 - 0x7fffffff
    tb.log.info(f"  Slave 0 (ddr): 0x00000000-0x7fffffff")    # Test base address
    await tb.write_transaction(0, 0x00000000, 0x00000000, txn_id=0)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(0, txn_id=0)
    await ClockCycles(tb.clock, 3)

    # Test end address
    await tb.write_transaction(0, 0x7ffffffc, 0x11111111, txn_id=0)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(0, txn_id=0)
    await ClockCycles(tb.clock, 3)
    # Slave 1: sram
    # Range: 0x80000000 - 0xffffffff
    tb.log.info(f"  Slave 1 (sram): 0x80000000-0xffffffff")    # Test base address
    await tb.write_transaction(0, 0x80000000, 0x00000001, txn_id=0)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(1, txn_id=0)
    await ClockCycles(tb.clock, 3)

    # Test end address
    await tb.write_transaction(0, 0xfffffffc, 0x11111112, txn_id=0)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(1, txn_id=0)
    await ClockCycles(tb.clock, 3)    # Master 1: dma
    tb.log.info(f"Testing master 1 address decode")
    # Slave 0: ddr
    # Range: 0x00000000 - 0x7fffffff
    tb.log.info(f"  Slave 0 (ddr): 0x00000000-0x7fffffff")    # Test base address
    await tb.write_transaction(1, 0x00000000, 0x00000000, txn_id=1)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(0, txn_id=1)
    await ClockCycles(tb.clock, 3)

    # Test end address
    await tb.write_transaction(1, 0x7ffffffc, 0x11111111, txn_id=1)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(0, txn_id=1)
    await ClockCycles(tb.clock, 3)
    # Slave 1: sram
    # Range: 0x80000000 - 0xffffffff
    tb.log.info(f"  Slave 1 (sram): 0x80000000-0xffffffff")    # Test base address
    await tb.write_transaction(1, 0x80000000, 0x00000001, txn_id=1)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(1, txn_id=1)
    await ClockCycles(tb.clock, 3)

    # Test end address
    await tb.write_transaction(1, 0xfffffffc, 0x11111112, txn_id=1)
    await ClockCycles(tb.clock, 3)
    await tb.slave_respond_write(1, txn_id=1)
    await ClockCycles(tb.clock, 3)
    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Address decode test PASSED")
    tb.log.info("=" * 80)
@cocotb.test(timeout_time=1000, timeout_unit="ms")
async def cocotb_test_arbitration(dut):
    """
    Multi-master arbitration test

    Test plan:
    1. Multiple masters simultaneously request same slave
    2. Verify round-robin arbitration grants access
    3. Verify non-winning masters are backpressured
    4. Verify transactions complete correctly
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting arbitration test")
    tb.log.info("=" * 80)

    # TODO: Implement concurrent transaction test
    # This requires cocotb.start_soon() for parallel master activity

    await ClockCycles(tb.clock, 100)
    tb.log.info("Arbitration test PASSED")

# ============================================================================
# Pytest Wrapper Functions (collected by pytest, call specific cocotb_test_*)
# ============================================================================

def test_bridge_2x2_rw_basic_connectivity(request):
    """Pytest wrapper for basic connectivity test"""

    # Get standard paths
    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    # Get sources from filelist
    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    # Per-test naming follows the q32 canonical pattern
    # (design_dv/q32/tests/macro/test_q32_*.py): test_<dut>_<testcase>
    # plus an optional pytest-xdist worker suffix when running in parallel.
    # `test_name_plus_params` drives EVERY artifact path (log, xml, sim_build,
    # dump.fst) so each parameterised test invocation gets its own
    # directory and outputs.
    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_basic_connectivity"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # Waveforms via the canonical helper in TBClasses.shared.utilities.
    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_basic_connectivity",
        sim_build=sim_build,
        waves=False,            # cocotb-test compile flags handled via extra_args
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )


def test_bridge_2x2_rw_address_decode(request):
    """Pytest wrapper for address decode test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_address_decode"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_address_decode",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )
def test_bridge_2x2_rw_arbitration(request):
    """Pytest wrapper for arbitration test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_arbitration"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_arbitration",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )

if __name__ == "__main__":
    # Run pytest on this file
    pytest.main([__file__, '-v', '-s'])