#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# Test file for bridge_1x4_rd
# Generated by bridge test generator from CSV configuration
#
# Configuration:
#   Masters: 1 (cpu_rd)
#   Slaves:  4 (periph_rd, ddr_rd, hbm_rd, apb_periph)
#   Channels: RD

import os
import sys
import pytest
import logging

# Import framework utilities (PYTHONPATH includes bin/)
from TBClasses.shared.utilities import get_repo_root

# Add repo root to Python path using robust git-based method
repo_root = get_repo_root()
sys.path.insert(0, repo_root)

import cocotb
from cocotb.triggers import RisingEdge, ClockCycles
from cocotb_test.simulator import run
from TBClasses.shared.utilities import get_paths, get_wave_config
from TBClasses.shared.filelist_utils import get_sources_from_filelist

# Import generated testbench class
from projects.components.bridge.dv.tbclasses.bridge1x4_rd_tb import Bridge1x4RdTB


# ============================================================================
# CocoTB Test Functions
# ============================================================================
#
# Each cocotb test function is named with the rtl_module_name baked in
# (cocotb_test_<module>_<phase>) so that when pytest collects the full
# bridge suite — every test_bridge_*.py imported into the same Python
# process — no two files share a cocotb-registered test name. Sharing
# names causes cross-test state pollution (one config's cocotb.test
# registration overwrites another's, and tests that pass in isolation
# fail in the full regression). Stream's per-module naming was the
# reference.

@cocotb.test(timeout_time=200, timeout_unit="ms")
async def cocotb_test_bridge_1x4_rd_basic_connectivity(dut):
    """
    Basic connectivity — every (master, slave) pair gets one write and/or
    one read at a non-base offset inside the slave's window. Reads check
    against the pre-seeded slave memory pattern; writes verify the bytes
    landed in the slave's memory at the expected offset.

    The slave BFMs auto-respond from their MemoryModel honoring whatever
    ARSIZE/ARLEN/ARADDR (or AWSIZE/AWLEN/AWADDR) the bridge forwards, so
    the same test body works across direct, width-converted, and
    AXIL-shimmed paths — the bridge moves bytes, we read the bytes back.
    """
    tb = Bridge1x4RdTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting basic connectivity test")
    tb.log.info(f"Configuration: 1M x 4S, RD channels")
    tb.log.info("=" * 80)


    # ---- Read connectivity ---------------------------------------------
    tb.log.info(f"Master 0 (cpu_rd) — reads")
    # Master 0 → Slave 0 (periph_rd)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00000100
    expected = tb.slave_mem_read(0, test_addr, master_idx=0)
    tb.log.info(f"  R slave=0 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 0 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 1 (ddr_rd)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x10000100
    expected = tb.slave_mem_read(1, test_addr, master_idx=0)
    tb.log.info(f"  R slave=1 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 1 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 2 (hbm_rd)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x50000100
    expected = tb.slave_mem_read(2, test_addr, master_idx=0)
    tb.log.info(f"  R slave=2 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 2 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 3 (apb_periph)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x80000100
    expected = tb.slave_mem_read(3, test_addr, master_idx=0)
    tb.log.info(f"  R slave=3 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 3 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Basic connectivity test PASSED")
    tb.log.info("=" * 80)


@cocotb.test(timeout_time=500, timeout_unit="ms")
async def cocotb_test_bridge_1x4_rd_address_decode(dut):
    """
    Address decode — for each (master, slave) pair, probe three offsets
    per page (bottom / middle / top of the page) back-to-back, at either
    the boundary pages of the slave window (default) or every page
    (BRIDGE_ADDR_DECODE_MODE=all).

    Routing IS the data round-trip: a misroute lands the write at a
    different slave or different offset and the seed pattern shows
    through instead of the tagged write data. Data verification is
    skipped for probes past the SLAVE_MEM_CAP_BYTES seeded region —
    the slave BFM silently drops OOR writes and fakes reads with
    data=addr, so OOR probes still exercise the decoder pathway but
    can't be data-checked. If/when we want explicit AW/AR routing
    monitors, wire them up at the bridge slave ports separately.

    Set BRIDGE_ADDR_DECODE_MODE=all in the environment to walk every page
    instead of bottom/mid/top — useful for small-window slaves under
    regression, exhausting for GB-class DDR.
    """
    tb = Bridge1x4RdTB(dut)
    await tb.setup_clocks_and_reset()

    mode = os.environ.get('BRIDGE_ADDR_DECODE_MODE', 'boundary').lower()
    if mode not in ('boundary', 'all'):
        tb.log.warning(f"Unknown BRIDGE_ADDR_DECODE_MODE={mode!r}, falling back to 'boundary'")
        mode = 'boundary'

    tb.log.info("=" * 80)
    tb.log.info(f"Starting address decode test (mode={mode})")
    tb.log.info("=" * 80)

    tb.log.info(f"Master 0 (cpu_rd)")
    # Slave 0 (periph_rd): 0x00000000-0x0fffffff
    pages_0_0 = tb.slave_probe_pages(0, mode=mode)
    in_page_0_0 = tb.page_probe_offsets(0, master_idx=0)
    tb.log.info(f"  slave 0: {len(pages_0_0)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_0):
        for probe_idx, probe_off in enumerate(in_page_0_0):
            addr = page_base + probe_off
            got = await tb.master_read(0, addr)
            # Read of the seeded pattern IS the routing check.
            if tb.is_seeded(0, addr):
                exp = tb.slave_mem_read(0, addr, master_idx=0)
                assert got == exp, (
                    f"M0←S0 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{exp:08x}")
    # Slave 1 (ddr_rd): 0x10000000-0x4fffffff
    pages_0_1 = tb.slave_probe_pages(1, mode=mode)
    in_page_0_1 = tb.page_probe_offsets(1, master_idx=0)
    tb.log.info(f"  slave 1: {len(pages_0_1)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_1):
        for probe_idx, probe_off in enumerate(in_page_0_1):
            addr = page_base + probe_off
            got = await tb.master_read(0, addr)
            # Read of the seeded pattern IS the routing check.
            if tb.is_seeded(1, addr):
                exp = tb.slave_mem_read(1, addr, master_idx=0)
                assert got == exp, (
                    f"M0←S1 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{exp:08x}")
    # Slave 2 (hbm_rd): 0x50000000-0x7fffffff
    pages_0_2 = tb.slave_probe_pages(2, mode=mode)
    in_page_0_2 = tb.page_probe_offsets(2, master_idx=0)
    tb.log.info(f"  slave 2: {len(pages_0_2)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_2):
        for probe_idx, probe_off in enumerate(in_page_0_2):
            addr = page_base + probe_off
            got = await tb.master_read(0, addr)
            # Read of the seeded pattern IS the routing check.
            if tb.is_seeded(2, addr):
                exp = tb.slave_mem_read(2, addr, master_idx=0)
                assert got == exp, (
                    f"M0←S2 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{exp:08x}")
    # Slave 3 (apb_periph): 0x80000000-0x8000ffff
    pages_0_3 = tb.slave_probe_pages(3, mode=mode)
    in_page_0_3 = tb.page_probe_offsets(3, master_idx=0)
    tb.log.info(f"  slave 3: {len(pages_0_3)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_3):
        for probe_idx, probe_off in enumerate(in_page_0_3):
            addr = page_base + probe_off
            got = await tb.master_read(0, addr)
            # Read of the seeded pattern IS the routing check.
            if tb.is_seeded(3, addr):
                exp = tb.slave_mem_read(3, addr, master_idx=0)
                assert got == exp, (
                    f"M0←S3 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{exp:08x}")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Address decode test PASSED")
    tb.log.info("=" * 80)

# ============================================================================
# Pytest Wrapper Functions (collected by pytest, call specific cocotb_test_*)
# ============================================================================

def test_bridge_1x4_rd_basic_connectivity(request):
    """Pytest wrapper for basic connectivity test"""

    # Get standard paths
    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_1x4_rd"

    # Get sources from filelist
    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_1x4_rd.f'
    )

    # Per-test naming follows the q32 canonical pattern
    # (design_dv/q32/tests/macro/test_q32_*.py): test_<dut>_<testcase>
    # plus an optional pytest-xdist worker suffix when running in parallel.
    # `test_name_plus_params` drives EVERY artifact path (log, xml, sim_build,
    # dump.fst) so each parameterised test invocation gets its own
    # directory and outputs.
    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_basic_connectivity"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # Waveforms via the canonical helper in TBClasses.shared.utilities.
    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_1x4_rd_basic_connectivity",
        sim_build=sim_build,
        waves=False,            # cocotb-test compile flags handled via extra_args
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )


def test_bridge_1x4_rd_address_decode(request):
    """Pytest wrapper for address decode test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_1x4_rd"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_1x4_rd.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_address_decode"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_1x4_rd_address_decode",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )

if __name__ == "__main__":
    # Run pytest on this file
    pytest.main([__file__, '-v', '-s'])