#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# Test file for bridge_2x2_rw
# Generated by bridge test generator from CSV configuration
#
# Configuration:
#   Masters: 2 (cpu, dma)
#   Slaves:  2 (ddr, sram)
#   Channels: RW

import os
import sys
import pytest
import logging

# Import framework utilities (PYTHONPATH includes bin/)
from TBClasses.shared.utilities import get_repo_root, sim_build_path

# Add repo root to Python path using robust git-based method
repo_root = get_repo_root()
sys.path.insert(0, repo_root)

import cocotb
from cocotb.triggers import ReadOnly, RisingEdge, ClockCycles
from cocotb_test.simulator import run
from TBClasses.shared.utilities import get_paths, get_wave_config
from TBClasses.shared.filelist_utils import get_sources_from_filelist

# Import generated testbench class
from projects.components.bridge.dv.tbclasses.bridge2x2_rw_tb import Bridge2x2RwTB


# ============================================================================
# CocoTB Test Functions
# ============================================================================
#
# Each cocotb test function is named with the rtl_module_name baked in
# (cocotb_test_<module>_<phase>) so that when pytest collects the full
# bridge suite — every test_bridge_*.py imported into the same Python
# process — no two files share a cocotb-registered test name. Sharing
# names causes cross-test state pollution (one config's cocotb.test
# registration overwrites another's, and tests that pass in isolation
# fail in the full regression). Stream's per-module naming was the
# reference.

@cocotb.test(timeout_time=200, timeout_unit="ms")
async def cocotb_test_bridge_2x2_rw_basic_connectivity(dut):
    """
    Basic connectivity — every (master, slave) pair gets one write and/or
    one read at a non-base offset inside the slave's window. Reads check
    against the pre-seeded slave memory pattern; writes verify the bytes
    landed in the slave's memory at the expected offset.

    The slave BFMs auto-respond from their MemoryModel honoring whatever
    ARSIZE/ARLEN/ARADDR (or AWSIZE/AWLEN/AWADDR) the bridge forwards, so
    the same test body works across direct, width-converted, and
    AXIL-shimmed paths — the bridge moves bytes, we read the bytes back.
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting basic connectivity test")
    tb.log.info(f"Configuration: 2M x 2S, RW channels")
    tb.log.info("=" * 80)

    # ---- Write connectivity --------------------------------------------
    tb.log.info(f"Master 0 (cpu) — writes")
    # Master 0 → Slave 0 (ddr)
    test_addr = 0x00000100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 0)
    tb.log.info(f"  W slave=0 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(0, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 0 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 1 (sram)
    test_addr = 0x80000100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 1)
    tb.log.info(f"  W slave=1 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(1, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 1 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    tb.log.info(f"Master 1 (dma) — writes")
    # Master 1 → Slave 0 (ddr)
    test_addr = 0x00000100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (1 << 12) | 0)
    tb.log.info(f"  W slave=0 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(1, test_addr, test_data)
    # Read back at master 1's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(0, test_addr, master_idx=1)
    assert actual == test_data, (
        f"Slave 0 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 1 → Slave 1 (sram)
    test_addr = 0x80000100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (1 << 12) | 1)
    tb.log.info(f"  W slave=1 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(1, test_addr, test_data)
    # Read back at master 1's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(1, test_addr, master_idx=1)
    assert actual == test_data, (
        f"Slave 1 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")

    # ---- Read connectivity ---------------------------------------------
    tb.log.info(f"Master 0 (cpu) — reads")
    # Master 0 → Slave 0 (ddr)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00000100
    expected = tb.slave_mem_read(0, test_addr, master_idx=0)
    tb.log.info(f"  R slave=0 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 0 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 1 (sram)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x80000100
    expected = tb.slave_mem_read(1, test_addr, master_idx=0)
    tb.log.info(f"  R slave=1 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 1 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    tb.log.info(f"Master 1 (dma) — reads")
    # Master 1 → Slave 0 (ddr)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00000100
    expected = tb.slave_mem_read(0, test_addr, master_idx=1)
    tb.log.info(f"  R slave=0 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(1, test_addr)
    assert actual == expected, (
        f"Read mismatch master 1 ← slave 0 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 1 → Slave 1 (sram)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x80000100
    expected = tb.slave_mem_read(1, test_addr, master_idx=1)
    tb.log.info(f"  R slave=1 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(1, test_addr)
    assert actual == expected, (
        f"Read mismatch master 1 ← slave 1 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Basic connectivity test PASSED")
    tb.log.info("=" * 80)


@cocotb.test(timeout_time=500, timeout_unit="ms")
async def cocotb_test_bridge_2x2_rw_boundary_probe(dut):
    """
    Boundary probe — for each (master, slave) pair, probe three offsets
    per page (bottom / middle / top of the page) back-to-back, at either
    the boundary pages of the slave window (default) or every page
    (BRIDGE_BOUNDARY_PROBE_MODE=all).

    NB: previously named "address_decode". The failure modes it surfaces
    are not in the address decoder (which is per-bridge generated inline
    in <master>_adapter.sv and is fine across all configs); they're in
    the downstream protocol shims — axi4_to_axil4_{wr,rd}, axi4_to_apb4
    — stressed by the b2b page probes that the simpler basic_connectivity
    test never reaches.

    Routing IS the data round-trip: a misroute lands the write at a
    different slave or different offset and the seed pattern shows
    through instead of the tagged write data. Data verification is
    skipped for probes past the SLAVE_MEM_CAP_BYTES seeded region —
    the slave BFM silently drops OOR writes and fakes reads with
    data=addr, so OOR probes still exercise the decoder pathway but
    can't be data-checked. If/when we want explicit AW/AR routing
    monitors, wire them up at the bridge slave ports separately.

    Set BRIDGE_BOUNDARY_PROBE_MODE=all in the environment to walk every
    page instead of bottom/mid/top — useful for small-window slaves
    under regression, exhausting for GB-class DDR.
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    mode = os.environ.get('BRIDGE_BOUNDARY_PROBE_MODE', 'boundary').lower()
    if mode not in ('boundary', 'all'):
        tb.log.warning(f"Unknown BRIDGE_BOUNDARY_PROBE_MODE={mode!r}, falling back to 'boundary'")
        mode = 'boundary'

    tb.log.info("=" * 80)
    tb.log.info(f"Starting boundary probe test (mode={mode})")
    tb.log.info("=" * 80)

    tb.log.info(f"Master 0 (cpu)")
    # Slave 0 (ddr): 0x00000000-0x7fffffff
    pages_0_0 = tb.slave_probe_pages(0, mode=mode)
    in_page_0_0 = tb.page_probe_offsets(0, master_idx=0)
    tb.log.info(f"  slave 0: {len(pages_0_0)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_0):
        for probe_idx, probe_off in enumerate(in_page_0_0):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (0 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(0, addr):
                got = tb.slave_mem_read(0, addr, master_idx=0)
                assert got == d, (
                    f"M0→S0 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 1 (sram): 0x80000000-0xffffffff
    pages_0_1 = tb.slave_probe_pages(1, mode=mode)
    in_page_0_1 = tb.page_probe_offsets(1, master_idx=0)
    tb.log.info(f"  slave 1: {len(pages_0_1)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_1):
        for probe_idx, probe_off in enumerate(in_page_0_1):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (1 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(1, addr):
                got = tb.slave_mem_read(1, addr, master_idx=0)
                assert got == d, (
                    f"M0→S1 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    tb.log.info(f"Master 1 (dma)")
    # Slave 0 (ddr): 0x00000000-0x7fffffff
    pages_1_0 = tb.slave_probe_pages(0, mode=mode)
    in_page_1_0 = tb.page_probe_offsets(0, master_idx=1)
    tb.log.info(f"  slave 0: {len(pages_1_0)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_1_0):
        for probe_idx, probe_off in enumerate(in_page_1_0):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (1 << 20) | (0 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(1, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(0, addr):
                got = tb.slave_mem_read(0, addr, master_idx=1)
                assert got == d, (
                    f"M1→S0 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 1 (sram): 0x80000000-0xffffffff
    pages_1_1 = tb.slave_probe_pages(1, mode=mode)
    in_page_1_1 = tb.page_probe_offsets(1, master_idx=1)
    tb.log.info(f"  slave 1: {len(pages_1_1)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_1_1):
        for probe_idx, probe_off in enumerate(in_page_1_1):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (1 << 20) | (1 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(1, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(1, addr):
                got = tb.slave_mem_read(1, addr, master_idx=1)
                assert got == d, (
                    f"M1→S1 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Boundary probe test PASSED")
    tb.log.info("=" * 80)
@cocotb.test(timeout_time=1000, timeout_unit="ms")
async def cocotb_test_bridge_2x2_rw_arbitration(dut):
    """
    Multi-master arbitration test

    Test plan:
    1. Multiple masters simultaneously request same slave
    2. Verify round-robin arbitration grants access
    3. Verify non-winning masters are backpressured
    4. Verify transactions complete correctly
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting arbitration test")
    tb.log.info("=" * 80)

    # TODO: Implement concurrent transaction test
    # This requires cocotb.start_soon() for parallel master activity

    await ClockCycles(tb.clock, 100)
    tb.log.info("Arbitration test PASSED")


@cocotb.test(timeout_time=2000, timeout_unit="ms")
async def cocotb_test_bridge_2x2_rw_outstanding_overflow(dut):
    """
    BRIDGE-011: offer more concurrent writes to one slave than its
    response-tracking FIFO is deep, and require the bridge to hold the line.

    Each slave adapter records the ORIGINATING MASTER for every accepted AW in
    a fixed-depth FIFO and pops it on the response, routing B by FIFO POSITION.
    Push is unconditional on the AW handshake with no full check, so nothing
    stops the pointer running past the reader:

      * past DEPTH, live entries are overwritten -- a response is routed by a
        stale entry, to the WRONG MASTER;
      * at exactly 2*DEPTH the write pointer LAPS the read pointer, the
        `wr_ptr != rd_ptr` occupancy test reads EMPTY, `bid_valid` drops and
        the response is never routed at all -- the master waits forever.

    The invariant asserted here is the one the fix establishes: occupancy NEVER
    exceeds DEPTH, because awready is gated on the FIFO being not-full. That
    holds on fixed RTL and is violated on broken RTL, so it works in both
    directions -- unlike "occupancy exceeded DEPTH", which only a broken
    bridge can satisfy.

    Two conditions are needed and no other test in this suite has either: TWO
    masters outstanding on ONE slave (a single master's entries are all
    identical, so overwriting them is invisible), and a SLOW slave, since the
    default BFM answers in about a cycle and never builds depth.
    """
    tb = Bridge2x2RwTB(dut)
    await tb.setup_clocks_and_reset()

    FIFO_DEPTH = 16    # WR_FIFO_DEPTH in ddr_adapter.sv
    PER_MASTER = 40    # 80 concurrent -- well past both DEPTH and 2*DEPTH
    B_DELAY    = 80    # cycles; must outlast the issue phase

    tb.log.info("=" * 80)
    tb.log.info(f"BRIDGE-011: {2 * PER_MASTER} concurrent writes to slave 0 "
                f"(tracking FIFO is {FIFO_DEPTH} deep)")
    tb.log.info("=" * 80)

    tb.set_slave_response_delay(0, B_DELAY)

    # Ground truth, straight off the adapter's own pointers. Port-level
    # arithmetic was tried first and disagreed with itself: the FIFO pops on
    # the CROSSBAR-side B, not the slave-port B, so counting handshakes at the
    # slave port measures something else entirely.
    fifo = {'peak': 0, 'probed': False}

    async def _fifo_probe():
        wr = tb.dut.u_ddr_adapter.wr_ptr
        rd = tb.dut.u_ddr_adapter.rd_ptr
        fifo['probed'] = True
        while True:
            await RisingEdge(tb.clock)
            await ReadOnly()
            occ = (int(wr.value) - int(rd.value)) & 0x1F
            if occ > fifo['peak']:
                fifo['peak'] = occ

    cocotb.start_soon(_fifo_probe())

    # Disjoint AWID ranges: bit 3 tags the owning master, so a response
    # delivered to the wrong port is identifiable ON THE BUS. Counting
    # completions cannot see it -- misroutes come in pairs and both masters
    # still receive the right NUMBER of responses.
    bad_route = []

    async def _b_watch(master_idx, bid_sig, bvalid_sig, bready_sig):
        while True:
            await RisingEdge(tb.clock)
            await ReadOnly()
            if bvalid_sig.value == 1 and bready_sig.value == 1:
                got = int(bid_sig.value)
                if ((got >> 3) & 1) != master_idx:
                    bad_route.append((master_idx, got))

    cocotb.start_soon(_b_watch(0, tb.dut.cpu_m_axi_bid,
                               tb.dut.cpu_m_axi_bvalid, tb.dut.cpu_m_axi_bready))
    cocotb.start_soon(_b_watch(1, tb.dut.dma_m_axi_bid,
                               tb.dut.dma_m_axi_bvalid, tb.dut.dma_m_axi_bready))

    plan = []
    for m in (0, 1):
        for i in range(PER_MASTER):
            plan.append((m,
                         0x00001000 + (m * 0x400) + (i * 4),
                         0xB0110000 | (m << 12) | i,
                         (m << 3) | (i % 8)))

    done = []

    async def _issue(m, addr, data, txn_id):
        await tb.master_write(m, addr, data, txn_id=txn_id)
        done.append((m, addr, data))

    # Launched before any of them awaits, so the offered load is 80
    # concurrent writes by construction -- no runtime check needed to know
    # the stimulus was strong enough.
    for (m, addr, data, txn_id) in plan:
        cocotb.start_soon(_issue(m, addr, data, txn_id))

    for _ in range(6000):
        if len(done) == len(plan):
            break
        await ClockCycles(tb.clock, 10)

    assert fifo['probed'], "FIFO pointer probe never ran -- test proves nothing"

    tb.log.info(f"peak tracking-FIFO occupancy: {fifo['peak']} "
                f"(depth {FIFO_DEPTH}), completed {len(done)}/{len(plan)}")

    # THE invariant. Gating awready on not-full makes this unconditional.
    assert fifo['peak'] <= FIFO_DEPTH, (
        f"BRIDGE-011: slave 0's tracking FIFO reached {fifo['peak']} entries "
        f"with only {FIFO_DEPTH} slots. Past {FIFO_DEPTH} a live entry is "
        f"overwritten and its response is routed to the wrong master; at "
        f"{2 * FIFO_DEPTH} the pointers lap, occupancy reads EMPTY and the "
        f"response is never routed at all. awready must be gated on not-full.")

    assert not bad_route, (
        f"BRIDGE-011: {len(bad_route)} response(s) delivered to the wrong "
        f"master -- first, master port {bad_route[0][0]} received BID "
        f"0x{bad_route[0][1]:x}.")

    if len(done) != len(plan):
        per_master = {0: 0, 1: 0}
        for (m, _a, _d) in done:
            per_master[m] += 1
        raise AssertionError(
            f"BRIDGE-011: only {len(done)}/{len(plan)} writes completed "
            f"(master 0: {per_master[0]}/{PER_MASTER}, master 1: "
            f"{per_master[1]}/{PER_MASTER}). A response was dropped or "
            f"consumed by the wrong master.")

    for (m, addr, data, _id) in plan:
        actual = tb.slave_mem_read(0, addr, master_idx=m)
        assert actual == data, (
            f"slave 0 memory mismatch at 0x{addr:08x} (master {m}): "
            f"got 0x{actual:08x}, expected 0x{data:08x}")

    tb.log.info(f"All {len(plan)} writes completed; peak occupancy "
                f"{fifo['peak']} stayed within the {FIFO_DEPTH}-entry FIFO")


# ============================================================================
# Pytest Wrapper Functions (collected by pytest, call specific cocotb_test_*)
# ============================================================================

def test_bridge_2x2_rw_basic_connectivity(request):
    """Pytest wrapper for basic connectivity test"""

    # Get standard paths
    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    # Get sources from filelist
    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    # Per-test naming follows the q32 canonical pattern
    # (design_dv/q32/tests/macro/test_q32_*.py): test_<dut>_<testcase>
    # plus an optional pytest-xdist worker suffix when running in parallel.
    # `test_name_plus_params` drives EVERY artifact path (log, xml, sim_build,
    # dump.fst) so each parameterised test invocation gets its own
    # directory and outputs.
    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_basic_connectivity"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    # sim_build_path(), not a hand-built join: it honours SIM_BUILD_ROOT so
    # concurrent sessions do not share one build tree, and drops an advisory
    # busy marker so a cleaner can tell "being built in right now" from
    # "leftover". Hand-joining tests_dir/local_sim_build puts every session
    # back in the same directory, which is what f01853fe was written to stop.
    sim_build = sim_build_path(tests_dir, sim_build_name)
    os.makedirs(log_dir, exist_ok=True)

    # Waveforms via the canonical helper in TBClasses.shared.utilities.
    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_2x2_rw_basic_connectivity",
        sim_build=sim_build,
        waves=False,            # cocotb-test compile flags handled via extra_args
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )


def test_bridge_2x2_rw_boundary_probe(request):
    """Pytest wrapper for boundary probe test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_boundary_probe"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    # sim_build_path(), not a hand-built join: it honours SIM_BUILD_ROOT so
    # concurrent sessions do not share one build tree, and drops an advisory
    # busy marker so a cleaner can tell "being built in right now" from
    # "leftover". Hand-joining tests_dir/local_sim_build puts every session
    # back in the same directory, which is what f01853fe was written to stop.
    sim_build = sim_build_path(tests_dir, sim_build_name)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_2x2_rw_boundary_probe",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )
def test_bridge_2x2_rw_arbitration(request):
    """Pytest wrapper for arbitration test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_arbitration"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    # sim_build_path(), not a hand-built join: it honours SIM_BUILD_ROOT so
    # concurrent sessions do not share one build tree, and drops an advisory
    # busy marker so a cleaner can tell "being built in right now" from
    # "leftover". Hand-joining tests_dir/local_sim_build puts every session
    # back in the same directory, which is what f01853fe was written to stop.
    sim_build = sim_build_path(tests_dir, sim_build_name)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_2x2_rw_arbitration",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )

if __name__ == "__main__":
    # Run pytest on this file
    pytest.main([__file__, '-v', '-s'])

def test_bridge_2x2_rw_outstanding_overflow(request):
    """Pytest wrapper for the BRIDGE-011 outstanding-depth test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_2x2_rw"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/components/bridge/rtl/filelists/bridge_2x2_rw.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_outstanding_overflow"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    # sim_build_path(), not a hand-built join: it honours SIM_BUILD_ROOT so
    # concurrent sessions do not share one build tree, and drops an advisory
    # busy marker so a cleaner can tell "being built in right now" from
    # "leftover". Hand-joining tests_dir/local_sim_build puts every session
    # back in the same directory, which is what f01853fe was written to stop.
    sim_build = sim_build_path(tests_dir, sim_build_name)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_2x2_rw_outstanding_overflow",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )
