# Master filelist for the andesite DDR4/LPDDR4 controller
-f fub/andesite_smoke.f
-f fub/andesite_dfi_cmd_formatter.f
-f fub/andesite_mode_register.f
-f fub/andesite_init_sequencer.f
-f fub/andesite_bank_timer.f
-f fub/andesite_bank_timers.f
-f fub/andesite_page_policy.f
-f fub/andesite_rd_cmd_cam.f
-f fub/andesite_wr_data_cam.f
-f fub/andesite_wr_splitter.f
-f fub/andesite_axi_burst_chopper.f
-f fub/andesite_rd_return_ring.f
-f fub/andesite_dfi_cdc.f
-f fub/andesite_cmd_history_checker.f
