# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sean galloway
#
# Module: rapids_char_io
# Purpose: Host-side UART transport + AXIL region map for rapids_char_top.
#          Reuses the repo's existing UARTAxiBridge (the SAME wire protocol the
#          stream_char host uses) to drive the FPGA over 115200-8N1, and layers
#          the rapids_char_top word-address region map on top of it.
#
# Wire protocol (uart_axil_bridge.sv, ASCII, verified by its README/TB):
#   write:  "W <addr_hex8> <data_hex8>\n"  -> "OK\n"
#   read:   "R <addr_hex8>\n"              -> "0x<data_hex>\n"
# UARTAxiBridge (projects/components/converters/bin/uart_axi_bridge.py) already
# implements this exactly, so we do NOT re-implement byte framing here.
#
# Host word-address map (region = addr[19:16]), from rapids_char_top.sv header:
#   0x0_0000  DUT-REG   : AXIL -> apb_master -> harness s_apb (addr[12:0]=APB byte)
#   0x1_0000  DESC-LOAD : DESC_WORD[0..7] + DESC_ADDR + DESC_KICK + DESC_STATUS
#   0x2_0000  HARNESS CSR: gen/chk/mem/mon control + status readback
#
# Author: sean galloway
# Created: 2026-07-04

"""UART transport and AXIL region map for the RAPIDS beats char board."""

import os
import sys
import time

# The UART/AXIL wire driver lives with the converter RTL it talks to. Reuse it
# rather than re-rolling serial framing (single source of truth for the protocol).
_CONVERTERS_BIN = os.path.join(
    os.environ.get('REPO_ROOT', ''),
    'projects/components/converters/bin')
if _CONVERTERS_BIN and _CONVERTERS_BIN not in sys.path:
    sys.path.insert(0, _CONVERTERS_BIN)

try:
    from uart_axi_bridge import UARTAxiBridge
except ImportError:  # pragma: no cover - only hit without REPO_ROOT / pyserial
    UARTAxiBridge = None


# ---------------------------------------------------------------------------
# Region bases (region = host word-address bits [19:16]).
# ---------------------------------------------------------------------------
REGION_APB = 0x0        # DUT-REG
REGION_DESC = 0x1       # DESC-LOAD
REGION_CSR = 0x2        # HARNESS CSR
_REGION_SHIFT = 16


def region_base(region: int) -> int:
    return region << _REGION_SHIFT


# ---------------------------------------------------------------------------
# DUT-REG (region 0) sub-addresses: 13-bit APB byte address. The half is
# selected by APB addr bit[12] (SRC=0x0000, SNK=0x1000), matching the two
# RegisterMap start_addresses used by rapids_char_harness_tb.py.
# ---------------------------------------------------------------------------
APB_SRC_BASE = 0x0000
APB_SNK_BASE = 0x1000


# ---------------------------------------------------------------------------
# DESC-LOAD (region 1) registers are accessed BY NAME via rapids_harness_desc_regmap
# (DESC_WORD0-7, DESC_ADDR, DESC_KICK{HALF}, DESC_STATUS{OK}) -- see desc_write_reg /
# desc_read_reg below. No offset constants: load_descriptor() uses the names.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# HARNESS CSR (region 2) + DESC-LOAD (region 1) registers are accessed BY NAME
# through the hand-maintained regmaps (rapids_harness_csr_regmap.py /
# rapids_harness_desc_regmap.py, generated by bin/gen_rapids_harness_regmap.py to
# mirror rapids_char_top.sv). NEVER hardcode a CSR/DESC offset or bitmask here --
# RapidsCharIO exposes csr_write/csr_addr/desc_write etc. keyed on register+field
# name (see below). CSR_ID is the read alias of CTRL @ 0x000.
# ---------------------------------------------------------------------------
CSR_ID_EXPECTED = 0x5241_5031  # "RAP1"


def autodetect_port(baud: int = 115200, want: str = None) -> str:
    """Find the ttyUSB the rapids_char harness is on.

    The USB-UART re-enumerates across reboots/replugs, so never hardcode the
    port. Probe each candidate by reading the CSR_ID register (region 2 @ 0x000);
    the board that answers with the 'RAP1' magic is ours. `want`: if the caller
    passed --port explicitly (not 'auto'), try it first. Mirrors the STREAM char
    harness autodetect (SCRATCH round-trip) with the rapids identity register.
    """
    import glob
    cands = []
    if want and want != "auto":
        cands.append(want)
    cands += sorted(p for p in glob.glob("/dev/ttyUSB*") if p not in cands)

    for port in cands:
        try:
            with RapidsCharIO(port=port, baudrate=baud, timeout=0.4) as io:
                if io.ping():
                    print(f"[autodetect] rapids_char harness found on {port}")
                    return port
        except Exception:
            continue
    raise SystemExit(
        f"[autodetect] no rapids_char harness responded on any of: "
        f"{cands or '(no /dev/ttyUSB* present)'}. "
        f"Is the board powered and programmed with rapids_char.bit?")


def _harness_regmap(basename: str):
    """Load a hand-rolled harness regmap (../rtl/<basename>) by name."""
    from TBClasses.apb.register_map import RegisterMap
    import contextlib
    import io as _io
    import logging as _logging
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', 'rtl', basename)
    log = _logging.getLogger('rapids_harness')
    log.addHandler(_logging.NullHandler())
    with contextlib.redirect_stdout(_io.StringIO()):
        return RegisterMap(path, 32, 32, 0, log)


def _compose(regmap, name: str, **fields: int) -> int:
    """Compose a register word by setting named FIELDS at their regmap
    offsets/widths (unspecified fields keep the reset default). Mirrors the
    stream_addrs.compose pattern -- registers programmed by field name, never a
    hand-assembled bitmask."""
    info = regmap.registers.get(name)
    if info is None:
        raise KeyError(f"unknown rapids harness register {name!r}")
    word = int(info.get('default', '0x0'), 16)
    for fname, val in fields.items():
        fld = info.get(fname)
        if not isinstance(fld, dict) or 'offset' not in fld:
            raise KeyError(f"unknown field {name}.{fname}")
        off = fld['offset']
        hi, lo = (int(x) for x in off.split(':')) if ':' in off \
            else (int(off), int(off))
        mask = ((1 << (hi - lo + 1)) - 1) << lo
        word = (word & ~mask) | ((int(val) << lo) & mask)
    return word & 0xFFFF_FFFF


class RapidsCharIO:
    """AXIL region-aware transport over the rapids_char_top UART link."""

    def __init__(self, port='/dev/ttyUSB1', baudrate=115200, timeout=1.0,
                 bridge=None):
        """Open the UART link (or wrap an existing UARTAxiBridge).

        Pass an already-open `bridge` to share a session with other host tools.
        """
        if bridge is not None:
            self.bridge = bridge
            self._owns_bridge = False
        else:
            if UARTAxiBridge is None:
                raise RuntimeError(
                    "UARTAxiBridge unavailable: set REPO_ROOT and `pip install "
                    "pyserial` (it lives in projects/components/converters/bin).")
            self.bridge = UARTAxiBridge(port=port, baudrate=baudrate,
                                        timeout=timeout)
            self._owns_bridge = True
        # Hand-rolled harness register maps (by-name access; see _harness_regmap).
        self._csr_map = _harness_regmap('rapids_harness_csr_regmap.py')
        self._desc_map = _harness_regmap('rapids_harness_desc_regmap.py')

    # ---- Raw 32-bit AXIL primitives (delegated to the UART bridge) ----------

    def axil_write(self, addr: int, data: int) -> bool:
        """32-bit AXIL write. Returns True when the bridge acked with 'OK'."""
        return bool(self.bridge.write(addr & 0xFFFF_FFFF, data & 0xFFFF_FFFF))

    def axil_read(self, addr: int) -> int:
        """32-bit AXIL read. Returns the data word (or None on parse error)."""
        return self.bridge.read(addr & 0xFFFF_FFFF)

    # ---- Region helpers -----------------------------------------------------

    def dut_reg_write(self, apb_byte_addr: int, data: int) -> bool:
        return self.axil_write(region_base(REGION_APB) | apb_byte_addr, data)

    def dut_reg_read(self, apb_byte_addr: int) -> int:
        return self.axil_read(region_base(REGION_APB) | apb_byte_addr)

    def desc_write(self, offset: int, data: int) -> bool:
        return self.axil_write(region_base(REGION_DESC) | offset, data)

    def desc_read(self, offset: int) -> int:
        return self.axil_read(region_base(REGION_DESC) | offset)

    def csr_write(self, offset: int, data: int) -> bool:
        return self.axil_write(region_base(REGION_CSR) | offset, data)

    def csr_read(self, offset: int, retries: int = 3) -> int:
        """Robust 32-bit CSR read.

        The underlying UARTAxiBridge occasionally returns a malformed/short
        frame (parsed as None, or raises mid-frame). Re-issue the read a couple
        of times before giving up rather than propagating a spurious None into
        the scoreboard (which would look like a false failure). The wire
        protocol is unchanged — this is a pure host-side retry.
        """
        addr = region_base(REGION_CSR) | offset
        result = None
        for attempt in range(max(1, retries)):
            try:
                result = self.axil_read(addr)
            except Exception:  # noqa: BLE001 - bad frame surfaces as an exception
                result = None
            if result is not None:
                return result
            if attempt + 1 < retries:
                time.sleep(0.005)  # let the UART line settle before retrying
        return result

    # ---- By-name harness register access (region 1 DESC / region 2 CSR) -----

    def csr_addr(self, name: str) -> int:
        """Absolute AXIL address of a harness CSR register, by name."""
        return region_base(REGION_CSR) | int(self._csr_map.registers[name]['address'], 16)

    def desc_addr(self, name: str) -> int:
        """Absolute AXIL address of a DESC-LOAD register, by name."""
        return region_base(REGION_DESC) | int(self._desc_map.registers[name]['address'], 16)

    def csr_write_reg(self, name: str, **fields: int) -> int:
        """Set CSR register FIELDS by name, then write. Returns the word written."""
        word = _compose(self._csr_map, name, **fields)
        self.csr_write(int(self._csr_map.registers[name]['address'], 16), word)
        return word

    def csr_read_reg(self, name: str) -> int:
        """Read a harness CSR register by name."""
        return self.csr_read(int(self._csr_map.registers[name]['address'], 16))

    def csr_field(self, name: str, field: str) -> int:
        """Read one field of a harness CSR register by name."""
        val = self.csr_read_reg(name) or 0
        off = self._csr_map.registers[name][field]['offset']
        hi, lo = (int(x) for x in off.split(':')) if ':' in off else (int(off), int(off))
        return (val >> lo) & ((1 << (hi - lo + 1)) - 1)

    def desc_write_reg(self, name: str, value: int = None, **fields: int) -> int:
        """Write a DESC-LOAD register by name. `value` for a plain word (VALUE),
        or FIELD kwargs for a fielded register."""
        if value is not None:
            fields = {'VALUE': value}
        word = _compose(self._desc_map, name, **fields)
        self.desc_write(int(self._desc_map.registers[name]['address'], 16), word)
        return word

    def desc_read_reg(self, name: str) -> int:
        return self.desc_read(int(self._desc_map.registers[name]['address'], 16))

    # ---- Convenience: CSR pulses / selected-channel reads -------------------

    def cam_clear(self) -> None:
        self.csr_write_reg("CTRL", CAM_CLEAR=1)

    def select_channel(self, channel: int) -> None:
        """Point the indexed per-channel CSR reads (0xA0-0xAC) at `channel`."""
        self.csr_write_reg("CH_SEL", VALUE=channel)

    def read_status(self) -> int:
        return self.csr_read_reg("STATUS")

    def read_bus_meter(self, direction: str) -> dict:
        """Read one direction's frozen axi_bus_meter buckets by name.

        direction: 'rd' (source-read R channel) or 'wr' (sink-write W channel).
        Returns raw PROD/BP/STARV/IDLE cycle counts + window total + utilization
        (prod / total). The meter is auto-windowed in the harness (opened on DMA
        busy, frozen 16 idle cycles after the last beat), so these are the
        buckets for exactly one workload.
        """
        if direction not in ('rd', 'wr'):
            raise ValueError(f"direction must be 'rd' or 'wr', got {direction!r}")
        d = direction.upper()
        prod = self.csr_read_reg(f"OBS_{d}_PROD") or 0
        bp = self.csr_read_reg(f"OBS_{d}_BP") or 0
        starv = self.csr_read_reg(f"OBS_{d}_STARV") or 0
        idle = self.csr_read_reg(f"OBS_{d}_IDLE") or 0
        total = prod + bp + starv + idle
        return {'prod': prod, 'bp': bp, 'starv': starv, 'idle': idle,
                'total': total, 'util': (prod / total) if total else 0.0}

    def read_bus_meters(self) -> dict:
        """Read both directions' bus meters -> {'rd': {...}, 'wr': {...}}."""
        return {'rd': self.read_bus_meter('rd'), 'wr': self.read_bus_meter('wr')}

    def ping(self) -> bool:
        """Verify the UART link + CSR block are alive via the ID register
        (CTRL @ 0x000 reads back the 'RAP1' magic)."""
        return self.csr_read_reg("CTRL") == CSR_ID_EXPECTED

    # ---- Descriptor load into on-chip descriptor RAM ------------------------

    def load_descriptor(self, half: str, ram_byte_addr: int, desc_words) -> bool:
        """Assemble a 256-bit descriptor in the DESC-LOAD holding registers and
        issue ONE single-beat AXI4 write into the SRC/SNK descriptor RAM.

        This mirrors the cocotb TB's load_descriptor() (which drives the same
        desc_src_*/desc_snk_* host-write port directly). `half` is 'src' or 'snk';
        `ram_byte_addr` is where the DUT will fetch the descriptor when kicked;
        `desc_words` is the 8-word list from descriptor_to_words().
        Returns the DESC_STATUS OK bit after the write.
        """
        if len(desc_words) != 8:
            raise ValueError(f"expected 8 descriptor words, got {len(desc_words)}")
        half_sel = 0 if half == 'src' else 1

        for i, word in enumerate(desc_words):
            self.desc_write_reg(f"DESC_WORD{i}", word)
        self.desc_write_reg("DESC_ADDR", ram_byte_addr & 0xFFFF_FFFF)
        self.desc_write_reg("DESC_KICK", HALF=half_sel)   # issues the AXI4 write
        status = self.desc_read_reg("DESC_STATUS")
        return status is not None and (status & 0x1) == 1

    # ---- Cleanup ------------------------------------------------------------

    def close(self) -> None:
        if self._owns_bridge and self.bridge is not None:
            self.bridge.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
