// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package uart_16550_regs_pkg;

    localparam UART_16550_REGS_DATA_WIDTH = 32;
    localparam UART_16550_REGS_MIN_ADDR_WIDTH = 6;
    localparam UART_16550_REGS_SIZE = 'h2c;

    typedef struct {
        logic [7:0] next;
    } uart_16550_regs__UART_DATA__rx_data__in_t;

    typedef struct {
        uart_16550_regs__UART_DATA__rx_data__in_t rx_data;
    } uart_16550_regs__UART_DATA__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_IIR__int_not_pending__in_t;

    typedef struct {
        logic [1:0] next;
    } uart_16550_regs__UART_IIR__int_id__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_IIR__timeout_pending__in_t;

    typedef struct {
        logic [1:0] next;
    } uart_16550_regs__UART_IIR__fifo_status__in_t;

    typedef struct {
        uart_16550_regs__UART_IIR__int_not_pending__in_t int_not_pending;
        uart_16550_regs__UART_IIR__int_id__in_t int_id;
        uart_16550_regs__UART_IIR__timeout_pending__in_t timeout_pending;
        uart_16550_regs__UART_IIR__fifo_status__in_t fifo_status;
    } uart_16550_regs__UART_IIR__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_LSR__data_ready__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_LSR__overrun_error__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_LSR__parity_error__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_LSR__framing_error__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_LSR__break_interrupt__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_LSR__tx_holding_empty__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_LSR__tx_empty__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_LSR__rx_fifo_error__in_t;

    typedef struct {
        uart_16550_regs__UART_LSR__data_ready__in_t data_ready;
        uart_16550_regs__UART_LSR__overrun_error__in_t overrun_error;
        uart_16550_regs__UART_LSR__parity_error__in_t parity_error;
        uart_16550_regs__UART_LSR__framing_error__in_t framing_error;
        uart_16550_regs__UART_LSR__break_interrupt__in_t break_interrupt;
        uart_16550_regs__UART_LSR__tx_holding_empty__in_t tx_holding_empty;
        uart_16550_regs__UART_LSR__tx_empty__in_t tx_empty;
        uart_16550_regs__UART_LSR__rx_fifo_error__in_t rx_fifo_error;
    } uart_16550_regs__UART_LSR__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_MSR__delta_cts__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_MSR__delta_dsr__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_MSR__trailing_ri__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } uart_16550_regs__UART_MSR__delta_dcd__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_MSR__cts__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_MSR__dsr__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_MSR__ri__in_t;

    typedef struct {
        logic next;
    } uart_16550_regs__UART_MSR__dcd__in_t;

    typedef struct {
        uart_16550_regs__UART_MSR__delta_cts__in_t delta_cts;
        uart_16550_regs__UART_MSR__delta_dsr__in_t delta_dsr;
        uart_16550_regs__UART_MSR__trailing_ri__in_t trailing_ri;
        uart_16550_regs__UART_MSR__delta_dcd__in_t delta_dcd;
        uart_16550_regs__UART_MSR__cts__in_t cts;
        uart_16550_regs__UART_MSR__dsr__in_t dsr;
        uart_16550_regs__UART_MSR__ri__in_t ri;
        uart_16550_regs__UART_MSR__dcd__in_t dcd;
    } uart_16550_regs__UART_MSR__in_t;

    typedef struct {
        uart_16550_regs__UART_DATA__in_t UART_DATA;
        uart_16550_regs__UART_IIR__in_t UART_IIR;
        uart_16550_regs__UART_LSR__in_t UART_LSR;
        uart_16550_regs__UART_MSR__in_t UART_MSR;
    } uart_16550_regs__in_t;

    typedef struct {
        logic [7:0] value;
    } uart_16550_regs__UART_DATA__tx_data__out_t;

    typedef struct {
        uart_16550_regs__UART_DATA__tx_data__out_t tx_data;
    } uart_16550_regs__UART_DATA__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_IER__rx_data_avail_ie__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_IER__tx_empty_ie__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_IER__rx_line_status_ie__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_IER__modem_status_ie__out_t;

    typedef struct {
        uart_16550_regs__UART_IER__rx_data_avail_ie__out_t rx_data_avail_ie;
        uart_16550_regs__UART_IER__tx_empty_ie__out_t tx_empty_ie;
        uart_16550_regs__UART_IER__rx_line_status_ie__out_t rx_line_status_ie;
        uart_16550_regs__UART_IER__modem_status_ie__out_t modem_status_ie;
    } uart_16550_regs__UART_IER__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_FCR__fifo_enable__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_FCR__rx_fifo_reset__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_FCR__tx_fifo_reset__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_FCR__dma_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } uart_16550_regs__UART_FCR__rx_trigger__out_t;

    typedef struct {
        uart_16550_regs__UART_FCR__fifo_enable__out_t fifo_enable;
        uart_16550_regs__UART_FCR__rx_fifo_reset__out_t rx_fifo_reset;
        uart_16550_regs__UART_FCR__tx_fifo_reset__out_t tx_fifo_reset;
        uart_16550_regs__UART_FCR__dma_mode__out_t dma_mode;
        uart_16550_regs__UART_FCR__rx_trigger__out_t rx_trigger;
    } uart_16550_regs__UART_FCR__out_t;

    typedef struct {
        logic [1:0] value;
    } uart_16550_regs__UART_LCR__word_length__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__stop_bits__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__parity_enable__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__even_parity__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__stick_parity__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__set_break__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_LCR__dlab__out_t;

    typedef struct {
        uart_16550_regs__UART_LCR__word_length__out_t word_length;
        uart_16550_regs__UART_LCR__stop_bits__out_t stop_bits;
        uart_16550_regs__UART_LCR__parity_enable__out_t parity_enable;
        uart_16550_regs__UART_LCR__even_parity__out_t even_parity;
        uart_16550_regs__UART_LCR__stick_parity__out_t stick_parity;
        uart_16550_regs__UART_LCR__set_break__out_t set_break;
        uart_16550_regs__UART_LCR__dlab__out_t dlab;
    } uart_16550_regs__UART_LCR__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_MCR__dtr__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_MCR__rts__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_MCR__out1__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_MCR__out2__out_t;

    typedef struct {
        logic value;
    } uart_16550_regs__UART_MCR__loopback__out_t;

    typedef struct {
        uart_16550_regs__UART_MCR__dtr__out_t dtr;
        uart_16550_regs__UART_MCR__rts__out_t rts;
        uart_16550_regs__UART_MCR__out1__out_t out1;
        uart_16550_regs__UART_MCR__out2__out_t out2;
        uart_16550_regs__UART_MCR__loopback__out_t loopback;
    } uart_16550_regs__UART_MCR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_16550_regs__UART_SCR__scratch__out_t;

    typedef struct {
        uart_16550_regs__UART_SCR__scratch__out_t scratch;
    } uart_16550_regs__UART_SCR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_16550_regs__UART_DLL__dll__out_t;

    typedef struct {
        uart_16550_regs__UART_DLL__dll__out_t dll;
    } uart_16550_regs__UART_DLL__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_16550_regs__UART_DLM__dlm__out_t;

    typedef struct {
        uart_16550_regs__UART_DLM__dlm__out_t dlm;
    } uart_16550_regs__UART_DLM__out_t;

    typedef struct {
        uart_16550_regs__UART_DATA__out_t UART_DATA;
        uart_16550_regs__UART_IER__out_t UART_IER;
        uart_16550_regs__UART_FCR__out_t UART_FCR;
        uart_16550_regs__UART_LCR__out_t UART_LCR;
        uart_16550_regs__UART_MCR__out_t UART_MCR;
        uart_16550_regs__UART_SCR__out_t UART_SCR;
        uart_16550_regs__UART_DLL__out_t UART_DLL;
        uart_16550_regs__UART_DLM__out_t UART_DLM;
    } uart_16550_regs__out_t;
endpackage
