# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sean galloway
#
# Region and half base map for the RAPIDS characterization harness host link.
# GENERATED by bin/gen_rapids_harness_regmap.py (cross-checked against the
# REGION_* localparams of rapids_byte_harness.sv) -- never hand-edit.
# Address = (REGIONS[region] << REGION_SHIFT) | (half << HALF_SHIFT) | offset,
# where offset comes from the by-name regmaps.

"""RAPIDS characterization harness region map."""

REGION_SHIFT = 16
REGIONS = {'APB': 0, 'DESC': 1, 'CSR': 2, 'OBS': 3}
HALF_SHIFT = 12
APB_HALVES = {'src': 0, 'snk': 1}
OBS_HALVES = {'axi': 0, 'axis': 1}
