// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module pit_regs (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [4:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input pit_regs_pkg::pit_regs__in_t hwif_in,
        output pit_regs_pkg::pit_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic PIT_CONFIG;
        logic PIT_CONTROL;
        logic PIT_STATUS;
        logic RESERVED_0C;
        logic COUNTER0_DATA;
        logic COUNTER1_DATA;
        logic COUNTER2_DATA;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.PIT_CONFIG = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.PIT_CONTROL = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.PIT_STATUS = cpuif_req_masked & (cpuif_addr == 5'h8);
        decoded_reg_strb.RESERVED_0C = cpuif_req_masked & (cpuif_addr == 5'hc);
        decoded_reg_strb.COUNTER0_DATA = cpuif_req_masked & (cpuif_addr == 5'h10);
        decoded_reg_strb.COUNTER1_DATA = cpuif_req_masked & (cpuif_addr == 5'h14);
        decoded_reg_strb.COUNTER2_DATA = cpuif_req_masked & (cpuif_addr == 5'h18);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } pit_enable;
            struct {
                logic next;
                logic load_next;
            } clock_select;
        } PIT_CONFIG;
        struct {
            struct {
                logic next;
                logic load_next;
            } bcd;
            struct {
                logic [2:0] next;
                logic load_next;
            } mode;
            struct {
                logic [1:0] next;
                logic load_next;
            } rw_mode;
            struct {
                logic [1:0] next;
                logic load_next;
            } counter_select;
        } PIT_CONTROL;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } counter0_data;
        } COUNTER0_DATA;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } counter1_data;
        } COUNTER1_DATA;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } counter2_data;
        } COUNTER2_DATA;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } pit_enable;
            struct {
                logic value;
            } clock_select;
        } PIT_CONFIG;
        struct {
            struct {
                logic value;
            } bcd;
            struct {
                logic [2:0] value;
            } mode;
            struct {
                logic [1:0] value;
            } rw_mode;
            struct {
                logic [1:0] value;
            } counter_select;
        } PIT_CONTROL;
        struct {
            struct {
                logic [15:0] value;
            } counter0_data;
        } COUNTER0_DATA;
        struct {
            struct {
                logic [15:0] value;
            } counter1_data;
        } COUNTER1_DATA;
        struct {
            struct {
                logic [15:0] value;
            } counter2_data;
        } COUNTER2_DATA;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: pit_regs.PIT_CONFIG.pit_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONFIG.pit_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONFIG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONFIG.pit_enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.PIT_CONFIG.pit_enable.next = next_c;
        field_combo.PIT_CONFIG.pit_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONFIG.pit_enable.value <= 1'h0;
        end else begin
            if(field_combo.PIT_CONFIG.pit_enable.load_next) begin
                field_storage.PIT_CONFIG.pit_enable.value <= field_combo.PIT_CONFIG.pit_enable.next;
            end
        end
    end
    assign hwif_out.PIT_CONFIG.pit_enable.value = field_storage.PIT_CONFIG.pit_enable.value;
    // Field: pit_regs.PIT_CONFIG.clock_select
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONFIG.clock_select.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONFIG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONFIG.clock_select.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.PIT_CONFIG.clock_select.next = next_c;
        field_combo.PIT_CONFIG.clock_select.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONFIG.clock_select.value <= 1'h0;
        end else begin
            if(field_combo.PIT_CONFIG.clock_select.load_next) begin
                field_storage.PIT_CONFIG.clock_select.value <= field_combo.PIT_CONFIG.clock_select.next;
            end
        end
    end
    assign hwif_out.PIT_CONFIG.clock_select.value = field_storage.PIT_CONFIG.clock_select.value;
    // Field: pit_regs.PIT_CONTROL.bcd
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONTROL.bcd.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONTROL.bcd.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.PIT_CONTROL.bcd.next = next_c;
        field_combo.PIT_CONTROL.bcd.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONTROL.bcd.value <= 1'h0;
        end else begin
            if(field_combo.PIT_CONTROL.bcd.load_next) begin
                field_storage.PIT_CONTROL.bcd.value <= field_combo.PIT_CONTROL.bcd.next;
            end
        end
    end
    assign hwif_out.PIT_CONTROL.bcd.value = field_storage.PIT_CONTROL.bcd.value;
    // Field: pit_regs.PIT_CONTROL.mode
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONTROL.mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONTROL.mode.value & ~decoded_wr_biten[3:1]) | (decoded_wr_data[3:1] & decoded_wr_biten[3:1]);
            load_next_c = '1;
        end
        field_combo.PIT_CONTROL.mode.next = next_c;
        field_combo.PIT_CONTROL.mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONTROL.mode.value <= 3'h0;
        end else begin
            if(field_combo.PIT_CONTROL.mode.load_next) begin
                field_storage.PIT_CONTROL.mode.value <= field_combo.PIT_CONTROL.mode.next;
            end
        end
    end
    assign hwif_out.PIT_CONTROL.mode.value = field_storage.PIT_CONTROL.mode.value;
    // Field: pit_regs.PIT_CONTROL.rw_mode
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONTROL.rw_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONTROL.rw_mode.value & ~decoded_wr_biten[5:4]) | (decoded_wr_data[5:4] & decoded_wr_biten[5:4]);
            load_next_c = '1;
        end
        field_combo.PIT_CONTROL.rw_mode.next = next_c;
        field_combo.PIT_CONTROL.rw_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONTROL.rw_mode.value <= 2'h0;
        end else begin
            if(field_combo.PIT_CONTROL.rw_mode.load_next) begin
                field_storage.PIT_CONTROL.rw_mode.value <= field_combo.PIT_CONTROL.rw_mode.next;
            end
        end
    end
    assign hwif_out.PIT_CONTROL.rw_mode.value = field_storage.PIT_CONTROL.rw_mode.value;
    // Field: pit_regs.PIT_CONTROL.counter_select
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PIT_CONTROL.counter_select.value;
        load_next_c = '0;
        if(decoded_reg_strb.PIT_CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PIT_CONTROL.counter_select.value & ~decoded_wr_biten[7:6]) | (decoded_wr_data[7:6] & decoded_wr_biten[7:6]);
            load_next_c = '1;
        end
        field_combo.PIT_CONTROL.counter_select.next = next_c;
        field_combo.PIT_CONTROL.counter_select.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PIT_CONTROL.counter_select.value <= 2'h0;
        end else begin
            if(field_combo.PIT_CONTROL.counter_select.load_next) begin
                field_storage.PIT_CONTROL.counter_select.value <= field_combo.PIT_CONTROL.counter_select.next;
            end
        end
    end
    assign hwif_out.PIT_CONTROL.counter_select.value = field_storage.PIT_CONTROL.counter_select.value;
    // Field: pit_regs.COUNTER0_DATA.counter0_data
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.COUNTER0_DATA.counter0_data.value;
        load_next_c = '0;
        if(decoded_reg_strb.COUNTER0_DATA && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.COUNTER0_DATA.counter0_data.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.COUNTER0_DATA.counter0_data.next;
            load_next_c = '1;
        end
        field_combo.COUNTER0_DATA.counter0_data.next = next_c;
        field_combo.COUNTER0_DATA.counter0_data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.COUNTER0_DATA.counter0_data.value <= 16'h0;
        end else begin
            if(field_combo.COUNTER0_DATA.counter0_data.load_next) begin
                field_storage.COUNTER0_DATA.counter0_data.value <= field_combo.COUNTER0_DATA.counter0_data.next;
            end
        end
    end
    assign hwif_out.COUNTER0_DATA.counter0_data.value = field_storage.COUNTER0_DATA.counter0_data.value;
    // Field: pit_regs.COUNTER1_DATA.counter1_data
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.COUNTER1_DATA.counter1_data.value;
        load_next_c = '0;
        if(decoded_reg_strb.COUNTER1_DATA && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.COUNTER1_DATA.counter1_data.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.COUNTER1_DATA.counter1_data.next;
            load_next_c = '1;
        end
        field_combo.COUNTER1_DATA.counter1_data.next = next_c;
        field_combo.COUNTER1_DATA.counter1_data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.COUNTER1_DATA.counter1_data.value <= 16'h0;
        end else begin
            if(field_combo.COUNTER1_DATA.counter1_data.load_next) begin
                field_storage.COUNTER1_DATA.counter1_data.value <= field_combo.COUNTER1_DATA.counter1_data.next;
            end
        end
    end
    assign hwif_out.COUNTER1_DATA.counter1_data.value = field_storage.COUNTER1_DATA.counter1_data.value;
    // Field: pit_regs.COUNTER2_DATA.counter2_data
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.COUNTER2_DATA.counter2_data.value;
        load_next_c = '0;
        if(decoded_reg_strb.COUNTER2_DATA && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.COUNTER2_DATA.counter2_data.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.COUNTER2_DATA.counter2_data.next;
            load_next_c = '1;
        end
        field_combo.COUNTER2_DATA.counter2_data.next = next_c;
        field_combo.COUNTER2_DATA.counter2_data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.COUNTER2_DATA.counter2_data.value <= 16'h0;
        end else begin
            if(field_combo.COUNTER2_DATA.counter2_data.load_next) begin
                field_storage.COUNTER2_DATA.counter2_data.value <= field_combo.COUNTER2_DATA.counter2_data.next;
            end
        end
    end
    assign hwif_out.COUNTER2_DATA.counter2_data.value = field_storage.COUNTER2_DATA.counter2_data.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[7];
    assign readback_array[0][0:0] = (decoded_reg_strb.PIT_CONFIG && !decoded_req_is_wr) ? field_storage.PIT_CONFIG.pit_enable.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.PIT_CONFIG && !decoded_req_is_wr) ? field_storage.PIT_CONFIG.clock_select.value : '0;
    assign readback_array[0][31:2] = (decoded_reg_strb.PIT_CONFIG && !decoded_req_is_wr) ? 30'h0 : '0;
    assign readback_array[1][7:0] = '0;
    assign readback_array[1][31:8] = (decoded_reg_strb.PIT_CONTROL && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[2][7:0] = (decoded_reg_strb.PIT_STATUS && !decoded_req_is_wr) ? hwif_in.PIT_STATUS.counter0_status.next : '0;
    assign readback_array[2][15:8] = (decoded_reg_strb.PIT_STATUS && !decoded_req_is_wr) ? hwif_in.PIT_STATUS.counter1_status.next : '0;
    assign readback_array[2][23:16] = (decoded_reg_strb.PIT_STATUS && !decoded_req_is_wr) ? hwif_in.PIT_STATUS.counter2_status.next : '0;
    assign readback_array[2][31:24] = (decoded_reg_strb.PIT_STATUS && !decoded_req_is_wr) ? 8'h0 : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.RESERVED_0C && !decoded_req_is_wr) ? 32'h0 : '0;
    assign readback_array[4][15:0] = (decoded_reg_strb.COUNTER0_DATA && !decoded_req_is_wr) ? field_storage.COUNTER0_DATA.counter0_data.value : '0;
    assign readback_array[4][31:16] = (decoded_reg_strb.COUNTER0_DATA && !decoded_req_is_wr) ? 16'h0 : '0;
    assign readback_array[5][15:0] = (decoded_reg_strb.COUNTER1_DATA && !decoded_req_is_wr) ? field_storage.COUNTER1_DATA.counter1_data.value : '0;
    assign readback_array[5][31:16] = (decoded_reg_strb.COUNTER1_DATA && !decoded_req_is_wr) ? 16'h0 : '0;
    assign readback_array[6][15:0] = (decoded_reg_strb.COUNTER2_DATA && !decoded_req_is_wr) ? field_storage.COUNTER2_DATA.counter2_data.value : '0;
    assign readback_array[6][31:16] = (decoded_reg_strb.COUNTER2_DATA && !decoded_req_is_wr) ? 16'h0 : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<7; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
