@startuml ProjectAutomation_RunTest
!include automation_rematcher.puml

class RunTest {
    - original_directory : str
    - repo_root : str
    - env
    - config_dct : dict
    - test_list : str
    - tag : str
    - test : str
    - seed : str
    - params : dict
    - regression_dir : str

    + __init__(test : str, test_list : str, tag : str, seed : str, params : dict)
    + _ready_run_area()
    + _parse_makefile(makefile_path : str) : tuple
    + run_test()
    + run_test_list()
    + report_regression(test_count : int, fail_count : int, fail_list : list)
    + get_unique_dir_name(base_name : str) : str
    + process_results(output_file : str) : bool
    + update_makefile(makefile_path : str, seed : str, params : dict)
    + run_make(repo_root : str, test : str, base_test_path : str, path_out : str, env, seed : str, params : dict) : bool

    note right of RunTest
        Represents a test runner that runs a test and reports
        the regression test results.
    end note
}

RunTest --> REMatcher

@enduml
