# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sean galloway
#
# Register map for the STREAM characterization HARNESS CSRs (harness_csr.sv).
# SEPARATE from stream_regmap.py (the STREAM IP registers) -- this is the char
# harness's own control/status/timer/observer/kick block at base 0x0001_0000.
# Fed to the harness code as its own device so harness registers are accessed by
# name: harness.write("KICK_GO", MASK=...) / harness.read("TIMER_CYCLES_LO") /
# harness.field("TIMER_STATUS", "DONE"), exactly like the STREAM device.
#
# Hand-maintained to mirror harness_csr.sv's documented address map (the harness
# CSRs are hand-coded RTL, not PeakRDL). Offsets are relative to the base; the
# UartRegisterMap/Device is given start_address=0x0001_0000.
#
# Usage:
#   from TBClasses.harness.uart_register_map import UartRegisterMap
#   regs = UartRegisterMap(bridge, start_address=0x0001_0000,
#                          regmap_file=".../harness_csr_regmap.py")

"""STREAM Characterization Harness CSR Register Map (base 0x0001_0000)."""

top_block = {'BUILD_ID': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
              'address': '0x24',
              'default': '0x00000000',
              'name': 'BUILD_ID',
              'offset': '0x24',
              'size': 4,
              'sw': 'r',
              'type': 'reg'},
 'CH0_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xb0',
                   'default': '0x00000000',
                   'name': 'CH0_KICK_ADDR',
                   'offset': '0xb0',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH1_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xb4',
                   'default': '0x00000000',
                   'name': 'CH1_KICK_ADDR',
                   'offset': '0xb4',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH2_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xb8',
                   'default': '0x00000000',
                   'name': 'CH2_KICK_ADDR',
                   'offset': '0xb8',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH3_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xbc',
                   'default': '0x00000000',
                   'name': 'CH3_KICK_ADDR',
                   'offset': '0xbc',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH4_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xc4',
                   'default': '0x00000000',
                   'name': 'CH4_KICK_ADDR',
                   'offset': '0xc4',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH5_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xc8',
                   'default': '0x00000000',
                   'name': 'CH5_KICK_ADDR',
                   'offset': '0xc8',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH6_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xcc',
                   'default': '0x00000000',
                   'name': 'CH6_KICK_ADDR',
                   'offset': '0xcc',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'CH7_KICK_ADDR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                   'address': '0xd0',
                   'default': '0x00000000',
                   'name': 'CH7_KICK_ADDR',
                   'offset': '0xd0',
                   'size': 4,
                   'sw': 'rw',
                   'type': 'reg'},
 'COMP_CAM_MISS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x1f0',
                   'default': '0x00000000',
                   'name': 'COMP_CAM_MISS',
                   'offset': '0x1f0',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'COMP_DELTA_TS_OVF': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                       'address': '0x1f4',
                       'default': '0x00000000',
                       'name': 'COMP_DELTA_TS_OVF',
                       'offset': '0x1f4',
                       'size': 4,
                       'sw': 'r',
                       'type': 'reg'},
 'COMP_ED_DELTA_OVF': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                       'address': '0x1fc',
                       'default': '0x00000000',
                       'name': 'COMP_ED_DELTA_OVF',
                       'offset': '0x1fc',
                       'size': 4,
                       'sw': 'r',
                       'type': 'reg'},
 'COMP_EVENT_DATA_OVF': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                         'address': '0x1f8',
                         'default': '0x00000000',
                         'name': 'COMP_EVENT_DATA_OVF',
                         'offset': '0x1f8',
                         'size': 4,
                         'sw': 'r',
                         'type': 'reg'},
 'COMP_TIER0': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x1ec',
                'default': '0x00000000',
                'name': 'COMP_TIER0',
                'offset': '0x1ec',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'COMP_TIER1_A': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x1e0',
                  'default': '0x00000000',
                  'name': 'COMP_TIER1_A',
                  'offset': '0x1e0',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'COMP_TIER1_B': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x1e4',
                  'default': '0x00000000',
                  'name': 'COMP_TIER1_B',
                  'offset': '0x1e4',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'COMP_TIER1_C': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x1e8',
                  'default': '0x00000000',
                  'name': 'COMP_TIER1_C',
                  'offset': '0x1e8',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'CRC_MATCH': {'MATCH': {'default': '0x0', 'offset': '0:0', 'sw': 'r', 'type': 'field'},
               'RSVD': {'default': '0x0', 'offset': '31:2', 'sw': 'r', 'type': 'field'},
               'VALID': {'default': '0x0', 'offset': '1:1', 'sw': 'r', 'type': 'field'},
               'address': '0x1c',
               'default': '0x00000000',
               'name': 'CRC_MATCH',
               'offset': '0x1c',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'CRC_MATCH_MASK': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0xa4',
                    'default': '0x00000000',
                    'name': 'CRC_MATCH_MASK',
                    'offset': '0xa4',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_EXPECTED': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x10',
                     'default': '0x00000000',
                     'name': 'CRC_RD_EXPECTED',
                     'offset': '0x10',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'CRC_RD_PER_CH0': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x60',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH0',
                    'offset': '0x60',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH1': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x64',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH1',
                    'offset': '0x64',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH2': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x68',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH2',
                    'offset': '0x68',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH3': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x6c',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH3',
                    'offset': '0x6c',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH4': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x70',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH4',
                    'offset': '0x70',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH5': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x74',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH5',
                    'offset': '0x74',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH6': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x78',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH6',
                    'offset': '0x78',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_RD_PER_CH7': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x7c',
                    'default': '0x00000000',
                    'name': 'CRC_RD_PER_CH7',
                    'offset': '0x7c',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_VALID_MASK': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0xa0',
                    'default': '0x00000000',
                    'name': 'CRC_VALID_MASK',
                    'offset': '0xa0',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_COMPUTED': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x18',
                     'default': '0x00000000',
                     'name': 'CRC_WR_COMPUTED',
                     'offset': '0x18',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'CRC_WR_EXPECTED': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x14',
                     'default': '0x00000000',
                     'name': 'CRC_WR_EXPECTED',
                     'offset': '0x14',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'CRC_WR_PER_CH0': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x80',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH0',
                    'offset': '0x80',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH1': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x84',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH1',
                    'offset': '0x84',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH2': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x88',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH2',
                    'offset': '0x88',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH3': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x8c',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH3',
                    'offset': '0x8c',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH4': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x90',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH4',
                    'offset': '0x90',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH5': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x94',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH5',
                    'offset': '0x94',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH6': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x98',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH6',
                    'offset': '0x98',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CRC_WR_PER_CH7': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x9c',
                    'default': '0x00000000',
                    'name': 'CRC_WR_PER_CH7',
                    'offset': '0x9c',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'CTRL': {'CAM_CLEAR': {'default': '0x0', 'offset': '4:4', 'sw': 'w', 'type': 'field'},
          'CLEAR_STATS': {'default': '0x0', 'offset': '1:1', 'sw': 'w', 'type': 'field'},
          'FREEZE_TRACE': {'default': '0x0', 'offset': '2:2', 'sw': 'rw', 'type': 'field'},
          'RSVD': {'default': '0x0', 'offset': '31:5', 'sw': 'r', 'type': 'field'},
          'SOFT_RESET': {'default': '0x0', 'offset': '3:3', 'sw': 'w', 'type': 'field'},
          'START': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
          'address': '0x0',
          'default': '0x00000000',
          'name': 'CTRL',
          'offset': '0x0',
          'size': 4,
          'sw': 'rw',
          'type': 'reg'},
 'DBG_OVERFLOW': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0xc',
                  'default': '0x00000000',
                  'name': 'DBG_OVERFLOW',
                  'offset': '0xc',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'DBG_WR_PTR': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0x8',
                'default': '0x00000000',
                'name': 'DBG_WR_PTR',
                'offset': '0x8',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'DESC_AR_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0xe0',
                'default': '0x00000000',
                'name': 'DESC_AR_HS',
                'offset': '0xe0',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'DESC_AR_STALL': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0xe4',
                   'default': '0x00000000',
                   'name': 'DESC_AR_STALL',
                   'offset': '0xe4',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'DESC_AW_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                'address': '0xf0',
                'default': '0x00000000',
                'name': 'DESC_AW_HS',
                'offset': '0xf0',
                'size': 4,
                'sw': 'r',
                'type': 'reg'},
 'DESC_B_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0xf8',
               'default': '0x00000000',
               'name': 'DESC_B_HS',
               'offset': '0xf8',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'DESC_R_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0xe8',
               'default': '0x00000000',
               'name': 'DESC_R_HS',
               'offset': '0xe8',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'DESC_R_STALL': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0xec',
                  'default': '0x00000000',
                  'name': 'DESC_R_STALL',
                  'offset': '0xec',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'DESC_SRAM_AR_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0xd4',
                     'default': '0x00000000',
                     'name': 'DESC_SRAM_AR_HS',
                     'offset': '0xd4',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'DESC_SRAM_R_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0xd8',
                    'default': '0x00000000',
                    'name': 'DESC_SRAM_R_HS',
                    'offset': '0xd8',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'DESC_VR_LIVE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0xfc',
                  'default': '0x00000000',
                  'name': 'DESC_VR_LIVE',
                  'offset': '0xfc',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'DESC_W_HS': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0xf4',
               'default': '0x00000000',
               'name': 'DESC_W_HS',
               'offset': '0xf4',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'KICK_GO': {'MASK': {'default': '0x0', 'offset': '7:0', 'sw': 'w', 'type': 'field'},
             'RSVD': {'default': '0x0', 'offset': '31:8', 'sw': 'r', 'type': 'field'},
             'address': '0xc0',
             'default': '0x00000000',
             'name': 'KICK_GO',
             'offset': '0xc0',
             'size': 4,
             'sw': 'rw',
             'type': 'reg'},
 'OBS_HIST_DATA': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                   'address': '0x124',
                   'default': '0x00000000',
                   'name': 'OBS_HIST_DATA',
                   'offset': '0x124',
                   'size': 4,
                   'sw': 'r',
                   'type': 'reg'},
 'OBS_HIST_SEL': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
                  'address': '0x120',
                  'default': '0x00000000',
                  'name': 'OBS_HIST_SEL',
                  'offset': '0x120',
                  'size': 4,
                  'sw': 'rw',
                  'type': 'reg'},
 'OBS_HIST_TOTAL': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                    'address': '0x128',
                    'default': '0x00000000',
                    'name': 'OBS_HIST_TOTAL',
                    'offset': '0x128',
                    'size': 4,
                    'sw': 'r',
                    'type': 'reg'},
 'OBS_RD_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0x104',
               'default': '0x00000000',
               'name': 'OBS_RD_BP',
               'offset': '0x104',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'OBS_RD_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x10c',
                 'default': '0x00000000',
                 'name': 'OBS_RD_IDLE',
                 'offset': '0x10c',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_RD_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x100',
                 'default': '0x00000000',
                 'name': 'OBS_RD_PROD',
                 'offset': '0x100',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_RD_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x108',
                  'default': '0x00000000',
                  'name': 'OBS_RD_STARV',
                  'offset': '0x108',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'OBS_WR_BP': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
               'address': '0x114',
               'default': '0x00000000',
               'name': 'OBS_WR_BP',
               'offset': '0x114',
               'size': 4,
               'sw': 'r',
               'type': 'reg'},
 'OBS_WR_IDLE': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x11c',
                 'default': '0x00000000',
                 'name': 'OBS_WR_IDLE',
                 'offset': '0x11c',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_WR_PROD': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                 'address': '0x110',
                 'default': '0x00000000',
                 'name': 'OBS_WR_PROD',
                 'offset': '0x110',
                 'size': 4,
                 'sw': 'r',
                 'type': 'reg'},
 'OBS_WR_STARV': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                  'address': '0x118',
                  'default': '0x00000000',
                  'name': 'OBS_WR_STARV',
                  'offset': '0x118',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'RESP_DELAY': {'RD_DELAY': {'default': '0x0', 'offset': '15:0', 'sw': 'rw', 'type': 'field'},
                'WR_DELAY': {'default': '0x0', 'offset': '31:16', 'sw': 'rw', 'type': 'field'},
                'address': '0x3c',
                'default': '0x00000000',
                'name': 'RESP_DELAY',
                'offset': '0x3c',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'SCRATCH': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'rw', 'type': 'field'},
             'address': '0x20',
             'default': '0x00000000',
             'name': 'SCRATCH',
             'offset': '0x20',
             'size': 4,
             'sw': 'rw',
             'type': 'reg'},
 'STATUS': {'ANY_ERROR': {'default': '0x0', 'offset': '1:1', 'sw': 'r', 'type': 'field'},
            'CLEAR_BUSY': {'default': '0x0', 'offset': '3:3', 'sw': 'r', 'type': 'field'},
            'RSVD': {'default': '0x0', 'offset': '31:4', 'sw': 'r', 'type': 'field'},
            'STREAM_IRQ': {'default': '0x0', 'offset': '0:0', 'sw': 'r', 'type': 'field'},
            'TRACE_OVERFLOW': {'default': '0x0', 'offset': '2:2', 'sw': 'r', 'type': 'field'},
            'address': '0x4',
            'default': '0x00000000',
            'name': 'STATUS',
            'offset': '0x4',
            'size': 4,
            'sw': 'r',
            'type': 'reg'},
 'TIMER_CTRL': {'CLEAR': {'default': '0x0', 'offset': '0:0', 'sw': 'w', 'type': 'field'},
                'RSVD': {'default': '0x0', 'offset': '31:1', 'sw': 'r', 'type': 'field'},
                'address': '0x28',
                'default': '0x00000000',
                'name': 'TIMER_CTRL',
                'offset': '0x28',
                'size': 4,
                'sw': 'rw',
                'type': 'reg'},
 'TIMER_CYCLES_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x34',
                     'default': '0x00000000',
                     'name': 'TIMER_CYCLES_HI',
                     'offset': '0x34',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'TIMER_CYCLES_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x30',
                     'default': '0x00000000',
                     'name': 'TIMER_CYCLES_LO',
                     'offset': '0x30',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'TIMER_EXPECTED_BEATS': {'VALUE': {'default': '0x0',
                                    'offset': '31:0',
                                    'sw': 'rw',
                                    'type': 'field'},
                          'address': '0x38',
                          'default': '0x00000000',
                          'name': 'TIMER_EXPECTED_BEATS',
                          'offset': '0x38',
                          'size': 4,
                          'sw': 'rw',
                          'type': 'reg'},
 'TIMER_R_FIRST_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x44',
                      'default': '0x00000000',
                      'name': 'TIMER_R_FIRST_HI',
                      'offset': '0x44',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'TIMER_R_FIRST_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x40',
                      'default': '0x00000000',
                      'name': 'TIMER_R_FIRST_LO',
                      'offset': '0x40',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'TIMER_R_LAST_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x4c',
                     'default': '0x00000000',
                     'name': 'TIMER_R_LAST_HI',
                     'offset': '0x4c',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'TIMER_R_LAST_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x48',
                     'default': '0x00000000',
                     'name': 'TIMER_R_LAST_LO',
                     'offset': '0x48',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'TIMER_STATUS': {'DONE': {'default': '0x0', 'offset': '0:0', 'sw': 'r', 'type': 'field'},
                  'PASS': {'default': '0x0', 'offset': '2:2', 'sw': 'r', 'type': 'field'},
                  'RSVD': {'default': '0x0', 'offset': '31:3', 'sw': 'r', 'type': 'field'},
                  'RUNNING': {'default': '0x0', 'offset': '1:1', 'sw': 'r', 'type': 'field'},
                  'address': '0x2c',
                  'default': '0x00000000',
                  'name': 'TIMER_STATUS',
                  'offset': '0x2c',
                  'size': 4,
                  'sw': 'r',
                  'type': 'reg'},
 'TIMER_W_FIRST_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x54',
                      'default': '0x00000000',
                      'name': 'TIMER_W_FIRST_HI',
                      'offset': '0x54',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'TIMER_W_FIRST_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                      'address': '0x50',
                      'default': '0x00000000',
                      'name': 'TIMER_W_FIRST_LO',
                      'offset': '0x50',
                      'size': 4,
                      'sw': 'r',
                      'type': 'reg'},
 'TIMER_W_LAST_HI': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x5c',
                     'default': '0x00000000',
                     'name': 'TIMER_W_LAST_HI',
                     'offset': '0x5c',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'},
 'TIMER_W_LAST_LO': {'VALUE': {'default': '0x0', 'offset': '31:0', 'sw': 'r', 'type': 'field'},
                     'address': '0x58',
                     'default': '0x00000000',
                     'name': 'TIMER_W_LAST_LO',
                     'offset': '0x58',
                     'size': 4,
                     'sw': 'r',
                     'type': 'reg'}}
