# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RTL Design Sherpa
email: rtldesignsherpa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Picture this: You stand at the threshold of an enigmatic realm—the world of FPGAs and digital design, a place brimming with endless possibilities yet concealed in an aura of intrigue. Navigating this captivating terrain can be challenging, but fear not, for I am your guide on this journey, a digital sherpa of the unknown.
  As we embark on this mysterious quest, I shall unveil a series of captivating activities designed to sharpen your skills. But there's more. I'll also introduce obscure tomes and unique Udemy classes to expand your knowledge—knowledge that, in my twilight wisdom, I may not have the time to fully explore.
  Prepare to traverse this intriguing path with tools as free as the spirits and scripts I've conjured from the depths of the digital abyss. Our journey will adhere to industry-standard practices as closely as practicality allows.
  Enter, if you dare, into the realm of FPGA and digital design—a place where the ordinary transforms into the extraordinary, and the boundaries of knowledge blur into obscurity.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rtldesignsherpa.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sean-galloway

# Build settings
#theme: minima
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
