// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop__Syms.h"
#include "Vtop___024root.h"

// Parameter definitions for Vtop___024root
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_FILTERING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_ML_FILTER;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ADD_PIPELINE_STAGE;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_CLOCK_GATING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_ADAPTIVE_CG;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_HISTOGRAMS;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__ENABLE_QOS_MON;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__ENABLE_FILTERING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__ADD_PIPELINE_STAGE;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__ENABLE_CLOCK_GATING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__CG_GATE_MONITOR;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__CG_GATE_REPORTER;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__CG_GATE_TIMERS;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__ENABLE_FILTERING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__ADD_PIPELINE_STAGE;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__IS_READ;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__IS_AXI;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ENABLE_PERF_PACKETS;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ENABLE_DEBUG_MODULE;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ENABLE_FILTERING;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ADD_PIPELINE_STAGE;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__IS_READ;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__IS_AXI;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__ENABLE_PERF_PACKETS;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timeout__DOT__IS_READ;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__IS_READ;
constexpr CData/*0:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__ENABLE_PERF_PACKETS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__SKID_DEPTH_AR;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__SKID_DEPTH_R;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AXI_USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AXI_WSTRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__PREFETCH_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__BURST_OPTIMIZE;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__PIPELINE_STAGES;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__QOS_LEVELS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__CG_IDLE_CYCLES;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__HISTOGRAM_BINS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__SW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__UW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__SKID_DEPTH_AR;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__SKID_DEPTH_R;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AXI_USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AXI_WSTRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__CG_IDLE_CYCLES;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__SW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__UW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__SKID_DEPTH_AR;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__SKID_DEPTH_R;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AXI_USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AXI_WSTRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__SW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__UW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__SKID_DEPTH_AR;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__SKID_DEPTH_R;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AXI_USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AXI_WSTRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__SW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__UW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ARSize;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__RSize;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__BUF_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__BW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__BUF_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__BW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ADDR_BITS_IN_PKT;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__IS_READ;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__IS_AXI;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ENABLE_PERF_PACKETS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ENABLE_DEBUG_MODULE;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__INTR_FIFO_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__DEBUG_FIFO_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__ADDR_BITS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__trans_mgr__DOT__IW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timer__DOT__timer_counter__DOT__COUNTER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timer__DOT__timer_counter__DOT__PRESCALER_MAX;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timer__DOT__timer_counter__DOT__prescaler_counter__DOT__MAX;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timeout__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__timeout__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__MAX_TRANSACTIONS;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__UNIT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__AGENT_ID;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__INTR_FIFO_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__REGISTERED;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__ALMOST_WR_MARGIN;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__ALMOST_RD_MARGIN;
constexpr VlWide<3>/*71:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__INSTANCE_NAME;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__D;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__write_pointer_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__write_pointer_inst__DOT__MAX;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__read_pointer_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__read_pointer_inst__DOT__MAX;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__ALMOST_WR_MARGIN;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__ALMOST_RD_MARGIN;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__REGISTERED;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__D;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__AFULL;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__AEMPTY;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__AFT;
constexpr IData/*31:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi_monitor_inst__DOT__u_axi_monitor_base__DOT__reporter__DOT__intr_fifo__DOT__fifo_control_inst__DOT__AET;
constexpr QData/*55:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__ar_channel__DOT__INSTANCE_NAME;
constexpr QData/*47:0*/ Vtop___024root::axi4_master_rd_hp_mon__DOT__hp_core_inst__DOT__axi4_master_rd_mon_inst__DOT__axi4_master_rd_inst__DOT__r_channel__DOT__INSTANCE_NAME;


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    if (false && first) {}  // Prevent unused
}

Vtop___024root::~Vtop___024root() {
}
