// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package rtc_regs_pkg;

    localparam RTC_REGS_DATA_WIDTH = 32;
    localparam RTC_REGS_MIN_ADDR_WIDTH = 6;
    localparam RTC_REGS_SIZE = 'h34;

    typedef struct {
        logic next;
    } rtc_regs__RTC_STATUS__alarm_flag__in_t;

    typedef struct {
        logic next;
    } rtc_regs__RTC_STATUS__second_tick__in_t;

    typedef struct {
        logic next;
    } rtc_regs__RTC_STATUS__time_valid__in_t;

    typedef struct {
        logic next;
    } rtc_regs__RTC_STATUS__pm_indicator__in_t;

    typedef struct {
        rtc_regs__RTC_STATUS__alarm_flag__in_t alarm_flag;
        rtc_regs__RTC_STATUS__second_tick__in_t second_tick;
        rtc_regs__RTC_STATUS__time_valid__in_t time_valid;
        rtc_regs__RTC_STATUS__pm_indicator__in_t pm_indicator;
    } rtc_regs__RTC_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_SECONDS__seconds__in_t;

    typedef struct {
        rtc_regs__RTC_SECONDS__seconds__in_t seconds;
    } rtc_regs__RTC_SECONDS__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_MINUTES__minutes__in_t;

    typedef struct {
        rtc_regs__RTC_MINUTES__minutes__in_t minutes;
    } rtc_regs__RTC_MINUTES__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_HOURS__hours__in_t;

    typedef struct {
        rtc_regs__RTC_HOURS__hours__in_t hours;
    } rtc_regs__RTC_HOURS__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_DAY__day__in_t;

    typedef struct {
        rtc_regs__RTC_DAY__day__in_t day;
    } rtc_regs__RTC_DAY__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_MONTH__month__in_t;

    typedef struct {
        rtc_regs__RTC_MONTH__month__in_t month;
    } rtc_regs__RTC_MONTH__in_t;

    typedef struct {
        logic [7:0] next;
    } rtc_regs__RTC_YEAR__year__in_t;

    typedef struct {
        rtc_regs__RTC_YEAR__year__in_t year;
    } rtc_regs__RTC_YEAR__in_t;

    typedef struct {
        rtc_regs__RTC_STATUS__in_t RTC_STATUS;
        rtc_regs__RTC_SECONDS__in_t RTC_SECONDS;
        rtc_regs__RTC_MINUTES__in_t RTC_MINUTES;
        rtc_regs__RTC_HOURS__in_t RTC_HOURS;
        rtc_regs__RTC_DAY__in_t RTC_DAY;
        rtc_regs__RTC_MONTH__in_t RTC_MONTH;
        rtc_regs__RTC_YEAR__in_t RTC_YEAR;
    } rtc_regs__in_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONFIG__rtc_enable__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONFIG__hour_mode_12__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONFIG__bcd_mode__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONFIG__clock_select__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONFIG__time_set_mode__out_t;

    typedef struct {
        rtc_regs__RTC_CONFIG__rtc_enable__out_t rtc_enable;
        rtc_regs__RTC_CONFIG__hour_mode_12__out_t hour_mode_12;
        rtc_regs__RTC_CONFIG__bcd_mode__out_t bcd_mode;
        rtc_regs__RTC_CONFIG__clock_select__out_t clock_select;
        rtc_regs__RTC_CONFIG__time_set_mode__out_t time_set_mode;
    } rtc_regs__RTC_CONFIG__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONTROL__alarm_enable__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONTROL__alarm_int_enable__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_CONTROL__second_int_enable__out_t;

    typedef struct {
        rtc_regs__RTC_CONTROL__alarm_enable__out_t alarm_enable;
        rtc_regs__RTC_CONTROL__alarm_int_enable__out_t alarm_int_enable;
        rtc_regs__RTC_CONTROL__second_int_enable__out_t second_int_enable;
    } rtc_regs__RTC_CONTROL__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_SECONDS__seconds__out_t;

    typedef struct {
        rtc_regs__RTC_SECONDS__seconds__out_t seconds;
    } rtc_regs__RTC_SECONDS__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_MINUTES__minutes__out_t;

    typedef struct {
        rtc_regs__RTC_MINUTES__minutes__out_t minutes;
    } rtc_regs__RTC_MINUTES__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_HOURS__hours__out_t;

    typedef struct {
        rtc_regs__RTC_HOURS__hours__out_t hours;
    } rtc_regs__RTC_HOURS__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_DAY__day__out_t;

    typedef struct {
        rtc_regs__RTC_DAY__day__out_t day;
    } rtc_regs__RTC_DAY__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_MONTH__month__out_t;

    typedef struct {
        rtc_regs__RTC_MONTH__month__out_t month;
    } rtc_regs__RTC_MONTH__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_YEAR__year__out_t;

    typedef struct {
        rtc_regs__RTC_YEAR__year__out_t year;
    } rtc_regs__RTC_YEAR__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_ALARM_SEC__alarm_seconds__out_t;

    typedef struct {
        rtc_regs__RTC_ALARM_SEC__alarm_seconds__out_t alarm_seconds;
    } rtc_regs__RTC_ALARM_SEC__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_ALARM_MIN__alarm_minutes__out_t;

    typedef struct {
        rtc_regs__RTC_ALARM_MIN__alarm_minutes__out_t alarm_minutes;
    } rtc_regs__RTC_ALARM_MIN__out_t;

    typedef struct {
        logic [7:0] value;
    } rtc_regs__RTC_ALARM_HOUR__alarm_hours__out_t;

    typedef struct {
        rtc_regs__RTC_ALARM_HOUR__alarm_hours__out_t alarm_hours;
    } rtc_regs__RTC_ALARM_HOUR__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_ALARM_MASK__sec_match_en__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_ALARM_MASK__min_match_en__out_t;

    typedef struct {
        logic value;
    } rtc_regs__RTC_ALARM_MASK__hour_match_en__out_t;

    typedef struct {
        rtc_regs__RTC_ALARM_MASK__sec_match_en__out_t sec_match_en;
        rtc_regs__RTC_ALARM_MASK__min_match_en__out_t min_match_en;
        rtc_regs__RTC_ALARM_MASK__hour_match_en__out_t hour_match_en;
    } rtc_regs__RTC_ALARM_MASK__out_t;

    typedef struct {
        rtc_regs__RTC_CONFIG__out_t RTC_CONFIG;
        rtc_regs__RTC_CONTROL__out_t RTC_CONTROL;
        rtc_regs__RTC_SECONDS__out_t RTC_SECONDS;
        rtc_regs__RTC_MINUTES__out_t RTC_MINUTES;
        rtc_regs__RTC_HOURS__out_t RTC_HOURS;
        rtc_regs__RTC_DAY__out_t RTC_DAY;
        rtc_regs__RTC_MONTH__out_t RTC_MONTH;
        rtc_regs__RTC_YEAR__out_t RTC_YEAR;
        rtc_regs__RTC_ALARM_SEC__out_t RTC_ALARM_SEC;
        rtc_regs__RTC_ALARM_MIN__out_t RTC_ALARM_MIN;
        rtc_regs__RTC_ALARM_HOUR__out_t RTC_ALARM_HOUR;
        rtc_regs__RTC_ALARM_MASK__out_t RTC_ALARM_MASK;
    } rtc_regs__out_t;
endpackage
