#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2025 sean galloway
#
# Test file for bridge_stream_mon_axil
# Generated by bridge test generator from CSV configuration
#
# Configuration:
#   Masters: 4 (host, stream_desc, monbus_wr, slave_monbus_wr)
#   Slaves:  12 (obs_apb, slvmon_apb, stream_apb, harness_csr, desc_ram, stream_err, stream_tally, dma_axil, slave_err, slave_tally, stream_tally_cfg, slave_tally_cfg)
#   Channels: RW

import os
import sys
import pytest
import logging

# Import framework utilities (PYTHONPATH includes bin/)
from TBClasses.shared.utilities import get_repo_root

# Add repo root to Python path using robust git-based method
repo_root = get_repo_root()
sys.path.insert(0, repo_root)

import cocotb
from cocotb.triggers import RisingEdge, ClockCycles
from cocotb_test.simulator import run
from TBClasses.shared.utilities import get_paths, get_wave_config
from TBClasses.shared.filelist_utils import get_sources_from_filelist

# Import generated testbench class
from projects.fpga-systems.Genesys2.stream.rtl.bridges.dv.tbclasses.bridge_stream_mon_axil_tb import BridgeStreamMonAxilTB


# ============================================================================
# CocoTB Test Functions
# ============================================================================
#
# Each cocotb test function is named with the rtl_module_name baked in
# (cocotb_test_<module>_<phase>) so that when pytest collects the full
# bridge suite — every test_bridge_*.py imported into the same Python
# process — no two files share a cocotb-registered test name. Sharing
# names causes cross-test state pollution (one config's cocotb.test
# registration overwrites another's, and tests that pass in isolation
# fail in the full regression). Stream's per-module naming was the
# reference.

@cocotb.test(timeout_time=200, timeout_unit="ms")
async def cocotb_test_bridge_stream_mon_axil_basic_connectivity(dut):
    """
    Basic connectivity — every (master, slave) pair gets one write and/or
    one read at a non-base offset inside the slave's window. Reads check
    against the pre-seeded slave memory pattern; writes verify the bytes
    landed in the slave's memory at the expected offset.

    The slave BFMs auto-respond from their MemoryModel honoring whatever
    ARSIZE/ARLEN/ARADDR (or AWSIZE/AWLEN/AWADDR) the bridge forwards, so
    the same test body works across direct, width-converted, and
    AXIL-shimmed paths — the bridge moves bytes, we read the bytes back.
    """
    tb = BridgeStreamMonAxilTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting basic connectivity test")
    tb.log.info(f"Configuration: 4M x 12S, RW channels")
    tb.log.info("=" * 80)

    # ---- Write connectivity --------------------------------------------
    tb.log.info(f"Master 0 (host) — writes")
    # Master 0 → Slave 0 (obs_apb)
    test_addr = 0x00190100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 0)
    tb.log.info(f"  W slave=0 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(0, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 0 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 1 (slvmon_apb)
    test_addr = 0x00180100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 1)
    tb.log.info(f"  W slave=1 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(1, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 1 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 2 (stream_apb)
    test_addr = 0x00000100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 2)
    tb.log.info(f"  W slave=2 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(2, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 2 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 3 (harness_csr)
    test_addr = 0x00010100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 3)
    tb.log.info(f"  W slave=3 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(3, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 3 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 4 (desc_ram)
    test_addr = 0x00020100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 4)
    tb.log.info(f"  W slave=4 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(4, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 4 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 5 (stream_err)
    test_addr = 0x00030100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 5)
    tb.log.info(f"  W slave=5 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(5, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 5 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 6 (stream_tally)
    test_addr = 0x00040100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 6)
    tb.log.info(f"  W slave=6 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(6, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 6 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 7 (dma_axil)
    test_addr = 0x00080100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 7)
    tb.log.info(f"  W slave=7 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(7, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 7 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 8 (slave_err)
    test_addr = 0x00090100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 8)
    tb.log.info(f"  W slave=8 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(8, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 8 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 9 (slave_tally)
    test_addr = 0x000c0100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 9)
    tb.log.info(f"  W slave=9 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(9, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 9 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 10 (stream_tally_cfg)
    test_addr = 0x00100100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 10)
    tb.log.info(f"  W slave=10 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(10, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 10 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    # Master 0 → Slave 11 (slave_tally_cfg)
    test_addr = 0x00140100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (0 << 12) | 11)
    tb.log.info(f"  W slave=11 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(0, test_addr, test_data)
    # Read back at master 0's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(11, test_addr, master_idx=0)
    assert actual == test_data, (
        f"Slave 11 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    tb.log.info(f"Master 1 (stream_desc) — writes")
    # Master 1 → Slave 4 (desc_ram)
    test_addr = 0x00020100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (1 << 12) | 4)
    tb.log.info(f"  W slave=4 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(1, test_addr, test_data)
    # Read back at master 1's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(4, test_addr, master_idx=1)
    assert actual == test_data, (
        f"Slave 4 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    tb.log.info(f"Master 2 (monbus_wr) — writes")
    # Master 2 → Slave 6 (stream_tally)
    test_addr = 0x00040100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (2 << 12) | 6)
    tb.log.info(f"  W slave=6 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(2, test_addr, test_data)
    # Read back at master 2's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(6, test_addr, master_idx=2)
    assert actual == test_data, (
        f"Slave 6 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")
    tb.log.info(f"Master 3 (slave_monbus_wr) — writes")
    # Master 3 → Slave 9 (slave_tally)
    test_addr = 0x000c0100
    # Non-pattern data: upper byte 0xDE so it can't be confused with any
    # slave's seed pattern (which uses 0x01..0xFF in the upper byte for
    # the slave ID). Lower byte tags the (master, slave) pair for debug.
    test_data = (0xDE000000 | (3 << 12) | 9)
    tb.log.info(f"  W slave=9 addr=0x{test_addr:08x} data=0x{test_data:08x}")
    await tb.master_write(3, test_addr, test_data)
    # Read back at master 3's width — only the bytes the master
    # actually wrote should be compared; trailing bytes are still the seed.
    actual = tb.slave_mem_read(9, test_addr, master_idx=3)
    assert actual == test_data, (
        f"Slave 9 memory mismatch at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{test_data:08x}")

    # ---- Read connectivity ---------------------------------------------
    tb.log.info(f"Master 0 (host) — reads")
    # Master 0 → Slave 0 (obs_apb)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00190100
    expected = tb.slave_mem_read(0, test_addr, master_idx=0)
    tb.log.info(f"  R slave=0 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 0 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 1 (slvmon_apb)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00180100
    expected = tb.slave_mem_read(1, test_addr, master_idx=0)
    tb.log.info(f"  R slave=1 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 1 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 2 (stream_apb)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00000100
    expected = tb.slave_mem_read(2, test_addr, master_idx=0)
    tb.log.info(f"  R slave=2 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 2 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 3 (harness_csr)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00010100
    expected = tb.slave_mem_read(3, test_addr, master_idx=0)
    tb.log.info(f"  R slave=3 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 3 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 4 (desc_ram)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00020100
    expected = tb.slave_mem_read(4, test_addr, master_idx=0)
    tb.log.info(f"  R slave=4 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 4 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 5 (stream_err)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00030100
    expected = tb.slave_mem_read(5, test_addr, master_idx=0)
    tb.log.info(f"  R slave=5 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 5 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 6 (stream_tally)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00040100
    expected = tb.slave_mem_read(6, test_addr, master_idx=0)
    tb.log.info(f"  R slave=6 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 6 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 7 (dma_axil)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00080100
    expected = tb.slave_mem_read(7, test_addr, master_idx=0)
    tb.log.info(f"  R slave=7 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 7 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 8 (slave_err)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00090100
    expected = tb.slave_mem_read(8, test_addr, master_idx=0)
    tb.log.info(f"  R slave=8 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 8 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 9 (slave_tally)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x000c0100
    expected = tb.slave_mem_read(9, test_addr, master_idx=0)
    tb.log.info(f"  R slave=9 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 9 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 10 (stream_tally_cfg)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00100100
    expected = tb.slave_mem_read(10, test_addr, master_idx=0)
    tb.log.info(f"  R slave=10 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 10 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    # Master 0 → Slave 11 (slave_tally_cfg)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00140100
    expected = tb.slave_mem_read(11, test_addr, master_idx=0)
    tb.log.info(f"  R slave=11 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(0, test_addr)
    assert actual == expected, (
        f"Read mismatch master 0 ← slave 11 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    tb.log.info(f"Master 1 (stream_desc) — reads")
    # Master 1 → Slave 4 (desc_ram)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00020100
    expected = tb.slave_mem_read(4, test_addr, master_idx=1)
    tb.log.info(f"  R slave=4 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(1, test_addr)
    assert actual == expected, (
        f"Read mismatch master 1 ← slave 4 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    tb.log.info(f"Master 2 (monbus_wr) — reads")
    # Master 2 → Slave 6 (stream_tally)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x00040100
    expected = tb.slave_mem_read(6, test_addr, master_idx=2)
    tb.log.info(f"  R slave=6 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(2, test_addr)
    assert actual == expected, (
        f"Read mismatch master 2 ← slave 6 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")
    tb.log.info(f"Master 3 (slave_monbus_wr) — reads")
    # Master 3 → Slave 9 (slave_tally)
    # Probe a non-base offset; addr_range is 4 KB-aligned by validator so
    # +0x100 is always safely inside the slave's window.
    test_addr = 0x000c0100
    expected = tb.slave_mem_read(9, test_addr, master_idx=3)
    tb.log.info(f"  R slave=9 addr=0x{test_addr:08x} expect=0x{expected:08x}")
    actual = await tb.master_read(3, test_addr)
    assert actual == expected, (
        f"Read mismatch master 3 ← slave 9 at 0x{test_addr:08x}: "
        f"got 0x{actual:08x}, expected 0x{expected:08x} (seeded pattern)")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Basic connectivity test PASSED")
    tb.log.info("=" * 80)


@cocotb.test(timeout_time=500, timeout_unit="ms")
async def cocotb_test_bridge_stream_mon_axil_boundary_probe(dut):
    """
    Boundary probe — for each (master, slave) pair, probe three offsets
    per page (bottom / middle / top of the page) back-to-back, at either
    the boundary pages of the slave window (default) or every page
    (BRIDGE_BOUNDARY_PROBE_MODE=all).

    NB: previously named "address_decode". The failure modes it surfaces
    are not in the address decoder (which is per-bridge generated inline
    in <master>_adapter.sv and is fine across all configs); they're in
    the downstream protocol shims — axi4_to_axil4_{wr,rd}, axi4_to_apb
    — stressed by the b2b page probes that the simpler basic_connectivity
    test never reaches.

    Routing IS the data round-trip: a misroute lands the write at a
    different slave or different offset and the seed pattern shows
    through instead of the tagged write data. Data verification is
    skipped for probes past the SLAVE_MEM_CAP_BYTES seeded region —
    the slave BFM silently drops OOR writes and fakes reads with
    data=addr, so OOR probes still exercise the decoder pathway but
    can't be data-checked. If/when we want explicit AW/AR routing
    monitors, wire them up at the bridge slave ports separately.

    Set BRIDGE_BOUNDARY_PROBE_MODE=all in the environment to walk every
    page instead of bottom/mid/top — useful for small-window slaves
    under regression, exhausting for GB-class DDR.
    """
    tb = BridgeStreamMonAxilTB(dut)
    await tb.setup_clocks_and_reset()

    mode = os.environ.get('BRIDGE_BOUNDARY_PROBE_MODE', 'boundary').lower()
    if mode not in ('boundary', 'all'):
        tb.log.warning(f"Unknown BRIDGE_BOUNDARY_PROBE_MODE={mode!r}, falling back to 'boundary'")
        mode = 'boundary'

    tb.log.info("=" * 80)
    tb.log.info(f"Starting boundary probe test (mode={mode})")
    tb.log.info("=" * 80)

    tb.log.info(f"Master 0 (host)")
    # Slave 0 (obs_apb): 0x00190000-0x00190fff
    pages_0_0 = tb.slave_probe_pages(0, mode=mode)
    in_page_0_0 = tb.page_probe_offsets(0, master_idx=0)
    tb.log.info(f"  slave 0: {len(pages_0_0)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_0):
        for probe_idx, probe_off in enumerate(in_page_0_0):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (0 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(0, addr):
                got = tb.slave_mem_read(0, addr, master_idx=0)
                assert got == d, (
                    f"M0→S0 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 1 (slvmon_apb): 0x00180000-0x00180fff
    pages_0_1 = tb.slave_probe_pages(1, mode=mode)
    in_page_0_1 = tb.page_probe_offsets(1, master_idx=0)
    tb.log.info(f"  slave 1: {len(pages_0_1)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_1):
        for probe_idx, probe_off in enumerate(in_page_0_1):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (1 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(1, addr):
                got = tb.slave_mem_read(1, addr, master_idx=0)
                assert got == d, (
                    f"M0→S1 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 2 (stream_apb): 0x00000000-0x00001fff
    pages_0_2 = tb.slave_probe_pages(2, mode=mode)
    in_page_0_2 = tb.page_probe_offsets(2, master_idx=0)
    tb.log.info(f"  slave 2: {len(pages_0_2)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_2):
        for probe_idx, probe_off in enumerate(in_page_0_2):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (2 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(2, addr):
                got = tb.slave_mem_read(2, addr, master_idx=0)
                assert got == d, (
                    f"M0→S2 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 3 (harness_csr): 0x00010000-0x00010fff
    pages_0_3 = tb.slave_probe_pages(3, mode=mode)
    in_page_0_3 = tb.page_probe_offsets(3, master_idx=0)
    tb.log.info(f"  slave 3: {len(pages_0_3)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_3):
        for probe_idx, probe_off in enumerate(in_page_0_3):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (3 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(3, addr):
                got = tb.slave_mem_read(3, addr, master_idx=0)
                assert got == d, (
                    f"M0→S3 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 4 (desc_ram): 0x00020000-0x0002ffff
    pages_0_4 = tb.slave_probe_pages(4, mode=mode)
    in_page_0_4 = tb.page_probe_offsets(4, master_idx=0)
    tb.log.info(f"  slave 4: {len(pages_0_4)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_4):
        for probe_idx, probe_off in enumerate(in_page_0_4):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (4 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(4, addr):
                got = tb.slave_mem_read(4, addr, master_idx=0)
                assert got == d, (
                    f"M0→S4 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 5 (stream_err): 0x00030000-0x00030fff
    pages_0_5 = tb.slave_probe_pages(5, mode=mode)
    in_page_0_5 = tb.page_probe_offsets(5, master_idx=0)
    tb.log.info(f"  slave 5: {len(pages_0_5)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_5):
        for probe_idx, probe_off in enumerate(in_page_0_5):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (5 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(5, addr):
                got = tb.slave_mem_read(5, addr, master_idx=0)
                assert got == d, (
                    f"M0→S5 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 6 (stream_tally): 0x00040000-0x0007ffff
    pages_0_6 = tb.slave_probe_pages(6, mode=mode)
    in_page_0_6 = tb.page_probe_offsets(6, master_idx=0)
    tb.log.info(f"  slave 6: {len(pages_0_6)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_6):
        for probe_idx, probe_off in enumerate(in_page_0_6):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (6 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(6, addr):
                got = tb.slave_mem_read(6, addr, master_idx=0)
                assert got == d, (
                    f"M0→S6 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 7 (dma_axil): 0x00080000-0x00080fff
    pages_0_7 = tb.slave_probe_pages(7, mode=mode)
    in_page_0_7 = tb.page_probe_offsets(7, master_idx=0)
    tb.log.info(f"  slave 7: {len(pages_0_7)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_7):
        for probe_idx, probe_off in enumerate(in_page_0_7):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (7 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(7, addr):
                got = tb.slave_mem_read(7, addr, master_idx=0)
                assert got == d, (
                    f"M0→S7 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 8 (slave_err): 0x00090000-0x00090fff
    pages_0_8 = tb.slave_probe_pages(8, mode=mode)
    in_page_0_8 = tb.page_probe_offsets(8, master_idx=0)
    tb.log.info(f"  slave 8: {len(pages_0_8)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_8):
        for probe_idx, probe_off in enumerate(in_page_0_8):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (8 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(8, addr):
                got = tb.slave_mem_read(8, addr, master_idx=0)
                assert got == d, (
                    f"M0→S8 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 9 (slave_tally): 0x000c0000-0x000fffff
    pages_0_9 = tb.slave_probe_pages(9, mode=mode)
    in_page_0_9 = tb.page_probe_offsets(9, master_idx=0)
    tb.log.info(f"  slave 9: {len(pages_0_9)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_9):
        for probe_idx, probe_off in enumerate(in_page_0_9):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (9 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(9, addr):
                got = tb.slave_mem_read(9, addr, master_idx=0)
                assert got == d, (
                    f"M0→S9 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 10 (stream_tally_cfg): 0x00100000-0x0013ffff
    pages_0_10 = tb.slave_probe_pages(10, mode=mode)
    in_page_0_10 = tb.page_probe_offsets(10, master_idx=0)
    tb.log.info(f"  slave 10: {len(pages_0_10)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_10):
        for probe_idx, probe_off in enumerate(in_page_0_10):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (10 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(10, addr):
                got = tb.slave_mem_read(10, addr, master_idx=0)
                assert got == d, (
                    f"M0→S10 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    # Slave 11 (slave_tally_cfg): 0x00140000-0x0017ffff
    pages_0_11 = tb.slave_probe_pages(11, mode=mode)
    in_page_0_11 = tb.page_probe_offsets(11, master_idx=0)
    tb.log.info(f"  slave 11: {len(pages_0_11)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_0_11):
        for probe_idx, probe_off in enumerate(in_page_0_11):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (0 << 20) | (11 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(0, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(11, addr):
                got = tb.slave_mem_read(11, addr, master_idx=0)
                assert got == d, (
                    f"M0→S11 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    tb.log.info(f"Master 1 (stream_desc)")
    # Slave 4 (desc_ram): 0x00020000-0x0002ffff
    pages_1_4 = tb.slave_probe_pages(4, mode=mode)
    in_page_1_4 = tb.page_probe_offsets(4, master_idx=1)
    tb.log.info(f"  slave 4: {len(pages_1_4)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_1_4):
        for probe_idx, probe_off in enumerate(in_page_1_4):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (1 << 20) | (4 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(1, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(4, addr):
                got = tb.slave_mem_read(4, addr, master_idx=1)
                assert got == d, (
                    f"M1→S4 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    tb.log.info(f"Master 2 (monbus_wr)")
    # Slave 6 (stream_tally): 0x00040000-0x0007ffff
    pages_2_6 = tb.slave_probe_pages(6, mode=mode)
    in_page_2_6 = tb.page_probe_offsets(6, master_idx=2)
    tb.log.info(f"  slave 6: {len(pages_2_6)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_2_6):
        for probe_idx, probe_off in enumerate(in_page_2_6):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (2 << 20) | (6 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(2, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(6, addr):
                got = tb.slave_mem_read(6, addr, master_idx=2)
                assert got == d, (
                    f"M2→S6 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")
    tb.log.info(f"Master 3 (slave_monbus_wr)")
    # Slave 9 (slave_tally): 0x000c0000-0x000fffff
    pages_3_9 = tb.slave_probe_pages(9, mode=mode)
    in_page_3_9 = tb.page_probe_offsets(9, master_idx=3)
    tb.log.info(f"  slave 9: {len(pages_3_9)} pages x 3 probes/page")
    for page_idx, page_base in enumerate(pages_3_9):
        for probe_idx, probe_off in enumerate(in_page_3_9):
            addr = page_base + probe_off
            # Tag data with (master, slave, page_idx, probe_idx) — every
            # probe within an (M,S) pair gets a unique 16-bit ID so a
            # misroute (write lands at wrong slave / wrong offset) is
            # visible at a glance in the failure message.
            d = (0xDE000000 | (3 << 20) | (9 << 16)
                 | ((page_idx & 0xFFF) << 4) | (probe_idx & 0xF))
            await tb.master_write(3, addr, d)
            # Data round-trip IS the routing check: a misrouted write
            # lands at a different slave (or different offset) and the
            # seed pattern shows through instead of d. Skip the check
            # for non-seeded probes (write still exercises the decode
            # path, framework just drops OOR memory writes silently).
            if tb.is_seeded(9, addr):
                got = tb.slave_mem_read(9, addr, master_idx=3)
                assert got == d, (
                    f"M3→S9 data mismatch at "
                    f"0x{addr:08x} (page=0x{page_base:08x}, off=0x{probe_off:x}): "
                    f"got 0x{got:08x}, expected 0x{d:08x}")

    await ClockCycles(tb.clock, 20)
    tb.log.info("=" * 80)
    tb.log.info("Boundary probe test PASSED")
    tb.log.info("=" * 80)
@cocotb.test(timeout_time=1000, timeout_unit="ms")
async def cocotb_test_bridge_stream_mon_axil_arbitration(dut):
    """
    Multi-master arbitration test

    Test plan:
    1. Multiple masters simultaneously request same slave
    2. Verify round-robin arbitration grants access
    3. Verify non-winning masters are backpressured
    4. Verify transactions complete correctly
    """
    tb = BridgeStreamMonAxilTB(dut)
    await tb.setup_clocks_and_reset()

    tb.log.info("=" * 80)
    tb.log.info("Starting arbitration test")
    tb.log.info("=" * 80)

    # TODO: Implement concurrent transaction test
    # This requires cocotb.start_soon() for parallel master activity

    await ClockCycles(tb.clock, 100)
    tb.log.info("Arbitration test PASSED")

# ============================================================================
# Pytest Wrapper Functions (collected by pytest, call specific cocotb_test_*)
# ============================================================================

def test_bridge_stream_mon_axil_basic_connectivity(request):
    """Pytest wrapper for basic connectivity test"""

    # Get standard paths
    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_stream_mon_axil"

    # Get sources from filelist
    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/fpga-systems/Genesys2/stream/rtl/bridges/filelists/bridge_stream_mon_axil.f'
    )

    # Per-test naming follows the q32 canonical pattern
    # (design_dv/q32/tests/macro/test_q32_*.py): test_<dut>_<testcase>
    # plus an optional pytest-xdist worker suffix when running in parallel.
    # `test_name_plus_params` drives EVERY artifact path (log, xml, sim_build,
    # dump.fst) so each parameterised test invocation gets its own
    # directory and outputs.
    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_basic_connectivity"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # Waveforms via the canonical helper in TBClasses.shared.utilities.
    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_stream_mon_axil_basic_connectivity",
        sim_build=sim_build,
        waves=False,            # cocotb-test compile flags handled via extra_args
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )


def test_bridge_stream_mon_axil_boundary_probe(request):
    """Pytest wrapper for boundary probe test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_stream_mon_axil"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/fpga-systems/Genesys2/stream/rtl/bridges/filelists/bridge_stream_mon_axil.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_boundary_probe"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_stream_mon_axil_boundary_probe",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )
def test_bridge_stream_mon_axil_arbitration(request):
    """Pytest wrapper for arbitration test"""

    module, repo_root, tests_dir, log_dir, rtl_dict = get_paths({
        'rtl_bridge': '../../../../rtl/bridge',
        'rtl_common': '../../../../rtl/common',
        'rtl_amba': '../../../../rtl/amba'
    })

    dut_name = "bridge_stream_mon_axil"

    verilog_sources, includes = get_sources_from_filelist(
        repo_root=repo_root,
        filelist_path='projects/fpga-systems/Genesys2/stream/rtl/bridges/filelists/bridge_stream_mon_axil.f'
    )

    worker_id = os.environ.get('PYTEST_XDIST_WORKER', '')
    worker_suffix = f"_{worker_id}" if worker_id else ""
    test_name_plus_params = f"test_{dut_name}_arbitration"
    sim_build_name = f"{test_name_plus_params}{worker_suffix}"

    log_path = os.path.join(log_dir, f'{sim_build_name}.log')
    results_path = os.path.join(log_dir, f'results_{sim_build_name}.xml')
    sim_build = os.path.join(tests_dir, 'local_sim_build', sim_build_name)
    os.makedirs(sim_build, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    waves = get_wave_config(sim_build)

    extra_args = ['--assert', '--coverage'] + waves['extra_args']
    extra_env = {
        'COCOTB_LOG_LEVEL': 'INFO',
        'LOG_PATH': log_path,
        'COCOTB_RESULTS_FILE': results_path,
        **waves['extra_env'],
    }

    run(
        python_search=[tests_dir],
        verilog_sources=verilog_sources,
        includes=includes,
        toplevel=dut_name,
        module=module,
        testcase="cocotb_test_bridge_stream_mon_axil_arbitration",
        sim_build=sim_build,
        waves=False,
        extra_args=extra_args,
        plus_args=waves['sim_args'],
        extra_env=extra_env
    )

if __name__ == "__main__":
    # Run pytest on this file
    pytest.main([__file__, '-v', '-s'])