#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2026 sean galloway
#
# Comprehensive monitor stress test for bridge_stream_mon_axil_mon.
# Generated by bridge test generator (generate_monitor_tests) -- DO NOT EDIT.
#
# Targets the _mon bridge top directly (no smoke wrapper): cfg + monbus
# backpressure are driven at runtime via cocotb. Reuses the generated TB class
# (AXI4 geometry) and the shared MonbusGroupHarness. Sequences
# traffic / WRITE_BP / ERR_BP(compl) / ERR_BP(slverr) stress phases in one
# build, reconfiguring monitor cfg between phases.

import os
import sys

from TBClasses.shared.utilities import get_repo_root

repo_root = get_repo_root()
sys.path.insert(0, repo_root)
_REPO_ROOT_FOR_SHARED = repo_root

import cocotb
from cocotb_test.simulator import run  # noqa: F401

from TBClasses.shared.utilities import get_paths
# Import the testbench class. NOT as a dotted package path: the area
# lives under projects/fpga-systems/, and 'fpga-systems' contains a
# hyphen, which is not a legal Python identifier -- 'from
# projects.fpga-systems....' is a SyntaxError, so these five test files
# could not even be collected. Put the tbclasses dir on sys.path and
# import the module by its own name instead.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, 'tbclasses'))
from bridge_stream_mon_axil_mon_tb import BridgeStreamMonAxilMonTB  # noqa: E402
# monitor_stress_common is shared collateral that lives with the bridge
# component, not in this area. Put its directory on sys.path rather than
# copying the module (a second copy is how the two drift apart).
sys.path.insert(0, os.path.join(_REPO_ROOT_FOR_SHARED, 'projects/components/bridge/dv/tests'))
from monitor_stress_common import run_comprehensive, run_monitor_sim  # noqa: E402
# The area's bin/ must be on sys.path HERE, not only via conftest: cocotb
# re-imports this module inside the SIMULATOR process, where pytest's
# conftest never runs and python_search only supplies tests_dir.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, os.pardir, os.pardir, os.pardir, 'bin'))
import stream_levels  # noqa: E402


CFG_PREFIXES = ['host_0_rd', 'host_0_wr', 'stream_desc_1_rd', 'monbus_wr_2_wr', 'obs_apb_0_rd', 'obs_apb_0_wr', 'slvmon_apb_1_rd', 'slvmon_apb_1_wr', 'stream_apb_2_rd', 'stream_apb_2_wr', 'harness_csr_3_rd', 'harness_csr_3_wr', 'desc_ram_4_rd', 'desc_ram_4_wr', 'stream_err_5_rd', 'stream_err_5_wr', 'stream_tally_6_rd', 'stream_tally_6_wr', 'dma_axil_7_rd', 'dma_axil_7_wr', 'slave_err_8_rd', 'slave_err_8_wr', 'slave_tally_9_rd', 'slave_tally_9_wr', 'comp_sram_10_rd', 'comp_sram_10_wr', 'stream_tally_cfg_11_rd', 'stream_tally_cfg_11_wr', 'slave_tally_cfg_12_rd', 'slave_tally_cfg_12_wr']
BLOCK_READY_PATH = "u_host_adapter.u_timing_wrapper_rd"
REACHABLE_SLAVES = [4]
HAS_COMPL = True
IS_REGBLOCK = False


@cocotb.test(timeout_time=600, timeout_unit="ms")
async def cocotb_test_bridge_stream_mon_axil_mon_monitor(dut):
    tb = BridgeStreamMonAxilMonTB(dut)
    await tb.setup_clocks_and_reset()
    await run_comprehensive(
        dut, tb,
        cfg_prefixes=CFG_PREFIXES,
        block_ready_path=BLOCK_READY_PATH,
        reachable_slaves=REACHABLE_SLAVES,
        has_compl=HAS_COMPL,
        is_regblock=IS_REGBLOCK,
        # gate/func/full. stress_count() -- the helper's own default -- is 256
        # at both gate and func and only rises at FULL, so a smoke run paid the
        # full 256-read stress. Pass n explicitly instead of changing
        # stress_count(), which is shared bridge-component collateral with
        # other callers.
        n=stream_levels.scale(32, 256, 512),
    )


def test_bridge_stream_mon_axil_mon_monitor(request):
    module, repo_root_, tests_dir, log_dir, _ = get_paths({
        'rtl_amba': '../../../../rtl/amba',
    })
    run_monitor_sim(
        module=module, repo_root=repo_root_, tests_dir=tests_dir, log_dir=log_dir,
        dut_name="bridge_stream_mon_axil_mon",
        testcase="cocotb_test_bridge_stream_mon_axil_mon_monitor",
        filelist='projects/fpga-systems/Genesys2/stream/rtl/bridges/filelists/bridge_stream_mon_axil_mon.f',
        # The generated PeakRDL CSR (*_mon_cfg.sv) drives one 'field_combo'
        # struct from many always_comb blocks, each writing a DIFFERENT
        # member. Verilator's MULTIDRIVEN fires on the aggregate, so these
        # are false positives -- and there are enough of them to trip the
        # warning-count limit and fail the COMPILE, not the assertions.
        extra_no_warn=('-Wno-MULTIDRIVEN',),
    )
