#==============================================================================
# create_project.tcl -- Vivado project for the Genesys 2 LiteDRAM DDR3 board proof
#==============================================================================
# Board:  Digilent Genesys 2 (xc7k325tffg900-2)
# Top:    litedram_ddr3_board_top
# Usage:  run via `make bitstream`, which exports the env vars below.
#==============================================================================

set project_name "litedram_ddr3"
set project_dir  "build/vivado_project"
set part_name    "xc7k325tffg900-2"

set script_dir   [file dirname [file normalize [info script]]]
# FPGA_PROJECT_ROOT is where Vivado WRITES (fpga/); FPGA_BUILD_ROOT is where the
# build's SOURCES live (rtl/, gen/). They are different directories and were the
# same only under the older flat layout -- a tcl that uses one for both is right
# by accident until the layout splits.
set project_root [expr {[info exists ::env(FPGA_PROJECT_ROOT)] \
                        ? [file normalize $::env(FPGA_PROJECT_ROOT)] \
                        : [file normalize "$script_dir/.."]}]
set build_root   [expr {[info exists ::env(FPGA_BUILD_ROOT)] \
                        ? [file normalize $::env(FPGA_BUILD_ROOT)] \
                        : [file normalize "$script_dir/../.."]}]

if {![info exists ::env(REPO_ROOT)]} {
    puts stderr "ERROR: REPO_ROOT is not set. Run via the build Makefile."
    exit 1
}

puts "========================================================================"
puts "RTL Design Sherpa -- Genesys 2 LiteDRAM DDR3 BOARD PROOF"
puts "========================================================================"
puts "  This build contains NO scoria RTL. Its only job is to establish that"
puts "  the board, the pins, the K7DDRPHY and the DRAM are sound, so that a"
puts "  later scoria failure has a denominator."
puts "  Project root: $project_root"
puts "========================================================================"

create_project $project_name "$project_root/$project_dir" -part $part_name -force

set obj [current_project]
set_property -name "default_lib"        -value "xil_defaultlib" -objects $obj
set_property -name "target_language"    -value "Verilog"        -objects $obj
set_property -name "simulator_language" -value "Mixed"          -objects $obj

# ---- sources, from the filelist the Makefile already names ------------------
set rds_root [expr {[info exists ::env(REPO_ROOT)] ? $::env(REPO_ROOT) \
                    : [string trim [exec git -C $script_dir rev-parse --show-toplevel]]}]
source "$rds_root/make/tcl/filelist_utils.tcl"

set top_filelist [expr {[info exists ::env(FPGA_FILELIST)] \
                        ? [file normalize $::env(FPGA_FILELIST)] \
                        : "$build_root/rtl/filelists/litedram_ddr3_board.f"}]
puts "\nExpanding filelist: $top_filelist"
if {![file exists $top_filelist]} {
    puts stderr "ERROR: filelist not found: $top_filelist"
    exit 1
}
lassign [filelist::flatten $top_filelist] sv_sources incdirs defines
puts "  [llength $sv_sources] source file(s)"

# Drop the Verilator-only files. Both are `ifdef VERILATOR guarded, but Vivado
# must not even SEE them: the blackbox stub declares a module with the same name
# as the real generated core, and whichever Vivado read last would win.
set filtered {}
foreach src $sv_sources {
    if {[string match "*verilator_xilinx_stubs.sv" $src]}      { continue }
    if {[string match "*litedram_genesys2_ddr3_bb.sv" $src]}   { continue }
    lappend filtered $src
}
set sv_sources $filtered

foreach src $sv_sources {
    if {![file exists $src]} {
        puts stderr "ERROR: source not found: $src"
        puts stderr "  If it is the generated core, run ./regen.sh first."
        exit 1
    }
}
set src_fs [get_filesets sources_1]
add_files -norecurse -fileset $src_fs $sv_sources
foreach src [get_files -of_objects $src_fs -filter {FILE_TYPE == "Verilog"}] {
    if {[string match *.sv $src] || [string match *.svh $src]} {
        set_property FILE_TYPE SystemVerilog $src
    }
}
set_property include_dirs $incdirs $src_fs
if {[llength $defines] > 0} { set_property verilog_define $defines $src_fs }

set_property top "litedram_ddr3_board_top" $src_fs
update_compile_order -fileset sources_1

# ---- constraints -----------------------------------------------------------
# Two files on purpose: ddr3_pins.xdc is GENERATED by
# bin/gen_genesys2_ddr3_xdc.py and must stay regenerable, so hand-written pins
# live beside it in board_pins.xdc rather than inside it where the next regen
# would clobber them.
set cf [get_filesets constrs_1]
add_files -norecurse -fileset $cf \
    "$project_root/constraints/ddr3_pins.xdc" \
    "$project_root/constraints/board_pins.xdc"

# The core ships its OWN timing constraints, and they are not optional. It
# emits litedram_genesys2_ddr3.xdc beside the Verilog carrying:
#   set_false_path  -to   [cells mr_ff == TRUE]          multi-register CDC
#   set_false_path  -to   PRE pins of ars_ff1/ars_ff2    async-reset sync
#   set_max_delay 2 -from ars_ff1/C -to ars_ff2/D        the sync chain itself
#
# Leave them out and Vivado times those asynchronous paths as real logic, so
# the design "misses" timing on paths that are architecturally not paths. The
# first attempt here closed at WNS=-0.329 without this file. That is the same
# phantom-failure class as the invalid auto-inferred generated clock that once
# produced a -23.5 ns WNS on the DDR2 char build: the number was real, the
# failure was not.
#
# It lives under gen/ (gitignored, regenerated by ./regen.sh) so it is added
# from build_root, not from the constraints directory.
set core_xdc "$build_root/gen/gateware/litedram_genesys2_ddr3.xdc"
if {![file exists $core_xdc]} {
    puts stderr "ERROR: the core's own XDC is missing: $core_xdc"
    puts stderr "  Run ./regen.sh -- without it the CDC paths are timed as real."
    exit 1
}
add_files -norecurse -fileset $cf $core_xdc
puts "Added the core's generated timing constraints: $core_xdc"

set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
set_property strategy "Performance_Explore"       [get_runs impl_1]
set_property steps.phys_opt_design.is_enabled true [get_runs impl_1]

puts "\nProject created: $project_root/$project_dir/${project_name}.xpr"
