name: Field Config Usage Linting

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/field-config-linting.yml'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  field-config-lint:
    name: Field Config Usage Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install pylint flake8
        pip install -e .  # Install your package
    
    - name: Run field config linting
      run: |
        echo "Checking field configuration usage..."
        python -m pylint --load-plugins=tools.linting.field_config_checker \
          --disable=all --enable=field-config-usage \
          CocoTBFramework/tbclasses/axi_errmon/
    
    - name: Run flake8 field config checks
      run: |
        python -m flake8 --select=FC CocoTBFramework/tbclasses/axi_errmon/

